In [2]:
import pandas as pd

In [3]:
str = pd.read_csv('updated_strs.csv')

In [4]:
str

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,...,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11",...,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,STR-Yv4hq7,False,16,7,31.3,18,"11.1, 15.1",12,12,10,...,MC-000713-IUJj,NaN,NaN,PT-FQOeFS,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41:01.795310+00:00,2024-06-13 16:41:01.795310+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11",...,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39:31.198745+00:00,2024-08-16 16:39:28.322066+00:00
3,STR-gifaLI,False,18,7,"30.3, 32.3","10, 14","7.1, 11.1","11, 13","11, 13","9, 12",...,MC-000960-RI7G,NaN,NaN,PT-N5YXV2,Internal,WGS Inferred,NaN,NaN,2024-04-23 18:08:28.005757+00:00,2024-04-23 18:08:28.005757+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,...,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9302,STR-Wr25NT,False,"16, 17",9,30,15,"5, 15","10, 12","10, 12",11,...,MC-000633-iIki,NaN,NaN,PT-zUYVjw,Internal,GPP,NaN,FU97-Cas9VY,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9303,STR-oeTHfb,False,16,"6, 9.3","27, 29","13, 14",13,12,"10, 12","9, 11",...,MC-000406-va7T,Not Detected,NaN,PT-ZwaNYv,Internal,GPP,NaN,U937-311cas9,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9304,STR-lkgw1v,False,"14, 17, 18",6,28,12,10,"10, 11, 12","8, 11, 12, 13","10, 13",...,MC-000109-cK3a,NaN,NaN,PT-Zwpb82,Internal,GPP,NaN,NCIH3255,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9305,STR-fnFh09,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10",...,MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepA-p5,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9306,STR-eo2Vx2,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10",...,MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepB-p5,2024-08-13 15:46:14.890555+00:00,2024-08-13 15:46:14.890555+00:00

In [5]:
str.columns

Index(['id', 'is_reference', 'd3s1358', 'th01', 'd21s11', 'd18s51', 'penta_e',
       'd5s818', 'd13s317', 'd7s820', 'd16s539', 'csf1po', 'penta_d', 'vwa',
       'd8s1179', 'tpox', 'fga', 'pellet_creation_date',
       'percentage_match_to_parental', 'lab_corp_spec_nbr',
       'lab_corp_case_nbr', 'comments', 'amelogenin', 'model_condition_id',
       'mouse', 'mycoplasma', 'patient_id', 'source', 'source_group',
       'pellet_submitted_date', 'sample_reference', 'created_at',
       'updated_at'],
      dtype='object')

In [6]:
condition_counts = str['model_condition_id'].value_counts()
duplicate_conditions = condition_counts[condition_counts > 1].index

In [7]:
filtered_df = str[str['model_condition_id'].isin(duplicate_conditions)]
filtered_df

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,...,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11",...,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11",...,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39:31.198745+00:00,2024-08-16 16:39:28.322066+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,...,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
5,STR-arZ1Ml,True,17,"8, 9",30,15,20,"10, 11","12, 13",10,...,MC-001346-JhaA,NaN,NaN,PT-VXDXrs,Internal,DMX,NaN,H103,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
6,STR-BzNhKk,False,"15, 18",7,"31.2, 32.2","12, 18","5, 12","9, 12","8, 11",8,...,MC-001465-V7hs,NaN,NaN,PT-7eVJ3u,Internal,GPP,NaN,CHLA136--HumagneCD-RepA-P3(D21),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9302,STR-Wr25NT,False,"16, 17",9,30,15,"5, 15","10, 12","10, 12",11,...,MC-000633-iIki,NaN,NaN,PT-zUYVjw,Internal,GPP,NaN,FU97-Cas9VY,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9303,STR-oeTHfb,False,16,"6, 9.3","27, 29","13, 14",13,12,"10, 12","9, 11",...,MC-000406-va7T,Not Detected,NaN,PT-ZwaNYv,Internal,GPP,NaN,U937-311cas9,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9304,STR-lkgw1v,False,"14, 17, 18",6,28,12,10,"10, 11, 12","8, 11, 12, 13","10, 13",...,MC-000109-cK3a,NaN,NaN,PT-Zwpb82,Internal,GPP,NaN,NCIH3255,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9305,STR-fnFh09,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10",...,MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepA-p5,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9306,STR-eo2Vx2,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10",...,MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepB-p5,2024-08-13 15:46:14.890555+00:00,2024-08-13 15:46:14.890555+00:00

In [8]:
condition_counts2 = filtered_df['sample_reference'].value_counts()
duplicate_conditions2 = condition_counts2[condition_counts2 > 1].index

In [9]:
filtered_df2 = filtered_df[filtered_df['sample_reference'].isin(duplicate_conditions2)]
filtered_df2

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,...,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
165,STR-PnrNGc,True,16,"7, 9","29, 30","14, 15","12, 16","11, 13","11, 12","8, 11",...,MC-001542-iWSd,NaN,NaN,PT-wu5c1x,Internal,DMX,NaN,KON,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
198,STR-f1Q2i1,True,16,"7, 9","29, 32.2","13, 14","5, 14","10, 13",11,10,...,MC-001578-6Nny,NaN,NaN,PT-OqrZ3f,Internal,DMX,NaN,NCCIT,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
267,STR-WWzBpU,False,"16, 17",9.3,"28, 30",16,5,11,12,10,...,MC-000296-bgzW,NaN,NaN,PT-GezIUF,Internal,GPP,NaN,OUMS23Cas9VY,2024-08-13 15:46:14.431081+00:00,2024-08-13 15:46:14.431081+00:00
371,STR-KajknE,True,"14, 16","9, 9.3","29, 31","15, 16","13, 16",10,"11, 12","10, 12",...,MC-001997-n8wz,NaN,NaN,PT-jmmNcQ,Internal,DMX,NaN,ECC2,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
381,STR-NiNe1v,True,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9",...,MC-001984-aM63,NaN,NaN,PT-c5NLTF,Internal,DMX,NaN,NZM4,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9261,STR-4IfqVQ,False,"14, 18","6, 9.3",29,16,"5, 13","12, 13",11,"9, 11",...,MC-000677-aJN8,NaN,NaN,PT-Z9x3iF,Internal,GPP,NaN,SW1573,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9263,STR-dNQSYy,False,"15, 16",9,"28, 30",12,"18, 19","11, 12","11, 12","8, 11",...,MC-001393-GjYg,Not Detected,NaN,PT-Zd61pI,Internal,GPP,NaN,SUM190PT-311cas9-RepA-p6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9264,STR-dzCOco,False,"15, 16",9,"28, 30",12,"18, 19","11, 12","11, 12","8, 11",...,MC-001393-GjYg,Not Detected,NaN,PT-Zd61pI,Internal,GPP,NaN,SUM190PT-311cas9-RepA-p6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9296,STR-0URWVh,False,15,"6, 9","30, 31.2",14,"14, 19",12,"11, 12","12, 13",...,MC-000836-gosu,NaN,NaN,PT-ZS5SNw,Internal,GPP,NaN,YD15-311Cas9-RepA-P6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9297,STR-UtsqQf,False,15,"6, 9","30, 31.2",14,"14, 19",12,"11, 12","12, 13",...,MC-000836-gosu,Not Detected,NaN,PT-ZS5SNw,Internal,GPP,NaN,YD15-311Cas9-RepA-P6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00

In [10]:
pd.set_option('display.max_columns', 40)
pd.set_option('display.max_rows', 340)
str.head()

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11","11, 13","12, 13","9, 10","16, 18","11, 14","8, 10","18, 19",NaN,NaN,76M91400,CX4003615,matches reference; STR matches reference profi...,X,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,STR-Yv4hq7,False,16,7,31.3,18,"11.1, 15.1",12,12,10,9,"10, 13",11,NaN,"9, 14",NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-000713-IUJj,NaN,NaN,PT-FQOeFS,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41:01.795310+00:00,2024-06-13 16:41:01.795310+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11","9, 12",11,"8, 13",NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39:31.198745+00:00,2024-08-16 16:39:28.322066+00:00
3,STR-gifaLI,False,18,7,"30.3, 32.3","10, 14","7.1, 11.1","11, 13","11, 13","9, 12",9,"10, 12","8, 10",NaN,"13, 15",NaN,"22, 23",NaN,NaN,NaN,NaN,NaN,NaN,MC-000960-RI7G,NaN,NaN,PT-N5YXV2,Internal,WGS Inferred,NaN,NaN,2024-04-23 18:08:28.005757+00:00,2024-04-23 18:08:28.005757+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,"10, 11",12,"10, 11",NaN,"13, 15","11, 8",24,NaN,0.8696,NaN,NaN,NaN,NaN,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [11]:
condition_counts3 = filtered_df2['lab_corp_case_nbr'].value_counts()
duplicate_conditions3 = condition_counts3[condition_counts3 > 1].index

In [12]:
filtered_df3 = filtered_df2[filtered_df2['lab_corp_case_nbr'].isin(duplicate_conditions3)]
filtered_df3

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
267,STR-WWzBpU,False,"16, 17",9.3,"28, 30",16,5,11,12,10,11,12,"9, 12",16,"13, 16",11,23.2,2024-03-11,NaN,NaN,CX4018877,NaN,X,MC-000296-bgzW,NaN,NaN,PT-GezIUF,Internal,GPP,NaN,OUMS23Cas9VY,2024-08-13 15:46:14.431081+00:00,2024-08-13 15:46:14.431081+00:00
495,STR-Bv7v3q,True,"15, 16","6, 8, 9.3","28, 29, 32","13, 15, 17","7, 11, 12",11,11,"8, 9, 10","11, 12","10, 11, 12","9, 11","14, 17",13,"8, 9","22, 23",NaN,NaN,23790540,CX4013150,Matches reference,X,MC-003017-iLhU,NaN,Not Detected,PT-cqv92I,Internal,Achilles,NaN,EAHY926,2024-04-09 16:00:46.487764+00:00,2024-08-16 18:32:15.763300+00:00
527,STR-iq3kI6,False,"14, 15",9.3,31,13,"10, 12",12,"11, 12","9, 12",9,"10, 12",9,"18, 19","12, 13","8, 11","21, 26",NaN,1.0,2AQ91020,CX4014974,Matches reference,"X, Y",MC-003077-naD1,NaN,Not Detected,PT-O15HlH,Internal,Achilles,NaN,VCaPEnzR,2024-04-09 16:00:46.487764+00:00,2024-08-16 18:32:52.086095+00:00
577,STR-lbeRRR,False,15,6,"29, 31.2",15,"8, 11","11, 12",12,12,"11, 12",12,"12, 13","14, 18",8,8,"20, 23",NaN,NaN,3BF90940,CX4017930,NaN,"X, Y",MC-002433-iccX,NaN,NaN,PT-k1gvKS,Internal,GPP,2023-11-01,CCLFPEDS0019T-enCas12a-HumagneCD-RepB-P6(D21),2024-04-29 14:57:27.131270+00:00,2024-04-29 14:57:27.131295+00:00
664,STR-U7lF8I,False,18,9.3,30.2,20,12,13,11,10,12,12,12,"15, 17","11, 13","10, 13",23,NaN,NaN,NaN,CX4012569,NaN,X,MC-002499-dWxK,NaN,NaN,PT-j6UudO,Internal,GPP,NaN,UACC3199-311cas9,2024-08-13 14:32:29.862597+00:00,2024-08-13 14:32:29.862597+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9261,STR-4IfqVQ,False,"14, 18","6, 9.3",29,16,"5, 13","12, 13",11,"9, 11","12, 14","10, 12",9,20,11,"8, 11",21,2023-11-30,NaN,NaN,CX4018125,NaN,X,MC-000677-aJN8,NaN,NaN,PT-Z9x3iF,Internal,GPP,NaN,SW1573,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9263,STR-dNQSYy,False,"15, 16",9,"28, 30",12,"18, 19","11, 12","11, 12","8, 11",11,"8, 10","10, 11","14, 17","10, 15","8, 9",22,NaN,NaN,NaN,CX4010790,NaN,X,MC-001393-GjYg,Not Detected,NaN,PT-Zd61pI,Internal,GPP,NaN,SUM190PT-311cas9-RepA-p6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9264,STR-dzCOco,False,"15, 16",9,"28, 30",12,"18, 19","11, 12","11, 12","8, 11",11,"8, 10","10, 11","14, 17","10, 15","8, 9",22,NaN,NaN,NaN,CX4010882,NaN,X,MC-001393-GjYg,Not Detected,NaN,PT-Zd61pI,Internal,GPP,NaN,SUM190PT-311cas9-RepA-p6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9296,STR-0URWVh,False,15,"6, 9","30, 31.2",14,"14, 19",12,"11, 12","12, 13","9, 12","10, 12",9,15,15,9,23,NaN,NaN,NaN,CX4011254,NaN,"X, Y",MC-000836-gosu,NaN,NaN,PT-ZS5SNw,Internal,GPP,NaN,YD15-311Cas9-RepA-P6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9297,STR-UtsqQf,False,15,"6, 9","30, 31.2",14,"14, 19",12,"11, 12","12, 13","9, 12","10, 12",9,15,15,9,23,NaN,NaN,NaN,CX4010883,NaN,"X, Y",MC-000836-gosu,Not Detected,NaN,PT-ZS5SNw,Internal,GPP,NaN,YD15-311Cas9-RepA-P6,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00

In [13]:
filtered_df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4155 entries, 267 to 9297
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            4155 non-null   object
 1   is_reference                  4155 non-null   bool
 2   d3s1358                       4150 non-null   object
 3   th01                          4150 non-null   object
 4   d21s11                        4131 non-null   object
 5   d18s51                        4150 non-null   object
 6   penta_e                       4150 non-null   object
 7   d5s818                        4150 non-null   object
 8   d13s317                       4150 non-null   object
 9   d7s820                        4150 non-null   object
 10  d16s539                       4150 non-null   object
 11  csf1po                        4150 non-null   object
 12  penta_d                       4150 non-null   object
 13  vwa                           4150 non-null   object
 14  d8s1179                       4150 non-null   object
 15  tpox                          4150 non-null   object
 16  fga                           4150 non-null   object
 17  pellet_creation_date          2305 non-null   object
 18  percentage_match_to_parental  143 non-null    float64
 19  lab_corp_spec_nbr             33 non-null     object
 20  lab_corp_case_nbr             4155 non-null   object
 21  comments                      27 non-null     object
 22  amelogenin                    4149 non-null   object
 23  model_condition_id            4155 non-null   object
 24  mouse                         694 non-null    object
 25  mycoplasma                    24 non-null     object
 26  patient_id                    4155 non-null   object
 27  source                        4155 non-null   object
 28  source_group                  4155 non-null   object
 29  pellet_submitted_date         4 non-null      object
 30  sample_reference              4155 non-null   object
 31  created_at                    4155 non-null   object
 32  updated_at                    4155 non-null   object
dtypes: bool(1), float64(1), object(31)
memory usage: 1.1+ MB

In [14]:
case_num = filtered_df3.groupby('lab_corp_case_nbr')['model_condition_id'].value_counts().unstack(fill_value=0)
case_num

model_condition_id,MC-000001-ztiA,MC-000004-pA3k,MC-000011-bxAg,MC-000014-aXo5,MC-000024-kxGf,MC-000025-jryP,MC-000026-oSZT,MC-000034-1Ulp,MC-000035-aT3G,MC-000037-Q40d,MC-000041-uPBf,MC-000047-fRLW,MC-000052-uUW6,MC-000054-JG3n,MC-000057-XS1q,MC-000067-Fdh5,MC-000070-XibM,MC-000074-OKtM,MC-000077-BZeg,MC-000085-DjQm,...,MC-003410-erdf,MC-003513-b264,MC-003515-8vbw,MC-003530-ffd1,MC-003531-ss81,MC-003574-pj39,MC-003586-nlw2,MC-003587-2bha,MC-003589-ujhg,MC-003590-l2c4,MC-003595-45tr,MC-003596-uytg,MC-003597-uyhg,MC-003598-lkjh,MC-003599-34rf,MC-003611-mc8r,MC-003612-l0w8,MC-003613-ce4z,MC-003621-oipl,MC-003623-uijh
lab_corp_case_nbr,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
CX4004394,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4009888,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4009889,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4009997,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4009998,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010243,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010244,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010245,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010486,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010487,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010578,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010579,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010632,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010651,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010790,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010882,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4010883,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011038,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011039,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011161,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011162,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011254,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011363,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011449,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011713,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011714,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011831,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4011955,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4012006,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4012173,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4012391,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4012569,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4012612,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4012829,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4012984,0,0,0,0,0,0,0,0,0,0,6,0,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013151,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013371,0,0,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013372,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013483,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013484,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013654,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013655,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013693,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013758,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013759,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013811,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4013922,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014019,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014130,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014296,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014375,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014376,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014497,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014498,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014596,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014597,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014598,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014681,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014682,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014840,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014841,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014842,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014972,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014973,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014974,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4014975,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015091,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015092,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015093,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015094,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015203,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015204,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015205,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015206,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015425,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015426,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015427,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015549,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015550,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015551,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015699,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015701,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015873,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015874,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015910,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015911,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4015912,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016034,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016035,0,0,0,0,3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016036,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016247,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016248,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016249,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016250,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016251,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016389,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016390,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016391,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016392,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016533,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016534,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016535,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016536,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016822,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016823,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016824,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016891,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016892,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016893,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4016894,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017164,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017165,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017166,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017462,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017464,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017465,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017466,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017693,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017694,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017695,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017696,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017697,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017727,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017728,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017796,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017797,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017927,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017928,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017929,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4017930,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018027,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018028,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018126,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018282,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018283,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018284,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018339,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018340,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018341,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018414,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0
CX4018415,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018416,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018535,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018536,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018633,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018634,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018751,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018752,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4018877,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,0,0,0,0,0,0,3,0,0,0,0,0
CX4018878,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019079,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0
CX4019080,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019190,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,3,0,0,0,3,0,0,3,0,0,0,0,0,0
CX4019191,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019192,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0,0,3,0,0,0,0,0,0,0,0
CX4019286,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,0,0,3,0,3,0,0,0,0,0,0
CX4019383,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
CX4019413,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3
CX4019414,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,...,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019482,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0
CX4019483,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CX4019637,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,2,0,2,3,0,3,0,0,0,0,0,0,0,0,0,0,0,3,0
CX4019638,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,3,0,0,0,0,0,0,0,3,3,0,3,5,0,0,0
CX4019639,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
case_num1 = filtered_df3.groupby('lab_corp_case_nbr')['model_condition_id'].value_counts().reset_index(name='count')
case_num1.iloc[0:250]

    lab_corp_case_nbr model_condition_id  count
0           CX4004394     MC-001861-0lWH      1
1           CX4004394     MC-001864-217M      1
2           CX4004394     MC-001862-LLaC      1
3           CX4009888     MC-001422-2WUe      6
4           CX4009888     MC-002465-1j4t      6
5           CX4009888     MC-000160-11p8      5
6           CX4009888     MC-000922-l1Wf      5
7           CX4009888     MC-001098-vhLt      3
8           CX4009888     MC-000707-Dpdu      2
9           CX4009888     MC-001028-iOnL      2
10          CX4009888     MC-002471-uRkn      1
11          CX4009889     MC-000101-0kr1      6
12          CX4009889     MC-001675-IXck      6
13          CX4009889     MC-001098-vhLt      3
14          CX4009889     MC-001694-EG4Q      3
15          CX4009997     MC-000362-z9Q8     12
16          CX4009997     MC-000168-L3Ll      6
17          CX4009997     MC-000696-I5h5      6
18          CX4009997     MC-001528-qmGv      5
19          CX4009997     MC-001694-EG4Q      3
20          CX4009997     MC-002067-S9Nv      3
21          CX4009998     MC-000287-D5Mr      6
22          CX4009998     MC-001562-lvLb      6
23          CX4009998     MC-002066-nmqF      3
24          CX4009998     MC-001338-wh8o      3
25          CX4009998     MC-001606-pW33      3
26          CX4009998     MC-001649-aJin      3
27          CX4009998     MC-001557-elcL      2
28          CX4010243     MC-000384-jGYO      9
29          CX4010243     MC-001054-Azxo      6
30          CX4010243     MC-000160-11p8      5
31          CX4010243     MC-000871-aeyP      3
32          CX4010243     MC-001985-mJzv      3
33          CX4010243     MC-002034-oyVP      3
34          CX4010243     MC-002043-M15K      3
35          CX4010243     MC-002544-9Y33      3
36          CX4010243     MC-002659-6thC      3
37          CX4010243     MC-002669-Ivra      3
38          CX4010243     MC-001028-iOnL      2
39          CX4010244     MC-000147-Uovr      6
40          CX4010244     MC-000716-J43k      6
41          CX4010244     MC-000944-cm2a      6
42          CX4010244     MC-001338-wh8o      6
43          CX4010244     MC-001641-0Q0R      6
44          CX4010244     MC-001669-PygV      6
45          CX4010244     MC-002511-mxVh      6
46          CX4010244     MC-002707-Hdrr      6
47          CX4010244     MC-000489-H7Ic      3
48          CX4010244     MC-000404-GqDy      2
49          CX4010245     MC-000595-Gzg4      6
50          CX4010245     MC-001982-nWKb      6
51          CX4010245     MC-001984-aM63      3
52          CX4010245     MC-002664-cIbD      3
53          CX4010245     MC-002785-qo9e      3
54          CX4010245     MC-001172-cKtB      3
55          CX4010245     MC-000776-YERh      3
56          CX4010245     MC-000665-FOD6      3
57          CX4010245     MC-000052-uUW6      3
58          CX4010245     MC-000372-lJjw      1
59          CX4010245     MC-002471-uRkn      1
60          CX4010245     MC-002541-qEKQ      1
61          CX4010486     MC-000052-uUW6      3
62          CX4010486     MC-000532-NN9r      3
63          CX4010486     MC-000776-YERh      3
64          CX4010486     MC-001172-cKtB      3
65          CX4010486     MC-001972-Ric2      3
66          CX4010486     MC-002291-NqNs      3
67          CX4010486     MC-002716-JXsE      3
68          CX4010486     MC-001491-3JVj      2
69          CX4010486     MC-000145-3ydU      2
70          CX4010486     MC-000372-lJjw      1
71          CX4010486     MC-002541-qEKQ      1
72          CX4010487     MC-002708-tPxj      5
73          CX4010487     MC-000077-BZeg      3
74          CX4010487     MC-001984-aM63      3
75          CX4010487     MC-002051-2Ddi      3
76          CX4010487     MC-002060-kXBN      3
77          CX4010487     MC-002500-qPav      3
78          CX4010487     MC-002524-ZbQT      3
79          CX4010487     MC-001691-0y4G      2
80          CX4010487     MC-002070-tGf5      2
81          CX4010578     MC-000067-Fdh5      5
82          CX4010578     MC-000964-tTts      5
83          CX4010578     MC-000781-G5rR      3
84          CX4010578     MC-001445-i0gH      3
85          CX4010578     MC-002693-Sw2e      3
86          CX4010578     MC-001028-iOnL      2
87          CX4010578     MC-002541-qEKQ      1
88          CX4010579     MC-002664-cIbD      6
89          CX4010579     MC-002659-6thC      6
90          CX4010579     MC-002066-nmqF      6
91          CX4010579     MC-000502-yIwz      3
92          CX4010579     MC-000804-Hxgj      3
93          CX4010579     MC-001858-c43i      3
94          CX4010579     MC-001557-elcL      2
95          CX4010632     MC-001701-aj6n      6
96          CX4010632     MC-000074-OKtM      3
97          CX4010632     MC-000097-qJSn      3
98          CX4010632     MC-000664-F5u7      3
99          CX4010632     MC-002214-vqKT      3
100         CX4010651     MC-001441-SMif      6
101         CX4010651     MC-001649-aJin      6
102         CX4010651     MC-001054-Azxo      3
103         CX4010651     MC-000077-BZeg      3
104         CX4010790     MC-000964-tTts     15
105         CX4010790     MC-002051-2Ddi      9
106         CX4010790     MC-002043-M15K      6
107         CX4010790     MC-000804-Hxgj      6
108         CX4010790     MC-001606-pW33      6
109         CX4010790     MC-002544-9Y33      6
110         CX4010790     MC-002669-Ivra      6
111         CX4010790     MC-002785-qo9e      6
112         CX4010790     MC-001369-jLCX      5
113         CX4010790     MC-001028-iOnL      4
114         CX4010790     MC-000074-OKtM      3
115         CX4010790     MC-000502-yIwz      3
116         CX4010790     MC-001054-Azxo      3
117         CX4010790     MC-001532-MUr8      3
118         CX4010790     MC-002035-O8Pm      3
119         CX4010790     MC-002531-OoyZ      3
120         CX4010790     MC-001393-GjYg      1
121         CX4010882     MC-000067-Fdh5     10
122         CX4010882     MC-001858-c43i      6
123         CX4010882     MC-002291-NqNs      6
124         CX4010882     MC-000271-2YJJ      3
125         CX4010882     MC-000502-yIwz      3
126         CX4010882     MC-001393-GjYg      1
127         CX4010883     MC-001500-IO4l      6
128         CX4010883     MC-001972-Ric2      6
129         CX4010883     MC-002523-IXGJ      5
130         CX4010883     MC-000145-3ydU      4
131         CX4010883     MC-002834-mbYE      3
132         CX4010883     MC-002660-GpFz      3
133         CX4010883     MC-000271-2YJJ      3
134         CX4010883     MC-000836-gosu      1
135         CX4010883     MC-002516-QoE6      1
136         CX4011038     MC-000097-qJSn      6
137         CX4011038     MC-000658-XV7I      6
138         CX4011038     MC-000664-F5u7      6
139         CX4011038     MC-001054-Azxo      6
140         CX4011038     MC-000074-OKtM      6
141         CX4011038     MC-000145-3ydU      2
142         CX4011038     MC-000583-payY      2
143         CX4011038     MC-002516-QoE6      1
144         CX4011039     MC-000939-pxY0      6
145         CX4011039     MC-002060-kXBN      6
146         CX4011039     MC-002524-ZbQT      6
147         CX4011039     MC-001691-0y4G      4
148         CX4011039     MC-001986-OUuR      3
149         CX4011039     MC-002020-ZmHZ      3
150         CX4011039     MC-000774-GTYc      2
151         CX4011161     MC-000696-I5h5      6
152         CX4011161     MC-002716-JXsE      6
153         CX4011161     MC-002070-tGf5      4
154         CX4011161     MC-001509-3x7y      3
155         CX4011161     MC-002834-mbYE      3
156         CX4011161     MC-002847-b2Oj      3
157         CX4011161     MC-001350-yZDB      2
158         CX4011162     MC-000160-11p8     10
159         CX4011162     MC-000502-yIwz      6
160         CX4011162     MC-002500-qPav      6
161         CX4011162     MC-002681-4WzP      5
162         CX4011162     MC-000664-F5u7      3
163         CX4011162     MC-002662-0u5H      3
164         CX4011162     MC-002074-ehWg      2
165         CX4011162     MC-001578-6Nny      1
166         CX4011254     MC-002708-tPxj     10
167         CX4011254     MC-002531-OoyZ      6
168         CX4011254     MC-000221-ha4a      3
169         CX4011254     MC-002650-KUc6      3
170         CX4011254     MC-002654-HZBL      3
171         CX4011254     MC-002703-bKS3      3
172         CX4011254     MC-002711-FIAF      3
173         CX4011254     MC-002778-QeHD      3
174         CX4011254     MC-002787-1SfB      3
175         CX4011254     MC-002794-62RZ      3
176         CX4011254     MC-002801-Dhlv      3
177         CX4011254     MC-000836-gosu      1
178         CX4011363     MC-001369-jLCX     10
179         CX4011363     MC-002214-vqKT      6
180         CX4011363     MC-002693-Sw2e      6
181         CX4011363     MC-000462-xIRj      4
182         CX4011363     MC-001980-s7Og      3
183         CX4011363     MC-000221-ha4a      3
184         CX4011363     MC-001370-W35c      1
185         CX4011449     MC-002523-IXGJ     10
186         CX4011449     MC-002035-O8Pm      6
187         CX4011449     MC-000532-NN9r      3
188         CX4011449     MC-002806-K1rH      2
189         CX4011449     MC-002471-uRkn      1
190         CX4011713     MC-001369-jLCX      5
191         CX4011713     MC-002925-yAya      3
192         CX4011713     MC-001172-cKtB      3
193         CX4011713     MC-001289-BpdI      3
194         CX4011713     MC-001436-7CDG      3
195         CX4011713     MC-001715-Jkow      3
196         CX4011713     MC-002030-mJL7      3
197         CX4011713     MC-002677-Kddq      3
198         CX4011713     MC-002781-ot8s      3
199         CX4011713     MC-002922-66Xg      2
200         CX4011714     MC-001986-OUuR      6
201         CX4011714     MC-002020-ZmHZ      6
202         CX4011714     MC-002834-mbYE      6
203         CX4011714     MC-002052-GfvX      5
204         CX4011714     MC-000750-bafP      3
205         CX4011714     MC-002051-2Ddi      3
206         CX4011714     MC-002690-2vlv      3
207         CX4011831     MC-000067-Fdh5     15
208         CX4011831     MC-002662-0u5H      6
209         CX4011831     MC-002650-KUc6      6
210         CX4011831     MC-000871-aeyP      6
211         CX4011831     MC-000532-NN9r      3
212         CX4011831     MC-001053-eiEy      3
213         CX4011831     MC-001289-BpdI      3
214         CX4011831     MC-001481-8jhv      3
215         CX4011831     MC-001715-Jkow      3
216         CX4011831     MC-002789-mav3      3
217         CX4011955     MC-002787-1SfB      6
218         CX4011955     MC-002847-b2Oj      6
219         CX4011955     MC-002681-4WzP      5
220         CX4011955     MC-002532-oQQy      3
221         CX4011955     MC-001053-eiEy      3
222         CX4012006     MC-000035-aT3G      6
223         CX4012006     MC-000463-0z7G      6
224         CX4012006     MC-000747-stgN      6
225         CX4012006     MC-002662-0u5H      6
226         CX4012006     MC-002802-uneq      3
227         CX4012006     MC-002678-XQSC      3
228         CX4012006     MC-001676-Iulf      3
229         CX4012006     MC-002529-DNem      2
230         CX4012173     MC-002794-62RZ      6
231         CX4012173     MC-002922-66Xg      4
232         CX4012173     MC-002660-GpFz      3
233         CX4012173     MC-002677-Kddq      3
234         CX4012173     MC-002834-mbYE      3
235         CX4012173     MC-002529-DNem      2
236         CX4012391     MC-002703-bKS3      6
237         CX4012391     MC-001028-iOnL      4
238         CX4012391     MC-000528-BMri      3
239         CX4012391     MC-000694-gObM      3
240         CX4012391     MC-002030-mJL7      3
241         CX4012391     MC-002522-BP3K      3
242         CX4012391     MC-002543-1Me7      3
243         CX4012391     MC-002677-Kddq      3
244         CX4012391     MC-002690-2vlv      3
245         CX4012391     MC-002794-62RZ      3
246         CX4012569     MC-000744-mCbj      6
247         CX4012569     MC-000515-ooNl      6
248         CX4012569     MC-002801-Dhlv      6
249         CX4012569     MC-002678-XQSC      6

In [16]:
three sep uploads?

Object `uploads` not found.

In [17]:
str

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11","11, 13","12, 13","9, 10","16, 18","11, 14","8, 10","18, 19",NaN,NaN,76M91400,CX4003615,matches reference; STR matches reference profi...,X,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,STR-Yv4hq7,False,16,7,31.3,18,"11.1, 15.1",12,12,10,9,"10, 13",11,NaN,"9, 14",NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-000713-IUJj,NaN,NaN,PT-FQOeFS,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41:01.795310+00:00,2024-06-13 16:41:01.795310+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11","9, 12",11,"8, 13",NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39:31.198745+00:00,2024-08-16 16:39:28.322066+00:00
3,STR-gifaLI,False,18,7,"30.3, 32.3","10, 14","7.1, 11.1","11, 13","11, 13","9, 12",9,"10, 12","8, 10",NaN,"13, 15",NaN,"22, 23",NaN,NaN,NaN,NaN,NaN,NaN,MC-000960-RI7G,NaN,NaN,PT-N5YXV2,Internal,WGS Inferred,NaN,NaN,2024-04-23 18:08:28.005757+00:00,2024-04-23 18:08:28.005757+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,"10, 11",12,"10, 11",NaN,"13, 15","11, 8",24,NaN,0.8696,NaN,NaN,NaN,NaN,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9302,STR-Wr25NT,False,"16, 17",9,30,15,"5, 15","10, 12","10, 12",11,"9, 11",12,14,17,"14, 15",12,19,2023-12-08,NaN,NaN,CX4018282,NaN,X,MC-000633-iIki,NaN,NaN,PT-zUYVjw,Internal,GPP,NaN,FU97-Cas9VY,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9303,STR-oeTHfb,False,16,"6, 9.3","27, 29","13, 14",13,12,"10, 12","9, 11",12,12,"12, 13","14, 15","12, 13","8, 11","22, 25",NaN,NaN,NaN,CX4010790,NaN,X,MC-000406-va7T,Not Detected,NaN,PT-ZwaNYv,Internal,GPP,NaN,U937-311cas9,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9304,STR-lkgw1v,False,"14, 17, 18",6,28,12,10,"10, 11, 12","8, 11, 12, 13","10, 13",8,"11, 12, 14","9, 14",16,13,"8, 11","22, 23, 25",2024-06-07,NaN,NaN,CX4019637,NaN,"X, Y",MC-000109-cK3a,NaN,NaN,PT-Zwpb82,Internal,GPP,NaN,NCIH3255,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9305,STR-fnFh09,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepA-p5,2024-08-13 15:46:14.862611+00:00,2024-08-13 15:46:14.862611+00:00
9306,STR-eo2Vx2,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepB-p5,2024-08-13 15:46:14.890555+00:00,2024-08-13 15:46:14.890555+00:00

In [18]:
str.head()

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11","11, 13","12, 13","9, 10","16, 18","11, 14","8, 10","18, 19",NaN,NaN,76M91400,CX4003615,matches reference; STR matches reference profi...,X,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,STR-Yv4hq7,False,16,7,31.3,18,"11.1, 15.1",12,12,10,9,"10, 13",11,NaN,"9, 14",NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-000713-IUJj,NaN,NaN,PT-FQOeFS,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41:01.795310+00:00,2024-06-13 16:41:01.795310+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11","9, 12",11,"8, 13",NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39:31.198745+00:00,2024-08-16 16:39:28.322066+00:00
3,STR-gifaLI,False,18,7,"30.3, 32.3","10, 14","7.1, 11.1","11, 13","11, 13","9, 12",9,"10, 12","8, 10",NaN,"13, 15",NaN,"22, 23",NaN,NaN,NaN,NaN,NaN,NaN,MC-000960-RI7G,NaN,NaN,PT-N5YXV2,Internal,WGS Inferred,NaN,NaN,2024-04-23 18:08:28.005757+00:00,2024-04-23 18:08:28.005757+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,"10, 11",12,"10, 11",NaN,"13, 15","11, 8",24,NaN,0.8696,NaN,NaN,NaN,NaN,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [19]:
str.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9307 entries, 0 to 9306
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            9307 non-null   object
 1   is_reference                  9307 non-null   bool
 2   d3s1358                       9233 non-null   object
 3   th01                          9252 non-null   object
 4   d21s11                        8006 non-null   object
 5   d18s51                        9086 non-null   object
 6   penta_e                       8918 non-null   object
 7   d5s818                        9187 non-null   object
 8   d13s317                       9184 non-null   object
 9   d7s820                        9234 non-null   object
 10  d16s539                       9254 non-null   object
 11  csf1po                        9264 non-null   object
 12  penta_d                       9005 non-null   object
 13  vwa                           7103 non-null   object
 14  d8s1179                       9159 non-null   object
 15  tpox                          8535 non-null   object
 16  fga                           9079 non-null   object
 17  pellet_creation_date          3036 non-null   object
 18  percentage_match_to_parental  1658 non-null   float64
 19  lab_corp_spec_nbr             2134 non-null   object
 20  lab_corp_case_nbr             7036 non-null   object
 21  comments                      1538 non-null   object
 22  amelogenin                    7093 non-null   object
 23  model_condition_id            8526 non-null   object
 24  mouse                         1828 non-null   object
 25  mycoplasma                    118 non-null    object
 26  patient_id                    9307 non-null   object
 27  source                        9307 non-null   object
 28  source_group                  9302 non-null   object
 29  pellet_submitted_date         601 non-null    object
 30  sample_reference              7078 non-null   object
 31  created_at                    9307 non-null   object
 32  updated_at                    9307 non-null   object
dtypes: bool(1), float64(1), object(31)
memory usage: 2.3+ MB

In [20]:
dates = str

In [21]:
dates['created_at'] = pd.to_datetime(dates['created_at']).dt.strftime('%Y-%m-%d %H:%M%z')
dates.head()

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11","11, 13","12, 13","9, 10","16, 18","11, 14","8, 10","18, 19",NaN,NaN,76M91400,CX4003615,matches reference; STR matches reference profi...,X,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00+0000,2024-04-09 16:00:46.668811+00:00
1,STR-Yv4hq7,False,16,7,31.3,18,"11.1, 15.1",12,12,10,9,"10, 13",11,NaN,"9, 14",NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-000713-IUJj,NaN,NaN,PT-FQOeFS,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41+0000,2024-06-13 16:41:01.795310+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11","9, 12",11,"8, 13",NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39+0000,2024-08-16 16:39:28.322066+00:00
3,STR-gifaLI,False,18,7,"30.3, 32.3","10, 14","7.1, 11.1","11, 13","11, 13","9, 12",9,"10, 12","8, 10",NaN,"13, 15",NaN,"22, 23",NaN,NaN,NaN,NaN,NaN,NaN,MC-000960-RI7G,NaN,NaN,PT-N5YXV2,Internal,WGS Inferred,NaN,NaN,2024-04-23 18:08+0000,2024-04-23 18:08:28.005757+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,"10, 11",12,"10, 11",NaN,"13, 15","11, 8",24,NaN,0.8696,NaN,NaN,NaN,NaN,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00+0000,2024-04-09 16:00:46.668811+00:00

In [22]:
dates['created_at'].value_counts()

created_at
2024-04-09 16:00+0000    3742
2024-08-13 15:46+0000    2201
2024-08-13 15:45+0000    1300
2024-08-13 14:32+0000    1200
2024-08-13 15:00+0000     100
2024-08-13 15:01+0000     100
2024-04-10 18:00+0000      42
2024-04-10 18:02+0000      42
2024-04-10 19:12+0000      38
2024-04-10 18:03+0000      38
2024-04-10 18:01+0000      37
2024-05-24 16:39+0000      33
2024-05-24 16:40+0000      24
2024-05-01 16:39+0000      22
2024-04-10 18:04+0000      22
2024-04-10 19:34+0000      20
2024-05-01 16:40+0000      18
2024-04-10 20:12+0000      18
2024-05-24 16:43+0000      16
2024-05-24 16:38+0000      15
2024-07-01 17:02+0000      13
2024-04-10 18:05+0000      12
2024-07-01 14:59+0000      12
2024-05-01 16:38+0000      11
2024-05-24 16:48+0000      10
2024-04-10 19:13+0000      10
2024-05-22 16:39+0000       7
2024-07-03 16:38+0000       7
2024-04-23 18:09+0000       7
2024-06-13 16:41+0000       6
2024-04-23 18:08+0000       5
2024-04-10 18:07+0000       5
2024-07-02 16:38+0000       5
2024-04-10 17:59+0000       4
2024-05-23 16:39+0000       4
2024-06-13 16:48+0000       4
2024-06-13 16:40+0000       4
2024-06-12 16:40+0000       4
2024-07-01 15:00+0000       3
2024-04-10 19:48+0000       3
2024-04-10 18:06+0000       3
2024-07-03 16:40+0000       3
2024-04-10 18:08+0000       3
2024-06-13 16:42+0000       3
2024-05-24 16:49+0000       3
2024-05-23 16:40+0000       3
2024-05-24 16:50+0000       3
2024-05-22 16:40+0000       3
2024-07-03 16:42+0000       3
2024-05-24 16:44+0000       3
2024-07-25 16:40+0000       3
2024-04-23 18:22+0000       3
2024-06-13 16:39+0000       2
2024-06-12 16:41+0000       2
2024-05-24 16:41+0000       2
2024-05-01 16:41+0000       2
2024-05-24 16:42+0000       2
2024-04-10 18:12+0000       2
2024-07-03 16:39+0000       2
2024-04-10 18:33+0000       2
2024-04-10 19:15+0000       2
2024-06-03 16:39+0000       2
2024-04-10 18:11+0000       2
2024-08-16 16:39+0000       2
2024-07-02 16:41+0000       2
2024-05-02 16:39+0000       2
2024-05-24 16:51+0000       2
2024-05-23 16:41+0000       2
2024-07-02 16:40+0000       2
2024-07-31 16:39+0000       2
2024-07-02 16:39+0000       2
2024-07-03 16:41+0000       2
2024-06-27 20:37+0000       1
2024-06-14 21:06+0000       1
2024-06-24 18:39+0000       1
2024-06-10 20:40+0000       1
2024-05-23 16:43+0000       1
2024-06-28 16:20+0000       1
2024-06-10 20:06+0000       1
2024-06-10 19:43+0000       1
2024-04-10 19:35+0000       1
2024-06-28 15:47+0000       1
2024-06-28 15:49+0000       1
2024-07-22 20:41+0000       1
2024-04-10 18:14+0000       1
2024-07-31 16:38+0000       1
2024-06-26 16:32+0000       1
2024-07-24 16:41+0000       1
2024-05-24 16:45+0000       1
2024-06-14 20:39+0000       1
2024-07-24 16:39+0000       1
2024-06-12 16:42+0000       1
2024-07-16 16:41+0000       1
2024-06-26 16:51+0000       1
2024-06-28 15:38+0000       1
2024-06-26 19:21+0000       1
2024-06-10 19:56+0000       1
2024-06-27 17:28+0000       1
2024-06-14 21:02+0000       1
2024-05-24 16:52+0000       1
2024-06-14 16:39+0000       1
2024-04-10 18:38+0000       1
2024-04-24 16:40+0000       1
2024-06-14 20:54+0000       1
2024-05-23 16:38+0000       1
2024-06-20 14:08+0000       1
2024-04-29 14:57+0000       1
2024-04-24 16:58+0000       1
2024-04-24 16:41+0000       1
2024-06-11 14:28+0000       1
2024-05-24 16:47+0000       1
2024-06-12 16:39+0000       1
2024-04-23 18:10+0000       1
2024-06-03 16:55+0000       1
2024-06-03 16:44+0000       1
2024-06-26 16:46+0000       1
2024-06-03 16:42+0000       1
2024-06-11 14:15+0000       1
2024-06-11 14:07+0000       1
2024-07-31 16:40+0000       1
2024-06-03 14:57+0000       1
2024-06-26 17:15+0000       1
2024-06-26 17:06+0000       1
2024-06-28 15:42+0000       1
2024-05-01 16:54+0000       1
2024-04-10 17:49+0000       1
2024-04-10 18:20+0000       1
2024-05-01 16:50+0000       1
2024-04-10 18:13+0000       1
2024-05-01 16:49+0000       1
2024-05-22 16:38+0000       1
2024-06-11 14:32+0000       1
2024-07-02 16:50+0000       1
2024-07-02 16:47+0000       1
2024-06-14 20:20+0000       1
2024-07-02 16:46+0000       1
2024-06-26 17:56+0000       1
2024-05-22 16:49+0000       1
2024-06-27 17:36+0000       1
Name: count, dtype: int64

In [23]:
time00 = '2024-08-13 15:00+0000'
dates00 = dates[dates['created_at'] == time00]
dates00.sort_values(by='sample_reference')

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
1709,STR-zsmFgI,False,"16, 18","6, 8","28, 32.2","12, 14","12, 21","12, 13","9, 12",10,11,"10, 11","11, 12","15, 17","12, 14","8, 11",22,NaN,NaN,NaN,CX4011162,NaN,"X, Y",MC-002681-4WzP,NaN,NaN,PT-2QAfke,Internal,GPP,NaN,538MGBA-311cas9,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1670,STR-OhLlEY,False,"16, 18","6, 8","28, 32.2","12, 14","12, 21","12, 13","9, 12",10,11,"10, 11","11, 12","15, 16, 17","12, 14","8, 11",22,NaN,NaN,NaN,CX4011955,NaN,"X, Y",MC-002681-4WzP,Not Detected,NaN,PT-2QAfke,Internal,GPP,NaN,538MGBA-311cas9-RepA-p6,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1317,STR-X75UtJ,False,"16, 18","8, 9","28, 32.2","1, 15","7, 10","11, 13","11, 12","10, 11","11, 12","11, 12","10, 13","16, 18","1, 12","8, 11","20, 23",NaN,NaN,NaN,CX4016034,NaN,"X, Y",MC-000070-XibM,NaN,NaN,PT-0yrZJC,Internal,GPP,NaN,697-311cas9(9/29/2016),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1120,STR-p6LROF,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4011162,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311Cas9-RepA (p6),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1128,STR-t8B72N,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4011162,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311Cas9-RepB (p6),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1149,STR-mXyHyr,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4009888,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311cas9,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1152,STR-0oYqpo,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4010243,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311cas9 Prensner-uORF,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1223,STR-ndKchg,False,17,"6, 8, 10","28, 30",14,"11, 22","11, 12","11, 12","8, 12",12,"10, 11","11, 12","15, 17","12, 14","8, 11",26,2023-11-09,NaN,NaN,CX4017928,NaN,X,MC-000433-fLcb,NaN,NaN,PT-0UOmyW,Internal,GPP,NaN,CAKI1,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1444,STR-AS3WEG,False,"13, 14, 15","6, 7","30, 31, 33.2, 34.2, 35.2","12, 13, 18","5, 13, 14","11, 12, 13",11,"9, 13","10, 13","10, 11, 13","10, 11","17, 19","12, 13","7, 8","22, 23, 24, 25",2024-06-07,NaN,NaN,CX4019637,NaN,X,MC-001738-adad,NaN,NaN,PT-1wfNxx,Internal,GPP,NaN,CCRFCEM-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1479,STR-oIoolA,False,"15, 17","6, 9.3","31.2, 32.2, 33.2, 34.2","13, 14, 16, 20, 21","8, 10, 12","9, 10, 12","8, 10, 11, 12","8, 10","9, 10, 11","10, 11","11, 12, 12.4, 14","18, 19","11, 12, 13","8, 10","19, 21, 22, 24",2024-06-14,NaN,NaN,CX4019638,NaN,"X, Y",MC-001738-adad,NaN,NaN,PT-1wfNxx,Internal,GPP,NaN,CCRFCEM-ubc-enCas12a-mch,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
989,STR-42bCys,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4010487,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
977,STR-gXdz7j,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4011254,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9-RepA-p6,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
979,STR-rZZq4u,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4011254,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9-RepB-p6,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
2018,STR-9VxpsY,False,15,"7, 9",30,14,"10, 12",11,11,"10, 12",10,12,9,14,"9, 10","8, 11",20,NaN,NaN,NaN,CX4014597,NaN,X,MC-002024-AOt6,NaN,NaN,PT-2Stxl0,Internal,GPP,NaN,ECC4,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1221,STR-z0ZMCt,False,"16, 17","8, 9.3",28,"17, 19","12, 13","13, 15","11, 12","11, 12",9,12,12,"16, 18","11, 13","8, 9",21,2023-03-09,NaN,NaN,CX4015874,NaN,X,MC-000835-jJ80,NaN,NaN,PT-0RBdNq,Internal,GPP,NaN,GCT-311Cas9(9/20/16),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1183,STR-JnS1HD,False,"15, 16",7,"29, 31.2",17,"7, 12",12,"8, 11","10, 11","11, 13",11,"11, 13",15,"13, 14, 15","8, 11","21, 22",2024-06-14,NaN,NaN,CX4019638,NaN,"X, Y",MC-002652-Q8UF,NaN,NaN,PT-0LOocN,Internal,GPP,NaN,GF-D8-ubc-enCas12a-mch,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1168,STR-0hvuAM,False,16,"8, 9.3",28,17,12,9,"8, 11","11, 12","9, 11",12,7,19,"13, 15",8,20,2024-02-16,NaN,NaN,CX4018633,NaN,X,MC-000712-GZtg,NaN,NaN,PT-0H6Zc0,Internal,GPP,NaN,HCC1833,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1816,STR-ayqJCk,False,18,7,29,14,"12, 19","10, 14","8, 9","10, 12","10, 12","12, 13","9, 11",14,"13, 14","8, 10","21, 23",2022-09-22,NaN,NaN,CX4014681,NaN,X,MC-000467-3FoK,NaN,NaN,PT-2RDjdA,Internal,GPP,NaN,HCC56,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1817,STR-yUFtQw,False,18,7,29,14,"12, 19","10, 14","8, 9","10, 12","10, 12","12, 13","9, 11",14,"13, 14","8, 10","21, 23",2024-01-25,NaN,NaN,CX4018415,NaN,X,MC-000467-3FoK,NaN,NaN,PT-2RDjdA,Internal,GPP,NaN,HCC56-Cas9VY,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1824,STR-VvJLaq,False,"12, 16, 17, 18, 19, 20","8, 9","29, 30","14, 15, 16, 17","13, 14","10, 11, 12","10, 12, 13","11, 12, 13","11, 12, 13, 14","7, 10","9, 13","15, 17, 18, 19, 20, 21, 22, 23, 24","11, 12, 13, 14, 15",8,"18, 23, 24, 25",2023-10-24,NaN,NaN,CX4017727,NaN,X,MC-000971-cQQl,NaN,NaN,PT-2Roqq2,Internal,GPP,NaN,HCT116,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1848,STR-yxAMA9,False,"12, 17, 18, 19, 20","8, 9","29, 30","16, 17, 18","12, 13, 14","10, 11, 12","10, 12, 13","11, 12, 13","11, 13, 14","7, 10","9, 13","16, 17, 18, 21, 22, 23","10, 11, 12, 13, 14, 15","8, 9","18, 22, 23, 24",2023-09-11,NaN,NaN,CX4017693,NaN,X,MC-000971-cQQl,NaN,NaN,PT-2Roqq2,Internal,GPP,NaN,HCT116-311Cas9,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1561,STR-AeqExd,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4011831,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-HB-SetC-p4,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1576,STR-vSkM5e,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4011831,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-HB-SetD-p4,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1613,STR-hnJqpk,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 12, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4011831,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-LB-SetC-p4,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1589,STR-HTfZzi,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4010882,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-SetC-p4,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1603,STR-2E5ck7,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4010882,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-SetD-p4,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1608,STR-wiOhj0,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4010578,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-encas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1413,STR-esfByH,False,16,9,"30, 31","13, 15","10, 12","9, 13","10, 13","9, 10","9, 11",12,9,"16, 18","11, 15",11,"23, 24",NaN,NaN,NaN,CX4009997,NaN,"X, Y",MC-001528-qmGv,NaN,NaN,PT-1Qm9m0,Internal,GPP,NaN,IHH4-311cas9-RepA-p6,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1211,STR-J1JJiG,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-12-15,NaN,NaN,CX4018283,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1212,STR-ZqdRm1,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-06-20,NaN,NaN,CX4016823,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1-Cas9VY,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1214,STR-1bi44J,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-12-04,NaN,NaN,CX4018126,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1-Cas9VY-ParalogV2-RepA-P6(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1220,STR-lZRfx5,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-12-04,NaN,NaN,CX4018126,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1-Cas9VY-ParalogV2-RepB-P6(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1530,STR-kSi90l,False,"16, 16.2",9.3,"29, 36",14,"11, 12",12,"11, 12","10, 11","9, 10",12,"9, 13","16, 19","13, 14, 15","8, 11",19,2023-11-16,NaN,NaN,CX4018027,NaN,"X, Y",MC-002923-TlcE,NaN,NaN,PT-22FXN6,Internal,GPP,NaN,LAI5S-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1533,STR-qF8tzP,False,"16, 16.2","8, 9.3","29, 35, 36",14,"11, 12",12,"11, 12",10,9,12,"9, 13","16, 19","13, 14","8, 11","19, 24",2023-08-03,NaN,NaN,CX4017165,NaN,"X, Y",MC-002670-e9s1,NaN,NaN,PT-22FXN6,Internal,GPP,NaN,LAN1,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1539,STR-zG0TEY,False,16.2,"8, 9.3","29, 36",14,"11, 12",12,"11, 12",10,9,12,"9, 13","16, 19","13, 14","8, 11","19, 24",2023-09-22,NaN,NaN,CX4017693,NaN,"X, Y",MC-002670-e9s1,NaN,NaN,PT-22FXN6,Internal,GPP,NaN,LAN1-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1184,STR-ZiY4IO,False,"16, 18",7,29,"14, 16",17,"12, 13",12,"7, 10","12, 14",12,12,"15, 17",15,"8, 9",24,2024-04-02,NaN,NaN,CX4019014,NaN,X,MC-001804-JH97,NaN,NaN,PT-0lPf2W,Internal,GPP,NaN,LPS510-311cas9,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1003,STR-DpTAJs,False,16,9,"29, 33.1","13, 15",5,13,11,12,9,11,"9, 10",17,"11, 13","8, 12","22, 23",NaN,NaN,NaN,CX4011714,NaN,"X, Y",MC-002052-GfvX,NaN,NaN,PT-0531Uw,Internal,GPP,NaN,LU139-311cas9,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1001,STR-KuSguX,False,16,9,"29, 33.1","13, 15",5,13,11,12,9,11,"9, 10",17,"11, 13","8, 12","22, 23",NaN,NaN,NaN,CX4014375,NaN,"X, Y",MC-002052-GfvX,NaN,NaN,PT-0531Uw,Internal,GPP,NaN,LU139-311cas9-RepB-p5,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1269,STR-rTCCEz,False,16,9.3,"30, 32.2","12, 15","8, 14","10, 11",11,"9, 12","11, 12",12,"12, 13",17,15,"8, 11","20, 24",NaN,NaN,NaN,CX4013483,NaN,X,MC-000934-sl2O,NaN,NaN,PT-0VWXIm,Internal,GPP,NaN,MDAMB361-enCas12a 10xB,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1323,STR-KDTYit,False,"15, 16, 17","6, 8","29, 30","13, 17, 18","14, 16",12,"12, 13, 14","8, 10","11, 13, 14","11, 12, 13","8, 13",17,"9, 13, 14, 15, 16",8,"21, 22, 23, 24",2023-10-06,NaN,NaN,CX4017694,NaN,"X, Y",MC-000964-tTts,NaN,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1335,STR-ODz4cB,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",NaN,NaN,NaN,CX4010578,NaN,X,MC-000964-tTts,Not Detected,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3 restock,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1381,STR-8oonkP,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",2020-11-12,NaN,NaN,CX4010790,NaN,X,MC-000964-tTts,Not Detected,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3(11/12/2020),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1384,STR-gULc78,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",2020-07-16,NaN,NaN,CX4010790,NaN,X,MC-000964-tTts,Not Detected,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3(12/10/2020),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1350,STR-bx3Gks,False,"15, 16, 17","6, 8","29, 30, 31","13, 17, 18","14, 16",12,"12, 13","8, 10","11, 13, 14","11, 12","8, 13","17, 18","9, 13, 14, 15, 16",8,"21, 22, 23, 24",2023-05-19,NaN,NaN,CX4016391,NaN,"X, Y",MC-000964-tTts,NaN,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1349,STR-QmVPI0,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",NaN,NaN,NaN,CX4010790,NaN,X,MC-000964-tTts,NaN,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3_MOLT4(8/11/2020),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1555,STR-lh8MRK,False,17,8,30,"17, 18",8,11,12,10,13,11,"9, 13",17,14,11,20,2023-10-23,NaN,NaN,CX4017727,NaN,X,MC-001993-EcIk,NaN,NaN,PT-22pOAT,Internal,GPP,NaN,NALM16,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1007,STR-of8RDy,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",NaN,NaN,NaN,CX4013811,NaN,"X, Y",MC-000586-9LVL,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1876-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1060,STR-VzjdbF,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",2022-08-04,NaN,NaN,CX4014497,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1061,STR-H82Tw4,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",2022-12-06,NaN,NaN,CX4015425,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1027,STR-btr7ng,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",2023-06-13,NaN,NaN,CX4016824,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne C+DA-P4(D15),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1031,STR-lbMO4y,False,17,"6, 9.3, 10",29,18,13,11,12,"10, 12",12,11,"12, 13",17,"10, 12, 14","8, 9","21, 24",2023-06-13,NaN,NaN,CX4016824,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne C+DB-P4(D15),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1036,STR-VmupVK,False,"1, 16","1, 5","1, 28","1, 17","1, 12","1, 10","1, 11","10, 12","1, 11","1, 10","12, 13","1, 16","12, 14","8, 9","21, 24",NaN,NaN,NaN,CX4015911,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne-RepA-P6(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1046,STR-UcOspF,False,"1, 16","1, 5","1, 28","1, 17","1, 12","1, 10","1, 11","10, 12","1, 11","1, 10","12, 13","1, 16","12, 14","8, 9","21, 24",NaN,NaN,NaN,CX4015911,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne-RepB-P6(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1085,STR-PJzfG0,False,"15, 18","6, 7","28, 31","18, 19","5, 11",11,11,"11, 12",11,13,"8, 11","17, 18","14, 15",8,"21, 25",2024-04-11,NaN,NaN,CX4019190,NaN,X,MC-000414-MWUF,NaN,NaN,PT-0Fp6tq,Internal,GPP,NaN,NCIH1944-Cas9VY,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1485,STR-pXG1OE,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 14","9, 11",14,13,8,25,2022-11-11,NaN,NaN,CX4015205,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1510,STR-xHyQoG,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 13, 14","9, 11",14,13,8,25,2022-12-09,NaN,NaN,CX4015425,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1514,STR-7RB2rl,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 14","9, 11",14,13,8,25,2024-03-01,NaN,NaN,CX4018752,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2-enCas12a-HumagneCD-RepA-P3(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1529,STR-IiUIG5,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 14","9, 11",14,13,8,25,2024-03-01,NaN,NaN,CX4018752,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2-enCas12a-HumagneCD-RepB-P3(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1419,STR-KMMV8l,False,"16, 17","6, 9.3","28, 31",16,"7, 14","11, 12","11, 12",8,"10, 11","10, 13",10,"19, 20","13, 14",8,22,2023-05-23,NaN,NaN,CX4016392,NaN,X,MC-001368-TN5O,NaN,NaN,PT-1Sm4U9,Internal,GPP,NaN,OACM51-311Cas9-ParalogV2-RepA-P6(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1443,STR-jUolwq,False,"16, 17","6, 9.3","28, 31",16,"7, 14","11, 12","11, 12",8,"10, 11","10, 13",10,"19, 20","13, 14",8,22,2023-05-23,NaN,NaN,CX4016392,NaN,X,MC-001368-TN5O,NaN,NaN,PT-1Sm4U9,Internal,GPP,NaN,OACM51-311Cas9-ParalogV2-RepB-P6(D21),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1092,STR-YtsDbR,False,"14, 21",6,29,15,"7, 11","10, 12",11,12,11,12,10,"14, 17","13, 15","9, 11","20, 24",NaN,NaN,NaN,CX4011363,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1114,STR-mTJVvD,False,"14, 16","7, 9.3","28, 31.2, 32.2","17, 18, 19","11, 18","10, 11","10, 11, 12","8, 12","10, 11, 12","11, 13, 14",9,"18, 19, 21, 22, 23, 24",13,11,"18, 19, 23, 24",NaN,NaN,NaN,CX4011713,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X(from DMX),2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1094,STR-g41LKE,False,"14, 21",6,29,15,"7, 11","10, 12",11,12,11,12,10,"14, 17","13, 15","9, 11","20, 24",NaN,NaN,NaN,CX4011363,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X-311cas9,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1096,STR-wG06Uy,False,14,6,29,15,"7, 11","10, 12",11,12,11,12,10,"14, 17","12, 13, 15","9, 11","20, 24",NaN,NaN,NaN,CX4010790,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
1062,STR-yReXFj,False,"15, 17","6, 9.3","29, 32.2",17,"7, 16",13,12,11,"11, 14",10,"11, 13",17,"13, 15",11,"18, 24",2024-06-24,NaN,NaN,CX4019638,NaN,X,MC-003612-l0w8,Positive,NaN,PT-0eB7jK,Internal,GPP,NaN,OS766-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
2034,STR-6G2z8s,False,"17, 19",6,"28, 30",17,"7, 13","12, 13","9, 11","10, 13","8, 12","10, 12","8, 11","15, 18","13, 15",8,"19, 21",2022-10-06,NaN,NaN,CX4014972,NaN,X,MC-003106-p5ta,NaN,NaN,PT-2ZzFHs,Internal,GPP,NaN,RC,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00
2048,STR-R4zcDd,False,"17, 19",6,"28, 30",17,"7, 13","12, 13","9, 11","10, 13","8, 12","10, 12","8, 11","15, 18","13, 15",8,"19, 21",2022-11-22,NaN,NaN,CX4015204,NaN,X,MC-003106-p5ta,NaN,NaN,PT-2ZzFHs,Internal,GPP,NaN,RC-enCas12a,2024-08-13 15:00+0000,2024-08-13 15:00:15.893191+00:00

In [24]:
time01 = '2024-08-13 15:01+0000'
dates01 = dates[dates['created_at'] == time01]
dates01.sort_values(by='sample_reference')

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
2645,STR-sqHrMF,False,"16, 18","6, 8","28, 32.2","12, 14","12, 21","12, 13","9, 12",10,11,"10, 11","11, 12","15, 17","12, 14","8, 11",22,NaN,NaN,NaN,CX4011162,NaN,"X, Y",MC-002681-4WzP,NaN,NaN,PT-2QAfke,Internal,GPP,NaN,538MGBA-311cas9,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2635,STR-dfskqJ,False,"16, 18","6, 8","28, 32.2","12, 14","12, 21","12, 13","9, 12",10,11,"10, 11","11, 12","15, 16, 17","12, 14","8, 11",22,NaN,NaN,NaN,CX4011955,NaN,"X, Y",MC-002681-4WzP,Not Detected,NaN,PT-2QAfke,Internal,GPP,NaN,538MGBA-311cas9-RepA-p6,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2309,STR-7bPokG,False,"16, 18","8, 9","28, 32.2","1, 15","7, 10","11, 13","11, 12","10, 11","11, 12","11, 12","10, 13","16, 18","1, 12","8, 11","20, 23",NaN,NaN,NaN,CX4016034,NaN,"X, Y",MC-000070-XibM,NaN,NaN,PT-0yrZJC,Internal,GPP,NaN,697-311cas9(9/29/2016),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2241,STR-3zmZyE,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4011162,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311Cas9-RepA (p6),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2242,STR-PuV6dm,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4011162,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311Cas9-RepB (p6),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2247,STR-141pbF,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4009888,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311cas9,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2252,STR-3FvS6J,False,"15, 16","7, 9","29, 33.2","13, 14","12, 17",12,"11, 13","9, 12","11, 12","10, 12","9, 11","16, 18","13, 15","8, 11",22,NaN,NaN,NaN,CX4010243,NaN,X,MC-000160-11p8,NaN,NaN,PT-0GrZ0k,Internal,GPP,NaN,BT12-311cas9 Prensner-uORF,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2283,STR-XYld7i,False,17,"6, 8, 10","28, 30",14,"11, 22","11, 12","11, 12","8, 12",12,"10, 11","11, 12","15, 17","12, 14","8, 11",26,2023-11-09,NaN,NaN,CX4017928,NaN,X,MC-000433-fLcb,NaN,NaN,PT-0UOmyW,Internal,GPP,NaN,CAKI1,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2377,STR-OOsezH,False,"13, 14, 15","6, 7","30, 31, 33.2, 34.2, 35.2","12, 13, 18","5, 13, 14","11, 12, 13",11,"9, 13","10, 13","10, 11, 13","10, 11","17, 19","12, 13","7, 8","22, 23, 24, 25",2024-06-07,NaN,NaN,CX4019637,NaN,X,MC-001738-adad,NaN,NaN,PT-1wfNxx,Internal,GPP,NaN,CCRFCEM-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2381,STR-b85Kk5,False,"15, 17","6, 9.3","31.2, 32.2, 33.2, 34.2","13, 14, 16, 20, 21","8, 10, 12","9, 10, 12","8, 10, 11, 12","8, 10","9, 10, 11","10, 11","11, 12, 12.4, 14","18, 19","11, 12, 13","8, 10","19, 21, 22, 24",2024-06-14,NaN,NaN,CX4019638,NaN,"X, Y",MC-001738-adad,NaN,NaN,PT-1wfNxx,Internal,GPP,NaN,CCRFCEM-ubc-enCas12a-mch,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2168,STR-RUIlYU,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4010487,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2160,STR-XOid31,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4011254,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9-RepA-p6,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2165,STR-1YntnD,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4011254,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9-RepB-p6,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2960,STR-rgoBlk,False,15,"7, 9",30,14,"10, 12",11,11,"10, 12",10,12,9,14,"9, 10","8, 11",20,NaN,NaN,NaN,CX4014597,NaN,X,MC-002024-AOt6,NaN,NaN,PT-2Stxl0,Internal,GPP,NaN,ECC4,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2278,STR-6LfFkz,False,"16, 17","8, 9.3",28,"17, 19","12, 13","13, 15","11, 12","11, 12",9,12,12,"16, 18","11, 13","8, 9",21,2023-03-09,NaN,NaN,CX4015874,NaN,X,MC-000835-jJ80,NaN,NaN,PT-0RBdNq,Internal,GPP,NaN,GCT-311Cas9(9/20/16),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2259,STR-tbKIdY,False,"15, 16",7,"29, 31.2",17,"7, 12",12,"8, 11","10, 11","11, 13",11,"11, 13",15,"13, 14, 15","8, 11","21, 22",2024-06-14,NaN,NaN,CX4019638,NaN,"X, Y",MC-002652-Q8UF,NaN,NaN,PT-0LOocN,Internal,GPP,NaN,GF-D8-ubc-enCas12a-mch,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2253,STR-nGG9aQ,False,16,"8, 9.3",28,17,12,9,"8, 11","11, 12","9, 11",12,7,19,"13, 15",8,20,2024-02-16,NaN,NaN,CX4018633,NaN,X,MC-000712-GZtg,NaN,NaN,PT-0H6Zc0,Internal,GPP,NaN,HCC1833,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2791,STR-FcPRtj,False,18,7,29,14,"12, 19","10, 14","8, 9","10, 12","10, 12","12, 13","9, 11",14,"13, 14","8, 10","21, 23",2022-09-22,NaN,NaN,CX4014681,NaN,X,MC-000467-3FoK,NaN,NaN,PT-2RDjdA,Internal,GPP,NaN,HCC56,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2792,STR-NjxaWS,False,18,7,29,14,"12, 19","10, 14","8, 9","10, 12","10, 12","12, 13","9, 11",14,"13, 14","8, 10","21, 23",2024-01-25,NaN,NaN,CX4018415,NaN,X,MC-000467-3FoK,NaN,NaN,PT-2RDjdA,Internal,GPP,NaN,HCC56-Cas9VY,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2796,STR-gZxJDh,False,"12, 16, 17, 18, 19, 20","8, 9","29, 30","14, 15, 16, 17","13, 14","10, 11, 12","10, 12, 13","11, 12, 13","11, 12, 13, 14","7, 10","9, 13","15, 17, 18, 19, 20, 21, 22, 23, 24","11, 12, 13, 14, 15",8,"18, 23, 24, 25",2023-10-24,NaN,NaN,CX4017727,NaN,X,MC-000971-cQQl,NaN,NaN,PT-2Roqq2,Internal,GPP,NaN,HCT116,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2797,STR-oOBgJH,False,"12, 17, 18, 19, 20","8, 9","29, 30","16, 17, 18","12, 13, 14","10, 11, 12","10, 12, 13","11, 12, 13","11, 13, 14","7, 10","9, 13","16, 17, 18, 21, 22, 23","10, 11, 12, 13, 14, 15","8, 9","18, 22, 23, 24",2023-09-11,NaN,NaN,CX4017693,NaN,X,MC-000971-cQQl,NaN,NaN,PT-2Roqq2,Internal,GPP,NaN,HCT116-311Cas9,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2463,STR-p0lWox,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4011831,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-HB-SetC-p4,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2466,STR-2iJwsa,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4011831,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-HB-SetD-p4,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2561,STR-q4ibRy,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 12, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4011831,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-LB-SetC-p4,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2471,STR-rX2J43,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4010882,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-SetC-p4,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2505,STR-X326GN,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4010882,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-enCas12a-SetD-p4,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2523,STR-KosQTt,False,"14, 16","6, 8","27, 33.2","12, 14","13, 15","11, 12","8, 12",11,"9, 10","9, 13","13, 14","18, 20","12, 13","8, 11","21.2, 22",NaN,NaN,NaN,CX4010578,NaN,"X, Y",MC-000067-Fdh5,Not Detected,NaN,PT-25yL7C,Internal,GPP,NaN,HS683-encas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2334,STR-0RogKJ,False,16,9,"30, 31","13, 15","10, 12","9, 13","10, 13","9, 10","9, 11",12,9,"16, 18","11, 15",11,"23, 24",NaN,NaN,NaN,CX4009997,NaN,"X, Y",MC-001528-qmGv,NaN,NaN,PT-1Qm9m0,Internal,GPP,NaN,IHH4-311cas9-RepA-p6,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2269,STR-zWuiDq,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-12-15,NaN,NaN,CX4018283,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2270,STR-jozdGV,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-06-20,NaN,NaN,CX4016823,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1-Cas9VY,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2274,STR-F68D03,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-12-04,NaN,NaN,CX4018126,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1-Cas9VY-ParalogV2-RepA-P6(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2277,STR-lfyMMw,False,15,9.3,29,13,"11, 18","12, 13",11,"10, 12",10,12,9,16,"10, 14","8, 11",22,2023-12-04,NaN,NaN,CX4018126,NaN,X,MC-001853-bIA7,NaN,NaN,PT-0MsFyj,Internal,GPP,NaN,KMCH1-Cas9VY-ParalogV2-RepB-P6(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2430,STR-zTGSYe,False,"16, 16.2",9.3,"29, 36",14,"11, 12",12,"11, 12","10, 11","9, 10",12,"9, 13","16, 19","13, 14, 15","8, 11",19,2023-11-16,NaN,NaN,CX4018027,NaN,"X, Y",MC-002923-TlcE,NaN,NaN,PT-22FXN6,Internal,GPP,NaN,LAI5S-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2438,STR-InHQBz,False,"16, 16.2","8, 9.3","29, 35, 36",14,"11, 12",12,"11, 12",10,9,12,"9, 13","16, 19","13, 14","8, 11","19, 24",2023-08-03,NaN,NaN,CX4017165,NaN,"X, Y",MC-002670-e9s1,NaN,NaN,PT-22FXN6,Internal,GPP,NaN,LAN1,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2443,STR-qPZTlL,False,16.2,"8, 9.3","29, 36",14,"11, 12",12,"11, 12",10,9,12,"9, 13","16, 19","13, 14","8, 11","19, 24",2023-09-22,NaN,NaN,CX4017693,NaN,"X, Y",MC-002670-e9s1,NaN,NaN,PT-22FXN6,Internal,GPP,NaN,LAN1-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2260,STR-1uXSin,False,"16, 18",7,29,"14, 16",17,"12, 13",12,"7, 10","12, 14",12,12,"15, 17",15,"8, 9",24,2024-04-02,NaN,NaN,CX4019014,NaN,X,MC-001804-JH97,NaN,NaN,PT-0lPf2W,Internal,GPP,NaN,LPS510-311cas9,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2177,STR-Ek508f,False,16,9,"29, 33.1","13, 15",5,13,11,12,9,11,"9, 10",17,"11, 13","8, 12","22, 23",NaN,NaN,NaN,CX4011714,NaN,"X, Y",MC-002052-GfvX,NaN,NaN,PT-0531Uw,Internal,GPP,NaN,LU139-311cas9,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2172,STR-olE2jz,False,16,9,"29, 33.1","13, 15",5,13,11,12,9,11,"9, 10",17,"11, 13","8, 12","22, 23",NaN,NaN,NaN,CX4014375,NaN,"X, Y",MC-002052-GfvX,NaN,NaN,PT-0531Uw,Internal,GPP,NaN,LU139-311cas9-RepB-p5,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2284,STR-00xTEh,False,16,9.3,"30, 32.2","12, 15","8, 14","10, 11",11,"9, 12","11, 12",12,"12, 13",17,15,"8, 11","20, 24",NaN,NaN,NaN,CX4013483,NaN,X,MC-000934-sl2O,NaN,NaN,PT-0VWXIm,Internal,GPP,NaN,MDAMB361-enCas12a 10xB,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2312,STR-eEqQw3,False,"15, 16, 17","6, 8","29, 30","13, 17, 18","14, 16",12,"12, 13, 14","8, 10","11, 13, 14","11, 12, 13","8, 13",17,"9, 13, 14, 15, 16",8,"21, 22, 23, 24",2023-10-06,NaN,NaN,CX4017694,NaN,"X, Y",MC-000964-tTts,NaN,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2313,STR-MVaSdD,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",NaN,NaN,NaN,CX4010578,NaN,X,MC-000964-tTts,Not Detected,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3 restock,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2322,STR-Gbgntt,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",2020-11-12,NaN,NaN,CX4010790,NaN,X,MC-000964-tTts,Not Detected,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3(11/12/2020),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2329,STR-vnKBnn,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",2020-07-16,NaN,NaN,CX4010790,NaN,X,MC-000964-tTts,Not Detected,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3(12/10/2020),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2315,STR-n4sdr4,False,"15, 16, 17","6, 8","29, 30, 31","13, 17, 18","14, 16",12,"12, 13","8, 10","11, 13, 14","11, 12","8, 13","17, 18","9, 13, 14, 15, 16",8,"21, 22, 23, 24",2023-05-19,NaN,NaN,CX4016391,NaN,"X, Y",MC-000964-tTts,NaN,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2314,STR-hC58i8,False,"15, 18","8, 9.3","29, 30","15, 20","5, 17",9,"11, 13","8, 9","11, 12",10,"9, 10",15,"10, 13","8, 11","23, 24",NaN,NaN,NaN,CX4010790,NaN,X,MC-000964-tTts,NaN,NaN,PT-1559gB,Internal,GPP,NaN,MOLT3_MOLT4(8/11/2020),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2451,STR-0VGW7Q,False,17,8,30,"17, 18",8,11,12,10,13,11,"9, 13",17,14,11,20,2023-10-23,NaN,NaN,CX4017727,NaN,X,MC-001993-EcIk,NaN,NaN,PT-22pOAT,Internal,GPP,NaN,NALM16,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2183,STR-0GolK3,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",NaN,NaN,NaN,CX4013811,NaN,"X, Y",MC-000586-9LVL,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1876-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2212,STR-J2R41g,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",2022-08-04,NaN,NaN,CX4014497,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2227,STR-3cm7n5,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",2022-12-06,NaN,NaN,CX4015425,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2198,STR-Xfddcq,False,17,6,29,18,13,11,12,"10, 12",12,11,"12, 13",17,"12, 14","8, 9","21, 24",2023-06-13,NaN,NaN,CX4016824,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne C+DA-P4(D15),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2199,STR-kGbMC2,False,17,"6, 9.3, 10",29,18,13,11,12,"10, 12",12,11,"12, 13",17,"10, 12, 14","8, 9","21, 24",2023-06-13,NaN,NaN,CX4016824,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne C+DB-P4(D15),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2206,STR-gt5Cd4,False,"1, 16","1, 5","1, 28","1, 17","1, 12","1, 10","1, 11","10, 12","1, 11","1, 10","12, 13","1, 16","12, 14","8, 9","21, 24",NaN,NaN,NaN,CX4015911,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne-RepA-P6(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2207,STR-KbTXCj,False,"1, 16","1, 5","1, 28","1, 17","1, 12","1, 10","1, 11","10, 12","1, 11","1, 10","12, 13","1, 16","12, 14","8, 9","21, 24",NaN,NaN,NaN,CX4015911,NaN,"X, Y",MC-002490-4KoT,NaN,NaN,PT-0a2F5a,Internal,GPP,NaN,NCIH1882-enCas12a-Humagne-RepB-P6(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2235,STR-A1SkaS,False,"15, 18","6, 7","28, 31","18, 19","5, 11",11,11,"11, 12",11,13,"8, 11","17, 18","14, 15",8,"21, 25",2024-04-11,NaN,NaN,CX4019190,NaN,X,MC-000414-MWUF,NaN,NaN,PT-0Fp6tq,Internal,GPP,NaN,NCIH1944-Cas9VY,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2394,STR-WwlMSJ,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 14","9, 11",14,13,8,25,2022-11-11,NaN,NaN,CX4015205,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2409,STR-0nprN8,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 13, 14","9, 11",14,13,8,25,2022-12-09,NaN,NaN,CX4015425,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2410,STR-DNMc97,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 14","9, 11",14,13,8,25,2024-03-01,NaN,NaN,CX4018752,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2-enCas12a-HumagneCD-RepA-P3(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2419,STR-JsDF1O,False,15,"7, 9.3","28, 32.2","12, 21","12, 16",12,11,"10, 11","11, 12","11, 14","9, 11",14,13,8,25,2024-03-01,NaN,NaN,CX4018752,NaN,X,MC-003184-xxvb,NaN,NaN,PT-21NMVa,Internal,GPP,NaN,NRHLMS2-enCas12a-HumagneCD-RepB-P3(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2351,STR-O4hOcO,False,"16, 17","6, 9.3","28, 31",16,"7, 14","11, 12","11, 12",8,"10, 11","10, 13",10,"19, 20","13, 14",8,22,2023-05-23,NaN,NaN,CX4016392,NaN,X,MC-001368-TN5O,NaN,NaN,PT-1Sm4U9,Internal,GPP,NaN,OACM51-311Cas9-ParalogV2-RepA-P6(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2365,STR-m5nZhF,False,"16, 17","6, 9.3","28, 31",16,"7, 14","11, 12","11, 12",8,"10, 11","10, 13",10,"19, 20","13, 14",8,22,2023-05-23,NaN,NaN,CX4016392,NaN,X,MC-001368-TN5O,NaN,NaN,PT-1Sm4U9,Internal,GPP,NaN,OACM51-311Cas9-ParalogV2-RepB-P6(D21),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2236,STR-eNIpyk,False,"14, 21",6,29,15,"7, 11","10, 12",11,12,11,12,10,"14, 17","13, 15","9, 11","20, 24",NaN,NaN,NaN,CX4011363,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2240,STR-gT4Bwa,False,"14, 16","7, 9.3","28, 31.2, 32.2","17, 18, 19","11, 18","10, 11","10, 11, 12","8, 12","10, 11, 12","11, 13, 14",9,"18, 19, 21, 22, 23, 24",13,11,"18, 19, 23, 24",NaN,NaN,NaN,CX4011713,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X(from DMX),2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2237,STR-mbIygQ,False,"14, 21",6,29,15,"7, 11","10, 12",11,12,11,12,10,"14, 17","13, 15","9, 11","20, 24",NaN,NaN,NaN,CX4011363,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X-311cas9,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2238,STR-TzOSy7,False,14,6,29,15,"7, 11","10, 12",11,12,11,12,10,"14, 17","12, 13, 15","9, 11","20, 24",NaN,NaN,NaN,CX4010790,NaN,X,MC-001369-jLCX,NaN,NaN,PT-0GisSs,Internal,GPP,NaN,OCIC5X-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2231,STR-Qbtusy,False,"15, 17","6, 9.3","29, 32.2",17,"7, 16",13,12,11,"11, 14",10,"11, 13",17,"13, 15",11,"18, 24",2024-06-24,NaN,NaN,CX4019638,NaN,X,MC-003612-l0w8,Positive,NaN,PT-0eB7jK,Internal,GPP,NaN,OS766-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2961,STR-IXdfDz,False,"17, 19",6,"28, 30",17,"7, 13","12, 13","9, 11","10, 13","8, 12","10, 12","8, 11","15, 18","13, 15",8,"19, 21",2022-10-06,NaN,NaN,CX4014972,NaN,X,MC-003106-p5ta,NaN,NaN,PT-2ZzFHs,Internal,GPP,NaN,RC,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00
2973,STR-BQNjj3,False,"17, 19",6,"28, 30",17,"7, 13","12, 13","9, 11","10, 13","8, 12","10, 12","8, 11","15, 18","13, 15",8,"19, 21",2022-11-22,NaN,NaN,CX4015204,NaN,X,MC-003106-p5ta,NaN,NaN,PT-2ZzFHs,Internal,GPP,NaN,RC-enCas12a,2024-08-13 15:01+0000,2024-08-13 15:01:15.012495+00:00

In [25]:
time02 = '2024-08-13 14:32+0000'
dates02 = dates[dates['created_at'] == time02]
dates02.sort_values(by='sample_reference')

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
5736,STR-rDFTNG,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4011713,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9,2024-08-13 14:32+0000,2024-08-13 14:32:29.586872+00:00
5734,STR-2Meekr,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4013151,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9-RepA-p6,2024-08-13 14:32+0000,2024-08-13 14:32:29.586872+00:00
5735,STR-FrqZPV,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4013151,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9-RepB-p6,2024-08-13 14:32+0000,2024-08-13 14:32:29.586872+00:00
5541,STR-Qjt2wK,False,15,"6, 9.3",29,"11, 13",11,"10, 12",9,9,"9, 12","10, 12",13,"17, 18",11,"8, 11","23, 24",NaN,NaN,NaN,CX4013759,NaN,X,MC-000011-bxAg,NaN,NaN,PT-AR7W9o,Internal,GPP,NaN,253J-311Cas9-ParalogV2-RepB-P6,2024-08-13 14:32+0000,2024-08-13 14:32:29.468693+00:00
5542,STR-7q3ZvN,False,15,"6, 9.3",29,"11, 13",11,"10, 12",9,9,"9, 12","10, 12",13,"17, 18",11,"8, 11","23, 24",NaN,NaN,NaN,CX4013655,NaN,X,MC-000011-bxAg,NaN,NaN,PT-AR7W9o,Internal,GPP,NaN,253J-311Cas9-RepA-p6-PV2,2024-08-13 14:32+0000,2024-08-13 14:32:29.468693+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5751,STR-dlLyhI,False,"15, 18","6, 7","30, 32","13, 16","5, 18","11, 12","8, 13","7, 10","11, 13",12,"11, 15",18,"10, 14",8,"22, 25",2024-05-08,0.9811,NaN,CX4019383,NaN,X,MC-003102-LSn8,NaN,NaN,PT-DD5K0b,Internal,GPP,NaN,Z33-enCas12a,2024-08-13 14:32+0000,2024-08-13 14:32:29.586872+00:00
5750,STR-RYhDlf,False,"15, 18","6, 7","30, 32","13, 16","5, 18","11, 12","8, 13","7, 10","11, 13",12,"11, 15",18,"10, 14",8,"22, 25",2023-06-08,0.9811,NaN,CX4016534,NaN,X,MC-003102-LSn8,NaN,NaN,PT-DD5K0b,Internal,GPP,NaN,Z33-enCas12a,2024-08-13 14:32+0000,2024-08-13 14:32:29.586872+00:00
6273,STR-l7HaWl,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4010632,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a,2024-08-13 14:32+0000,2024-08-13 14:32:29.862597+00:00
6274,STR-g4j02b,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4011038,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a-SetC-p4,2024-08-13 14:32+0000,2024-08-13 14:32:29.862597+00:00
6275,STR-B8kytr,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4011038,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a-SetD-p4,2024-08-13 14:32+0000,2024-08-13 14:32:29.862597+00:00

In [26]:
time03 = '2024-08-13 15:45+0000'
dates03 = dates[dates['created_at'] == time03]
dates03.sort_values(by='sample_reference')

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
6470,STR-oUIHWB,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4011713,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9,2024-08-13 15:45+0000,2024-08-13 15:45:03.664258+00:00
6468,STR-MOzWvA,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4013151,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9-RepA-p6,2024-08-13 15:45+0000,2024-08-13 15:45:03.664258+00:00
6469,STR-b6EueM,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4013151,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9-RepB-p6,2024-08-13 15:45+0000,2024-08-13 15:45:03.664258+00:00
5082,STR-VHsDy2,False,15,"6, 9.3",29,"11, 13",11,"10, 12",9,9,"9, 12","10, 12",13,"17, 18",11,"8, 11","23, 24",NaN,NaN,NaN,CX4013759,NaN,X,MC-000011-bxAg,NaN,NaN,PT-AR7W9o,Internal,GPP,NaN,253J-311Cas9-ParalogV2-RepB-P6,2024-08-13 15:45+0000,2024-08-13 15:45:03.572151+00:00
5083,STR-YAtTgY,False,15,"6, 9.3",29,"11, 13",11,"10, 12",9,9,"9, 12","10, 12",13,"17, 18",11,"8, 11","23, 24",NaN,NaN,NaN,CX4013655,NaN,X,MC-000011-bxAg,NaN,NaN,PT-AR7W9o,Internal,GPP,NaN,253J-311Cas9-RepA-p6-PV2,2024-08-13 15:45+0000,2024-08-13 15:45:03.572151+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6484,STR-2IHTTR,False,"15, 18","6, 7","30, 32","13, 16","5, 18","11, 12","8, 13","7, 10","11, 13",12,"11, 15",18,"10, 14",8,"22, 25",2023-06-08,NaN,NaN,CX4016534,NaN,X,MC-003102-LSn8,NaN,NaN,PT-DD5K0b,Internal,GPP,NaN,Z33-enCas12a,2024-08-13 15:45+0000,2024-08-13 15:45:03.664258+00:00
6485,STR-2kPqCX,False,"15, 18","6, 7","30, 32","13, 16","5, 18","11, 12","8, 13","7, 10","11, 13",12,"11, 15",18,"10, 14",8,"22, 25",2024-05-08,NaN,NaN,CX4019383,NaN,X,MC-003102-LSn8,NaN,NaN,PT-DD5K0b,Internal,GPP,NaN,Z33-enCas12a,2024-08-13 15:45+0000,2024-08-13 15:45:03.664258+00:00
6994,STR-lwh7iE,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4010632,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a,2024-08-13 15:45+0000,2024-08-13 15:45:04.163080+00:00
6995,STR-5EdPYQ,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4011038,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a-SetC-p4,2024-08-13 15:45+0000,2024-08-13 15:45:04.163080+00:00
6996,STR-3pyqNx,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4011038,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a-SetD-p4,2024-08-13 15:45+0000,2024-08-13 15:45:04.163080+00:00

In [27]:
time04 = '2024-08-13 15:46+0000'
dates04 = dates[dates['created_at'] == time04]
dates04.sort_values(by='sample_reference')

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
8892,STR-umts7t,False,"17, 18",9.3,28,13,13,"11, 12","8, 9",9,"11, 14",11,"12, 13","16, 17",12,8,22,NaN,NaN,NaN,CX4011955,NaN,X,MC-001435-1YlD,Not Detected,NaN,PT-TOxlxz,Internal,GPP,NaN,1156QE8-311cas9,2024-08-13 15:46+0000,2024-08-13 15:46:14.731606+00:00
7755,STR-s0ayKM,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4011713,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9,2024-08-13 15:46+0000,2024-08-13 15:46:14.364343+00:00
7753,STR-GzwuVJ,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4013151,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9-RepA-p6,2024-08-13 15:46+0000,2024-08-13 15:46:14.364343+00:00
7754,STR-fshNhU,False,14,"7, 9.3","31.2, 32",17,"10, 17",12,14,9,"9, 11",10,"9, 12","14, 18, 19","12, 13","8, 10",22,NaN,NaN,NaN,CX4013151,NaN,"X, Y",MC-001436-7CDG,NaN,NaN,PT-CzGU9G,Internal,GPP,NaN,1411H-311cas9-RepB-p6,2024-08-13 15:46+0000,2024-08-13 15:46:14.364343+00:00
8913,STR-Qz5ZR7,False,18,"6, 8","31, 31.2","12, 19","14, 17","11, 12","8, 11","8, 12","9, 10","12, 13","11, 12","15, 20","12, 13","8, 11","23, 25",NaN,NaN,NaN,CX4010245,NaN,X,MC-002680-Kgog,NaN,NaN,PT-UACtvx,Internal,GPP,NaN,170MGBA-311cas9,2024-08-13 15:46+0000,2024-08-13 15:46:14.763126+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7770,STR-BWSqz5,False,"15, 18","6, 7","30, 32","13, 16","5, 18","11, 12","8, 13","7, 10","11, 13",12,"11, 15",18,"10, 14",8,"22, 25",2024-05-08,NaN,NaN,CX4019383,NaN,X,MC-003102-LSn8,NaN,NaN,PT-DD5K0b,Internal,GPP,NaN,Z33-enCas12a,2024-08-13 15:46+0000,2024-08-13 15:46:14.364343+00:00
7769,STR-cGnDde,False,"15, 18","6, 7","30, 32","13, 16","5, 18","11, 12","8, 13","7, 10","11, 13",12,"11, 15",18,"10, 14",8,"22, 25",2023-06-08,NaN,NaN,CX4016534,NaN,X,MC-003102-LSn8,NaN,NaN,PT-DD5K0b,Internal,GPP,NaN,Z33-enCas12a,2024-08-13 15:46+0000,2024-08-13 15:46:14.364343+00:00
8293,STR-ajf6ze,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4010632,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a,2024-08-13 15:46+0000,2024-08-13 15:46:14.527747+00:00
8294,STR-h8IsX5,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4011038,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a-SetC-p4,2024-08-13 15:46+0000,2024-08-13 15:46:14.527747+00:00
8295,STR-MMlceX,False,"15, 16","7, 9.3",31,"13, 14","7, 14",13,9,"10, 11",11,"10, 11",14,"16, 18","11, 13",8,"20, 22",NaN,NaN,NaN,CX4011038,NaN,X,MC-000097-qJSn,Not Detected,NaN,PT-k1TO7o,Internal,GPP,NaN,ZR751-enCas12a-SetD-p4,2024-08-13 15:46+0000,2024-08-13 15:46:14.527747+00:00

In [28]:
dates00.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 977 to 2073
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            100 non-null    object
 1   is_reference                  100 non-null    bool
 2   d3s1358                       100 non-null    object
 3   th01                          100 non-null    object
 4   d21s11                        100 non-null    object
 5   d18s51                        100 non-null    object
 6   penta_e                       100 non-null    object
 7   d5s818                        100 non-null    object
 8   d13s317                       100 non-null    object
 9   d7s820                        100 non-null    object
 10  d16s539                       100 non-null    object
 11  csf1po                        100 non-null    object
 12  penta_d                       100 non-null    object
 13  vwa                           100 non-null    object
 14  d8s1179                       100 non-null    object
 15  tpox                          100 non-null    object
 16  fga                           100 non-null    object
 17  pellet_creation_date          66 non-null     object
 18  percentage_match_to_parental  0 non-null      float64
 19  lab_corp_spec_nbr             0 non-null      object
 20  lab_corp_case_nbr             100 non-null    object
 21  comments                      0 non-null      object
 22  amelogenin                    100 non-null    object
 23  model_condition_id            100 non-null    object
 24  mouse                         15 non-null     object
 25  mycoplasma                    0 non-null      object
 26  patient_id                    100 non-null    object
 27  source                        100 non-null    object
 28  source_group                  100 non-null    object
 29  pellet_submitted_date         0 non-null      object
 30  sample_reference              100 non-null    object
 31  created_at                    100 non-null    object
 32  updated_at                    100 non-null    object
dtypes: bool(1), float64(1), object(31)
memory usage: 25.9+ KB

In [29]:
dates01.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 2160 to 3013
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            100 non-null    object
 1   is_reference                  100 non-null    bool
 2   d3s1358                       100 non-null    object
 3   th01                          100 non-null    object
 4   d21s11                        100 non-null    object
 5   d18s51                        100 non-null    object
 6   penta_e                       100 non-null    object
 7   d5s818                        100 non-null    object
 8   d13s317                       100 non-null    object
 9   d7s820                        100 non-null    object
 10  d16s539                       100 non-null    object
 11  csf1po                        100 non-null    object
 12  penta_d                       100 non-null    object
 13  vwa                           100 non-null    object
 14  d8s1179                       100 non-null    object
 15  tpox                          100 non-null    object
 16  fga                           100 non-null    object
 17  pellet_creation_date          66 non-null     object
 18  percentage_match_to_parental  0 non-null      float64
 19  lab_corp_spec_nbr             0 non-null      object
 20  lab_corp_case_nbr             100 non-null    object
 21  comments                      0 non-null      object
 22  amelogenin                    100 non-null    object
 23  model_condition_id            100 non-null    object
 24  mouse                         15 non-null     object
 25  mycoplasma                    0 non-null      object
 26  patient_id                    100 non-null    object
 27  source                        100 non-null    object
 28  source_group                  100 non-null    object
 29  pellet_submitted_date         0 non-null      object
 30  sample_reference              100 non-null    object
 31  created_at                    100 non-null    object
 32  updated_at                    100 non-null    object
dtypes: bool(1), float64(1), object(31)
memory usage: 25.9+ KB

In [30]:
dates02.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 664 to 6284
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            1200 non-null   object
 1   is_reference                  1200 non-null   bool
 2   d3s1358                       1199 non-null   object
 3   th01                          1199 non-null   object
 4   d21s11                        1193 non-null   object
 5   d18s51                        1199 non-null   object
 6   penta_e                       1199 non-null   object
 7   d5s818                        1199 non-null   object
 8   d13s317                       1199 non-null   object
 9   d7s820                        1199 non-null   object
 10  d16s539                       1199 non-null   object
 11  csf1po                        1199 non-null   object
 12  penta_d                       1199 non-null   object
 13  vwa                           1199 non-null   object
 14  d8s1179                       1199 non-null   object
 15  tpox                          1199 non-null   object
 16  fga                           1199 non-null   object
 17  pellet_creation_date          671 non-null    object
 18  percentage_match_to_parental  138 non-null    float64
 19  lab_corp_spec_nbr             0 non-null      object
 20  lab_corp_case_nbr             1200 non-null   object
 21  comments                      0 non-null      object
 22  amelogenin                    1199 non-null   object
 23  model_condition_id            1200 non-null   object
 24  mouse                         198 non-null    object
 25  mycoplasma                    0 non-null      object
 26  patient_id                    1200 non-null   object
 27  source                        1200 non-null   object
 28  source_group                  1200 non-null   object
 29  pellet_submitted_date         0 non-null      object
 30  sample_reference              1200 non-null   object
 31  created_at                    1200 non-null   object
 32  updated_at                    1200 non-null   object
dtypes: bool(1), float64(1), object(31)
memory usage: 310.5+ KB

In [31]:
dates03.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1300 entries, 830 to 7106
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            1300 non-null   object
 1   is_reference                  1300 non-null   bool
 2   d3s1358                       1298 non-null   object
 3   th01                          1298 non-null   object
 4   d21s11                        1292 non-null   object
 5   d18s51                        1298 non-null   object
 6   penta_e                       1298 non-null   object
 7   d5s818                        1298 non-null   object
 8   d13s317                       1298 non-null   object
 9   d7s820                        1298 non-null   object
 10  d16s539                       1298 non-null   object
 11  csf1po                        1298 non-null   object
 12  penta_d                       1298 non-null   object
 13  vwa                           1298 non-null   object
 14  d8s1179                       1298 non-null   object
 15  tpox                          1298 non-null   object
 16  fga                           1298 non-null   object
 17  pellet_creation_date          719 non-null    object
 18  percentage_match_to_parental  0 non-null      float64
 19  lab_corp_spec_nbr             0 non-null      object
 20  lab_corp_case_nbr             1300 non-null   object
 21  comments                      0 non-null      object
 22  amelogenin                    1298 non-null   object
 23  model_condition_id            1300 non-null   object
 24  mouse                         222 non-null    object
 25  mycoplasma                    0 non-null      object
 26  patient_id                    1300 non-null   object
 27  source                        1300 non-null   object
 28  source_group                  1300 non-null   object
 29  pellet_submitted_date         0 non-null      object
 30  sample_reference              1300 non-null   object
 31  created_at                    1300 non-null   object
 32  updated_at                    1300 non-null   object
dtypes: bool(1), float64(1), object(31)
memory usage: 336.4+ KB

In [32]:
dates04.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2201 entries, 267 to 9306
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            2201 non-null   object
 1   is_reference                  2201 non-null   bool
 2   d3s1358                       2198 non-null   object
 3   th01                          2198 non-null   object
 4   d21s11                        2189 non-null   object
 5   d18s51                        2198 non-null   object
 6   penta_e                       2198 non-null   object
 7   d5s818                        2198 non-null   object
 8   d13s317                       2198 non-null   object
 9   d7s820                        2198 non-null   object
 10  d16s539                       2198 non-null   object
 11  csf1po                        2198 non-null   object
 12  penta_d                       2198 non-null   object
 13  vwa                           2198 non-null   object
 14  d8s1179                       2198 non-null   object
 15  tpox                          2198 non-null   object
 16  fga                           2198 non-null   object
 17  pellet_creation_date          1213 non-null   object
 18  percentage_match_to_parental  0 non-null      float64
 19  lab_corp_spec_nbr             0 non-null      object
 20  lab_corp_case_nbr             2201 non-null   object
 21  comments                      0 non-null      object
 22  amelogenin                    2198 non-null   object
 23  model_condition_id            2201 non-null   object
 24  mouse                         401 non-null    object
 25  mycoplasma                    0 non-null      object
 26  patient_id                    2201 non-null   object
 27  source                        2201 non-null   object
 28  source_group                  2201 non-null   object
 29  pellet_submitted_date         0 non-null      object
 30  sample_reference              2201 non-null   object
 31  created_at                    2201 non-null   object
 32  updated_at                    2201 non-null   object
dtypes: bool(1), float64(1), object(31)
memory usage: 569.6+ KB

In [33]:
strip_dupes = str

In [34]:
strip_dupes['created_at'] = pd.to_datetime(strip_dupes['created_at'])
date_filter = pd.Timestamp('2024-08-13').date()

In [35]:
df_removed_date = strip_dupes[strip_dupes['created_at'].dt.date != date_filter]
df_filtered = strip_dupes[strip_dupes['created_at'].dt.date == date_filter]

In [36]:
df_unique = df_filtered.drop_duplicates(subset='sample_reference')
df_unique

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
267,STR-WWzBpU,False,"16, 17",9.3,"28, 30",16,5,11,12,10,11,12,"9, 12",16,"13, 16",11,23.2,2024-03-11,NaN,NaN,CX4018877,NaN,X,MC-000296-bgzW,NaN,NaN,PT-GezIUF,Internal,GPP,NaN,OUMS23Cas9VY,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.431081+00:00
664,STR-U7lF8I,False,18,9.3,30.2,20,12,13,11,10,12,12,12,"15, 17","11, 13","10, 13",23,NaN,NaN,NaN,CX4012569,NaN,X,MC-002499-dWxK,NaN,NaN,PT-j6UudO,Internal,GPP,NaN,UACC3199-311cas9,2024-08-13 14:32:00+00:00,2024-08-13 14:32:29.862597+00:00
668,STR-QADpM0,False,18,9.3,30.2,20,12,13,11,10,12,12,12,"15, 17","11, 13","10, 13",23,2022-08-31,NaN,NaN,CX4014596,NaN,X,MC-002499-dWxK,NaN,NaN,PT-j6UudO,Internal,GPP,NaN,UACC3199-311Cas9-RepA-P4,2024-08-13 14:32:00+00:00,2024-08-13 14:32:29.862597+00:00
824,STR-lKKdW7,False,17,9,30,17,14,11,9,11,9,12,"9, 13",17,"10, 11",11,19,NaN,NaN,NaN,CX4011714,NaN,X,MC-002051-2Ddi,NaN,NaN,PT-K31XId,Internal,GPP,NaN,LU134A-311cas9,2024-08-13 14:32:00+00:00,2024-08-13 14:32:29.862597+00:00
830,STR-b5TCvd,False,"15, 16",9.3,"26.2, 31",13,"13, 18",11,12,"10, 11","11, 13","11, 12","9, 15","15, 16",14,8,"19, 21",2023-12-09,NaN,NaN,CX4018283,NaN,X,MC-003170-0VvA,NaN,NaN,PT-FJLnco,Internal,GPP,NaN,NRHLS1-enCas12a,2024-08-13 15:45:00+00:00,2024-08-13 15:45:03.795747+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9302,STR-Wr25NT,False,"16, 17",9,30,15,"5, 15","10, 12","10, 12",11,"9, 11",12,14,17,"14, 15",12,19,2023-12-08,NaN,NaN,CX4018282,NaN,X,MC-000633-iIki,NaN,NaN,PT-zUYVjw,Internal,GPP,NaN,FU97-Cas9VY,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
9303,STR-oeTHfb,False,16,"6, 9.3","27, 29","13, 14",13,12,"10, 12","9, 11",12,12,"12, 13","14, 15","12, 13","8, 11","22, 25",NaN,NaN,NaN,CX4010790,NaN,X,MC-000406-va7T,Not Detected,NaN,PT-ZwaNYv,Internal,GPP,NaN,U937-311cas9,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
9304,STR-lkgw1v,False,"14, 17, 18",6,28,12,10,"10, 11, 12","8, 11, 12, 13","10, 13",8,"11, 12, 14","9, 14",16,13,"8, 11","22, 23, 25",2024-06-07,NaN,NaN,CX4019637,NaN,"X, Y",MC-000109-cK3a,NaN,NaN,PT-Zwpb82,Internal,GPP,NaN,NCIH3255,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
9305,STR-fnFh09,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepA-p5,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
9306,STR-eo2Vx2,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepB-p5,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.890555+00:00

In [37]:
str_filtered = pd.concat([df_removed_date, df_unique], ignore_index=True)
str_filtered

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11","11, 13","12, 13","9, 10","16, 18","11, 14","8, 10","18, 19",NaN,NaN,76M91400,CX4003615,matches reference; STR matches reference profi...,X,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00:00+00:00,2024-04-09 16:00:46.668811+00:00
1,STR-Yv4hq7,False,16,7,31.3,18,"11.1, 15.1",12,12,10,9,"10, 13",11,NaN,"9, 14",NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-000713-IUJj,NaN,NaN,PT-FQOeFS,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41:00+00:00,2024-06-13 16:41:01.795310+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11","9, 12",11,"8, 13",NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39:00+00:00,2024-08-16 16:39:28.322066+00:00
3,STR-gifaLI,False,18,7,"30.3, 32.3","10, 14","7.1, 11.1","11, 13","11, 13","9, 12",9,"10, 12","8, 10",NaN,"13, 15",NaN,"22, 23",NaN,NaN,NaN,NaN,NaN,NaN,MC-000960-RI7G,NaN,NaN,PT-N5YXV2,Internal,WGS Inferred,NaN,NaN,2024-04-23 18:08:00+00:00,2024-04-23 18:08:28.005757+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,"10, 11",12,"10, 11",NaN,"13, 15","11, 8",24,NaN,0.8696,NaN,NaN,NaN,NaN,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:00+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6481,STR-Wr25NT,False,"16, 17",9,30,15,"5, 15","10, 12","10, 12",11,"9, 11",12,14,17,"14, 15",12,19,2023-12-08,NaN,NaN,CX4018282,NaN,X,MC-000633-iIki,NaN,NaN,PT-zUYVjw,Internal,GPP,NaN,FU97-Cas9VY,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6482,STR-oeTHfb,False,16,"6, 9.3","27, 29","13, 14",13,12,"10, 12","9, 11",12,12,"12, 13","14, 15","12, 13","8, 11","22, 25",NaN,NaN,NaN,CX4010790,NaN,X,MC-000406-va7T,Not Detected,NaN,PT-ZwaNYv,Internal,GPP,NaN,U937-311cas9,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6483,STR-lkgw1v,False,"14, 17, 18",6,28,12,10,"10, 11, 12","8, 11, 12, 13","10, 13",8,"11, 12, 14","9, 14",16,13,"8, 11","22, 23, 25",2024-06-07,NaN,NaN,CX4019637,NaN,"X, Y",MC-000109-cK3a,NaN,NaN,PT-Zwpb82,Internal,GPP,NaN,NCIH3255,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6484,STR-fnFh09,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepA-p5,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6485,STR-eo2Vx2,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepB-p5,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.890555+00:00

In [38]:
str_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6486 entries, 0 to 6485
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            6486 non-null   object
 1   is_reference                  6486 non-null   bool
 2   d3s1358                       6415 non-null   object
 3   th01                          6434 non-null   object
 4   d21s11                        5200 non-null   object
 5   d18s51                        6268 non-null   object
 6   penta_e                       6100 non-null   object
 7   d5s818                        6369 non-null   object
 8   d13s317                       6366 non-null   object
 9   d7s820                        6416 non-null   object
 10  d16s539                       6436 non-null   object
 11  csf1po                        6446 non-null   object
 12  penta_d                       6187 non-null   object
 13  vwa                           4285 non-null   object
 14  d8s1179                       6341 non-null   object
 15  tpox                          5717 non-null   object
 16  fga                           6261 non-null   object
 17  pellet_creation_date          1426 non-null   object
 18  percentage_match_to_parental  1586 non-null   float64
 19  lab_corp_spec_nbr             2134 non-null   object
 20  lab_corp_case_nbr             4215 non-null   object
 21  comments                      1538 non-null   object
 22  amelogenin                    4275 non-null   object
 23  model_condition_id            5705 non-null   object
 24  mouse                         1363 non-null   object
 25  mycoplasma                    118 non-null    object
 26  patient_id                    6486 non-null   object
 27  source                        6486 non-null   object
 28  source_group                  6481 non-null   object
 29  pellet_submitted_date         601 non-null    object
 30  sample_reference              4257 non-null   object
 31  created_at                    6486 non-null   datetime64[ns, UTC]
 32  updated_at                    6486 non-null   object
dtypes: bool(1), datetime64[ns, UTC](1), float64(1), object(30)
memory usage: 1.6+ MB

In [39]:
str_filtered

,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,STR-VfWJ0L,True,18,"6, 9.3","28, 30",15,"10, 17","11, 13",11,"9, 11","11, 13","12, 13","9, 10","16, 18","11, 14","8, 10","18, 19",NaN,NaN,76M91400,CX4003615,matches reference; STR matches reference profi...,X,MC-001046-dQN0,NaN,NaN,PT-JfAqx8,Internal,DMX,NaN,COR-L26,2024-04-09 16:00:00+00:00,2024-04-09 16:00:46.668811+00:00
1,STR-Yv4hq7,False,16,7,31.3,18,"11.1, 15.1",12,12,10,9,"10, 13",11,NaN,"9, 14",NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-000713-IUJj,NaN,NaN,PT-FQOeFS,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41:00+00:00,2024-06-13 16:41:01.795310+00:00
2,STR-Y0RKCH,False,17,6,NaN,23,11.1,"11, 12","8, 12","10, 11","9, 12",11,"8, 13",NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,MC-001567-Cfys,NaN,NaN,PT-fN0pV5,Internal,WGS Inferred,NaN,NaN,2024-08-16 16:39:00+00:00,2024-08-16 16:39:28.322066+00:00
3,STR-gifaLI,False,18,7,"30.3, 32.3","10, 14","7.1, 11.1","11, 13","11, 13","9, 12",9,"10, 12","8, 10",NaN,"13, 15",NaN,"22, 23",NaN,NaN,NaN,NaN,NaN,NaN,MC-000960-RI7G,NaN,NaN,PT-N5YXV2,Internal,WGS Inferred,NaN,NaN,2024-04-23 18:08:00+00:00,2024-04-23 18:08:28.005757+00:00
4,STR-7FEfGM,False,"16, 14","9, 8",32.3,"11, 15","15.1, 12.1","11, 12","10, 13",10,"10, 11",12,"10, 11",NaN,"13, 15","11, 8",24,NaN,0.8696,NaN,NaN,NaN,NaN,MC-002046-oaX8,NaN,NaN,PT-SKC9qY,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:00+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6481,STR-Wr25NT,False,"16, 17",9,30,15,"5, 15","10, 12","10, 12",11,"9, 11",12,14,17,"14, 15",12,19,2023-12-08,NaN,NaN,CX4018282,NaN,X,MC-000633-iIki,NaN,NaN,PT-zUYVjw,Internal,GPP,NaN,FU97-Cas9VY,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6482,STR-oeTHfb,False,16,"6, 9.3","27, 29","13, 14",13,12,"10, 12","9, 11",12,12,"12, 13","14, 15","12, 13","8, 11","22, 25",NaN,NaN,NaN,CX4010790,NaN,X,MC-000406-va7T,Not Detected,NaN,PT-ZwaNYv,Internal,GPP,NaN,U937-311cas9,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6483,STR-lkgw1v,False,"14, 17, 18",6,28,12,10,"10, 11, 12","8, 11, 12, 13","10, 13",8,"11, 12, 14","9, 14",16,13,"8, 11","22, 23, 25",2024-06-07,NaN,NaN,CX4019637,NaN,"X, Y",MC-000109-cK3a,NaN,NaN,PT-Zwpb82,Internal,GPP,NaN,NCIH3255,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6484,STR-fnFh09,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepA-p5,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.862611+00:00
6485,STR-eo2Vx2,False,"16, 17",9.3,"29, 30","15, 16",11,"10, 14","11, 13","7, 10","9, 11","10, 12","9, 13","14, 17","13, 14",8,"21, 22",NaN,NaN,NaN,CX4009888,NaN,"X, Y",MC-002461-8Uwl,NaN,NaN,PT-Zy2EsL,Internal,GPP,NaN,RVH421SKINFV1-311Cas9-RepB-p5,2024-08-13 15:46:00+00:00,2024-08-13 15:46:14.890555+00:00