In [1]:
import pandas as pd
import numpy as np

#SQL query for pulling updated strs

SELECT 
m.patient_id "model_patient_id",
str.patient_id "str_patient_id",
m.model_id "model_model_id",
mc.model_id "mc_model_id",
mc.model_condition_id "mc_model_condition_id",
str.model_condition_id "str_model_condition_id",
str.*
FROM str_profile str
LEFT JOIN model_condition mc ON str.model_condition_id=mc.model_condition_id
LEFT JOIN model m ON m.model_id=mc.model_id;

In [2]:
#changing display cols and rows to see more of readout
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)

In [3]:
#importing csv file from SQL query.
#make sure csv downloaded file is named 'after_update' and in the same folder as this notebook
all_str = pd.read_csv('str_filtered_after_update.csv')
all_str.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6486 entries, 0 to 6485
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      5705 non-null   object
 1   patient_id_model              5705 non-null   object
 2   model_model_id                5705 non-null   object
 3   mc_model_condition_id         5705 non-null   object
 4   mc_model_id                   5705 non-null   object
 5   patient_id_str                6486 non-null   object
 6   model_condition_id            5705 non-null   object
 7   id                            6486 non-null   object
 8   is_reference                  6486 non-null   bool
 9   d3s1358                       6415 non-null   object
 10  th01                          6434 non-null   object
 11  d21s11                        5200 non-null   object
 12  d18s51                        6268 non-null   object
 13  penta_e                       6100 non-null   object
 14  d5s818                        6369 non-null   object
 15  d13s317                       6366 non-null   object
 16  d7s820                        6416 non-null   object
 17  d16s539                       6436 non-null   object
 18  csf1po                        6446 non-null   object
 19  penta_d                       6187 non-null   object
 20  vwa                           4285 non-null   object
 21  d8s1179                       6341 non-null   object
 22  tpox                          5717 non-null   object
 23  fga                           6261 non-null   object
 24  pellet_creation_date          1426 non-null   object
 25  percentage_match_to_parental  1586 non-null   float64
 26  lab_corp_spec_nbr             2134 non-null   object
 27  lab_corp_case_nbr             4215 non-null   object
 28  comments                      1538 non-null   object
 29  amelogenin                    4275 non-null   object
 30  model_condition_id.1          5705 non-null   object
 31  mouse                         1363 non-null   object
 32  mycoplasma                    118 non-null    object
 33  patient_id                    6486 non-null   object
 34  source                        6486 non-null   object
 35  source_group                  6481 non-null   object
 36  pellet_submitted_date         601 non-null    object
 37  sample_reference              4257 non-null   object
 38  created_at                    6486 non-null   object
 39  updated_at                    6486 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 1.9+ MB

In [4]:
#rename columns
all_str.rename(columns={ 
    'patient_id_model': 'model_patient_id', 
    'patient_id_str': 'str_patient_id'}, inplace=True)

In [5]:
#checking for duplicates by lab corp case number, model_condition_id, and sample reference
#shows count - lookup in gumbo by sample_reference - will show duplicates - check upload dates 
#creates new df just to examine 
upload_dupe_check = all_str.groupby(['lab_corp_case_nbr', 'model_condition_id', 'sample_reference']).size().reset_index(name='count')
upload_dupe_check.sort_values(by='count', ascending=False).head(299)

,lab_corp_case_nbr,model_condition_id,sample_reference,count
2598,CX4016248,MC-001465-V7hs,CHLA136-enCas12a,2
1429,CX4012569,MC-002495-ZD9E,IOWA1T,2
2055,CX4014681,MC-003201-2p67,C42,2
3077,CX4017930,MC-002433-iccX,CCLFPEDS0019T-enCas12a-HumagneCD-RepB-P6(D21),2
2012,CX4014597,MC-000643-Lgxt,HDQP1,2
1555,CX4013150,MC-003072-zgEn,CHLA05ATRT,2
2062,CX4014682,MC-003118-NF4c,HMEC1,2
1808,CX4013811,MC-003016-CoPk,TELOHAEC,2
2418,CX4015873,MC-001212-ItHM,TTC642-311Cas9(5/30/2017),2
1567,CX4013151,MC-003061-5LP5,NCIH774,2
1539,CX4012984,MC-003057-Jtnx,CAHPV10,2
2018,CX4014597,MC-003125-sYQF,ASPSKY,2
1540,CX4012984,MC-003060-Due1,SNF022,2
1541,CX4012984,MC-003062-8J7Y,SALMAT,2
1542,CX4012984,MC-003064-tV5G,TE130T,2
1663,CX4013483,MC-003065-ALeQ,CHLA02ATRT,2
1438,CX4012569,MC-003019-6LhD,LASCPC01,2
1552,CX4013150,MC-003017-iLhU,EAHY926,2
1553,CX4013150,MC-003063-dkJo,LMMEL57,2
1554,CX4013150,MC-003066-E9vO,LMMEL53,2
2017,CX4014597,MC-003076-F4lx,CWRR1ca,2
2211,CX4015091,MC-003117-Z47z,HBEC5i,2
1618,CX4013371,MC-003071-5csX,NCIH748,2
1617,CX4013371,MC-003067-mq2p,CHLA01RMED,2
858,CX4010244,MC-000404-GqDy,K029AX-RDA174-SetC-P4,2
2154,CX4014974,MC-003077-naD1,VCaPEnzR,2
1487,CX4012829,MC-001383-xz0s,PWR1E,2
1614,CX4013371,MC-001281-1ole,CHLA01MED,2
2274,CX4015270,MC-002947-yu5B,ACH-002947 Post-C12 (2947 C12 FP) (p15),1
2293,CX4015271,MC-003236-kso9,ACH-003236 Pre-O (MSK BM61 FP/O) (pX+5),1
2267,CX4015205,MC-003177-oood,NRHUPS1-enCas12a,1
2266,CX4015205,MC-000709-QsXL,KMRC2-311Cas9,1
2265,CX4015205,MC-000495-g0D3,TUHR4TKB,1
2264,CX4015205,MC-000446-BoNJ,KPNSI9S-Parental,1
2291,CX4015271,MC-003193-bnde,ACH-003193 Post-CD01 (3193 Post CD1 FP) (p37),1
2292,CX4015271,MC-003216-0lf7,ACH-003216 Post-C12 (3216 C12 FP) (p22),1
2295,CX4015271,MC-003262-1p1p,ACH-003262 Pre-O (3262 FP/O) (p20),1
2294,CX4015271,MC-003258-QyyT,ACH-003258 Pre-O (3258 FP/O) (p17),1
2289,CX4015271,MC-003083-nyqF,ACH-003083 Post-CD02 (3083 C12 CD02 FP) (pX+12),1
2296,CX4015271,MC-003263-55yp,ACH-003263 Pre-O (3263 FP/O) (p14),1
2297,CX4015349,MC-003123-40jX,ACH-003123 Pre-O (3123 FP) (p14),1
2298,CX4015349,MC-003274-s5v9,ACH-003275 Post-C12 (3275 C12 FP) (p37),1
2263,CX4015205,MC-000333-V8cr,JHOM2B,1
2262,CX4015205,MC-000194-bjZY,HS934T,1
2261,CX4015205,MC-000191-En6E,BHT101-311Cas9,1
2290,CX4015271,MC-003130-fxrY,ACH-003130 Post-CD01 (3130 C12 Post CD01 FP),1
2269,CX4015205,MC-003184-xxvb,NRHLMS2,1
2268,CX4015205,MC-003183-dkwm,NRHMFS3,1
2273,CX4015206,MC-000881-H36w,RnD_MELJUSO_RDA816_CP1851,1
2275,CX4015270,MC-002954-yG88,ACH-002954 Pre-CD01 (2954) (p27),1
2276,CX4015270,MC-002983-Oo67,ACH-002983 Post-CD01 (2983 C12 D24 FP),1
2277,CX4015270,MC-002991-L346,ACH-002991 Post-CD02 (2991 Post-CD02 FP),1
2278,CX4015270,MC-002998-Bb45,ACH-002998 Post-C12 (2998 C12 FP) (p22),1
2272,CX4015206,MC-000881-H36w,RnD_MELJUSO_RDA816_CP1850,1
2279,CX4015270,MC-003023-LNSO,ACH-003023 Post-C12 (3023 C12x2 P31 FP) (p31),1
2280,CX4015270,MC-003026-LJBv,ACH-003026 Pre-O (3026 FP/O) (p17),1
2271,CX4015206,MC-000881-H36w,RnD_MELJUSO_RDA816_CP1847,1
2281,CX4015270,MC-003041-7ddT,ACH-003041 Post-CD01 (3041 Post CD01 FP),1
2282,CX4015270,MC-003046-ean0,ACH-003046 Post-CD02 (3046 Post-CD02),1
2270,CX4015206,MC-000881-H36w,RnD_MELJUSO_RDA816_CP1846,1
2283,CX4015270,MC-003193-bnde,ACH-003193 Pre-CD01 (3193 Pre-CD01) (p35),1
2284,CX4015270,MC-003235-ww88,ACH-003235 Pre-O (MSK-BM1 FP/O) (px+4),1
2285,CX4015270,MC-003237-45op,ACH-003237 Pre-O (MSK-ST1 FP/O) (pX+6),1
2286,CX4015271,MC-002818-ScCA,ACH-002818 Pre-O (2818 FP/O) (p15),1
2287,CX4015271,MC-002911-pklh,ACH-002911 Pre-O (2911 FP/O) (p18),1
2288,CX4015271,MC-003081-94lw,ACH-003081 Post-CD01 (3081 Post CD01 FP) (pX+14),1
0,CX4001842,MC-003171-Zuum,ACH-003171,1
2300,CX4015350,MC-003331-g556,PDM-30 Pre-O (PDM 30 FPO) (p6),1
2299,CX4015349,MC-003275-hds5,ACH-003274 Post-C12 (3274 C12 FP) (p21),1
2259,CX4015204,MC-003177-oood,NRHUPS1,1
2327,CX4015427,MC-001652-lAQg,SKGII-311Cas9-ParalogV2-RepA-P6(D21),1
2328,CX4015549,MC-000022-fRaU,PA-TU-8988S-PA-TU-8988T-311Cas9,1
2329,CX4015549,MC-000022-fRaU,PA-TU-8988S_PA-TU-8988T,1
2330,CX4015549,MC-000022-fRaU,PAT8988S-PATU8988T-311Cas9,1
2331,CX4015549,MC-000023-zYrZ,PA-TU-8988T,1
2332,CX4015549,MC-000055-M4n1,D283-311Cas9(3/4/2021),1
2333,CX4015549,MC-000078-SV5j,MHHNB11,1
2334,CX4015549,MC-000145-3ydU,SKLMS1-311Cas9,1
2335,CX4015549,MC-000168-L3Ll,NOMO1,1
2336,CX4015549,MC-000365-TMgT,SUDHL4-311Cas9,1
2337,CX4015549,MC-000740-PW6X,A253-311Cas9,1
2338,CX4015550,MC-000004-pA3k,HEL-11/21/13,1
2339,CX4015550,MC-000004-pA3k,HEL-311Cas9-6/12/16,1
2340,CX4015550,MC-000004-pA3k,HEL-5/31/16,1
2341,CX4015550,MC-000164-DAfq,Panc1,1
2342,CX4015550,MC-000299-oIsc,HNT34,1
2343,CX4015550,MC-000649-Hb96,786O-311Cas9,1
2344,CX4015550,MC-001099-jclT,KD-311Cas9,1
2345,CX4015550,MC-001997-n8wz,ECC2-311Cas9-8/3/18,1
2346,CX4015550,MC-001999-g7LW,9505BIK-311Cas9-7/20/18,1
2347,CX4015551,MC-000507-V957,KE39-311Cas9-ParalogV2-RepA-P4(D21),1
2348,CX4015551,MC-000507-V957,KE39-311Cas9-ParalogV2-RepB-P4(D21),1
2349,CX4015551,MC-000965-naxM,RL952-311Cas9-ParalogV2-RepA-p6,1
2326,CX4015427,MC-000947-2Nyc,OVK18-311Cas9-ParalogV2-RepB-P6(D21),1
2325,CX4015427,MC-000471-iBae,LI7-311Cas9-ParalogV2-RepB-P6(D22),1
2324,CX4015427,MC-000471-iBae,LI7-311Cas9-ParalogV2-RepA-P6(D22),1
2311,CX4015425,MC-003201-2p67,C42-enCas12a,1
2301,CX4015350,MC-003333-gII5,PDM-359 Pre-O (PDM 359) (p4),1
2302,CX4015350,MC-003337-rEeE,PDM-96 Pre-O (PDM-96 FP/Omics) (p4),1
2303,CX4015350,MC-003339-7yt5,PDM-223 Pre-O (PDM-223 FP/Omics) (p4),1
2304,CX4015350,MC-003341-kj34,PDM-36 Pre-O (PDM 36 FP/OM) (p6),1
2305,CX4015425,MC-000292-Oy94,NCIH841-enCas12a-20xB,1
2306,CX4015425,MC-000373-zafG,SKM1-enCas12a,1
2307,CX4015425,MC-000578-0XhE,HCC1171,1
2308,CX4015425,MC-001200-sM9G,STM9101-enCas12a,1
2309,CX4015425,MC-003184-xxvb,NRHLMS2-enCas12a,1
2310,CX4015425,MC-003191-gctw,NRHGCT2,1
2312,CX4015426,MC-000047-fRLW,GCIY-311Cas9,1
2323,CX4015427,MC-000142-E7OD,CAL29-311Cas9-ParalogV2-RepB-p6,1
2313,CX4015426,MC-000373-zafG,SKM1-enCas12a-30xB,1
2314,CX4015426,MC-001029-lvBN,CHLA10-enCas12a,1
2315,CX4015426,MC-001212-ItHM,TTC642-311Cas9,1
2316,CX4015426,MC-002795-z3lI,NCCCDS1X1C1-enCas12a,1
2317,CX4015426,MC-002796-wn6o,NCCCDS1X3C1-enCas12a,1
2318,CX4015426,MC-002944-c921,CCLFPEDS0045T-enCas12a,1
2319,CX4015426,MC-003124-dk5i,ASPS1-Cas9,1
2320,CX4015426,MC-003167-Is2j,KL1392T-enCas12a,1
2321,CX4015426,MC-003191-gctw,NRHGCT2-enCas12a,1
2322,CX4015427,MC-000142-E7OD,CAL29-311Cas9-ParalogV2-RepA-p6,1
2260,CX4015205,MC-000191-En6E,BHT101,1
2252,CX4015204,MC-000641-2Ca9,CMK-enCas12a,1
2258,CX4015204,MC-003106-p5ta,RC-enCas12a,1
2189,CX4015039,MC-003024-9vDT,ACH-003024 Pre-O (3024 FP/O) (p18),1
2178,CX4015038,MC-003051-eLE2,ACH-003051 Post-Cd01 (3051 Post H1 D) (p59),1
2179,CX4015038,MC-003051-eLE2,ACH-003051 Pre-CD01 (3051 Pre H1 FP) (p55),1
2180,CX4015038,MC-003081-94lw,ACH-003081-Pre-CD01 (3081 Pre CD01 FP) (pX+11),1
2181,CX4015038,MC-003083-nyqF,ACH-003083 Pre-CD02 (3083 C12 H2 FP) (pX+8),1
2182,CX4015038,MC-003232-038g,ACH-003232 Post-C12 (3232 C12 FP) (p15),1
2183,CX4015039,MC-002735-GLz3,ACH-002735 Pre-CD01 (2735-C12 Pre CD01 FP) (p26),1
2184,CX4015039,MC-002879-adel,ACH-002879 Pre-O (2879 FP/O) (p15),1
2185,CX4015039,MC-002882-ggtt,ACH-002882 Pre-O (2882 FP/O) (p11),1
2186,CX4015039,MC-002958-Fuyj,ACH-002958 Post-CD01 (2959 CD01 FP) (p18),1
2187,CX4015039,MC-002991-L346,ACH-002991 Pre-CD02 (2991 Pre CD02 FP),1
2188,CX4015039,MC-003008-uozb,ACH-003008 Post-C12 (3008 C12 FP) (p45),1
2190,CX4015039,MC-003046-ean0,ACH-003046 Post-C12 (3046 C12 FP) (p18),1
2257,CX4015204,MC-002809-88ut,BT360,1
2191,CX4015039,MC-003122-D3FN,ACH-003122 Post-C12 (3122 C12 FP) (p23),1
2192,CX4015039,MC-003126-6Fpt,ACH-003126 Post-CD01 (3126 Post H1 FP) (p24),1
2193,CX4015040,MC-002449-16qM,ACH-002449 Post-CD01 (2449 Post CD01 FP) (pX+13),1
2194,CX4015040,MC-002954-yG88,ACH-002954 Post-CD01 (2954 D24 FP),1
2195,CX4015040,MC-003041-7ddT,ACH-003041 Pre-CD01 (3041 Pre H1 FP) (p24),1
2196,CX4015040,MC-003055-vTRH,ACH-003055 Pre-O (3055 P10 FP) (p10),1
2197,CX4015040,MC-003055-vTRH,ACH-003055-Pre-Pre-O (3055 PX+6 FP) (pX+6),1
2198,CX4015040,MC-003130-fxrY,ACH-003130 Pre-CD01 (3130 C12 Pre H1 FP) (p21),1
2199,CX4015040,MC-003203-mwmw,ACH-003203 Post-C12x2 (3203 C12 re-inf FP) (p28),1
2200,CX4015040,MC-003219-ss5t,ACH-003219 Post-C12 (3219 C12 FP) (p14),1
2201,CX4015040,MC-003239-6uu7,ACH-003239 Pre-O (4392 FP/O) (p15),1
2177,CX4015038,MC-003047-mwE5,ACH-003047 Post-C12 (3047 C12 FP) (p18),1
2176,CX4015038,MC-003046-ean0,ACH-003046 Pre-CD02 (3046 Pre CD02 FP) (p22),1
2175,CX4015038,MC-002983-Oo67,ACH-002983 Pre-CD01 (2983 C12 FP) (p23),1
2174,CX4015038,MC-002878-ruio,ACH-002878 Pre-O (2878 FP/O) (p11),1
2150,CX4014974,MC-000312-oMfE,SKNBE2,1
2151,CX4014974,MC-000312-oMfE,SKNBE2-311cas9,1
2152,CX4014974,MC-000970-Bx3a,SNU-C5-311cas9(9/27/2016),1
2153,CX4014974,MC-002996-tuqK,CI34601-enCas12a,1
2155,CX4014974,MC-003099-DM4v,UCSFOT1109-enCas12a,1
2156,CX4014974,MC-003111-6XMJ,HS856T-enCas12a,1
2157,CX4014975,MC-000132-D7jg,JHOS2-311Cas9-ParalogV2-RepB-P6(D22),1
2158,CX4014975,MC-000253-eQci,COLO201-311Cas9-ParalogV2-RepB-p6,1
2159,CX4014975,MC-000657-vN70,A2780-311Cas9-ParalogV2-RepA-P6,1
2160,CX4014975,MC-000657-vN70,A2780-311Cas9-ParalogV2-RepB-P6,1
2161,CX4014975,MC-000952-7GXZ,MDAPCA2B-enCas12a-HumagneC-p4,1
2162,CX4014975,MC-000952-7GXZ,MDAPCA2B-enCas12a-HumagneD-p4,1
2163,CX4014975,MC-001151-dENl,OVCAR5-311Cas9-ParalogV2-RepA-P6,1
2164,CX4014975,MC-001151-dENl,OVCAR5-311Cas9-ParalogV2-RepB-P6,1
2165,CX4014975,MC-001407-g9d6,UMUC13-311Cas9-ParalogV2-RepA-P6,1
2166,CX4014975,MC-001411-EIzh,UMUC5-311Cas9-ParalogV2-RepA-p6,1
2167,CX4014975,MC-001411-EIzh,UMUC5-311Cas9-ParalogV2-RepB-p6,1
2168,CX4014975,MC-001578-6Nny,NCCIT-enCas12a-HumagneC-P4,1
2169,CX4014975,MC-001578-6Nny,NCCIT-enCas12a-HumagneD-P4,1
2170,CX4014975,MC-001676-Iulf,TY82-enCas12a-HumagneD-p4,1
2171,CX4014975,MC-002662-0u5H,JVE207-enCas12a-SetC-RepD-p6,1
2172,CX4014975,MC-002662-0u5H,JVE207-enCas12a-SetD-RepD-p6,1
2173,CX4015038,MC-002699-BhRd,ACH-002852 Pre-O (2852 FP/O) (p33),1
2202,CX4015091,MC-000037-Q40d,S117-311Cas9,1
2203,CX4015091,MC-000292-Oy94,NCIH841,1
2204,CX4015091,MC-000488-sREU,TE11-311Cas9,1
2232,CX4015094,MC-000741-Gvsa,UBLC1-311Cas9-ParalogV2-RepB-P6,1
2234,CX4015094,MC-000793-0iSa,KATOIII-311Cas9-ParalogV2-RepB-p6,1
2235,CX4015094,MC-000913-p0yT,ESS1-311Cas9-ParalogV2-RepB-p6,1
2236,CX4015094,MC-000947-2Nyc,OVK18-311Cas9-ParalogV2-RepA-P6,1
2237,CX4015094,MC-001407-g9d6,UMUC13-311Cas9-ParalogV2-RepB-P6,1
2238,CX4015203,MC-000047-fRLW,GCIY-311Cas9-2015,1
2239,CX4015203,MC-000047-fRLW,GCIY-311Cas9-2020,1
2240,CX4015203,MC-000168-L3Ll,NOMO1-enCas12a,1
2241,CX4015203,MC-000260-8I0U,SKNAS-311Cas9,1
2242,CX4015203,MC-000665-FOD6,SKMES1-311Cas9,1
2243,CX4015203,MC-000904-0w6Z,NCIH2106,1
2244,CX4015203,MC-001200-sM9G,STM9101,1
2245,CX4015203,MC-001418-yATq,UWB1289,1
2246,CX4015203,MC-001999-g7LW,9505BIK,1
2247,CX4015203,MC-002418-FEiN,CCLFNEURO0017T-enCas12a,1
2248,CX4015203,MC-002418-FEiN,CCLFNEURO0017T-enCas12a-Neurosphere,1
2249,CX4015204,MC-000231-tEoc,KALS1-311Cas9,1
2250,CX4015204,MC-000473-MpEw,RT112-311Cas9,1
2251,CX4015204,MC-000587-Rius,NCIH1975-311Cas9,1
2351,CX4015551,MC-001652-lAQg,SKGII-311Cas9-ParalogV2-RepB-P6(D21),1
2253,CX4015204,MC-000995-sJXn,JURKAT-311Cas9,1
2254,CX4015204,MC-001289-BpdI,COGAR359-311Cas9,1
2255,CX4015204,MC-002456-294k,CCLFNEURO0035T-enCas12a-Adherent-Neurosphere-10xB,1
2256,CX4015204,MC-002456-294k,CCLFNEURO0035T-enCas12a-Adherent-Neurosphere-50xB,1
2233,CX4015094,MC-000793-0iSa,KATOIII-311Cas9-ParalogV2-RepA-p6,1
2231,CX4015094,MC-000741-Gvsa,UBLC1-311Cas9-ParalogV2-RepA-P6,1
2205,CX4015091,MC-000886-8OYy,NCIH2009(5/20/13),1
2230,CX4015094,MC-000438-97t0,LU65-311Cas9-ParalogV2-RepB-p6,1
2206,CX4015091,MC-000886-8OYy,NCIH2009-311cas9(5/17/22),1
2207,CX4015091,MC-000886-8OYy,NCIH2009-311cas9(8/5/19),1
2208,CX4015091,MC-000886-8OYy,NCIH2009-311cas92014320 5ug/ml Blast(4/18/14),1
2209,CX4015091,MC-001029-lvBN,CHLA10,1
2210,CX4015091,MC-002433-iccX,CCLFPEDS0019T,1
2212,CX4015092,MC-000169-0day,RD-311Cas9,1
2213,CX4015092,MC-000495-g0D3,TUHR4TKB-311Cas9,1
2214,CX4015092,MC-000507-V957,KE39-311Cas9,1
2215,CX4015092,MC-000792-V2Ue,BFTC909-311Cas9,1
2216,CX4015092,MC-001150-wyma,OUMS27,1
2217,CX4015092,MC-001349-VGWT,HDMB03-enCas12a,1
2218,CX4015092,MC-001532-MUr8,JMURTK2-311Cas9,1
2219,CX4015092,MC-002798-3htH,NCCDFSP2C1,1
2220,CX4015093,MC-000001-ztiA,NIHOVCAR3,1
2221,CX4015093,MC-000373-zafG,SKM1,1
2222,CX4015093,MC-000641-2Ca9,CMK,1
2223,CX4015093,MC-000685-W4mj,L33,1
2224,CX4015093,MC-002794-62RZ,NCCMFS1C1,1
2225,CX4015093,MC-002936-EOFj,CCLFPEDS0043T,1
2226,CX4015093,MC-003072-zgEn,CHLA05ATRT-enCas12a(5/27/22),1
2227,CX4015093,MC-003072-zgEn,CHLA05ATRT-enCas12a(8/5/22),1
2228,CX4015093,MC-003072-zgEn,CHLA05ATRT-enCas12a(9/15/2022),1
2229,CX4015094,MC-000438-97t0,LU65-311Cas9-ParalogV2-RepA-p6,1
2350,CX4015551,MC-000965-naxM,RL952-311Cas9-ParalogV2-RepB-p6,1
2360,CX4015699,MC-001997-n8wz,ECC2(6/14/2018),1
2352,CX4015551,MC-001765-czdh,RH4-311Cas9-ParalogV2-RepB-P6(D21),1
2486,CX4015911,MC-003019-6LhD,LASCPC01-enCas12a-HumagneD-P4(D15),1
2488,CX4015911,MC-003124-dk5i,ASPS1-Cas9-AVANA4-RepB-P6(D22),1
2489,CX4015912,MC-000132-D7jg,JHOS2-311Cas9-ParalogV2-RepA-P6(D22),1
2490,CX4015912,MC-000520-YIm7,59M-311Cas9-ParalogV2-RepA-P6(D21),1
2491,CX4015912,MC-000520-YIm7,59M-311Cas9-ParalogV2-RepB-P6(D21),1
2492,CX4015912,MC-000665-FOD6,SKMES1-311Cas9-ParalogV2-RepA-P6(D21),1
2493,CX4015912,MC-000665-FOD6,SKMES1-311Cas9-ParalogV2-RepB-P6(D21),1
2494,CX4015912,MC-000973-F02J,639V-311Cas9-ParalogV2-RepA-P6(D22),1
2495,CX4015912,MC-000973-F02J,639V-311Cas9-ParalogV2-RepB-P6(D22),1
2496,CX4015912,MC-001401-l6Fd,SW13-enCas12a-HumagneC-P4(D14),1
2497,CX4015912,MC-001414-GNy8,UMUC6-311Cas9-ParalogV2-RepA-P6(D21),1
2498,CX4015912,MC-001414-GNy8,UMUC6-311Cas9-ParalogV2-RepB-P6(D21),1
2499,CX4015912,MC-002410-gy9C,CCLFNEURO0007T-enCas12a-HumagneC-P3(D21),1
2500,CX4015912,MC-002709-26zN,CMS-enCas12a-HumagneC-P4(D14),1
2501,CX4015912,MC-002709-26zN,CMS-enCas12a-HumagneD-P4(D14),1
2502,CX4016034,MC-000070-XibM,697-311cas9(9/29/2016),1
2503,CX4016034,MC-000076-het0,NCO2-311Cas9,1
2504,CX4016034,MC-000243-pHKG,DANG-Cas9VY,1
2505,CX4016034,MC-000369-hSYj,MOLM16-311cas9 but or OCIM2-311Cas9(7/25/2018),1
2506,CX4016034,MC-000381-B0uW,T84-311Cas9,1
2507,CX4016034,MC-000446-BoNJ,KPNS19S-enCas12a,1
2508,CX4016034,MC-000654-PqYC,RAJI-311Cas9,1
2509,CX4016034,MC-000792-V2Ue,BFTC909-Cas9VY,1
2510,CX4016034,MC-000935-E55p,MDST8-Cas9VY,1
2487,CX4015911,MC-003124-dk5i,ASPS1-Cas9-AVANA4-RepA-P6(D22),1
2485,CX4015911,MC-003019-6LhD,LASCPC01-enCas12a-HumagneC-P4(D15),1
2353,CX4015699,MC-000055-M4n1,D283-311cas9(8/24/2015),1
2484,CX4015911,MC-002490-4KoT,NCIH1882-enCas12a-Humagne-RepB-P6(D21),1
2461,CX4015893,MC-003047-mwE5,ACH-003047 Pre-CD01 (3047 C12v2 P24 2/28/23) (...,1
2462,CX4015893,MC-003216-0lf7,ACH-003216 Pre-CD01 (3216 C12 P6 3/1 PreCD0) (...,1
2463,CX4015893,MC-003234-jqap,ACH-003234 Pre-CD01 (3234 Pre CD01) (p13),1
2464,CX4015893,MC-003235-ww88,ACH-003235 Pre-CD01 (3235 Pre CD01) (pX+12),1
2465,CX4015893,MC-003236-kso9,ACH-003036 Pre-CD01 (3036 Pre CD01 FP) (pX+12),1
2466,CX4015893,MC-003337-rEeE,ACH-003337 Post-CD01 (PDM-96 Post-CD01 FP) (p14),1
2467,CX4015893,MC-003404-ilHH,ACH-003404 Post-C12 (3404 C12 FP) (p23),1
2468,CX4015910,MC-000496-10Gs,NCIH1792-311Cas9(8/3/2021),1
2469,CX4015910,MC-000643-Lgxt,HDQP1-enCas12a,1
2470,CX4015910,MC-000792-V2Ue,BFTC909,1
2471,CX4015910,MC-000841-bBw4,NCIH2087(1/26/2013),1
2472,CX4015910,MC-000937-QPMF,PF382-311Cas9(2/25/2016),1
2473,CX4015910,MC-000938-Syvo,NALM6- 311cas9(12/26/2016),1
2474,CX4015910,MC-001862-LLaC,TGBC52TKB,1
2475,CX4015910,MC-003181-pqth,NRHLMS1-enCas12a,1
2476,CX4015911,MC-000037-Q40d,S117-311Cas9-ParalogV2-RepA-P6(D21),1
2477,CX4015911,MC-000037-Q40d,S117-311Cas9-ParalogV2-RepB-P6(D21),1
2478,CX4015911,MC-000090-ycrc,PC3-enCas12a-Humagne-RepA-P6(D21),1
2479,CX4015911,MC-000488-sREU,TE11-311Cas9-ParalogV2-RepA-P6(D21),1
2480,CX4015911,MC-001349-VGWT,HDMB03-enCas12a-HumagneC-P6(D21),1
2481,CX4015911,MC-001349-VGWT,HDMB03-enCas12a-HumagneD-P6(D21),1
2482,CX4015911,MC-001502-YixM,GCT27-enCas12a-HumagneC-P6(D22),1
2483,CX4015911,MC-002490-4KoT,NCIH1882-enCas12a-Humagne-RepA-P6(D21),1
2511,CX4016034,MC-001106-BKoT,KOPN8-311cas9(12/9/2016),1
2512,CX4016034,MC-001428-h8A5,CCLFPEDS0010T-enCas12a,1
2513,CX4016034,MC-001428-h8A5,CCLFPEDS0010T-enCas12a (47a),1
2514,CX4016034,MC-001712-DTo0,Hs860T-311Cas9(2/3/2017),1
2541,CX4016155,MC-002947-yu5B,ACH-002947 Post-CD01 (2947 C12 CD01 D24 FP) (p21),1
2542,CX4016155,MC-003047-mwE5,ACH-003047 Post-CD01(3047 C12v2 Post-CD01 FP)(...,1
2543,CX4016155,MC-003083-nyqF,ACH-003083 Post-CD03(3083 C12 Post-CD03 FP)(pX...,1
2544,CX4016155,MC-003332-PH24,ACH-003332 Post-C12 (190 C12) (p10),1
2545,CX4016155,MC-003332-PH24,ACH-003332-Post C12 (3332 C12) (p11),1
2546,CX4016155,MC-003334-3g7u,ACH-003334-Post C12 (3334 C12) (p14),1
2547,CX4016155,MC-003335-wchi,ACH-003335-Post C12 (3335 C12) (p11),1
2548,CX4016155,MC-003359-lUz6,ACH-003359 Pre-O (3359 FP/O),1
2549,CX4016156,MC-002413-3wte,ACH-002413-Pre-CD01 (2413 Pre-CD01 FP) (pX+10),1
2550,CX4016156,MC-003083-nyqF,ACH-003083 Pre-CD03 (3083 C12 Pre-CD03 FP) (pX...,1
2551,CX4016156,MC-003216-0lf7,ACH-003216-Post-CD01 (3216 Post CD FP) (p24),1
2552,CX4016156,MC-003234-jqap,ACH-003434-Post-CD01(3234 C12 Post CD01 FP)(p16),1
2553,CX4016156,MC-003235-ww88,ACH-003235-Post-CD01(3235 C12 Post CD01 FP)(pX...,1

In [6]:
all_str.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6486 entries, 0 to 6485
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      5705 non-null   object
 1   model_patient_id              5705 non-null   object
 2   model_model_id                5705 non-null   object
 3   mc_model_condition_id         5705 non-null   object
 4   mc_model_id                   5705 non-null   object
 5   str_patient_id                6486 non-null   object
 6   model_condition_id            5705 non-null   object
 7   id                            6486 non-null   object
 8   is_reference                  6486 non-null   bool
 9   d3s1358                       6415 non-null   object
 10  th01                          6434 non-null   object
 11  d21s11                        5200 non-null   object
 12  d18s51                        6268 non-null   object
 13  penta_e                       6100 non-null   object
 14  d5s818                        6369 non-null   object
 15  d13s317                       6366 non-null   object
 16  d7s820                        6416 non-null   object
 17  d16s539                       6436 non-null   object
 18  csf1po                        6446 non-null   object
 19  penta_d                       6187 non-null   object
 20  vwa                           4285 non-null   object
 21  d8s1179                       6341 non-null   object
 22  tpox                          5717 non-null   object
 23  fga                           6261 non-null   object
 24  pellet_creation_date          1426 non-null   object
 25  percentage_match_to_parental  1586 non-null   float64
 26  lab_corp_spec_nbr             2134 non-null   object
 27  lab_corp_case_nbr             4215 non-null   object
 28  comments                      1538 non-null   object
 29  amelogenin                    4275 non-null   object
 30  model_condition_id.1          5705 non-null   object
 31  mouse                         1363 non-null   object
 32  mycoplasma                    118 non-null    object
 33  patient_id                    6486 non-null   object
 34  source                        6486 non-null   object
 35  source_group                  6481 non-null   object
 36  pellet_submitted_date         601 non-null    object
 37  sample_reference              4257 non-null   object
 38  created_at                    6486 non-null   object
 39  updated_at                    6486 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 1.9+ MB

In [7]:
#reformatting upload_date to remove seconds 
all_str_single_upload = all_str
all_str_single_upload['created_at'] = pd.to_datetime(all_str_single_upload['created_at']).dt.strftime('%Y-%m-%d %H:%M')

In [8]:
#showing upload dates - year, month, day, hour and minute 
# showing upload counts
all_str_single_upload['created_at'] = pd.to_datetime(all_str_single_upload['created_at'])
all_str_single_upload_sort = all_str_single_upload.sort_values(by='created_at')
counts = all_str_single_upload_sort['created_at'].value_counts().sort_index()
counts

created_at
2024-04-09 16:00:00    3742
2024-04-10 17:49:00       1
2024-04-10 17:59:00       4
2024-04-10 18:00:00      42
2024-04-10 18:01:00      37
2024-04-10 18:02:00      42
2024-04-10 18:03:00      38
2024-04-10 18:04:00      22
2024-04-10 18:05:00      12
2024-04-10 18:06:00       3
2024-04-10 18:07:00       5
2024-04-10 18:08:00       3
2024-04-10 18:11:00       2
2024-04-10 18:12:00       2
2024-04-10 18:13:00       1
2024-04-10 18:14:00       1
2024-04-10 18:20:00       1
2024-04-10 18:33:00       2
2024-04-10 18:38:00       1
2024-04-10 19:12:00      38
2024-04-10 19:13:00      10
2024-04-10 19:15:00       2
2024-04-10 19:34:00      20
2024-04-10 19:35:00       1
2024-04-10 19:48:00       3
2024-04-10 20:12:00      18
2024-04-23 18:08:00       5
2024-04-23 18:09:00       7
2024-04-23 18:10:00       1
2024-04-23 18:22:00       3
2024-04-24 16:40:00       1
2024-04-24 16:41:00       1
2024-04-24 16:58:00       1
2024-04-29 14:57:00       1
2024-05-01 16:38:00      11
2024-05-01 16:39:00      22
2024-05-01 16:40:00      18
2024-05-01 16:41:00       2
2024-05-01 16:49:00       1
2024-05-01 16:50:00       1
2024-05-01 16:54:00       1
2024-05-02 16:39:00       2
2024-05-22 16:38:00       1
2024-05-22 16:39:00       7
2024-05-22 16:40:00       3
2024-05-22 16:49:00       1
2024-05-23 16:38:00       1
2024-05-23 16:39:00       4
2024-05-23 16:40:00       3
2024-05-23 16:41:00       2
2024-05-23 16:43:00       1
2024-05-24 16:38:00      15
2024-05-24 16:39:00      33
2024-05-24 16:40:00      24
2024-05-24 16:41:00       2
2024-05-24 16:42:00       2
2024-05-24 16:43:00      16
2024-05-24 16:44:00       3
2024-05-24 16:45:00       1
2024-05-24 16:47:00       1
2024-05-24 16:48:00      10
2024-05-24 16:49:00       3
2024-05-24 16:50:00       3
2024-05-24 16:51:00       2
2024-05-24 16:52:00       1
2024-06-03 14:57:00       1
2024-06-03 16:39:00       2
2024-06-03 16:42:00       1
2024-06-03 16:44:00       1
2024-06-03 16:55:00       1
2024-06-10 19:43:00       1
2024-06-10 19:56:00       1
2024-06-10 20:06:00       1
2024-06-10 20:40:00       1
2024-06-11 14:07:00       1
2024-06-11 14:15:00       1
2024-06-11 14:28:00       1
2024-06-11 14:32:00       1
2024-06-12 16:39:00       1
2024-06-12 16:40:00       4
2024-06-12 16:41:00       2
2024-06-12 16:42:00       1
2024-06-13 16:39:00       2
2024-06-13 16:40:00       4
2024-06-13 16:41:00       6
2024-06-13 16:42:00       3
2024-06-13 16:48:00       4
2024-06-14 16:39:00       1
2024-06-14 20:20:00       1
2024-06-14 20:39:00       1
2024-06-14 20:54:00       1
2024-06-14 21:02:00       1
2024-06-14 21:06:00       1
2024-06-20 14:08:00       1
2024-06-24 18:39:00       1
2024-06-26 16:32:00       1
2024-06-26 16:46:00       1
2024-06-26 16:51:00       1
2024-06-26 17:06:00       1
2024-06-26 17:15:00       1
2024-06-26 17:56:00       1
2024-06-26 19:21:00       1
2024-06-27 17:28:00       1
2024-06-27 17:36:00       1
2024-06-27 20:37:00       1
2024-06-28 15:38:00       1
2024-06-28 15:42:00       1
2024-06-28 15:47:00       1
2024-06-28 15:49:00       1
2024-06-28 16:20:00       1
2024-07-01 14:59:00      12
2024-07-01 15:00:00       3
2024-07-01 17:02:00      13
2024-07-02 16:38:00       5
2024-07-02 16:39:00       2
2024-07-02 16:40:00       2
2024-07-02 16:41:00       2
2024-07-02 16:46:00       1
2024-07-02 16:47:00       1
2024-07-02 16:50:00       1
2024-07-03 16:38:00       7
2024-07-03 16:39:00       2
2024-07-03 16:40:00       3
2024-07-03 16:41:00       2
2024-07-03 16:42:00       3
2024-07-16 16:41:00       1
2024-07-22 20:41:00       1
2024-07-24 16:39:00       1
2024-07-24 16:41:00       1
2024-07-25 16:40:00       3
2024-07-31 16:38:00       1
2024-07-31 16:39:00       2
2024-07-31 16:40:00       1
2024-08-13 14:32:00     670
2024-08-13 15:00:00      97
2024-08-13 15:45:00     458
2024-08-13 15:46:00     855
2024-08-16 16:39:00       2
Name: count, dtype: int64

In [9]:
# stripping created_at column of hour and minute - just the year-month-day
all_str_single_upload = all_str
all_str_single_upload['created_at'] = pd.to_datetime(all_str_single_upload['created_at']).dt.date

In [10]:
#using date filter of 8-13-2024 - can edit this date
filter_date = pd.to_datetime('2024-08-13').date()

In [11]:
#separating df into two separate dataframes - one containing filter_date and one without filter_dat
str_containing_filter_date = all_str_single_upload[all_str_single_upload['created_at'] == filter_date]
remaining_df = all_str_single_upload[all_str_single_upload['created_at'] != filter_date]

In [12]:
#check
remaining_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4406 entries, 0 to 4405
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      3625 non-null   object
 1   model_patient_id              3625 non-null   object
 2   model_model_id                3625 non-null   object
 3   mc_model_condition_id         3625 non-null   object
 4   mc_model_id                   3625 non-null   object
 5   str_patient_id                4406 non-null   object
 6   model_condition_id            3625 non-null   object
 7   id                            4406 non-null   object
 8   is_reference                  4406 non-null   bool
 9   d3s1358                       4338 non-null   object
 10  th01                          4357 non-null   object
 11  d21s11                        3132 non-null   object
 12  d18s51                        4191 non-null   object
 13  penta_e                       4023 non-null   object
 14  d5s818                        4292 non-null   object
 15  d13s317                       4289 non-null   object
 16  d7s820                        4339 non-null   object
 17  d16s539                       4359 non-null   object
 18  csf1po                        4369 non-null   object
 19  penta_d                       4110 non-null   object
 20  vwa                           2208 non-null   object
 21  d8s1179                       4264 non-null   object
 22  tpox                          3640 non-null   object
 23  fga                           4184 non-null   object
 24  pellet_creation_date          301 non-null    object
 25  percentage_match_to_parental  1520 non-null   float64
 26  lab_corp_spec_nbr             2134 non-null   object
 27  lab_corp_case_nbr             2135 non-null   object
 28  comments                      1538 non-null   object
 29  amelogenin                    2198 non-null   object
 30  model_condition_id.1          3625 non-null   object
 31  mouse                         977 non-null    object
 32  mycoplasma                    118 non-null    object
 33  patient_id                    4406 non-null   object
 34  source                        4406 non-null   object
 35  source_group                  4401 non-null   object
 36  pellet_submitted_date         601 non-null    object
 37  sample_reference              2177 non-null   object
 38  created_at                    4406 non-null   object
 39  updated_at                    4406 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 1.3+ MB

In [13]:
#check
str_containing_filter_date.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2080 entries, 4406 to 6485
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      2080 non-null   object
 1   model_patient_id              2080 non-null   object
 2   model_model_id                2080 non-null   object
 3   mc_model_condition_id         2080 non-null   object
 4   mc_model_id                   2080 non-null   object
 5   str_patient_id                2080 non-null   object
 6   model_condition_id            2080 non-null   object
 7   id                            2080 non-null   object
 8   is_reference                  2080 non-null   bool
 9   d3s1358                       2077 non-null   object
 10  th01                          2077 non-null   object
 11  d21s11                        2068 non-null   object
 12  d18s51                        2077 non-null   object
 13  penta_e                       2077 non-null   object
 14  d5s818                        2077 non-null   object
 15  d13s317                       2077 non-null   object
 16  d7s820                        2077 non-null   object
 17  d16s539                       2077 non-null   object
 18  csf1po                        2077 non-null   object
 19  penta_d                       2077 non-null   object
 20  vwa                           2077 non-null   object
 21  d8s1179                       2077 non-null   object
 22  tpox                          2077 non-null   object
 23  fga                           2077 non-null   object
 24  pellet_creation_date          1125 non-null   object
 25  percentage_match_to_parental  66 non-null     float64
 26  lab_corp_spec_nbr             0 non-null      object
 27  lab_corp_case_nbr             2080 non-null   object
 28  comments                      0 non-null      object
 29  amelogenin                    2077 non-null   object
 30  model_condition_id.1          2080 non-null   object
 31  mouse                         386 non-null    object
 32  mycoplasma                    0 non-null      object
 33  patient_id                    2080 non-null   object
 34  source                        2080 non-null   object
 35  source_group                  2080 non-null   object
 36  pellet_submitted_date         0 non-null      object
 37  sample_reference              2080 non-null   object
 38  created_at                    2080 non-null   object
 39  updated_at                    2080 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 652.0+ KB

In [14]:
#dropping duplicates in the str_containing_filter_date based on 'sample_reference' and 'lab_corp_case_nbr'
str_containing_filter_date = str_containing_filter_date.drop_duplicates(subset=['sample_reference', 'lab_corp_case_nbr'], keep='first')
str_containing_filter_date.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2080 entries, 4406 to 6485
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      2080 non-null   object
 1   model_patient_id              2080 non-null   object
 2   model_model_id                2080 non-null   object
 3   mc_model_condition_id         2080 non-null   object
 4   mc_model_id                   2080 non-null   object
 5   str_patient_id                2080 non-null   object
 6   model_condition_id            2080 non-null   object
 7   id                            2080 non-null   object
 8   is_reference                  2080 non-null   bool
 9   d3s1358                       2077 non-null   object
 10  th01                          2077 non-null   object
 11  d21s11                        2068 non-null   object
 12  d18s51                        2077 non-null   object
 13  penta_e                       2077 non-null   object
 14  d5s818                        2077 non-null   object
 15  d13s317                       2077 non-null   object
 16  d7s820                        2077 non-null   object
 17  d16s539                       2077 non-null   object
 18  csf1po                        2077 non-null   object
 19  penta_d                       2077 non-null   object
 20  vwa                           2077 non-null   object
 21  d8s1179                       2077 non-null   object
 22  tpox                          2077 non-null   object
 23  fga                           2077 non-null   object
 24  pellet_creation_date          1125 non-null   object
 25  percentage_match_to_parental  66 non-null     float64
 26  lab_corp_spec_nbr             0 non-null      object
 27  lab_corp_case_nbr             2080 non-null   object
 28  comments                      0 non-null      object
 29  amelogenin                    2077 non-null   object
 30  model_condition_id.1          2080 non-null   object
 31  mouse                         386 non-null    object
 32  mycoplasma                    0 non-null      object
 33  patient_id                    2080 non-null   object
 34  source                        2080 non-null   object
 35  source_group                  2080 non-null   object
 36  pellet_submitted_date         0 non-null      object
 37  sample_reference              2080 non-null   object
 38  created_at                    2080 non-null   object
 39  updated_at                    2080 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 652.0+ KB

In [15]:
#combining the str_containing_filter_date that no longer has dupes wiht the remaining_df
all_str_single_upload = pd.concat([str_containing_filter_date, remaining_df]).drop_duplicates()
all_str_single_upload.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6486 entries, 4406 to 4405
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      5705 non-null   object
 1   model_patient_id              5705 non-null   object
 2   model_model_id                5705 non-null   object
 3   mc_model_condition_id         5705 non-null   object
 4   mc_model_id                   5705 non-null   object
 5   str_patient_id                6486 non-null   object
 6   model_condition_id            5705 non-null   object
 7   id                            6486 non-null   object
 8   is_reference                  6486 non-null   bool
 9   d3s1358                       6415 non-null   object
 10  th01                          6434 non-null   object
 11  d21s11                        5200 non-null   object
 12  d18s51                        6268 non-null   object
 13  penta_e                       6100 non-null   object
 14  d5s818                        6369 non-null   object
 15  d13s317                       6366 non-null   object
 16  d7s820                        6416 non-null   object
 17  d16s539                       6436 non-null   object
 18  csf1po                        6446 non-null   object
 19  penta_d                       6187 non-null   object
 20  vwa                           4285 non-null   object
 21  d8s1179                       6341 non-null   object
 22  tpox                          5717 non-null   object
 23  fga                           6261 non-null   object
 24  pellet_creation_date          1426 non-null   object
 25  percentage_match_to_parental  1586 non-null   float64
 26  lab_corp_spec_nbr             2134 non-null   object
 27  lab_corp_case_nbr             4215 non-null   object
 28  comments                      1538 non-null   object
 29  amelogenin                    4275 non-null   object
 30  model_condition_id.1          5705 non-null   object
 31  mouse                         1363 non-null   object
 32  mycoplasma                    118 non-null    object
 33  patient_id                    6486 non-null   object
 34  source                        6486 non-null   object
 35  source_group                  6481 non-null   object
 36  pellet_submitted_date         601 non-null    object
 37  sample_reference              4257 non-null   object
 38  created_at                    6486 non-null   object
 39  updated_at                    6486 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 2.0+ MB

In [16]:
#resetting index
all_str_single_upload = all_str_single_upload.reset_index(drop=True)
all_str_single_upload.head(10)

,model_id,model_patient_id,model_model_id,mc_model_condition_id,mc_model_id,str_patient_id,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id.1,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-000296,PT-GezIUF,ACH-000296,MC-000296-bgzW,ACH-000296,PT-GezIUF,MC-000296-bgzW,STR-WWzBpU,False,"16, 17",9.3,"28, 30",16,5,11,12,10,11,12,"9, 12",16,"13, 16",11,23.2,2024-03-11,NaN,NaN,CX4018877,NaN,X,MC-000296-bgzW,NaN,NaN,PT-GezIUF,Internal,GPP,NaN,OUMS23Cas9VY,2024-08-13,2024-08-13 15:46:14.431081+00:00
1,ACH-002499,PT-j6UudO,ACH-002499,MC-002499-dWxK,ACH-002499,PT-j6UudO,MC-002499-dWxK,STR-U7lF8I,False,18,9.3,30.2,20,12,13,11,10,12,12,12,"15, 17","11, 13","10, 13",23,NaN,NaN,NaN,CX4012569,NaN,X,MC-002499-dWxK,NaN,NaN,PT-j6UudO,Internal,GPP,NaN,UACC3199-311cas9,2024-08-13,2024-08-13 14:32:29.862597+00:00
2,ACH-002499,PT-j6UudO,ACH-002499,MC-002499-dWxK,ACH-002499,PT-j6UudO,MC-002499-dWxK,STR-QADpM0,False,18,9.3,30.2,20,12,13,11,10,12,12,12,"15, 17","11, 13","10, 13",23,2022-08-31,NaN,NaN,CX4014596,NaN,X,MC-002499-dWxK,NaN,NaN,PT-j6UudO,Internal,GPP,NaN,UACC3199-311Cas9-RepA-P4,2024-08-13,2024-08-13 14:32:29.862597+00:00
3,ACH-002051,PT-K31XId,ACH-002051,MC-002051-2Ddi,ACH-002051,PT-K31XId,MC-002051-2Ddi,STR-lKKdW7,False,17,9,30,17,14,11,9,11,9,12,"9, 13",17,"10, 11",11,19,NaN,NaN,NaN,CX4011714,NaN,X,MC-002051-2Ddi,NaN,NaN,PT-K31XId,Internal,GPP,NaN,LU134A-311cas9,2024-08-13,2024-08-13 14:32:29.862597+00:00
4,ACH-003170,PT-FJLnco,ACH-003170,MC-003170-0VvA,ACH-003170,PT-FJLnco,MC-003170-0VvA,STR-b5TCvd,False,"15, 16",9.3,"26.2, 31",13,"13, 18",11,12,"10, 11","11, 13","11, 12","9, 15","15, 16",14,8,"19, 21",2023-12-09,NaN,NaN,CX4018283,NaN,X,MC-003170-0VvA,NaN,NaN,PT-FJLnco,Internal,GPP,NaN,NRHLS1-enCas12a,2024-08-13,2024-08-13 15:45:03.795747+00:00
5,ACH-000085,PT-FnO2p8,ACH-000085,MC-000085-DjQm,ACH-000085,PT-FnO2p8,MC-000085-DjQm,STR-1EcCBm,False,14,9.3,32.2,16,"11, 12",11,"10, 13",12,"11, 12",10,10,"18, 19, 21",16,"11, 12","24, 25",2023-04-21,NaN,NaN,CX4016249,NaN,X,MC-000085-DjQm,NaN,NaN,PT-FnO2p8,Internal,GPP,NaN,T3M4-Cas9VY,2024-08-13,2024-08-13 15:45:03.795747+00:00
6,ACH-000085,PT-FnO2p8,ACH-000085,MC-000085-DjQm,ACH-000085,PT-FnO2p8,MC-000085-DjQm,STR-0tHUMB,False,14,9.3,32.2,16,"11, 12",11,"10, 13",12,"11, 12",10,10,"18, 21",16,"11, 12","24, 25",2023-09-07,NaN,NaN,CX4017466,NaN,X,MC-000085-DjQm,NaN,NaN,PT-FnO2p8,Internal,GPP,NaN,T3M4-Cas9VY-ParalogV2-RepA-P6(D22),2024-08-13,2024-08-13 15:45:03.795747+00:00
7,ACH-002708,PT-03AcoW,ACH-002708,MC-002708-tPxj,ACH-002708,PT-03AcoW,MC-002708-tPxj,STR-gXdz7j,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4011254,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9-RepA-p6,2024-08-13,2024-08-13 15:00:15.893191+00:00
8,ACH-002708,PT-03AcoW,ACH-002708,MC-002708-tPxj,ACH-002708,PT-03AcoW,MC-002708-tPxj,STR-rZZq4u,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4011254,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9-RepB-p6,2024-08-13,2024-08-13 15:00:15.893191+00:00
9,ACH-002708,PT-03AcoW,ACH-002708,MC-002708-tPxj,ACH-002708,PT-03AcoW,MC-002708-tPxj,STR-42bCys,False,"15, 16","8, 9",29,"14, 17","12, 16",12,"8, 11","10, 12","12, 13","10, 13","10, 12","14, 17","10, 14",8,20,NaN,NaN,NaN,CX4010487,NaN,X,MC-002708-tPxj,NaN,NaN,PT-03AcoW,Internal,GPP,NaN,DL221-311cas9,2024-08-13,2024-08-13 15:00:15.893191+00:00

In [17]:
all_str_single_upload.columns

Index(['model_id', 'model_patient_id', 'model_model_id',
       'mc_model_condition_id', 'mc_model_id', 'str_patient_id',
       'model_condition_id', 'id', 'is_reference', 'd3s1358', 'th01', 'd21s11',
       'd18s51', 'penta_e', 'd5s818', 'd13s317', 'd7s820', 'd16s539', 'csf1po',
       'penta_d', 'vwa', 'd8s1179', 'tpox', 'fga', 'pellet_creation_date',
       'percentage_match_to_parental', 'lab_corp_spec_nbr',
       'lab_corp_case_nbr', 'comments', 'amelogenin', 'model_condition_id.1',
       'mouse', 'mycoplasma', 'patient_id', 'source', 'source_group',
       'pellet_submitted_date', 'sample_reference', 'created_at',
       'updated_at'],
      dtype='object')

In [18]:
all_str_single_upload.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6486 entries, 0 to 6485
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      5705 non-null   object
 1   model_patient_id              5705 non-null   object
 2   model_model_id                5705 non-null   object
 3   mc_model_condition_id         5705 non-null   object
 4   mc_model_id                   5705 non-null   object
 5   str_patient_id                6486 non-null   object
 6   model_condition_id            5705 non-null   object
 7   id                            6486 non-null   object
 8   is_reference                  6486 non-null   bool
 9   d3s1358                       6415 non-null   object
 10  th01                          6434 non-null   object
 11  d21s11                        5200 non-null   object
 12  d18s51                        6268 non-null   object
 13  penta_e                       6100 non-null   object
 14  d5s818                        6369 non-null   object
 15  d13s317                       6366 non-null   object
 16  d7s820                        6416 non-null   object
 17  d16s539                       6436 non-null   object
 18  csf1po                        6446 non-null   object
 19  penta_d                       6187 non-null   object
 20  vwa                           4285 non-null   object
 21  d8s1179                       6341 non-null   object
 22  tpox                          5717 non-null   object
 23  fga                           6261 non-null   object
 24  pellet_creation_date          1426 non-null   object
 25  percentage_match_to_parental  1586 non-null   float64
 26  lab_corp_spec_nbr             2134 non-null   object
 27  lab_corp_case_nbr             4215 non-null   object
 28  comments                      1538 non-null   object
 29  amelogenin                    4275 non-null   object
 30  model_condition_id.1          5705 non-null   object
 31  mouse                         1363 non-null   object
 32  mycoplasma                    118 non-null    object
 33  patient_id                    6486 non-null   object
 34  source                        6486 non-null   object
 35  source_group                  6481 non-null   object
 36  pellet_submitted_date         601 non-null    object
 37  sample_reference              4257 non-null   object
 38  created_at                    6486 non-null   object
 39  updated_at                    6486 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 1.9+ MB

In [19]:
#checking for patient ids that dont match - including rows where one column has a na
mask = ((all_str_single_upload['model_patient_id'] != all_str_single_upload['str_patient_id']) |
    (all_str_single_upload['model_patient_id'].isna() != all_str_single_upload['str_patient_id'].isna()))
patient_id_discrepancies_including_na = all_str_single_upload[mask]
patient_id_discrepancies_including_na.head(15)

,model_id,model_patient_id,model_model_id,mc_model_condition_id,mc_model_id,str_patient_id,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id.1,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
2225,NaN,NaN,NaN,NaN,NaN,PT-vEZ2Aw,NaN,STR-wfpoXW,False,"15, 16","6, 9.3","27, 30","14, 17","7, 11",12,"10, 11","9, 10","12, 13",10,"11, 15","15, 16","11, 14",11,"21, 22",NaN,NaN,77I90570,CX4003713,unique; Unique cell line - no reference profil...,"X, Y",NaN,NaN,NaN,PT-vEZ2Aw,Internal,PRISM,NaN,C8166_LUA-4915,2024-04-09,2024-04-09 16:00:46.668811+00:00
2256,NaN,NaN,NaN,NaN,NaN,PT-xfVhgW,NaN,STR-0aaUxd,False,"14, 17","6, 9",30,"17, 19","5, 10","9, 13","9, 13","9, 11",13,"10, 11","11, 14",18,"12, 14","8, 11",23,NaN,NaN,82192670,CX4004605,matches reference; STR matches reference profi...,X,NaN,Not Detected,NaN,PT-xfVhgW,Internal,PRISM,NaN,TE 617.T_LUA-4867,2024-04-09,2024-04-09 16:00:46.668811+00:00
2277,NaN,NaN,NaN,NaN,NaN,PT-pktZZ0,NaN,STR-0C5Man,True,18,9,31.2,14,14,12,11,"8, 10",11,12,12,"14, 15","11, 13","8, 12",19,2022-07-11,NaN,27F91120,CX4014235,NaN,"X, Y",NaN,Not Detected,NaN,PT-pktZZ0,Internal,Mnemosyne,2022-07-14,ACH-002815-Pre-O (p6),2024-04-09,2024-04-09 16:00:46.668811+00:00
2290,NaN,NaN,NaN,NaN,NaN,PT-Mi0cKz,NaN,STR-0DiPWv,False,16,6,29,"16, 18","7, 10","10, 12",12,"10, 11",9,"10, 12","11, 15","17, 19",14,"8, 11","17, 22",NaN,NaN,7A590840,CX4004072,matches reference; STR matches reference profile,X,NaN,NaN,NaN,PT-Mi0cKz,Internal,PRISM,NaN,T24_LUA-3463,2024-04-09,2024-04-09 16:00:46.668811+00:00
2355,NaN,NaN,NaN,NaN,NaN,PT-j60QIc,NaN,STR-HoomuX,False,15,9.3,"28, 29, 30","15, 19","13, 15","12, 13","10, 13","8, 10","11, 13",10,"11, 12",18,"13, 15",12,"20, 21",NaN,NaN,84C92190,CX4004964,matches reference; STR matches reference profi...,"X, Y",NaN,Not Detected,NaN,PT-j60QIc,Internal,PRISM,NaN,WM-88_LUA-3105,2024-04-09,2024-04-09 16:00:46.668811+00:00
2387,NaN,NaN,NaN,NaN,NaN,PT-OfCVRv,NaN,STR-kM6u1h,True,15,9.3,"29, 30","12, 14","7, 14",11,11,"9, 11","11, 12",10,"12, 13","18, 19","11, 13",11,"19, 22",NaN,NaN,7AP91410,CX4004205,matches reference; Matches reference profile a...,X,NaN,Not Detected,NaN,PT-OfCVRv,Internal,DMX,NaN,184B5; From Legacy pellet MC-001827-qPLL,2024-04-09,2024-06-10 19:23:55.122242+00:00
2423,NaN,NaN,NaN,NaN,NaN,PT-kI5CjI,NaN,STR-hvDm3j,False,16,9,31.2,12,"15, 17",12,"11, 12","8, 12","11, 13","10, 12",13,17,"12, 13","8, 11",18,NaN,NaN,87691080,CX4005370,matches reference; STR matches reference profile,"X, Y",NaN,Not Detected,NaN,PT-kI5CjI,Internal,PRISM,NaN,A427_LUA-3196,2024-04-09,2024-04-09 16:00:46.668811+00:00
2446,NaN,NaN,NaN,NaN,NaN,PT-4qxYZb,NaN,STR-0vRjam,False,15,7,27,15,"7, 13",12,11,"9, 12",11,12,"2.2, 8",15,"12, 13","8, 11","19, 22",NaN,NaN,7A591310,CX4004074,matches reference; STR matches reference profile,X,NaN,NaN,NaN,PT-4qxYZb,Internal,PRISM,NaN,NCI-H2172_LUA-3983,2024-04-09,2024-04-09 16:00:46.668811+00:00
2492,NaN,NaN,NaN,NaN,NaN,PT-5LVIPg,NaN,STR-jvpSct,False,18,9.3,30,10,12,11,11,"8, 9","11, 12",11,8,18,12,11,20,NaN,NaN,7A591210,CX4004073,matches reference; STR matches reference profile,X,NaN,NaN,NaN,PT-5LVIPg,Internal,PRISM,NaN,NCI-H1650_LUA-3154,2024-04-09,2024-04-09 16:00:46.668811+00:00
2507,NaN,NaN,NaN,NaN,NaN,PT-T9nCW5,NaN,STR-17qBvb,False,16,9,31,"12, 16","5, 14",11,11,10,13,12,13,17,"10, 14",8,22,NaN,NaN,84C91470,CX4004961,matches reference; STR matches reference profi...,X,NaN,Not Detected,NaN,PT-T9nCW5,Internal,PRISM,NaN,Calu-6_LUA-3040,2024-04-09,2024-04-09 16:00:46.668811+00:00
2522,NaN,NaN,NaN,NaN,NaN,PT-Qpiidf,NaN,STR-18sjyU,False,16,"9, 9.3","29, 31","13, 16","14, 16",11,13,10,"11, 12","10, 12","12, 13","17, 18, 19","13, 15","8, 9","24, 26",NaN,0.9787,84C92960,CX4004967,matches reference; STR matches reference profile,"X, Y",NaN,Not Detected,NaN,PT-Qpiidf,Internal,PRISM,NaN,JVM-3_LUA-4392,2024-04-09,2024-04-09 16:00:46.668811+00:00
2526,NaN,NaN,NaN,NaN,NaN,PT-0F4qCF,NaN,STR-i2weMX,False,16,"8, 10","29, 30","12, 18","11, 13","11, 13","8, 13","9, 10","11, 13","11, 12","12, 13","17, 18","10, 12","8, 11",22,NaN,NaN,87691240,CX4005371,matches reference; STR matches reference profi...,X,NaN,Not Detected,NaN,PT-0F4qCF,Internal,PRISM,NaN,OCI-AML3_LUA-4107,2024-04-09,2024-04-09 16:00:46.668811+00:00
2551,NaN,NaN,NaN,NaN,NaN,PT-4bJRaf,NaN,STR-1aKGgJ,False,17,"6, 9","30, 31.2","14, 15","11, 15",11,11,"11, 14","9, 10","11, 12","9, 12","16, 18","11, 13",8,20,NaN,NaN,82193870,CX4004610,matches reference; STR matches reference profi...,"X, Y",NaN,NaN,NaN,PT-4bJRaf,Internal,PRISM,NaN,T3M-10_LUA-3913,2024-04-09,2024-04-09 16:00:46.668811+00:00
2554,ACH-003298,PT-a93e6k,ACH-003298,MC-003298-iops,ACH-003298,PT-DzY90c,MC-003298-iops,STR-wDl1PX,False,"17, 18","7, 9.3",NaN,"12, 17","7.1, 8.1","9, 11","12, 13","11, 12","11, 13","11, 12",NaN,NaN,"12, 14",11,"21, 25",NaN,NaN,NaN,NaN,NaN,NaN,MC-003298-iops,NaN,NaN,PT-DzY90c,Internal,WGS Inferred,NaN,NaN,2024-04-10,2024-04-10 18:01:27.529945+00:00
2555,NaN,NaN,NaN,NaN,NaN,PT-5XnRfQ,NaN,STR-1b5aoj,False,15,6,"27, 32.2",13,7,11,9,9,"12, 13","11, 12","10, 13",18,"14, 15",8,"22, 23",NaN,NaN,87691230,CX4005371,matches reference; STR matches reference profi...,"X, Y",NaN,Not Detected,NaN,PT-5XnRfQ,Internal,PRISM,NaN,U-118 MG_LUA-3697,2024-04-09,2024-04-09 16:00:46.668811+00:00

In [20]:
#saving as csv file
patient_id_discrepancies_including_na = patient_id_discrepancies_including_na.reset_index(drop=True)
patient_id_discrepancies_including_na.to_csv('patient_id_discrepancies_including_na.csv',index=False)
patient_id_discrepancies_including_na.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 789 entries, 0 to 788
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      8 non-null      object
 1   model_patient_id              8 non-null      object
 2   model_model_id                8 non-null      object
 3   mc_model_condition_id         8 non-null      object
 4   mc_model_id                   8 non-null      object
 5   str_patient_id                789 non-null    object
 6   model_condition_id            8 non-null      object
 7   id                            789 non-null    object
 8   is_reference                  789 non-null    bool
 9   d3s1358                       774 non-null    object
 10  th01                          788 non-null    object
 11  d21s11                        779 non-null    object
 12  d18s51                        768 non-null    object
 13  penta_e                       766 non-null    object
 14  d5s818                        787 non-null    object
 15  d13s317                       787 non-null    object
 16  d7s820                        786 non-null    object
 17  d16s539                       785 non-null    object
 18  csf1po                        783 non-null    object
 19  penta_d                       766 non-null    object
 20  vwa                           779 non-null    object
 21  d8s1179                       772 non-null    object
 22  tpox                          780 non-null    object
 23  fga                           769 non-null    object
 24  pellet_creation_date          10 non-null     object
 25  percentage_match_to_parental  75 non-null     float64
 26  lab_corp_spec_nbr             755 non-null    object
 27  lab_corp_case_nbr             755 non-null    object
 28  comments                      725 non-null    object
 29  amelogenin                    777 non-null    object
 30  model_condition_id.1          8 non-null      object
 31  mouse                         333 non-null    object
 32  mycoplasma                    0 non-null      object
 33  patient_id                    789 non-null    object
 34  source                        789 non-null    object
 35  source_group                  787 non-null    object
 36  pellet_submitted_date         41 non-null     object
 37  sample_reference              769 non-null    object
 38  created_at                    789 non-null    object
 39  updated_at                    789 non-null    object
dtypes: bool(1), float64(1), object(38)
memory usage: 241.3+ KB

In [21]:
#checking for patient ids that dont match - patient id are different (not including na)
mask = ( (all_str_single_upload['model_patient_id'] != all_str_single_upload['str_patient_id']) &
      (all_str_single_upload['model_patient_id'].notna() & all_str_single_upload['str_patient_id'].notna()))
patient_id_discrepancies = all_str_single_upload[mask]
patient_id_discrepancies

,model_id,model_patient_id,model_model_id,mc_model_condition_id,mc_model_id,str_patient_id,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id.1,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
2554,ACH-003298,PT-a93e6k,ACH-003298,MC-003298-iops,ACH-003298,PT-DzY90c,MC-003298-iops,STR-wDl1PX,False,"17, 18","7, 9.3",NaN,"12, 17","7.1, 8.1","9, 11","12, 13","11, 12","11, 13","11, 12",NaN,NaN,"12, 14",11,"21, 25",NaN,NaN,NaN,NaN,NaN,NaN,MC-003298-iops,NaN,NaN,PT-DzY90c,Internal,WGS Inferred,NaN,NaN,2024-04-10,2024-04-10 18:01:27.529945+00:00
3843,ACH-003298,PT-a93e6k,ACH-003298,MC-003298-iops,ACH-003298,PT-DzY90c,MC-003298-iops,STR-KcLKO2,False,"17, 18","9.3, 7",NaN,"12, 17","7.1, 8.1","11, 9","12, 13","12, 11","11, 13","12, 11",NaN,NaN,"12, 14",11,"25, 21",NaN,NaN,NaN,NaN,NaN,NaN,MC-003298-iops,NaN,NaN,PT-DzY90c,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
4387,ACH-000956,PT-FFSOW0,ACH-000956,MC-000956-WA5g,ACH-000956,PT-rqTCjv,MC-000956-WA5g,STR-ynUjMG,False,15,"6, 9.3",31.3,"13, 14",5.1,NaN,"9, 12","11, 9",12,10,"11, 8",NaN,"13, 14",8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MC-000956-WA5g,NaN,NaN,PT-rqTCjv,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
4436,ACH-002851,PT-QKOh5t,ACH-002851,MC-002851-Vej0,ACH-002851,PT-wKJvCj,MC-002851-Vej0,STR-R063A0,False,"15, 17",6,NaN,14,"12.1, 7.1","10, 11","9, 14","9, 12","11, 12","10, 11",12,NaN,"13, 14","9, 8","20, 21",NaN,NaN,NaN,NaN,NaN,NaN,MC-002851-Vej0,NaN,NaN,PT-wKJvCj,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
4790,ACH-002851,PT-QKOh5t,ACH-002851,MC-002851-Vej0,ACH-002851,PT-wKJvCj,MC-002851-Vej0,STR-dWuqsd,False,"15, 17",6,NaN,14,"7.1, 12.1","10, 11","9, 14","12, 9","11, 12","10, 11","11, 12",NaN,"13, 14","8, 9","21, 20",NaN,NaN,NaN,NaN,NaN,NaN,MC-002851-Vej0,NaN,NaN,PT-wKJvCj,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
5702,ACH-003370,PT-QKBqJJ,ACH-003370,MC-003370-hUep,ACH-003370,PT-l7O5zs,MC-003370-hUep,STR-neD4je,False,"15, 17","6, 9.3",NaN,"15, 20",7.1,"12, 13","9, 12",10,"9, 13","11, 12",10,NaN,"10, 13",NaN,"20, 23",NaN,NaN,NaN,NaN,NaN,NaN,MC-003370-hUep,NaN,NaN,PT-l7O5zs,Internal,WGS Inferred,NaN,NaN,2024-05-01,2024-05-01 16:39:43.608810+00:00
6067,ACH-002923,PT-22FXN6,ACH-002923,MC-002923-TlcE,ACH-002923,PT-5fEWVP,MC-002923-TlcE,STR-tByA3I,False,"16, 16.2",9.3,31.3,14,"11.1, 12.1",12,"11, 12","10, 11","9, 10",12,"8, 12",NaN,"13, 14",NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,MC-002923-TlcE,NaN,NaN,PT-5fEWVP,Internal,WGS Inferred,NaN,NaN,2024-05-22,2024-05-22 16:39:41.348395+00:00
6309,ACH-000000,PT-Q3O6VZ,ACH-000000,MC-000000-TEST,ACH-000000,PT-01q6LP,MC-000000-TEST,STR-CJTFQN,False,TEST1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MC-000000-TEST,NaN,NaN,PT-01q6LP,Internal,NaN,NaN,NaN,2024-07-22,2024-07-22 20:41:46.424788+00:00

In [22]:
#saving as csv file
patient_id_discrepancies = patient_id_discrepancies.reset_index(drop=True)
patient_id_discrepancies.to_csv('patient_id_discrepancies.csv',index=False)
patient_id_discrepancies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      8 non-null      object
 1   model_patient_id              8 non-null      object
 2   model_model_id                8 non-null      object
 3   mc_model_condition_id         8 non-null      object
 4   mc_model_id                   8 non-null      object
 5   str_patient_id                8 non-null      object
 6   model_condition_id            8 non-null      object
 7   id                            8 non-null      object
 8   is_reference                  8 non-null      bool
 9   d3s1358                       8 non-null      object
 10  th01                          7 non-null      object
 11  d21s11                        2 non-null      object
 12  d18s51                        7 non-null      object
 13  penta_e                       7 non-null      object
 14  d5s818                        6 non-null      object
 15  d13s317                       7 non-null      object
 16  d7s820                        7 non-null      object
 17  d16s539                       7 non-null      object
 18  csf1po                        7 non-null      object
 19  penta_d                       5 non-null      object
 20  vwa                           0 non-null      object
 21  d8s1179                       7 non-null      object
 22  tpox                          5 non-null      object
 23  fga                           6 non-null      object
 24  pellet_creation_date          0 non-null      object
 25  percentage_match_to_parental  0 non-null      float64
 26  lab_corp_spec_nbr             0 non-null      object
 27  lab_corp_case_nbr             0 non-null      object
 28  comments                      0 non-null      object
 29  amelogenin                    0 non-null      object
 30  model_condition_id.1          8 non-null      object
 31  mouse                         0 non-null      object
 32  mycoplasma                    0 non-null      object
 33  patient_id                    8 non-null      object
 34  source                        8 non-null      object
 35  source_group                  7 non-null      object
 36  pellet_submitted_date         0 non-null      object
 37  sample_reference              0 non-null      object
 38  created_at                    8 non-null      object
 39  updated_at                    8 non-null      object
dtypes: bool(1), float64(1), object(38)
memory usage: 2.6+ KB

In [23]:
#checking for model ids that dont match
mask_model = ( (all_str_single_upload['model_model_id'] != all_str_single_upload['mc_model_id']) &
      (all_str_single_upload['model_model_id'].notna() & all_str_single_upload['mc_model_id'].notna()))
model_id_discrepancies = all_str_single_upload[mask_model]
model_id_discrepancies

Empty DataFrame
Columns: [model_id, model_patient_id, model_model_id, mc_model_condition_id, mc_model_id, str_patient_id, model_condition_id, id, is_reference, d3s1358, th01, d21s11, d18s51, penta_e, d5s818, d13s317, d7s820, d16s539, csf1po, penta_d, vwa, d8s1179, tpox, fga, pellet_creation_date, percentage_match_to_parental, lab_corp_spec_nbr, lab_corp_case_nbr, comments, amelogenin, model_condition_id.1, mouse, mycoplasma, patient_id, source, source_group, pellet_submitted_date, sample_reference, created_at, updated_at]
Index: []

In [24]:
#saving as csv file
model_id_discrepancies = model_id_discrepancies.reset_index(drop=True)
model_id_discrepancies.to_csv('model_id_discrepancies.csv',index=False)
model_id_discrepancies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      0 non-null      object
 1   model_patient_id              0 non-null      object
 2   model_model_id                0 non-null      object
 3   mc_model_condition_id         0 non-null      object
 4   mc_model_id                   0 non-null      object
 5   str_patient_id                0 non-null      object
 6   model_condition_id            0 non-null      object
 7   id                            0 non-null      object
 8   is_reference                  0 non-null      bool
 9   d3s1358                       0 non-null      object
 10  th01                          0 non-null      object
 11  d21s11                        0 non-null      object
 12  d18s51                        0 non-null      object
 13  penta_e                       0 non-null      object
 14  d5s818                        0 non-null      object
 15  d13s317                       0 non-null      object
 16  d7s820                        0 non-null      object
 17  d16s539                       0 non-null      object
 18  csf1po                        0 non-null      object
 19  penta_d                       0 non-null      object
 20  vwa                           0 non-null      object
 21  d8s1179                       0 non-null      object
 22  tpox                          0 non-null      object
 23  fga                           0 non-null      object
 24  pellet_creation_date          0 non-null      object
 25  percentage_match_to_parental  0 non-null      float64
 26  lab_corp_spec_nbr             0 non-null      object
 27  lab_corp_case_nbr             0 non-null      object
 28  comments                      0 non-null      object
 29  amelogenin                    0 non-null      object
 30  model_condition_id.1          0 non-null      object
 31  mouse                         0 non-null      object
 32  mycoplasma                    0 non-null      object
 33  patient_id                    0 non-null      object
 34  source                        0 non-null      object
 35  source_group                  0 non-null      object
 36  pellet_submitted_date         0 non-null      object
 37  sample_reference              0 non-null      object
 38  created_at                    0 non-null      object
 39  updated_at                    0 non-null      object
dtypes: bool(1), float64(1), object(38)
memory usage: 132.0+ bytes

In [99]:
all_str_single_upload.to_csv('all_str_single_upload.csv', index=False)
all_str_single_upload.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6486 entries, 0 to 6485
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      5705 non-null   object
 1   model_patient_id              5705 non-null   object
 2   model_model_id                5705 non-null   object
 3   mc_model_condition_id         5705 non-null   object
 4   mc_model_id                   5705 non-null   object
 5   str_patient_id                6486 non-null   object
 6   model_condition_id            5705 non-null   object
 7   id                            6486 non-null   object
 8   is_reference                  6486 non-null   bool
 9   d3s1358                       6415 non-null   object
 10  th01                          6434 non-null   object
 11  d21s11                        5200 non-null   object
 12  d18s51                        6268 non-null   object
 13  penta_e                       6100 non-null   object
 14  d5s818                        6369 non-null   object
 15  d13s317                       6366 non-null   object
 16  d7s820                        6416 non-null   object
 17  d16s539                       6436 non-null   object
 18  csf1po                        6446 non-null   object
 19  penta_d                       6187 non-null   object
 20  vwa                           4285 non-null   object
 21  d8s1179                       6341 non-null   object
 22  tpox                          5717 non-null   object
 23  fga                           6261 non-null   object
 24  pellet_creation_date          1426 non-null   object
 25  percentage_match_to_parental  1586 non-null   float64
 26  lab_corp_spec_nbr             2134 non-null   object
 27  lab_corp_case_nbr             4215 non-null   object
 28  comments                      1538 non-null   object
 29  amelogenin                    4275 non-null   object
 30  model_condition_id.1          5705 non-null   object
 31  mouse                         1363 non-null   object
 32  mycoplasma                    118 non-null    object
 33  patient_id                    6486 non-null   object
 34  source                        6486 non-null   object
 35  source_group                  6481 non-null   object
 36  pellet_submitted_date         601 non-null    object
 37  sample_reference              4257 non-null   object
 38  created_at                    6486 non-null   object
 39  updated_at                    6486 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 1.9+ MB

In [26]:
#checking for model condition ids that dont match
mask_model_condition = ( (all_str_single_upload['mc_model_condition_id'] != all_str_single_upload['model_condition_id']) &
      (all_str_single_upload['mc_model_condition_id'].notna() & all_str_single_upload['model_condition_id'].notna()))
model_condition_id_discrepancies = all_str_single_upload[mask_model_condition]
model_condition_id_discrepancies

Empty DataFrame
Columns: [model_id, model_patient_id, model_model_id, mc_model_condition_id, mc_model_id, str_patient_id, model_condition_id, id, is_reference, d3s1358, th01, d21s11, d18s51, penta_e, d5s818, d13s317, d7s820, d16s539, csf1po, penta_d, vwa, d8s1179, tpox, fga, pellet_creation_date, percentage_match_to_parental, lab_corp_spec_nbr, lab_corp_case_nbr, comments, amelogenin, model_condition_id.1, mouse, mycoplasma, patient_id, source, source_group, pellet_submitted_date, sample_reference, created_at, updated_at]
Index: []

In [27]:
#saving as csv file
model_condition_id_discrepancies = model_condition_id_discrepancies.reset_index(drop=True)
model_condition_id_discrepancies.to_csv('model_condition_id_discrepancies.csv',index=False)
model_condition_id_discrepancies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      0 non-null      object
 1   model_patient_id              0 non-null      object
 2   model_model_id                0 non-null      object
 3   mc_model_condition_id         0 non-null      object
 4   mc_model_id                   0 non-null      object
 5   str_patient_id                0 non-null      object
 6   model_condition_id            0 non-null      object
 7   id                            0 non-null      object
 8   is_reference                  0 non-null      bool
 9   d3s1358                       0 non-null      object
 10  th01                          0 non-null      object
 11  d21s11                        0 non-null      object
 12  d18s51                        0 non-null      object
 13  penta_e                       0 non-null      object
 14  d5s818                        0 non-null      object
 15  d13s317                       0 non-null      object
 16  d7s820                        0 non-null      object
 17  d16s539                       0 non-null      object
 18  csf1po                        0 non-null      object
 19  penta_d                       0 non-null      object
 20  vwa                           0 non-null      object
 21  d8s1179                       0 non-null      object
 22  tpox                          0 non-null      object
 23  fga                           0 non-null      object
 24  pellet_creation_date          0 non-null      object
 25  percentage_match_to_parental  0 non-null      float64
 26  lab_corp_spec_nbr             0 non-null      object
 27  lab_corp_case_nbr             0 non-null      object
 28  comments                      0 non-null      object
 29  amelogenin                    0 non-null      object
 30  model_condition_id.1          0 non-null      object
 31  mouse                         0 non-null      object
 32  mycoplasma                    0 non-null      object
 33  patient_id                    0 non-null      object
 34  source                        0 non-null      object
 35  source_group                  0 non-null      object
 36  pellet_submitted_date         0 non-null      object
 37  sample_reference              0 non-null      object
 38  created_at                    0 non-null      object
 39  updated_at                    0 non-null      object
dtypes: bool(1), float64(1), object(38)
memory usage: 132.0+ bytes

In [28]:
#missing model conditions
missing_model_cond_id = all_str_single_upload[all_str_single_upload['mc_model_condition_id'].isna()]
missing_model_cond_id = missing_model_cond_id.reset_index(drop=True)
missing_model_cond_id.to_csv('missing_model_cond_id.csv')
missing_model_cond_id.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781 entries, 0 to 780
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      0 non-null      object
 1   model_patient_id              0 non-null      object
 2   model_model_id                0 non-null      object
 3   mc_model_condition_id         0 non-null      object
 4   mc_model_id                   0 non-null      object
 5   str_patient_id                781 non-null    object
 6   model_condition_id            0 non-null      object
 7   id                            781 non-null    object
 8   is_reference                  781 non-null    bool
 9   d3s1358                       766 non-null    object
 10  th01                          781 non-null    object
 11  d21s11                        777 non-null    object
 12  d18s51                        761 non-null    object
 13  penta_e                       759 non-null    object
 14  d5s818                        781 non-null    object
 15  d13s317                       780 non-null    object
 16  d7s820                        779 non-null    object
 17  d16s539                       778 non-null    object
 18  csf1po                        776 non-null    object
 19  penta_d                       761 non-null    object
 20  vwa                           779 non-null    object
 21  d8s1179                       765 non-null    object
 22  tpox                          775 non-null    object
 23  fga                           763 non-null    object
 24  pellet_creation_date          10 non-null     object
 25  percentage_match_to_parental  75 non-null     float64
 26  lab_corp_spec_nbr             755 non-null    object
 27  lab_corp_case_nbr             755 non-null    object
 28  comments                      725 non-null    object
 29  amelogenin                    777 non-null    object
 30  model_condition_id.1          0 non-null      object
 31  mouse                         333 non-null    object
 32  mycoplasma                    0 non-null      object
 33  patient_id                    781 non-null    object
 34  source                        781 non-null    object
 35  source_group                  780 non-null    object
 36  pellet_submitted_date         41 non-null     object
 37  sample_reference              769 non-null    object
 38  created_at                    781 non-null    object
 39  updated_at                    781 non-null    object
dtypes: bool(1), float64(1), object(38)
memory usage: 238.9+ KB

In [29]:
#STRs with percentage match <0.75
df_under75 = all_str_single_upload[all_str_single_upload['percentage_match_to_parental'] < 0.75]
df_under75.info()

<class 'pandas.core.frame.DataFrame'>
Index: 245 entries, 574 to 6420
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      231 non-null    object
 1   model_patient_id              231 non-null    object
 2   model_model_id                231 non-null    object
 3   mc_model_condition_id         231 non-null    object
 4   mc_model_id                   231 non-null    object
 5   str_patient_id                245 non-null    object
 6   model_condition_id            231 non-null    object
 7   id                            245 non-null    object
 8   is_reference                  245 non-null    bool
 9   d3s1358                       228 non-null    object
 10  th01                          236 non-null    object
 11  d21s11                        146 non-null    object
 12  d18s51                        206 non-null    object
 13  penta_e                       221 non-null    object
 14  d5s818                        230 non-null    object
 15  d13s317                       227 non-null    object
 16  d7s820                        232 non-null    object
 17  d16s539                       239 non-null    object
 18  csf1po                        237 non-null    object
 19  penta_d                       215 non-null    object
 20  vwa                           79 non-null     object
 21  d8s1179                       219 non-null    object
 22  tpox                          169 non-null    object
 23  fga                           215 non-null    object
 24  pellet_creation_date          34 non-null     object
 25  percentage_match_to_parental  245 non-null    float64
 26  lab_corp_spec_nbr             66 non-null     object
 27  lab_corp_case_nbr             71 non-null     object
 28  comments                      9 non-null      object
 29  amelogenin                    78 non-null     object
 30  model_condition_id.1          231 non-null    object
 31  mouse                         35 non-null     object
 32  mycoplasma                    1 non-null      object
 33  patient_id                    245 non-null    object
 34  source                        245 non-null    object
 35  source_group                  245 non-null    object
 36  pellet_submitted_date         59 non-null     object
 37  sample_reference              79 non-null     object
 38  created_at                    245 non-null    object
 39  updated_at                    245 non-null    object
dtypes: bool(1), float64(1), object(38)
memory usage: 76.8+ KB

In [30]:
df_under75

,model_id,model_patient_id,model_model_id,mc_model_condition_id,mc_model_id,str_patient_id,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id.1,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
574,ACH-000024,PT-codP7n,ACH-000024,MC-000024-kxGf,ACH-000024,PT-codP7n,MC-000024-kxGf,STR-KfHBSk,False,"15, 18","6, 7","30, 33.2, 34.2","13, 14","12, 21","1, 12","1, 10","1, 11","9, 13","12, 13","1, 8","14, 17","10, 13","1, 7","20, 21",2023-03-31,0.6792,NaN,CX4016035,NaN,X,MC-000024-kxGf,NaN,NaN,PT-codP7n,Internal,GPP,NaN,OPM2-311cas9(6/8/2018),2024-08-13,2024-08-13 14:32:29.535919+00:00
673,ACH-000243,PT-dLpuzD,ACH-000243,MC-000243-pHKG,ACH-000243,PT-dLpuzD,MC-000243-pHKG,STR-cUClKj,False,"1, 15","1, 8","29, 31.2, 32.2","1, 15","1, 6","12, 13","1, 7","10, 13","8, 11","1, 12","9, 13","16, 18","10, 11","1, 9","1, 19",2023-03-27,0.5200,NaN,CX4016034,NaN,X,MC-000243-pHKG,NaN,NaN,PT-dLpuzD,Internal,GPP,NaN,DANG-Cas9VY,2024-08-13,2024-08-13 14:32:29.586872+00:00
888,ACH-000502,PT-HGOuqa,ACH-000502,MC-000502-yIwz,ACH-000502,PT-HGOuqa,MC-000502-yIwz,STR-LoZQa3,False,"15, 16, 17","6, 7","28, 30, 30.2","16, 17, 18","7, 15, 19","8, 9, 11, 13","8, 12, 14","8, 11, 12","9, 11, 13","11, 12, 13","9, 10","17, 19","11, 12, 13, 16","11, 12","20, 23",NaN,0.6441,NaN,CX4010579,NaN,X,MC-000502-yIwz,Not Detected,NaN,PT-HGOuqa,Internal,GPP,NaN,TCCPAN2-encas12a,2024-08-13,2024-08-13 14:32:29.756766+00:00
889,ACH-000502,PT-HGOuqa,ACH-000502,MC-000502-yIwz,ACH-000502,PT-HGOuqa,MC-000502-yIwz,STR-kMG3Ry,False,"15, 17","7, 9.3","28, 30.2","17, 18","7, 15","8, 9","12, 14","11, 12","9, 13, 14","11, 12, 13","9, 10","17, 19","11, 12","11, 12",23,NaN,0.2500,NaN,CX4010882,NaN,X,MC-000502-yIwz,Not Detected,NaN,PT-HGOuqa,Internal,GPP,NaN,TCCPAN2-enCas12a-SetD-p4,2024-08-13,2024-08-13 14:32:29.756766+00:00
891,ACH-000502,PT-HGOuqa,ACH-000502,MC-000502-yIwz,ACH-000502,PT-HGOuqa,MC-000502-yIwz,STR-PeaGRb,False,"15, 17","7, 9.3","28, 30.2","17, 18","7, 15","8, 9","12, 14","11, 12","9, 13, 14","11, 12, 13","9, 10","17, 19","11, 12","11, 12",23,NaN,0.2500,NaN,CX4010790,NaN,X,MC-000502-yIwz,Not Detected,NaN,PT-HGOuqa,Internal,GPP,NaN,TCCPAN2-enCas12a-SetDp4,2024-08-13,2024-08-13 14:32:29.756766+00:00
2096,ACH-002459,PT-czDcsE,ACH-002459,MC-002459-cRI0,ACH-002459,PT-czDcsE,MC-002459-cRI0,STR-ywDfHZ,False,"14, 15","6, 9",NaN,15,12.1,"11, 14","11, 12",11,"12, 13",12,"8, 10",NaN,"13, 15",NaN,"23, 26",NaN,0.7442,NaN,NaN,NaN,NaN,MC-002459-cRI0,NaN,NaN,PT-czDcsE,Internal,WGS Inferred,NaN,NaN,2024-06-03,2024-06-03 16:39:03.919363+00:00
2111,ACH-001973,PT-oJTeSY,ACH-001973,MC-001973-ILv6,ACH-001973,PT-oJTeSY,MC-001973-ILv6,STR-FrA73B,False,14,NaN,32.3,"13, 17","10.1, 15.1","11, 12","11, 13",12,11,"11, 12","9, 11",NaN,"11, 13",NaN,"21, 23",NaN,0.7317,NaN,NaN,NaN,NaN,MC-001973-ILv6,NaN,NaN,PT-oJTeSY,Internal,WGS Inferred,NaN,NaN,2024-06-13,2024-06-13 16:41:08.205941+00:00
2124,ACH-001401,PT-7a0mgm,ACH-001401,MC-001401-l6Fd,ACH-001401,PT-7a0mgm,MC-001401-l6Fd,STR-o1zkEG,False,16,"7, 8",NaN,17,"7.1, 15.1",12,9,"8, 10",12,"11, 12","9, 12",NaN,10,NaN,20,NaN,0.7222,NaN,NaN,NaN,NaN,MC-001401-l6Fd,NaN,NaN,PT-7a0mgm,Internal,WGS Inferred,NaN,NaN,2024-04-10,2024-04-10 18:01:15.680098+00:00
2142,ACH-000093,PT-X8PfQy,ACH-000093,MC-000093-IB96,ACH-000093,PT-X8PfQy,MC-000093-IB96,STR-Lw91ng,False,"14, 16","6, 9.3",NaN,14,NaN,"12, 13","10, 12","9, 12","9, 11","12, 13","6, 8",NaN,"11, 13",NaN,"19, 23",NaN,0.1778,NaN,NaN,NaN,NaN,MC-000093-IB96,NaN,NaN,PT-X8PfQy,Internal,WGS Inferred,NaN,NaN,2024-06-03,2024-06-03 16:42:46.516476+00:00
2209,ACH-000201,PT-EY60tR,ACH-000201,MC-000201-rUIL,ACH-000201,PT-EY60tR,MC-000201-rUIL,STR-0gVv3Y,False,"17, 14","9.3, 8",31.3,NaN,"7.1, 10.1",12,"11, 12","10, 8","11, 12","10, 13","8, 12",NaN,"13, 15","9, 8",NaN,NaN,0.3913,NaN,NaN,NaN,NaN,MC-000201-rUIL,NaN,NaN,PT-EY60tR,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2236,ACH-002818,PT-1hPtyP,ACH-002818,MC-002818-6Tdd,ACH-002818,PT-1hPtyP,MC-002818-6Tdd,STR-uYdIZc,False,"15, 17","6, 9","30.3, 31.3",19,"10.1, 11.1",12,8,11,"11, 12",10,"7, 11",NaN,10,NaN,"20, 24",NaN,0.5926,NaN,NaN,NaN,NaN,MC-002818-6Tdd,NaN,NaN,PT-1hPtyP,Internal,WGS Inferred,NaN,NaN,2024-05-01,2024-05-01 16:38:42.011738+00:00
2239,ACH-002452,PT-pfztyJ,ACH-002452,MC-002452-vQCK,ACH-002452,PT-pfztyJ,MC-002452-vQCK,STR-Cu2Mgp,False,"15, 17","6, 9.3",31.3,"13, 15","12.1, 13.1",9,9,"10, 9","11, 12","10, 11","11, 12",NaN,"10, 14","10, 8","20, 26",NaN,0.6197,NaN,NaN,NaN,NaN,MC-002452-vQCK,NaN,NaN,PT-pfztyJ,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2297,ACH-002073,PT-kyVW2F,ACH-002073,MC-002073-dsik,ACH-002073,PT-kyVW2F,MC-002073-dsik,STR-okkgRJ,False,16,9,NaN,"23, 14",12.1,9,9,NaN,NaN,NaN,NaN,NaN,13,"9, 8","19, 21",NaN,0.7333,NaN,NaN,NaN,NaN,MC-002073-dsik,NaN,NaN,PT-kyVW2F,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2309,ACH-002412,PT-KHnzPB,ACH-002412,MC-002412-DqdM,ACH-002412,PT-KHnzPB,MC-002412-DqdM,STR-GZEpB1,False,"15, 16, 17, 19","6, 8, 9.3","30, 31, 32.2, 33.2","12, 16","5, 7, 12, 17","11, 12","9, 11, 13","9, 10, 11, 12","12, 13","9, 11","9, 12","16, 17","11, 13","8, 11","19, 20, 21",NaN,0.7385,35O91280,CX4016383,NaN,X,MC-002412-DqdM,Not Detected,NaN,PT-KHnzPB,Internal,Mnemosyne,2023-05-23,ACH-002412 Post-Cas12 (2412 C12 matrigel FP) (...,2024-04-09,2024-04-09 16:00:46.668811+00:00
2323,ACH-001786,PT-LbUj3S,ACH-001786,MC-001786-LoTy,ACH-001786,PT-LbUj3S,MC-001786-LoTy,STR-0jrV5l,False,"15, 16","7, 9",31.3,"12, 17","9.1, 16.1",12,"9, 11","11, 12","8, 14","11, 12","7, 11",NaN,10,NaN,"20, 22",NaN,0.6957,NaN,NaN,NaN,NaN,MC-001786-LoTy,NaN,NaN,PT-LbUj3S,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:38:50.644530+00:00
2342,ACH-001428,PT-XQvpFQ,ACH-001428,MC-001428-h8A5,ACH-001428,PT-XQvpFQ,MC-001428-h8A5,STR-CjLjoz,False,15,9,31.3,12,7.1,9,11,"11, 8",12,12,10,NaN,"13, 14",12,24,NaN,0.1538,NaN,NaN,NaN,NaN,MC-001428-h8A5,NaN,NaN,PT-XQvpFQ,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2385,ACH-000530,PT-Dxq8HG,ACH-000530,MC-000530-vUsT,ACH-000530,PT-Dxq8HG,MC-000530-vUsT,STR-7pLBbc,False,"17, 14","9.3, 8",31.3,18,7.1,12,NaN,"10, 11",12,11,12,NaN,13,"11, 8",NaN,NaN,0.7222,NaN,NaN,NaN,NaN,MC-000530-vUsT,NaN,NaN,PT-Dxq8HG,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2471,ACH-000093,PT-X8PfQy,ACH-000093,MC-000093-IB96,ACH-000093,PT-X8PfQy,MC-000093-IB96,STR-0z9fBq,False,"16, 14","6, 9.3",NaN,14,5.1,"13, 12","10, 12","9, 12","11, 9","12, 13","6, 8",NaN,"11, 13","9, 8","19, 23",NaN,0.2083,NaN,NaN,NaN,NaN,MC-000093-IB96,NaN,NaN,PT-X8PfQy,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2473,ACH-003189,PT-eY3uqu,ACH-003189,MC-003189-aahm,ACH-003189,PT-eY3uqu,MC-003189-aahm,STR-8mQP36,False,"15, 18","8, 9.3",NaN,"15, 19","7.1, 12.1","11, 12",12,"8, 10",11,"11, 12","8, 10",NaN,13,NaN,22,NaN,0.7442,NaN,NaN,NaN,NaN,MC-003189-aahm,NaN,NaN,PT-eY3uqu,Internal,WGS Inferred,NaN,NaN,2024-04-23,2024-04-23 18:22:27.511682+00:00
2477,ACH-003081,PT-KuyVds,ACH-003081,MC-003081-94lw,ACH-003081,PT-KuyVds,MC-003081-94lw,STR-N9NfWx,False,16,9.3,NaN,23,"8.1, 10.1","10, 13",12,"10, 8",11,"10, 11",7,NaN,14,9,"24, 21",NaN,0.6897,NaN,NaN,NaN,NaN,MC-003081-94lw,NaN,NaN,PT-KuyVds,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2489,ACH-000851,PT-klVvXs,ACH-000851,MC-000851-DKZr,ACH-000851,PT-klVvXs,MC-000851-DKZr,STR-ewqd2d,False,15,9,NaN,16,"11.1, 12.1","11, 13",NaN,"9, 11",12,11,"9, 12",NaN,"12, 13",NaN,22,NaN,0.0870,NaN,NaN,NaN,NaN,MC-000851-DKZr,NaN,NaN,PT-klVvXs,Internal,WGS Inferred,NaN,NaN,2024-04-10,2024-04-10 18:00:12.659835+00:00
2494,ACH-001664,PT-k5HJNy,ACH-001664,MC-001664-yvtF,ACH-001664,PT-k5HJNy,MC-001664-yvtF,STR-0ZlNDG,False,15,7,NaN,"14, 16",14.1,"10, 14",10,"9, 10","11, 13","10, 12",8,NaN,"11, 13",NaN,"17, 27",NaN,0.7391,NaN,NaN,NaN,NaN,MC-001664-yvtF,NaN,NaN,PT-k5HJNy,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:43:49.590741+00:00
2498,ACH-003034,PT-ozVjLA,ACH-003034,MC-003034-E98A,ACH-003034,PT-ozVjLA,MC-003034-E98A,STR-BCrwHR,False,15,"9, 9.3",31.3,18,11.1,NaN,11,NaN,11,"10, 12",NaN,NaN,"13, 14","11, 8",NaN,NaN,0.6857,NaN,NaN,NaN,NaN,MC-003034-E98A,NaN,NaN,PT-ozVjLA,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2513,ACH-001652,PT-IwYShD,ACH-001652,MC-001652-lAQg,ACH-001652,PT-IwYShD,MC-001652-lAQg,STR-UUu375,False,16,8,NaN,"13, 15",5.1,"12, 13",11,"8, 12",9,"10, 11",8,NaN,"13, 15",NaN,22,NaN,0.1875,NaN,NaN,NaN,NaN,MC-001652-lAQg,NaN,NaN,PT-IwYShD,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:47:59.920620+00:00
2528,ACH-003031,PT-WeKvQW,ACH-003031,MC-003031-Cfv7,ACH-003031,PT-WeKvQW,MC-003031-Cfv7,STR-S7SxmO,False,NaN,"6, 8",NaN,"19, 13",12.1,"11, 12","11, 13","11, 12","11, 8","10, 12",11,NaN,"10, 14","10, 8","19, 24",NaN,0.7143,NaN,NaN,NaN,NaN,MC-003031-Cfv7,NaN,NaN,PT-WeKvQW,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2546,ACH-003017,PT-cqv92I,ACH-003017,MC-003017-iLhU,ACH-003017,PT-cqv92I,MC-003017-iLhU,STR-t1YuSS,False,"15, 16","9.3, 8","31.3, 30.3","15, 17","11.1, 7.1",11,NaN,"10, 8",11,"11, 12","10, 8",NaN,13,"9, 8",23,NaN,0.6667,NaN,NaN,NaN,NaN,MC-003017-iLhU,NaN,NaN,PT-cqv92I,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-08-16 18:32:08.391635+00:00
2550,ACH-000644,PT-w6ABKA,ACH-000644,MC-000644-wPiH,ACH-000644,PT-w6ABKA,MC-000644-wPiH,STR-OZee5G,False,NaN,10,31.3,15,7.1,11,"11, 12","10, 8",13,11,"8, 12",NaN,"13, 14","11, 8",NaN,NaN,0.7027,NaN,NaN,NaN,NaN,MC-000644-wPiH,NaN,NaN,PT-w6ABKA,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2588,ACH-002734,PT-VvDCYY,ACH-002734,MC-002734-kaoo,ACH-002734,PT-VvDCYY,MC-002734-kaoo,STR-gaT2ZL,False,14,7,"29, 32.2",18,"7, 12",13,"11, 13",8,11,11,"11, 12","14, 17","11, 12","10, 11","21, 23",2021-03-09,0.2273,13I90930,CX4010782,NaN,"X, Y",MC-002734-kaoo,NaN,NaN,PT-VvDCYY,Internal,Minerva,2021-03-19,ACH-002734-PreS (p4),2024-04-09,2024-04-09 16:00:46.668811+00:00
2663,ACH-000296,PT-GezIUF,ACH-000296,MC-000296-bgzW,ACH-000296,PT-GezIUF,MC-000296-bgzW,STR-V8LoLY,False,"16, 17","7, 9.3",31.3,NaN,"5.1, 9.1",11,12,"10, 13",11,12,"8, 11",NaN,NaN,NaN,23.2,NaN,0.6471,NaN,NaN,NaN,NaN,MC-000296-bgzW,NaN,NaN,PT-GezIUF,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:39:37.404907+00:00
2678,ACH-001429,PT-KI2QoM,ACH-001429,MC-001429-IfGg,ACH-001429,PT-KI2QoM,MC-001429-IfGg,STR-TjYlHL,False,NaN,"6, 9",NaN,"12, 16",5.1,"11, 13","13, 12","11, 13","11, 8","11, 12","8, 12",NaN,"13, 16","11, 8",22,NaN,0.5455,NaN,NaN,NaN,NaN,MC-001429-IfGg,NaN,NaN,PT-KI2QoM,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2685,ACH-003093,PT-mG2brs,ACH-003093,MC-003093-jlhL,ACH-003093,PT-mG2brs,MC-003093-jlhL,STR-la1BYq,False,"15, 18","8, 7",31.3,"12, 19","12.1, 11.1","10, 12",11,"8, 9",13,"10, 11","11, 13",NaN,"15, 11","8, 11","21, 19",NaN,0.5556,NaN,NaN,NaN,NaN,MC-003093-jlhL,NaN,NaN,PT-mG2brs,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-29 16:15:10.179659+00:00
2692,ACH-001842,PT-QTHAca,ACH-001842,MC-001842-XQ3q,ACH-001842,PT-QTHAca,MC-001842-XQ3q,STR-7ti2CO,False,14,"8, 9",NaN,NaN,14.1,"12, 14","8, 11",NaN,12,12,"9, 12",NaN,13,NaN,"22, 25",NaN,0.6857,NaN,NaN,NaN,NaN,MC-001842-XQ3q,NaN,NaN,PT-QTHAca,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:39:40.908582+00:00
2704,ACH-001513,PT-KwMOW6,ACH-001513,MC-001513-eaBx,ACH-001513,PT-KwMOW6,MC-001513-eaBx,STR-QZkWiq,False,17,7,NaN,15,18.1,11,NaN,"10, 11",11,12,9,NaN,"11, 14",NaN,23,NaN,0.7333,NaN,NaN,NaN,NaN,MC-001513-eaBx,NaN,NaN,PT-KwMOW6,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:48:07.802372+00:00
2707,ACH-002381,PT-vOaofa,ACH-002381,MC-002381-Pg23,ACH-002381,PT-vOaofa,MC-002381-Pg23,STR-g4iLod,False,"16, 18","8, 9",31.3,15,"12.1, 15.1","12, 13",12,"10, 12","12, 11","10, 11","9, 7",NaN,13,"11, 9","20, 21",NaN,0.7143,NaN,NaN,NaN,NaN,MC-002381-Pg23,NaN,NaN,PT-vOaofa,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2711,ACH-002972,PT-dkXZB1,ACH-002972,MC-002972-J9L5,ACH-002972,PT-dkXZB1,MC-002972-J9L5,STR-kljJ6z,False,"15, 18","9.3, 7",NaN,"10, 16",5.1,"10, 11","8, 11","8, 12","11, 9","12, 11","10, 11",NaN,"15, 11","11, 9","24, 26",NaN,0.1364,NaN,NaN,NaN,NaN,MC-002972-J9L5,NaN,NaN,PT-dkXZB1,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2721,ACH-001799,PT-VjYY7b,ACH-001799,MC-001799-AkA5,ACH-001799,PT-VjYY7b,MC-001799-AkA5,STR-6C1UVF,False,17,NaN,"30.3, 31.3","11, 14","11.1, 12.1",12,13,"11, 12","12, 14","11, 12","8, 12",NaN,"11, 13",NaN,23,NaN,0.7179,NaN,NaN,NaN,NaN,MC-001799-AkA5,NaN,NaN,PT-VjYY7b,Internal,WGS Inferred,NaN,NaN,2024-07-01,2024-07-01 14:59:31.972828+00:00
2734,ACH-001655,PT-yc0xLp,ACH-001655,MC-001655-jaAf,ACH-001655,PT-yc0xLp,MC-001655-jaAf,STR-S99t8X,False,15,9,31.3,18,12.1,12,8,11,11,12,9,NaN,13,NaN,22,NaN,0.2667,NaN,NaN,NaN,NaN,MC-001655-jaAf,NaN,NaN,PT-yc0xLp,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:48:18.405296+00:00
2735,ACH-001429,PT-KI2QoM,ACH-001429,MC-001429-IfGg,ACH-001429,PT-KI2QoM,MC-001429-IfGg,STR-SwD0Dn,False,18,"6, 9","29, 30","12, 16","5, 20","11, 13","12, 13","11, 13","8, 11","11, 12","9, 15","14, 17","13, 16","8, 11",22,NaN,0.4865,32G90690,CX4015699,NaN,"X, Y",MC-001429-IfGg,NaN,NaN,PT-KI2QoM,Internal,GPP,2023-01-30,CCLFPEDS0009T-enCas12a (44a),2024-04-09,2024-04-09 16:00:46.668811+00:00
2737,ACH-002027,PT-vIwQtl,ACH-002027,MC-002027-w4Gn,ACH-002027,PT-vIwQtl,MC-002027-w4Gn,STR-vGTWgn,False,"17, 16","6, 9",31.3,"18, 24","15.1, 13.1","12, 15","13, 15","10, 12","9, 14",14,10,NaN,"12, 15","9, 8","21, 17",NaN,0.6774,NaN,NaN,NaN,NaN,MC-002027-w4Gn,NaN,NaN,PT-vIwQtl,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2743,ACH-002373,PT-yKJqsn,ACH-002373,MC-002373-2pl5,ACH-002373,PT-yKJqsn,MC-002373-2pl5,STR-a6b7PV,False,"15, 17",6,"32.3, 31.3","17, 19",12.1,"12, 11",11,"8, 11","10, 11",13,"10, 9",NaN,"12, 11",8,"21, 23",NaN,0.6857,NaN,NaN,NaN,NaN,MC-002373-2pl5,NaN,NaN,PT-yKJqsn,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2760,ACH-001428,PT-XQvpFQ,ACH-001428,MC-001428-h8A5,ACH-001428,PT-XQvpFQ,MC-001428-h8A5,STR-umPl4h,False,15,9,29,12,"7, 18",9,11,"8, 11",12,12,11,16,"13, 14",12,24,NaN,0.5000,33F91050,CX4015873,NaN,"X, Y",MC-001428-h8A5,Not Detected,NaN,PT-XQvpFQ,Internal,GPP,NaN,CCLFPEDS0010T (45a),2024-04-09,2024-04-09 16:00:46.668811+00:00
2772,ACH-001428,PT-XQvpFQ,ACH-001428,MC-001428-h8A5,ACH-001428,PT-XQvpFQ,MC-001428-h8A5,STR-joqOxT,False,15,9,29,12,"7, 18",9,11,"8, 11",12,12,11,16,"13, 14",12,24,NaN,0.5000,39E91220,CX4017464,NaN,"X, Y",MC-001428-h8A5,NaN,NaN,PT-XQvpFQ,Internal,GPP,NaN,CCLFPEDS0010T-HumagneCD-RepA-P6(D22) (54c),2024-04-09,2024-04-09 16:00:46.668811+00:00
2808,ACH-003046,PT-TZOWm8,ACH-003046,MC-003046-ean0,ACH-003046,PT-TZOWm8,MC-003046-ean0,STR-0tABRc,False,15,9,NaN,NaN,11.1,10,8,"8, 12",11,"11, 13","11, 8",NaN,"11, 14",11,24,NaN,0.1667,NaN,NaN,NaN,NaN,MC-003046-ean0,NaN,NaN,PT-TZOWm8,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2821,ACH-000884,PT-3NwoWt,ACH-000884,MC-000884-qtr4,ACH-000884,PT-3NwoWt,MC-000884-qtr4,STR-aq4LQI,False,14,"6, 7",31.3,NaN,"10.1, 12.1",12,12,NaN,13,11,"8, 10",NaN,13,NaN,21,NaN,0.5806,NaN,NaN,NaN,NaN,MC-000884-qtr4,NaN,NaN,PT-3NwoWt,Internal,WGS Inferred,NaN,NaN,2024-05-23,2024-05-23 16:39:16.388814+00:00
2823,ACH-002816,PT-vNiiSm,ACH-002816,MC-002816-BGmF,ACH-002816,PT-vNiiSm,MC-002816-BGmF,STR-d8Jkn1,False,NaN,"6, 9.3","29, 30.2",NaN,NaN,"10, 12",12,"9, 11","11, 14","10, 12",NaN,"16, 17",NaN,8,NaN,NaN,0.7179,NaN,NaN,NaN,X,MC-002816-BGmF,NaN,NaN,PT-vNiiSm,External,Mnemosyne,2022-04-29,BT179,2024-04-09,2024-04-09 16:00:46.668811+00:00
2857,ACH-000093,PT-X8PfQy,ACH-000093,MC-000093-IB96,ACH-000093,PT-X8PfQy,MC-000093-IB96,STR-otDIDD,False,"14, 16","6, 9.3","28, 33.2",14,"5, 18","12, 13","10, 12","9, 12","9, 11","12, 13","7, 9","15, 20","11, 13","8, 9","19, 23",NaN,0.3019,8CL91130,CX4006211,matches reference; Authenticated,X,MC-000093-IB96,Not Detected,NaN,PT-X8PfQy,Internal,DMX,NaN,Panc 05.04,2024-04-09,2024-04-09 16:00:46.668811+00:00
2858,ACH-001820,PT-UXPdpL,ACH-001820,MC-001820-U3Q6,ACH-001820,PT-UXPdpL,MC-001820-U3Q6,STR-r9thT9,False,"16, 17","7, 9",NaN,"15, 19",7.1,12,"12, 13",NaN,13,"10, 12","4, 9",NaN,"12, 14",NaN,22,NaN,0.6818,NaN,NaN,NaN,NaN,MC-001820-U3Q6,NaN,NaN,PT-UXPdpL,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:39:42.430433+00:00
2872,ACH-001370,PT-rC8bwa,ACH-001370,MC-001370-W35c,ACH-001370,PT-rC8bwa,MC-001370-W35c,STR-QU6Of1,False,14,6,31.3,15,"7.1, 11.1","10, 12",11,12,11,12,9,NaN,"13, 15",NaN,"20, 24",NaN,0.7429,NaN,NaN,NaN,NaN,MC-001370-W35c,NaN,NaN,PT-rC8bwa,Internal,WGS Inferred,NaN,NaN,2024-07-03,2024-07-03 16:42:41.913634+00:00
2909,ACH-001530,PT-hB4ARO,ACH-001530,MC-001530-i3NR,ACH-001530,PT-hB4ARO,MC-001530-i3NR,STR-F6KwJU,False,15,"9.3, 9",32.3,NaN,"12.1, 8.1","10, 11","11, 9","10, 12",13,"12, 11","8, 11",NaN,NaN,NaN,"24, 23",NaN,0.6667,NaN,NaN,NaN,NaN,MC-001530-i3NR,NaN,NaN,PT-hB4ARO,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
2911,ACH-000584,PT-g4qhEH,ACH-000584,MC-000584-AUVi,ACH-000584,PT-g4qhEH,MC-000584-AUVi,STR-sU7e8u,False,18,7,NaN,"14, 15",18.1,11,11,10,"9, 10",10,"9, 11",NaN,11,NaN,20,NaN,0.7273,NaN,NaN,NaN,NaN,MC-000584-AUVi,NaN,NaN,PT-g4qhEH,Internal,WGS Inferred,NaN,NaN,2024-05-23,2024-05-23 16:39:49.027156+00:00
2922,ACH-002821,PT-mDKTMq,ACH-002821,MC-002821-GeZX,ACH-002821,PT-mDKTMq,MC-002821-GeZX,STR-fv2RyC,False,NaN,"6, 9.3","29, 30",NaN,NaN,"11, 12","11, 12","9, 10","12, 14",11,NaN,"16, 18",NaN,8,NaN,NaN,0.7179,NaN,NaN,NaN,"X, Y",MC-002821-GeZX,NaN,NaN,PT-mDKTMq,External,Mnemosyne,2022-04-29,BT286,2024-04-09,2024-04-09 16:00:46.668811+00:00
2927,ACH-003093,PT-mG2brs,ACH-003093,MC-003093-jlhL,ACH-003093,PT-mG2brs,MC-003093-jlhL,STR-3wbI7z,False,"15, 18","7, 8",31.3,"12, 19","11.1, 12.1","10, 12",11,"8, 9",13,"10, 11","11, 13",NaN,"11, 15","8, 11","19, 21",NaN,0.5556,NaN,NaN,NaN,NaN,MC-003093-jlhL,NaN,NaN,PT-mG2brs,Internal,WGS Inferred,NaN,NaN,2024-04-10,2024-04-29 16:15:21.754473+00:00
2948,ACH-003332,PT-S0UaGz,ACH-003332,MC-003332-PH24,ACH-003332,PT-S0UaGz,MC-003332-PH24,STR-Il4s9J,False,15,"6, 7",NaN,NaN,"11.1, 12.1",11,"9, 12","8, 11","12, 13",12,"10, 13",NaN,"13, 14",NaN,24,NaN,0.7368,NaN,NaN,NaN,NaN,MC-003332-PH24,NaN,NaN,PT-S0UaGz,Internal,WGS Inferred,NaN,NaN,2024-05-23,2024-05-23 16:39:52.493350+00:00
2983,ACH-002381,PT-vOaofa,ACH-002381,MC-002381-Pg23,ACH-002381,PT-vOaofa,MC-002381-Pg23,STR-42UgAA,False,"16, 18","8, 9",31.3,15,"12.1, 15.1","12, 13",12,"10, 12","11, 12","10, 11","7, 9",NaN,13,"9, 11","20, 21",NaN,0.7143,NaN,NaN,NaN,NaN,MC-002381-Pg23,NaN,NaN,PT-vOaofa,Internal,WGS Inferred,NaN,NaN,2024-04-10,2024-04-10 18:01:32.194836+00:00
2992,ACH-003033,PT-ozVjLA,ACH-003033,MC-003033-vJLR,ACH-003033,PT-ozVjLA,MC-003033-vJLR,STR-DKWpYO,False,15,9.3,NaN,18,"11.1, 19.1","11, 13","12, 11","11, 7",11,"12, 11","14, 9",NaN,"13, 14",NaN,"22, 20",NaN,0.6667,NaN,NaN,NaN,NaN,MC-003033-vJLR,NaN,NaN,PT-ozVjLA,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
3052,ACH-000851,PT-klVvXs,ACH-000851,MC-000851-DKZr,ACH-000851,PT-klVvXs,MC-000851-DKZr,STR-KQkaFR,False,15,9,NaN,16,"12.1, 11.1","11, 13",NaN,"11, 9",12,11,"12, 9",NaN,"12, 13",NaN,22,NaN,0.0870,NaN,NaN,NaN,NaN,MC-000851-DKZr,NaN,NaN,PT-klVvXs,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
3071,ACH-003117,PT-xvWgsD,ACH-003117,MC-003117-Z47z,ACH-003117,PT-xvWgsD,MC-003117-Z47z,STR-wkdjSL,False,"17, 14","6, 9.3",NaN,"12, 13","13.1, 15.1","11, 13","12, 9",11,"10, 13","11, 13","8, 9",NaN,15,"8, 11","25, 22.2",NaN,0.3902,NaN,NaN,NaN,NaN,MC-003117-Z47z,NaN,NaN,PT-xvWgsD,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00

In [31]:
#STRs with percentage match >=0.75
df_above75 = all_str_single_upload[all_str_single_upload['percentage_match_to_parental'] >= 0.75]
df_above75.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1341 entries, 467 to 6483
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      1280 non-null   object
 1   model_patient_id              1280 non-null   object
 2   model_model_id                1280 non-null   object
 3   mc_model_condition_id         1280 non-null   object
 4   mc_model_id                   1280 non-null   object
 5   str_patient_id                1341 non-null   object
 6   model_condition_id            1280 non-null   object
 7   id                            1341 non-null   object
 8   is_reference                  1341 non-null   bool
 9   d3s1358                       1334 non-null   object
 10  th01                          1329 non-null   object
 11  d21s11                        817 non-null    object
 12  d18s51                        1286 non-null   object
 13  penta_e                       1179 non-null   object
 14  d5s818                        1331 non-null   object
 15  d13s317                       1315 non-null   object
 16  d7s820                        1330 non-null   object
 17  d16s539                       1330 non-null   object
 18  csf1po                        1332 non-null   object
 19  penta_d                       1237 non-null   object
 20  vwa                           474 non-null    object
 21  d8s1179                       1299 non-null   object
 22  tpox                          1106 non-null   object
 23  fga                           1313 non-null   object
 24  pellet_creation_date          211 non-null    object
 25  percentage_match_to_parental  1341 non-null   float64
 26  lab_corp_spec_nbr             396 non-null    object
 27  lab_corp_case_nbr             457 non-null    object
 28  comments                      84 non-null     object
 29  amelogenin                    474 non-null    object
 30  model_condition_id.1          1280 non-null   object
 31  mouse                         206 non-null    object
 32  mycoplasma                    10 non-null     object
 33  patient_id                    1341 non-null   object
 34  source                        1341 non-null   object
 35  source_group                  1341 non-null   object
 36  pellet_submitted_date         306 non-null    object
 37  sample_reference              471 non-null    object
 38  created_at                    1341 non-null   object
 39  updated_at                    1341 non-null   object
dtypes: bool(1), float64(1), object(38)
memory usage: 420.4+ KB

In [32]:
df_above75

,model_id,model_patient_id,model_model_id,mc_model_condition_id,mc_model_id,str_patient_id,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,penta_e,d5s818,d13s317,d7s820,d16s539,csf1po,penta_d,vwa,d8s1179,tpox,fga,pellet_creation_date,percentage_match_to_parental,lab_corp_spec_nbr,lab_corp_case_nbr,comments,amelogenin,model_condition_id.1,mouse,mycoplasma,patient_id,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
467,ACH-000970,PT-B2n6IN,ACH-000970,MC-000970-Bx3a,ACH-000970,PT-B2n6IN,MC-000970-Bx3a,STR-YuuzN8,False,15,"6, 9","29, 31.2","13, 15, 19, 20, 21, 22","19, 20","11, 12","8, 9",12,"8, 12, 13, 14","11, 13","10, 12, 13",15,"12, 14, 15",8,"19, 22, 23",2016-09-27,0.8308,NaN,CX4014974,NaN,X,MC-000970-Bx3a,NaN,NaN,PT-B2n6IN,Internal,GPP,NaN,SNU-C5-311cas9(9/27/2016),2024-08-13,2024-08-13 14:32:29.468693+00:00
469,ACH-000970,PT-B2n6IN,ACH-000970,MC-000970-Bx3a,ACH-000970,PT-B2n6IN,MC-000970-Bx3a,STR-OIfYbO,False,15,"6, 9","29, 31.2","15, 20, 21, 22",20,"11, 12",8,12,"8, 12, 13, 14","10, 11, 13","12, 13",15,"12, 14, 15",8,"18, 19, 22, 23",2023-07-07,0.8710,NaN,CX4016892,NaN,X,MC-000970-Bx3a,NaN,NaN,PT-B2n6IN,Internal,GPP,NaN,SNUC5-Cas9VY,2024-08-13,2024-08-13 14:32:29.468693+00:00
470,ACH-000970,PT-B2n6IN,ACH-000970,MC-000970-Bx3a,ACH-000970,PT-B2n6IN,MC-000970-Bx3a,STR-xW7cbo,False,15,"6, 9","29, 31.2","15, 20, 21, 22","20, 21","11, 12, 13",8,12,"8, 13","11, 12, 13, 14","12, 13",15,"12, 14, 15",8,"18, 19, 22, 23",2023-11-09,0.8254,NaN,CX4017930,NaN,X,MC-000970-Bx3a,NaN,NaN,PT-B2n6IN,Internal,GPP,NaN,SNUC5-Cas9VY-ParalogV2-RepA-P6(D22),2024-08-13,2024-08-13 14:32:29.468693+00:00
471,ACH-000970,PT-B2n6IN,ACH-000970,MC-000970-Bx3a,ACH-000970,PT-B2n6IN,MC-000970-Bx3a,STR-eFqrqg,False,"15, 16, 17","6, 9","29, 31.2","15, 20, 21, 22","20, 21","11, 12",8,12,"8, 13, 14, 15","11, 13, 14","12, 13",15,"12, 14, 15",8,"18, 19, 23",2023-10-19,0.8125,NaN,CX4017728,NaN,X,MC-000970-Bx3a,NaN,NaN,PT-B2n6IN,Internal,GPP,NaN,SNUC5-Cas9VY-ParalogV2-RepB-P6(D22),2024-08-13,2024-08-13 14:32:29.468693+00:00
481,ACH-003099,PT-BHjOZY,ACH-003099,MC-003099-DM4v,ACH-003099,PT-BHjOZY,MC-003099-DM4v,STR-5Vx5yk,False,16,"6, 7",30,15,"12, 13",12,"8, 12","10, 12","9, 13","11, 12","8, 9","16, 18","10, 13","8, 11","20, 25",2022-10-21,1.0000,NaN,CX4014974,NaN,X,MC-003099-DM4v,NaN,NaN,PT-BHjOZY,Internal,GPP,NaN,UCSFOT1109-enCas12a,2024-08-13,2024-08-13 14:32:29.468693+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6466,ACH-001031,PT-nuzviS,ACH-001031,MC-001031-oRDI,ACH-001031,PT-nuzviS,MC-001031-oRDI,STR-E42whd,False,"15, 18","6, 7",31.3,"17, 19",NaN,"10, 12","10, 9","10, 12","10, 12","10, 11","12, 13",NaN,"10, 14",NaN,"24, 23",NaN,0.8571,NaN,NaN,NaN,NaN,MC-001031-oRDI,NaN,NaN,PT-nuzviS,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00
6467,ACH-000449,PT-E7giyP,ACH-000449,MC-000449-iHb5,ACH-000449,PT-E7giyP,MC-000449-iHb5,STR-E6KW1y,False,"14, 17",6,NaN,"12, 15","7.1, 10.1",13,"11, 13","7, 11","11, 12",11,"12, 14",NaN,"14, 15",NaN,"20, 25",NaN,0.7556,NaN,NaN,NaN,NaN,MC-000449-iHb5,NaN,NaN,PT-E7giyP,Internal,WGS Inferred,NaN,NaN,2024-06-13,2024-06-13 16:48:18.244183+00:00
6477,ACH-002968,PT-pjhrsc,ACH-002968,MC-002968-WZFJ,ACH-002968,PT-pjhrsc,MC-002968-WZFJ,STR-JhhHTm,False,"15, 18",9.3,"30, 32.2",14,"5, 7","11, 12",12,11,12,"9, 12",10,17,"15, 16",9,"23, 24",NaN,1.0000,29G90970,CX4014631,NaN,X,MC-002968-WZFJ,Not Detected,NaN,PT-pjhrsc,Internal,Minerva,NaN,ACH-002968 Post H1 FP (pX+11),2024-04-09,2024-04-09 16:00:46.668811+00:00
6480,ACH-001310,PT-1UiNjR,ACH-001310,MC-001310-xz7e,ACH-001310,PT-1UiNjR,MC-001310-xz7e,STR-m7DSLR,False,"14, 17","6, 9.3",NaN,"12, 16","12.1, 15.1","11, 12",12,"9, 12","9, 13","10, 11","10, 13",NaN,"13, 15",NaN,"20, 22",NaN,0.7917,NaN,NaN,NaN,NaN,MC-001310-xz7e,NaN,NaN,PT-1UiNjR,Internal,WGS Inferred,NaN,NaN,2024-05-24,2024-05-24 16:43:47.000144+00:00
6483,ACH-003173,PT-7RzxsG,ACH-003173,MC-003173-Pyd2,ACH-003173,PT-7RzxsG,MC-003173-Pyd2,STR-X4LWcy,False,"17, 18","9.3, 7","30.3, 32.1","17, 14","16.1, 12.1",11,"12, 9","10, 11","13, 9","12, 11",NaN,NaN,"15, 11","11, 9",20,NaN,0.8696,NaN,NaN,NaN,NaN,MC-003173-Pyd2,NaN,NaN,PT-7RzxsG,Internal,WGS Inferred,NaN,NaN,2024-04-09,2024-04-09 16:00:46.668811+00:00

In [33]:
#reference
all_str_single_upload['is_reference'].value_counts()

is_reference
False    5394
True     1092
Name: count, dtype: int64

In [34]:
#source
all_str_single_upload['source'].value_counts()

source
Internal    6401
External      85
Name: count, dtype: int64

In [35]:
#source groups
all_str_single_upload['source_group'].value_counts()

source_group
WGS Inferred                2196
GPP                         2122
DMX                          783
PRISM                        718
Minerva                      452
Mnemosyne                    135
Achilles                      26
Cellosaurus                   25
Oslo University Hospital      23
CCLF                           1
Name: count, dtype: int64

In [36]:
#total counts of reference by patient id
counts = all_str_single_upload.groupby('str_patient_id')['is_reference'].value_counts()
counts = counts.reset_index(name='count')
counts.head(15)

   str_patient_id  is_reference  count
0       PT-00UDx5         False      3
1       PT-00UDx5          True      1
2       PT-01q6LP         False      2
3       PT-01q6LP          True      1
4       PT-03AcoW         False      5
5       PT-03AcoW          True      1
6       PT-04HLfu          True      1
7       PT-04HLfu         False      1
8       PT-04KbrE         False      1
9       PT-0531Uw         False      3
10      PT-0531Uw          True      1
11      PT-05dldv         False      2
12      PT-05hA76          True      1
13      PT-05hA76         False      1
14      PT-0Ds3by         False      1

In [37]:
#combined
ref_counts = all_str_single_upload.groupby(['str_patient_id', 'is_reference']).size().unstack(fill_value=0)
ref_counts.to_csv('ref_counts.csv')
ref_counts.head(50)

is_reference    False  True
str_patient_id
PT-00UDx5           3      1
PT-01q6LP           2      1
PT-03AcoW           5      1
PT-04HLfu           1      1
PT-04KbrE           1      0
PT-0531Uw           3      1
PT-05dldv           2      0
PT-05hA76           1      1
PT-0Ds3by           1      0
PT-0E9rgp           2      1
PT-0F4qCF           3      0
PT-0Fp6tq           4      0
PT-0GisSs           4      1
PT-0GrZ0k           7      0
PT-0H6Zc0           2      0
PT-0HjWKA           1      0
PT-0LOocN           1      0
PT-0MsFyj           5      1
PT-0RBdNq           4      0
PT-0UOmyW           3      0
PT-0VWXIm           3      0
PT-0ZDLSk           5      1
PT-0a2F5a          10      1
PT-0eB7jK           1      0
PT-0fXDWz           1      0
PT-0hCGTm           2      0
PT-0hMOxQ           2      0
PT-0lPf2W           3      1
PT-0lpZdv           1      1
PT-0mdkef           4      0
PT-0o7FOB           2      1
PT-0uFhp8           2      0
PT-0uXvN6           0      1
PT-0woxaX           1      0
PT-0yqjae           4      1
PT-0yrZJC           4      0
PT-0zEk9y           0      1
PT-1559gB           9      0
PT-1BkfPG           2      1
PT-1DyLm0           2      0
PT-1EAB3W           1      1
PT-1I8hCi           1      0
PT-1Ii4Q3           0      1
PT-1IphRN           1      1
PT-1JVU53           4      1
PT-1JhWBd           2      0
PT-1M8cz3           2      1
PT-1PBPXD           1      0
PT-1PHTgt           5      0
PT-1PVhNW           1      1

In [38]:
#sample str no ref str
ref_counts.columns = [ 'False', 'True']
no_refs = ref_counts[(ref_counts['False'] >= 1) & (ref_counts['True'] == 0)]
no_refs.to_csv('str_with_no_refs.csv')
no_refs

                False  True
str_patient_id
PT-04KbrE           1     0
PT-05dldv           2     0
PT-0Ds3by           1     0
PT-0F4qCF           3     0
PT-0Fp6tq           4     0
...               ...   ...
PT-zlBs5P           3     0
PT-zp1phR           1     0
PT-zqsQMh           1     0
PT-zrYGap           2     0
PT-zshCzw           5     0

[977 rows x 2 columns]

In [39]:
#ref str but no sample str
ref_no_sample = ref_counts[(ref_counts['False'] == 0) & (ref_counts['True'] >= 1)]
ref_no_sample.to_csv('str_with_refs_no_sample_strs.csv')
ref_no_sample

                False  True
str_patient_id
PT-0uXvN6           0     1
PT-0zEk9y           0     1
PT-1Ii4Q3           0     1
PT-1rbGNh           0     1
PT-2KZg5H           0     1
PT-2UMZn1           0     1
PT-2a1cpe           0     1
PT-2gvMHE           0     1
PT-2iz8vp           0     1
PT-3WE7tT           0     1
PT-4LNPhB           0     1
PT-4Nw0Gg           0     1
PT-4cABry           0     1
PT-4g0oOs           0     1
PT-4zySXj           0     1
PT-5WoxMn           0     1
PT-5s2EZm           0     1
PT-6DAmBn           0     1
PT-6FOEEj           0     1
PT-6kOhAX           0     1
PT-7kklUs           0     1
PT-8PKW0Q           0     1
PT-8TN03J           0     1
PT-9CCSAo           0     1
PT-9D3ue9           0     1
PT-9KxreI           0     1
PT-9SBdeX           0     1
PT-9iibBv           0     1
PT-Ak9O8Z           0     1
PT-BB1vF7           0     1
PT-BemhJ7           0     1
PT-BibKiA           0     1
PT-C880aD           0     1
PT-CNzzSN           0     1
PT-CSRXBn           0     1
PT-CVPxmk           0     1
PT-DdDGB6           0     1
PT-DkDAqQ           0     1
PT-E9sOoS           0     1
PT-Ea4nZo           0     1
PT-F6euB4           0     1
PT-FQ3AFJ           0     1
PT-FeUEcM           0     1
PT-FnR6bv           0     1
PT-G033m5           0     1
PT-G1dQTb           0     1
PT-GE4vq8           0     1
PT-GjHo2d           0     1
PT-H09155           0     1
PT-HDTipb           0     1
PT-HH6Idz           0     1
PT-HKGwye           0     1
PT-HPjp0i           0     1
PT-HjMPSE           0     1
PT-I1tcSd           0     1
PT-J5FdFW           0     1
PT-JbQXVN           0     1
PT-JsdCv7           0     1
PT-K3zKwo           0     1
PT-K7amRD           0     1
PT-K81KvW           0     1
PT-KEJgPW           0     1
PT-KaownI           0     1
PT-LA0Wfj           0     1
PT-LG2ZEU           0     1
PT-LNoIYy           0     1
PT-LcnpjK           0     1
PT-Li0oi0           0     1
PT-M9HtPD           0     1
PT-MWTVtt           0     1
PT-MrquRv           0     1
PT-ND5kWh           0     1
PT-Nc2afW           0     1
PT-NgiNgc           0     1
PT-NisxxL           0     1
PT-NkIUY4           0     1
PT-NstR9U           0     1
PT-OEvbBw           0     1
PT-OOowtC           0     1
PT-OP8ALo           0     1
PT-OVLWOO           0     1
PT-OcDhFp           0     1
PT-Ol229H           0     1
PT-P6M2l9           0     1
PT-PiCP8o           0     1
PT-Pzlr8k           0     1
PT-QWZuVb           0     1
PT-Qc9Qbw           0     1
PT-QowF1e           0     1
PT-ROzaOn           0     1
PT-RWRqpw           0     1
PT-Roe14Y           0     1
PT-SXLAbU           0     1
PT-SZz4EA           0     1
PT-SxCIHt           0     1
PT-TMbALQ           0     1
PT-TcuEsa           0     1
PT-Tj0cj3           0     1
PT-TsEQNZ           0     1
PT-U4xcgG           0     1
PT-UQGfCf           0     1
PT-UTRej4           0     1
PT-UZAkdb           0     1
PT-Uu4eY6           0     1
PT-V8yAFO           0     1
PT-VO317C           0     1
PT-VkVUay           0     1
PT-VzJIqw           0     1
PT-W7OD6X           0     1
PT-WRGYV2           0     1
PT-Wd9qZ2           0     1
PT-WoFoYC           0     1
PT-WpHvu2           0     1
PT-X6RNMT           0     1
PT-XBPexa           0     1
PT-XEjBz1           0     1
PT-Xi79sE           0     1
PT-YKRAPQ           0     1
PT-Yc254j           0     1
PT-Z9JUVl           0     1
PT-ZFeVCn           0     1
PT-ZKesLJ           0     1
PT-ZMhIZv           0     1
PT-Zep3T4           0     1
PT-ZhC0XK           0     1
PT-ZuJ50H           0     1
PT-a2ltr5           0     1
PT-aPiiX4           0     1
PT-b53yDc           0     1
PT-c34xau           0     1
PT-cIt896           0     1
PT-ccChqb           0     1
PT-cwA2Hh           0     1
PT-dYlXmf           0     1
PT-ddWBg4           0     1
PT-dfoUfk           0     1
PT-dlYxf2           0     1
PT-dxM1YV           0     1
PT-e1ofF2           0     1
PT-exue2X           0     1
PT-f9xU9Y           0     1
PT-fVqkJe           0     1
PT-fpxD8o           0     1
PT-g4RCgj           0     1
PT-gAK7fg           0     1
PT-gDQhpO           0     1
PT-gU9yO7           0     1
PT-gUUbZP           0     1
PT-gtNgXN           0     1
PT-gwfQe8           0     1
PT-hSuplk           0     1
PT-hoi5yn           0     1
PT-hqco5e           0     1
PT-huyXeM           0     1
PT-i2GM12           0     1
PT-i9dYpA           0     1
PT-iHWH73           0     1
PT-iJJU0s           0     1
PT-iJJxvM           0     1
PT-iPdYr4           0     1
PT-ilfTn2           0     1
PT-jExNUG           0     1
PT-jIQneo           0     1
PT-jalaJZ           0     1
PT-jj05kF           0     1
PT-jpF6oB           0     1
PT-jxNhRK           0     1
PT-l9J76R           0     1
PT-lKVNuC           0     1
PT-lg7hiV           0     1
PT-m3LgrV           0     1
PT-mVaoEC           0     1
PT-mdnFXo           0     1
PT-mojjC0           0     1
PT-nEBFkx           0     1
PT-nN0azP           0     1
PT-nQjnBw           0     1
PT-nk4Wls           0     1
PT-nkPe8R           0     1
PT-o9byHq           0     1
PT-oLzmwU           0     1
PT-oNClWO           0     1
PT-oPsAd9           0     1
PT-oQXmqM           0     1
PT-oVG8fA           0     1
PT-omPHH7           0     1
PT-osNzyX           0     1
PT-p0xqNM           0     1
PT-p93T4l           0     1
PT-pBU2pM           0     1
PT-plROGY           0     1
PT-pna1st           0     1
PT-q7epG7           0     1
PT-qCvJTe           0     1
PT-r25aIJ           0     1
PT-rA7p00           0     1
PT-rP4H2e           0     1
PT-sGq3XF           0     1
PT-sJivDn           0     1
PT-sos6TM           0     1
PT-spChit           0     1
PT-sqWfj7           0     1
PT-sxiEGA           0     1
PT-t4ODPe           0     1
PT-tj0IG3           0     1
PT-u1n8IU           0     1
PT-u9RLjX           0     1
PT-vMW17s           0     1
PT-vOlu5j           0     1
PT-vbLgiZ           0     1
PT-vcAXTz           0     1
PT-w3Ytiz           0     1
PT-wNQatL           0     1
PT-whFxr4           0     1
PT-xDPaCL           0     1
PT-xJ8KWT           0     1
PT-xU6EKP           0     1
PT-xZNbVe           0     1
PT-xjAe1V           0     1
PT-xjbffS           0     1
PT-xr77O8           0     1
PT-xygDvt           0     1
PT-yrG6JJ           0     1
PT-yrcwGU           0     1
PT-zAzHh6           0     1
PT-zQwaRW           0     1
PT-zXsYg6           0     1
PT-zx0MVs           0     1
PT-zzULgh           0     1

In [40]:
#sample str and ref str
both_ref_sample_str = ref_counts[(ref_counts['False'] >= 1) & (ref_counts['True'] >= 1)]
both_ref_sample_str.to_csv('str_with_both_refs.csv')
both_ref_sample_str

                False  True
str_patient_id
PT-00UDx5           3     1
PT-01q6LP           2     1
PT-03AcoW           5     1
PT-04HLfu           1     1
PT-0531Uw           3     1
...               ...   ...
PT-zfPfIU           6     1
PT-zjOA3C           1     1
PT-zuTmVR           3     1
PT-zwxgMM           3     1
PT-zy2Tek           1     1

[863 rows x 2 columns]

In [41]:
#including model_conditions
ref_counts_mod_cond = all_str_single_upload.groupby(['str_patient_id','model_condition_id', 'is_reference']).size().unstack(fill_value=0)
ref_counts_mod_cond

is_reference                       False  True
str_patient_id model_condition_id
PT-00UDx5      MC-003044-gcIN          3      1
PT-01q6LP      MC-000000-TEST          1      0
               MC-001541-ux7W          0      1
PT-03AcoW      MC-002708-tPxj          5      1
PT-04HLfu      MC-001533-SowA          1      1
...                                  ...    ...
PT-zwxgMM      MC-001484-dooe          1      1
               MC-001485-Qw1Y          2      0
PT-zx0MVs      MC-001865-3Vel          0      1
PT-zy2Tek      MC-003230-Uu6g          1      1
PT-zzULgh      MC-001913-ceWs          0      1

[2170 rows x 2 columns]

In [42]:
#ref str but no sample str with by model condition
ref_counts_mod_cond.columns = ['False', 'True']
ref_only_mod_cond = ref_counts_mod_cond[(ref_counts_mod_cond['False'] == 0) & (ref_counts_mod_cond['True'] == 1)]
ref_only_mod_cond

                                   False  True
str_patient_id model_condition_id
PT-01q6LP      MC-001541-ux7W          0     1
PT-0uXvN6      MC-001678-DptN          0     1
PT-0zEk9y      MC-001881-Ffwd          0     1
PT-1Ii4Q3      MC-001884-KhOL          0     1
PT-1rbGNh      MC-001907-Z0iF          0     1
PT-2KZg5H      MC-001361-ghvT          0     1
PT-2UMZn1      MC-001891-KFqz          0     1
PT-2a1cpe      MC-001620-6V1R          0     1
PT-2gvMHE      MC-001493-yY6r          0     1
PT-2iz8vp      MC-001910-rO8r          0     1
PT-3WE7tT      MC-001873-KdbD          0     1
PT-4LNPhB      MC-001764-xEGw          0     1
PT-4Nw0Gg      MC-001922-j0Ga          0     1
PT-4cABry      MC-001376-Gwba          0     1
PT-4zySXj      MC-002022-gVjv          0     1
PT-5s2EZm      MC-001605-h6eY          0     1
PT-6DAmBn      MC-001903-SgK4          0     1
PT-6FOEEj      MC-001612-OosV          0     1
PT-6kOhAX      MC-001898-UdWl          0     1
PT-7kklUs      MC-002844-JsTX          0     1
PT-8PKW0Q      MC-001531-cOj9          0     1
PT-8TN03J      MC-001866-7JSg          0     1
PT-9CCSAo      MC-000687-ggUv          0     1
PT-9D3ue9      MC-001901-PSmT          0     1
PT-9KxreI      MC-001644-fPXH          0     1
PT-9SBdeX      MC-001572-KGo8          0     1
PT-9iibBv      MC-001867-1UMz          0     1
PT-Ak9O8Z      MC-001923-FZV3          0     1
PT-BB1vF7      MC-001328-3LPD          0     1
PT-BN67ox      MC-000100-8Lil          0     1
PT-BemhJ7      MC-001536-hiad          0     1
PT-BibKiA      MC-002514-8d6C          0     1
PT-BpX01U      MC-000279-zY8v          0     1
PT-C880aD      MC-001347-gXUu          0     1
PT-CNzzSN      MC-001497-Jwk8          0     1
PT-CSRXBn      MC-002656-hzgh          0     1
PT-CVPxmk      MC-001626-xNA2          0     1
PT-DdDGB6      MC-000980-7KD6          0     1
PT-DkDAqQ      MC-001895-u9bJ          0     1
PT-E9sOoS      MC-002409-ybkg          0     1
PT-Ea4nZo      MC-001679-DRZr          0     1
PT-F6euB4      MC-001384-mAQS          0     1
PT-FMp5RI      MC-001633-qZwA          0     1
PT-FQ3AFJ      MC-001452-Fb1W          0     1
PT-FeUEcM      MC-001625-p0RD          0     1
PT-FnR6bv      MC-001924-nf5X          0     1
PT-FplxWn      MC-001596-naLh          0     1
PT-G033m5      MC-002515-AVOT          0     1
PT-G1dQTb      MC-001340-Rzvh          0     1
PT-GE4vq8      MC-001902-5AZF          0     1
PT-GjHo2d      MC-001889-OCEq          0     1
PT-H09155      MC-000512-BELB          0     1
PT-HDTipb      MC-001826-A8IJ          0     1
PT-HH6Idz      MC-001911-XSpR          0     1
PT-HKGwye      MC-000908-MMId          0     1
PT-HPjp0i      MC-001875-8kAk          0     1
PT-HjMPSE      MC-001914-lAca          0     1
PT-I1tcSd      MC-001897-325g          0     1
PT-IPboWn      MC-001825-AzSh          0     1
PT-J5FdFW      MC-002058-8na3          0     1
PT-JUL0sC      MC-003597-uyhg          0     1
PT-JWRsco      MC-002466-lZtp          0     1
PT-JbQXVN      MC-000578-0XhE          0     1
PT-K3zKwo      MC-002053-2s0M          0     1
PT-K7amRD      MC-002649-UTTt          0     1
PT-K81KvW      MC-002803-65Vx          0     1
PT-KEJgPW      MC-001565-FPrx          0     1
PT-KaownI      MC-002054-cJqA          0     1
PT-LA0Wfj      MC-000558-q891          0     1
PT-LG2ZEU      MC-001933-SEgj          0     1
PT-LNoIYy      MC-001534-OaQt          0     1
PT-LcnpjK      MC-002657-vtiS          0     1
PT-Li0oi0      MC-001438-SWHw          0     1
PT-Lz3i3Q      MC-001064-rtq2          0     1
PT-M9HtPD      MC-001449-rTVx          0     1
PT-MWTVtt      MC-001417-1P55          0     1
PT-MrquRv      MC-002666-imsA          0     1
PT-ND5kWh      MC-001373-janw          0     1
PT-Nc2afW      MC-001561-MKmJ          0     1
PT-NgiNgc      MC-002804-2XTW          0     1
PT-NisxxL      MC-001602-sA8Y          0     1
PT-NkIUY4      MC-001455-raxH          0     1
PT-NstR9U      MC-001927-P8bg          0     1
PT-OEvbBw      MC-001657-wvry          0     1
PT-OOowtC      MC-002071-QyVo          0     1
PT-OP8ALo      MC-002011-gwcQ          0     1
PT-OcDhFp      MC-001872-Oz74          0     1
PT-Ol229H      MC-002028-p28I          0     1
PT-P6M2l9      MC-002694-Ij4F          0     1
PT-PiCP8o      MC-001896-SiMM          0     1
PT-Pzlr8k      MC-002422-mQvp          0     1
PT-QWZuVb      MC-002085-NBuz          0     1
PT-Qc9Qbw      MC-001710-jQpR          0     1
PT-QowF1e      MC-002496-EIUN          0     1
PT-ROzaOn      MC-001815-E0EM          0     1
PT-RWRqpw      MC-003175-qSU0          0     1
PT-Roe14Y      MC-002037-KtIc          0     1
PT-SXLAbU      MC-001575-TtVj          0     1
PT-SZz4EA      MC-001601-3mtN          0     1
PT-SxCIHt      MC-001874-Q796          0     1
PT-TMbALQ      MC-001869-pWGS          0     1
PT-TcuEsa      MC-001868-uReX          0     1
PT-Tj0cj3      MC-001888-rIzk          0     1
PT-TsEQNZ      MC-002642-VZsX          0     1
PT-U4xcgG      MC-001931-7Hhx          0     1
PT-UQGfCf      MC-002673-PSLL          0     1
PT-UTRej4      MC-001900-3UQW          0     1
PT-UZAkdb      MC-001948-fmzr          0     1
PT-Uu4eY6      MC-001892-pjrL          0     1
PT-V8yAFO      MC-001399-jcVk          0     1
PT-VO317C      MC-001878-Kv1z          0     1
PT-VkVUay      MC-001916-hbqL          0     1
PT-VzJIqw      MC-001613-audg          0     1
PT-W7OD6X      MC-001708-hBpK          0     1
PT-WRGYV2      MC-001806-Wh2S          0     1
PT-WoFoYC      MC-002896-Ws7Y          0     1
PT-WpHvu2      MC-001883-5tvh          0     1
PT-X6RNMT      MC-001617-bsKb          0     1
PT-XBPexa      MC-001919-UTup          0     1
PT-XEjBz1      MC-001941-KQ66          0     1
PT-XYdNvp      MC-001037-y3GW          0     1
PT-Xi79sE      MC-001908-yeqh          0     1
PT-YKRAPQ      MC-001014-dNWL          0     1
PT-Yc254j      MC-001413-tAbm          0     1
PT-Z9JUVl      MC-001899-ntxP          0     1
PT-ZFeVCn      MC-001746-dNOt          0     1
PT-ZKesLJ      MC-001905-QjEn          0     1
PT-ZMhIZv      MC-002513-IBco          0     1
PT-ZSsyUS      MC-001501-ReDV          0     1
PT-Zep3T4      MC-001397-PG71          0     1
PT-ZhC0XK      MC-001909-Qep0          0     1
PT-ZuJ50H      MC-001854-sTtz          0     1
PT-a2ltr5      MC-001627-wPx0          0     1
PT-aPiiX4      MC-001921-yTtC          0     1
PT-b53yDc      MC-001666-70vb          0     1
PT-c34xau      MC-001086-D9pA          0     1
PT-cIt896      MC-001807-geak          0     1
PT-ccChqb      MC-001686-Zesm          0     1
PT-codP7n      MC-000057-XS1q          0     1
PT-cwA2Hh      MC-001689-ghwg          0     1
PT-dYlXmf      MC-001751-oEWE          0     1
PT-ddWBg4      MC-001837-LqWs          0     1
PT-dfoUfk      MC-001926-d9rE          0     1
PT-dlYxf2      MC-001639-ph75          0     1
PT-dxM1YV      MC-001915-8yIE          0     1
PT-e1ofF2      MC-001763-tWfR          0     1
PT-epgMPc      MC-001535-AEhI          0     1
PT-exue2X      MC-001717-q3w4          0     1
PT-f9xU9Y      MC-001405-0SiD          0     1
PT-fVqkJe      MC-001971-9Qqf          0     1
PT-fpxD8o      MC-001761-Wopu          0     1
PT-g4RCgj      MC-001629-xBqH          0     1
PT-gAK7fg      MC-001446-Kkz4          0     1
PT-gDQhpO      MC-001490-GghH          0     1
PT-gU9yO7      MC-002072-SomP          0     1
PT-gUUbZP      MC-001415-BCBQ          0     1
PT-gtNgXN      MC-002502-koOD          0     1
PT-gwfQe8      MC-001663-aiMJ          0     1
PT-hB4ARO      MC-001444-1Vou          0     1
PT-hSuplk      MC-001742-P3PS          0     1
PT-hf4hbl      MC-001339-5nRN          0     1
PT-hoi5yn      MC-002939-57CB          0     1
PT-hqco5e      MC-002402-nk1a          0     1
PT-huyXeM      MC-001389-JiiU          0     1
PT-i2GM12      MC-001437-kbI5          0     1
PT-i9dYpA      MC-001392-ka56          0     1
PT-iHWH73      MC-002078-ZTfU          0     1
PT-iJJU0s      MC-001762-Ojlw          0     1
PT-iJJxvM      MC-001358-t660          0     1
PT-iPdYr4      MC-001614-Zwml          0     1
PT-iW8GZP      MC-002398-SSy3          0     1
PT-ilfTn2      MC-001581-Cznj          0     1
PT-jExNUG      MC-001946-JpqH          0     1
PT-jIQneo      MC-001876-rNUN          0     1
PT-jZhsXq      MC-001621-JTww          0     1
PT-jalaJZ      MC-001847-IniK          0     1
PT-jj05kF      MC-001886-eYRX          0     1
PT-jpF6oB      MC-002989-7yYt          0     1
PT-jxNhRK      MC-001420-oMtu          0     1
PT-l9J76R      MC-001638-xwcP          0     1
PT-lKVNuC      MC-001877-IDfy          0     1
PT-lg7hiV      MC-001920-ATJP          0     1
PT-m3LgrV      MC-001894-nVq4          0     1
PT-mVaoEC      MC-002509-QORQ          0     1
PT-mdnFXo      MC-003128-3gEG          0     1
PT-mojjC0      MC-001371-rvSG          0     1
PT-nEBFkx      MC-001292-nJjY          0     1
PT-nN0azP      MC-002658-gZqG          0     1
PT-nQjnBw      MC-001912-MT2H          0     1
PT-nk4Wls      MC-001925-W7DY          0     1
PT-nkPe8R      MC-002008-PSKl          0     1
PT-o9byHq      MC-001871-jKen          0     1
PT-oLzmwU      MC-002481-V9kI          0     1
PT-oNClWO      MC-001937-xI6h          0     1
PT-oPsAd9      MC-001378-93SH          0     1
PT-oQXmqM      MC-001331-6yqw          0     1
PT-oVG8fA      MC-001906-hgXO          0     1
PT-omPHH7      MC-001788-PsBg          0     1
PT-osNzyX      MC-001958-33kg          0     1
PT-p0xqNM      MC-001890-Kp6s          0     1
PT-p93T4l      MC-002063-VZ3i          0     1
PT-pBU2pM      MC-001456-4fjm          0     1
PT-plROGY      MC-002385-uJxw          0     1
PT-pna1st      MC-001732-inf8          0     1
PT-q7epG7      MC-001516-bRnF          0     1
PT-qCvJTe      MC-001893-bXn0          0     1
PT-r25aIJ      MC-001904-Tlde          0     1
PT-rA7p00      MC-001381-slGN          0     1
PT-rP4H2e      MC-001615-iCPE          0     1
PT-rWyhmW      MC-002456-lbZB          0     1
PT-sGJOXH      MC-001345-KbHX          0     1
PT-sGq3XF      MC-001928-UxzW          0     1
PT-sJivDn      MC-001885-iuRp          0     1
PT-sos6TM      MC-002679-aITx          0     1
PT-spChit      MC-000465-SoO3          0     1
PT-sqWfj7      MC-001583-tLXX          0     1
PT-sxiEGA      MC-001698-xA1G          0     1
PT-t4ODPe      MC-001870-qCNI          0     1
PT-tj0IG3      MC-001855-5n8l          0     1
PT-u9RLjX      MC-001879-NDAK          0     1
PT-vMW17s      MC-001880-k88n          0     1
PT-vOlu5j      MC-001631-yR4C          0     1
PT-vbLgiZ      MC-000902-JVOX          0     1
PT-vcAXTz      MC-002682-zsU8          0     1
PT-w3Ytiz      MC-001512-Y7Ie          0     1
PT-wNQatL      MC-001930-Dy9Q          0     1
PT-whFxr4      MC-001940-SdQb          0     1
PT-xDPaCL      MC-002542-QBrO          0     1
PT-xJ8KWT      MC-001932-45lg          0     1
PT-xU6EKP      MC-001917-TFNp          0     1
PT-xZNbVe      MC-001829-oVB5          0     1
PT-xjAe1V      MC-001947-fZG7          0     1
PT-xjbffS      MC-001660-Q4rs          0     1
PT-xygDvt      MC-001537-4GEo          0     1
PT-yrG6JJ      MC-002318-cfeu          0     1
PT-yrcwGU      MC-001942-uIWi          0     1
PT-zAzHh6      MC-001063-vr23          0     1
PT-zQwaRW      MC-001951-hwox          0     1
PT-zXsYg6      MC-001457-RtM1          0     1
PT-zx0MVs      MC-001865-3Vel          0     1
PT-zzULgh      MC-001913-ceWs          0     1

In [43]:
#sample str no ref str by model condition
no_refs_mod_cond = ref_counts_mod_cond[(ref_counts_mod_cond['False'] >= 1) & (ref_counts_mod_cond['True'] == 0)]
no_refs_mod_cond

                                   False  True
str_patient_id model_condition_id
PT-01q6LP      MC-000000-TEST          1     0
PT-04KbrE      MC-000722-Bobx          1     0
PT-05dldv      MC-000979-bkVz          1     0
PT-0Ds3by      MC-000297-kYTw          1     0
PT-0E9rgp      MC-002822-EnEF          2     0
...                                  ...   ...
PT-zp1phR      MC-003629-S2H9          1     0
PT-zqsQMh      MC-003105-cFPR          1     0
PT-zrYGap      MC-000914-GsyT          1     0
PT-zshCzw      MC-000233-Fszn          4     0
PT-zwxgMM      MC-001485-Qw1Y          2     0

[1117 rows x 2 columns]

In [44]:
#both sample and ref str with model condition
no_refs_mod_cond_both = ref_counts_mod_cond[(ref_counts_mod_cond['False'] >= 1) & (ref_counts_mod_cond['True'] >= 1)]
no_refs_mod_cond_both

                                   False  True
str_patient_id model_condition_id
PT-00UDx5      MC-003044-gcIN          3     1
PT-03AcoW      MC-002708-tPxj          5     1
PT-04HLfu      MC-001533-SowA          1     1
PT-0531Uw      MC-002052-GfvX          3     1
PT-05hA76      MC-001680-sp3j          1     1
...                                  ...   ...
PT-zfPfIU      MC-002964-0orR          4     1
PT-zjOA3C      MC-001402-CPYn          1     1
PT-zuTmVR      MC-003334-3g7u          3     1
PT-zwxgMM      MC-001484-dooe          1     1
PT-zy2Tek      MC-003230-Uu6g          1     1

[812 rows x 2 columns]