In [2]:
import pandas as pd
import numpy as np

In [ ]:
!pwd

In [ ]:
cd Documents/

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 250)

In [4]:
STR_all = pd.read_csv('file_2.csv')

In [6]:
STR_all

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-001345,PT-sGJOXH,PT-sGJOXH,MC-001345-KbHX,STR-fs0TWY,True,"16, 18","7, 9.3","29, 30","12, 13",...,MC-001345-KbHX,NaN,NaN,PT-sGJOXH,Internal,DMX,NaN,GP5 D,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,ACH-001293,PT-nHktCj,PT-nHktCj,MC-001293-ZkY1,STR-hQB6tQ,True,"14, 16",6,"29, 32.2","15, 17",...,MC-001293-ZkY1,NaN,NaN,PT-nHktCj,Internal,DMX,NaN,CHLA-200,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2,ACH-001111,PT-glFbpW,PT-glFbpW,MC-001111-jbYD,STR-Y48Vnl,False,"18, 17",9.3,NaN,16,...,MC-001111-jbYD,NaN,NaN,PT-glFbpW,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3,ACH-001338,PT-cvCz0R,PT-cvCz0R,MC-001338-wh8o,STR-nv1QA1,True,16,"9, 9.3","28, 29","15, 18",...,MC-001338-wh8o,NaN,NaN,PT-cvCz0R,Internal,DMX,NaN,CHP-134,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4,ACH-001353,PT-dEG8Km,PT-dEG8Km,MC-001353-5EnB,STR-p7M1AR,True,"17, 18","9, 9.3","30, 31",14,...,MC-001353-5EnB,NaN,NaN,PT-dEG8Km,Internal,DMX,NaN,JOPACA-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,15,"7, 9",NaN,"16, 17",...,MC-000167-lZrU,NaN,NaN,PT-ghtKEp,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:01:31.405005+00:00,2024-04-10 18:01:31.405005+00:00
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,15,6,29,13,...,MC-002964-0orR,Not Detected,NaN,PT-zfPfIU,Internal,Minerva,2022-06-16,ACH-002964-Post-H1 (p22),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4317,ACH-001794,PT-jDDO2a,PT-jDDO2a,MC-001794-IAqD,STR-ugSbzY,False,NaN,"8, 9",NaN,"12, 17",...,MC-001794-IAqD,NaN,NaN,PT-jDDO2a,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:40:45.030904+00:00,2024-06-13 16:40:45.030904+00:00
4318,ACH-002067,PT-EcVEYs,PT-EcVEYs,MC-002067-S9Nv,STR-UI09f9,False,15,6,31.3,14,...,MC-002067-S9Nv,NaN,NaN,PT-EcVEYs,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [10]:
df = STR_all
df.columns

Index(['model_id', 'patient_id', 'patient_id.1', 'model_condition_id', 'id',
       'is_reference', 'd3s1358', 'th01', 'd21s11', 'd18s51', 'penta_e',
       'd5s818', 'd13s317', 'd7s820', 'd16s539', 'csf1po', 'penta_d', 'vwa',
       'd8s1179', 'tpox', 'fga', 'pellet_creation_date',
       'percentage_match_to_parental', 'lab_corp_spec_nbr',
       'lab_corp_case_nbr', 'comments', 'amelogenin', 'model_condition_id.1',
       'mouse', 'mycoplasma', 'patient_id.2', 'source', 'source_group',
       'pellet_submitted_date', 'sample_reference', 'created_at',
       'updated_at'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4319 entries, 0 to 4318
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   model_id                      3548 non-null   object
 1   patient_id                    3548 non-null   object
 2   patient_id.1                  4319 non-null   object
 3   model_condition_id            3548 non-null   object
 4   id                            4319 non-null   object
 5   is_reference                  4319 non-null   bool
 6   d3s1358                       4254 non-null   object
 7   th01                          4273 non-null   object
 8   d21s11                        3084 non-null   object
 9   d18s51                        4111 non-null   object
 10  penta_e                       3957 non-null   object
 11  d5s818                        4206 non-null   object
 12  d13s317                       4206 non-null   object
 13  d7s820                        4254 non-null   object
 14  d16s539                       4274 non-null   object
 15  csf1po                        4284 non-null   object
 16  penta_d                       4030 non-null   object
 17  vwa                           2193 non-null   object
 18  d8s1179                       4185 non-null   object
 19  tpox                          3625 non-null   object
 20  fga                           4100 non-null   object
 21  pellet_creation_date          301 non-null    object
 22  percentage_match_to_parental  1454 non-null   float64
 23  lab_corp_spec_nbr             2132 non-null   object
 24  lab_corp_case_nbr             2133 non-null   object
 25  comments                      1532 non-null   object
 26  amelogenin                    2183 non-null   object
 27  model_condition_id.1          3548 non-null   object
 28  mouse                         977 non-null    object
 29  mycoplasma                    118 non-null    object
 30  patient_id.2                  4319 non-null   object
 31  source                        4319 non-null   object
 32  source_group                  4316 non-null   object
 33  pellet_submitted_date         599 non-null    object
 34  sample_reference              2175 non-null   object
 35  created_at                    4319 non-null   object
 36  updated_at                    4319 non-null   object
dtypes: bool(1), float64(1), object(35)
memory usage: 1.2+ MB

In [9]:
df_patient_id_diff = [(df['patient_id'] != df['patient_id.1']) | (df['patient_id'] != df['patient_id.2']) | (df['patient_id.1'] != df['patient_id.2'])]
df_patient_id_diff

[0       False
 1       False
 2       False
 3       False
 4       False
         ...
 4314    False
 4315    False
 4316     True
 4317    False
 4318    False
 Length: 4319, dtype: bool]

In [10]:
pt_ids_diff = df[~((df['patient_id'] == df['patient_id.1']) & (df['patient_id.1'] == df['patient_id.2']))]
true_rows = pt_ids_diff.any(axis=1)

In [11]:
true_rows

60      True
147     True
174     True
186     True
187     True
        ...
4301    True
4303    True
4306    True
4312    True
4316    True
Length: 807, dtype: bool

In [12]:
df.iloc[4300:4317]

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
4300,ACH-003047,PT-ts2yuC,PT-ts2yuC,MC-003047-mwE5,STR-x9LrVF,False,16,6,30,16,...,MC-003047-mwE5,NaN,NaN,PT-ts2yuC,Internal,Minerva,2023-04-20,ACH-003047 Post-CD01(3047 C12v2 Post-CD01 FP)(...,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4301,NaN,NaN,PT-ulmNPq,NaN,STR-zvYQrx,False,"16, 19, 20, 21","7, 8","28, 30, 31","12, 13, 15, 16",...,NaN,NaN,NaN,PT-ulmNPq,Internal,PRISM,NaN,SNU-C4_LUA-3577,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4302,ACH-002677,PT-6AFvnc,PT-6AFvnc,MC-002677-Kddq,STR-ZXxHdo,True,"15, 16","6, 9.3",30,"11, 17",...,MC-002677-Kddq,NaN,NaN,PT-6AFvnc,Internal,DMX,NaN,U-2946,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4303,NaN,NaN,PT-SQ6fkx,NaN,STR-shrrBt,False,17,"6, 9","29, 32.2","14, 21",...,NaN,NaN,NaN,PT-SQ6fkx,Internal,PRISM,NaN,BC-3C_LUA-3398,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4304,ACH-001616,PT-oQqqCS,PT-oQqqCS,MC-001616-GhL4,STR-T3gUBN,False,"14, 15","6, 9",31.3,"15, 19",...,MC-001616-GhL4,NaN,NaN,PT-oQqqCS,Internal,WGS Inferred,NaN,NaN,2024-05-24 16:43:43.109824+00:00,2024-05-24 16:43:43.109824+00:00
4305,ACH-002946,PT-HryOAg,PT-HryOAg,MC-002946-4pvi,STR-XTpKMS,True,"14, 15","9, 9.3","27, 32.2","16, 19",...,MC-002946-4pvi,NaN,Not Detected,PT-HryOAg,Internal,DMX,NaN,UKE-1 (p2),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4306,NaN,NaN,PT-wbA1oa,NaN,STR-yRIqBE,False,15,"7, 8","30, 32.1",12,...,NaN,NaN,NaN,PT-wbA1oa,Internal,PRISM,NaN,KMRC-1_LUA-3564,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4307,ACH-002947,PT-Jlfsle,PT-Jlfsle,MC-002947-yu5B,STR-ZByt8z,False,16,"6, 9.3",30,"14, 16",...,MC-002947-yu5B,NaN,NaN,PT-Jlfsle,Internal,Minerva,2023-03-20,ACH-002947 Pre-CD01 (2947 C12 Pre CD01 FP) (p18),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4308,ACH-002958,PT-6y7Z6k,PT-6y7Z6k,MC-002958-Fuyj,STR-TJHxmW,False,15,9.3,"29, 30",14,...,MC-002958-Fuyj,Not Detected,NaN,PT-6y7Z6k,Internal,Minerva,NaN,ACH-002958 C12 FP (p14),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4309,ACH-002954,PT-piVxVb,PT-piVxVb,MC-002954-yG88,STR-tmYIe3,False,"15, 17",6,33.2,12,...,MC-002954-yG88,Positive,NaN,PT-piVxVb,Internal,Minerva,2022-08-25,ACH-002954-Post-C12 (p23),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4310,ACH-001949,PT-FxQs1g,PT-FxQs1g,MC-001949-eXWn,STR-VS3EPQ,True,15,7,"28, 32.2","16, 19",...,MC-001949-eXWn,Not Detected,NaN,PT-FxQs1g,Internal,DMX,NaN,MA-MEL-46,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4311,ACH-001828,PT-mexpVs,PT-mexpVs,MC-001828-se6f,STR-cvnKFq,True,"15, 17","6, 9.3","30, 32","16, 18",...,MC-001828-se6f,NaN,NaN,PT-mexpVs,External,Cellosaurus,NaN,NaN,2024-06-10 20:40:08.448261+00:00,2024-06-10 20:40:08.448280+00:00
4312,NaN,NaN,PT-Er9zxL,NaN,STR-DWrBck,True,"18, 19",7,"31, 33.2","13, 18",...,NaN,NaN,NaN,PT-Er9zxL,External,Cellosaurus,NaN,NaN,2024-06-14 21:06:05.759451+00:00,2024-06-14 21:06:05.759480+00:00
4313,ACH-003047,PT-ts2yuC,PT-ts2yuC,MC-003047-mwE5,STR-TzxQjU,False,16,6,30,NaN,...,MC-003047-mwE5,Not Detected,NaN,PT-ts2yuC,Internal,Minerva,NaN,ACH-003047 Pre Opt FP2 (p14),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,15,"7, 9",NaN,"16, 17",...,MC-000167-lZrU,NaN,NaN,PT-ghtKEp,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:01:31.405005+00:00,2024-04-10 18:01:31.405005+00:00
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,15,6,29,13,...,MC-002964-0orR,Not Detected,NaN,PT-zfPfIU,Internal,Minerva,2022-06-16,ACH-002964-Post-H1 (p22),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [13]:
#checking original df
df.iloc[60]

model_id                                              ACH-002745
patient_id                                             PT-urO852
patient_id.1                                           PT-SAJ1yK
model_condition_id                                MC-002745-Nzrl
id                                                    STR-0baHbR
is_reference                                                True
d3s1358                                                       15
th01                                                      7, 9.3
d21s11                                                        28
d18s51                                                        17
penta_e                                                    7, 14
d5s818                                                    11, 13
d13s317                                                       11
d7s820                                                        14
d16s539                                                   11, 13
csf1po                                                    10, 12
penta_d                                                   11, 12
vwa                                                       14, 15
d8s1179                                                       14
tpox                                                           8
fga                                                       20, 26
pellet_creation_date                                  2021-03-09
percentage_match_to_parental                                 NaN
lab_corp_spec_nbr                                       13I90940
lab_corp_case_nbr                                      CX4010782
comments                                                     NaN
amelogenin                                                     X
model_condition_id.1                              MC-002745-Nzrl
mouse                                                        NaN
mycoplasma                                                   NaN
patient_id.2                                           PT-SAJ1yK
source                                                  Internal
source_group                                             Minerva
pellet_submitted_date                                 2021-03-19
sample_reference                            ACH-002745-PreS (p5)
created_at                      2024-04-09 16:00:46.487764+00:00
updated_at                      2024-04-09 16:00:46.668811+00:00
Name: 60, dtype: object

In [14]:
reference_check = new_df = df.loc[~df['is_reference'], ['model_id', 'patient_id', 'patient_id.1', 'model_condition_id', 'id', 'is_reference', 'patient_id.2']]
reference_check

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,patient_id.2
2,ACH-001111,PT-glFbpW,PT-glFbpW,MC-001111-jbYD,STR-Y48Vnl,False,PT-glFbpW
9,ACH-000713,PT-FQOeFS,PT-FQOeFS,MC-000713-IUJj,STR-Yv4hq7,False,PT-FQOeFS
11,ACH-002046,PT-SKC9qY,PT-SKC9qY,MC-002046-oaX8,STR-7FEfGM,False,PT-SKC9qY
12,ACH-001465,PT-7eVJ3u,PT-7eVJ3u,MC-001465-V7hs,STR-BzNhKk,False,PT-7eVJ3u
13,ACH-001465,PT-7eVJ3u,PT-7eVJ3u,MC-001465-V7hs,STR-cv3IyE,False,PT-7eVJ3u
...,...,...,...,...,...,...,...
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,PT-ghtKEp
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,PT-zfPfIU
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,PT-gEiUjw
4317,ACH-001794,PT-jDDO2a,PT-jDDO2a,MC-001794-IAqD,STR-ugSbzY,False,PT-jDDO2a
4318,ACH-002067,PT-EcVEYs,PT-EcVEYs,MC-002067-S9Nv,STR-UI09f9,False,PT-EcVEYs

In [15]:
#str dups
str_dupes = df[df.duplicated(subset='id', keep=False)]
print(str_dupes)

Empty DataFrame
Columns: [model_id, patient_id, patient_id.1, model_condition_id, id, is_reference, d3s1358, th01, d21s11, d18s51, penta_e, d5s818, d13s317, d7s820, d16s539, csf1po, penta_d, vwa, d8s1179, tpox, fga, pellet_creation_date, percentage_match_to_parental, lab_corp_spec_nbr, lab_corp_case_nbr, comments, amelogenin, model_condition_id.1, mouse, mycoplasma, patient_id.2, source, source_group, pellet_submitted_date, sample_reference, created_at, updated_at]
Index: []

[0 rows x 37 columns]

In [16]:
unique_ids = df['id'].nunique()
unique_ids

4319

In [17]:
id_value_counts = df['id'].value_counts()
id_value_counts

id
STR-fs0TWY    1
STR-o8eAeP    1
STR-fCV6A0    1
STR-HrgofM    1
STR-A1CqH3    1
             ..
STR-b4UUqL    1
STR-PZgR2a    1
STR-RmitIO    1
STR-fKBoYC    1
STR-UI09f9    1
Name: count, Length: 4319, dtype: int64

In [18]:
#nan col check
nan_cols = df.columns[df.isnull().any()]
nan_cols

Index(['model_id', 'patient_id', 'model_condition_id', 'd3s1358', 'th01',
       'd21s11', 'd18s51', 'penta_e', 'd5s818', 'd13s317', 'd7s820', 'd16s539',
       'csf1po', 'penta_d', 'vwa', 'd8s1179', 'tpox', 'fga',
       'pellet_creation_date', 'percentage_match_to_parental',
       'lab_corp_spec_nbr', 'lab_corp_case_nbr', 'comments', 'amelogenin',
       'model_condition_id.1', 'mouse', 'mycoplasma', 'source_group',
       'pellet_submitted_date', 'sample_reference'],
      dtype='object')

In [19]:
nan_count = df.isnull().sum()
nan_count

model_id                         771
patient_id                       771
patient_id.1                       0
model_condition_id               771
id                                 0
is_reference                       0
d3s1358                           65
th01                              46
d21s11                          1235
d18s51                           208
penta_e                          362
d5s818                           113
d13s317                          113
d7s820                            65
d16s539                           45
csf1po                            35
penta_d                          289
vwa                             2126
d8s1179                          134
tpox                             694
fga                              219
pellet_creation_date            4018
percentage_match_to_parental    2865
lab_corp_spec_nbr               2187
lab_corp_case_nbr               2186
comments                        2787
amelogenin                      2136
model_condition_id.1             771
mouse                           3342
mycoplasma                      4201
patient_id.2                       0
source                             0
source_group                       3
pellet_submitted_date           3720
sample_reference                2144
created_at                         0
updated_at                         0
dtype: int64

In [20]:
df.head(100)

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-001345,PT-sGJOXH,PT-sGJOXH,MC-001345-KbHX,STR-fs0TWY,True,"16, 18","7, 9.3","29, 30","12, 13",...,MC-001345-KbHX,NaN,NaN,PT-sGJOXH,Internal,DMX,NaN,GP5 D,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,ACH-001293,PT-nHktCj,PT-nHktCj,MC-001293-ZkY1,STR-hQB6tQ,True,"14, 16",6,"29, 32.2","15, 17",...,MC-001293-ZkY1,NaN,NaN,PT-nHktCj,Internal,DMX,NaN,CHLA-200,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2,ACH-001111,PT-glFbpW,PT-glFbpW,MC-001111-jbYD,STR-Y48Vnl,False,"18, 17",9.3,NaN,16,...,MC-001111-jbYD,NaN,NaN,PT-glFbpW,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3,ACH-001338,PT-cvCz0R,PT-cvCz0R,MC-001338-wh8o,STR-nv1QA1,True,16,"9, 9.3","28, 29","15, 18",...,MC-001338-wh8o,NaN,NaN,PT-cvCz0R,Internal,DMX,NaN,CHP-134,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4,ACH-001353,PT-dEG8Km,PT-dEG8Km,MC-001353-5EnB,STR-p7M1AR,True,"17, 18","9, 9.3","30, 31",14,...,MC-001353-5EnB,NaN,NaN,PT-dEG8Km,Internal,DMX,NaN,JOPACA-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ACH-001454,PT-LAy4cf,PT-LAy4cf,MC-001454-oIL3,STR-NbDR38,True,"16, 17","6, 9.3","30, 31.2",18,...,MC-001454-oIL3,NaN,NaN,PT-LAy4cf,Internal,DMX,NaN,C10,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
96,ACH-001492,PT-LclWrD,PT-LclWrD,MC-001492-4vwy,STR-TuEpIG,True,"17, 18","6, 9","31.2, 33.2","13, 16",...,MC-001492-4vwy,NaN,NaN,PT-LclWrD,Internal,DMX,NaN,DOGKIT,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
97,ACH-002797,PT-nWAnv6,PT-nWAnv6,MC-002797-0VJZ,STR-w668k6,False,"15, 17","7, 9",32.3,"13, 14",...,MC-002797-0VJZ,NaN,NaN,PT-nWAnv6,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:41:14.116182+00:00,2024-06-13 16:41:14.116182+00:00
98,ACH-001455,PT-NkIUY4,PT-NkIUY4,MC-001455-raxH,STR-ZTzcSs,True,"14, 17",6,32.2,16,...,MC-001455-raxH,Not Detected,NaN,PT-NkIUY4,Internal,DMX,NaN,C106,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
99,ACH-000226,PT-ktST3K,PT-ktST3K,MC-000226-ZYgM,STR-0bxXWT,False,"15, 17","9.3, 8",31.3,"12, 14",...,MC-000226-ZYgM,NaN,NaN,PT-ktST3K,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [21]:
columns_to_check = ['model_id', 'patient_id', 'patient_id.1', 'model_condition_id', 'model_condition_id.1']
nan_df = df[df[columns_to_check].isnull().any(axis=1)][columns_to_check]

In [22]:
nan_df

     model_id patient_id patient_id.1 model_condition_id model_condition_id.1
147       NaN        NaN    PT-vEZ2Aw                NaN                  NaN
174       NaN        NaN    PT-xfVhgW                NaN                  NaN
186       NaN        NaN    PT-pktZZ0                NaN                  NaN
198       NaN        NaN    PT-Mi0cKz                NaN                  NaN
280       NaN        NaN    PT-j60QIc                NaN                  NaN
...       ...        ...          ...                ...                  ...
4301      NaN        NaN    PT-ulmNPq                NaN                  NaN
4303      NaN        NaN    PT-SQ6fkx                NaN                  NaN
4306      NaN        NaN    PT-wbA1oa                NaN                  NaN
4312      NaN        NaN    PT-Er9zxL                NaN                  NaN
4316      NaN        NaN    PT-gEiUjw                NaN                  NaN

[771 rows x 5 columns]

In [23]:
pellet_match_to_parental_value_counts = df['percentage_match_to_parental'].value_counts()
pellet_match_to_parental_value_counts

percentage_match_to_parental
1.0000    203
0.8000     58
0.8571     45
0.8333     43
0.8108     32
         ...
0.6197      1
0.8846      1
0.5455      1
0.6471      1
0.9630      1
Name: count, Length: 211, dtype: int64

In [24]:
df.sort_values(by=['percentage_match_to_parental'])

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
2596,ACH-002972,PT-dkXZB1,PT-dkXZB1,MC-002972-ufj0,STR-M9brIl,False,"18, 15","7, 9.3",NaN,"10, 16",...,MC-002972-ufj0,NaN,NaN,PT-dkXZB1,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
956,ACH-000851,PT-klVvXs,PT-klVvXs,MC-000851-DKZr,STR-KQkaFR,False,15,9,NaN,16,...,MC-000851-DKZr,NaN,NaN,PT-klVvXs,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
397,ACH-000851,PT-klVvXs,PT-klVvXs,MC-000851-DKZr,STR-ewqd2d,False,15,9,NaN,16,...,MC-000851-DKZr,NaN,NaN,PT-klVvXs,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:00:12.659835+00:00,2024-04-10 18:00:12.659835+00:00
3496,ACH-002972,PT-dkXZB1,PT-dkXZB1,MC-002972-J9L5,STR-4OcMg0,False,"15, 18","7, 9.3",NaN,"10, 16",...,MC-002972-J9L5,NaN,NaN,PT-dkXZB1,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:05:52.038659+00:00,2024-04-10 18:05:52.038659+00:00
615,ACH-002972,PT-dkXZB1,PT-dkXZB1,MC-002972-J9L5,STR-kljJ6z,False,"15, 18","9.3, 7",NaN,"10, 16",...,MC-002972-J9L5,NaN,NaN,PT-dkXZB1,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4310,ACH-001949,PT-FxQs1g,PT-FxQs1g,MC-001949-eXWn,STR-VS3EPQ,True,15,7,"28, 32.2","16, 19",...,MC-001949-eXWn,Not Detected,NaN,PT-FxQs1g,Internal,DMX,NaN,MA-MEL-46,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4311,ACH-001828,PT-mexpVs,PT-mexpVs,MC-001828-se6f,STR-cvnKFq,True,"15, 17","6, 9.3","30, 32","16, 18",...,MC-001828-se6f,NaN,NaN,PT-mexpVs,External,Cellosaurus,NaN,NaN,2024-06-10 20:40:08.448261+00:00,2024-06-10 20:40:08.448280+00:00
4312,NaN,NaN,PT-Er9zxL,NaN,STR-DWrBck,True,"18, 19",7,"31, 33.2","13, 18",...,NaN,NaN,NaN,PT-Er9zxL,External,Cellosaurus,NaN,NaN,2024-06-14 21:06:05.759451+00:00,2024-06-14 21:06:05.759480+00:00
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,15,"7, 9",NaN,"16, 17",...,MC-000167-lZrU,NaN,NaN,PT-ghtKEp,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:01:31.405005+00:00,2024-04-10 18:01:31.405005+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [25]:
pellet_match_to_parental_value_counts.sort_values(ascending=True)

percentage_match_to_parental
0.9630      1
0.9474      1
0.9388      1
0.3590      1
0.9851      1
         ...
0.8108     32
0.8333     43
0.8571     45
0.8000     58
1.0000    203
Name: count, Length: 211, dtype: int64

In [26]:
pellet_match_to_parental_value_counts

percentage_match_to_parental
1.0000    203
0.8000     58
0.8571     45
0.8333     43
0.8108     32
         ...
0.6197      1
0.8846      1
0.5455      1
0.6471      1
0.9630      1
Name: count, Length: 211, dtype: int64

In [27]:
pellet_match_to_parental_value_counts = pellet_match_to_parental_value_counts.to_frame()
pellet_match_to_parental_value_counts

                              count
percentage_match_to_parental
1.0000                          203
0.8000                           58
0.8571                           45
0.8333                           43
0.8108                           32
...                             ...
0.6197                            1
0.8846                            1
0.5455                            1
0.6471                            1
0.9630                            1

[211 rows x 1 columns]

In [28]:
pellet_match_to_parental_value_counts

                              count
percentage_match_to_parental
1.0000                          203
0.8000                           58
0.8571                           45
0.8333                           43
0.8108                           32
...                             ...
0.6197                            1
0.8846                            1
0.5455                            1
0.6471                            1
0.9630                            1

[211 rows x 1 columns]

In [29]:
pellet_match_to_parental_value_counts.sort_values(by='percentage_match_to_parental').head(35)

                              count
percentage_match_to_parental
0.0513                            1
0.0870                            2
0.1364                            2
0.1538                            1
0.1600                            1
0.1667                            1
0.1778                            2
0.1875                            1
0.1951                            1
0.2083                            1
0.2105                            1
0.2273                            2
0.2326                            7
0.2381                            2
0.2553                            1
0.2632                            2
0.2667                            1
0.2857                            1
0.2927                            2
0.2979                            1
0.3000                            3
0.3019                            1
0.3111                            1
0.3265                            1
0.3333                            1
0.3404                            6
0.3415                            1
0.3448                            1
0.3500                            1
0.3509                            1
0.3556                            1
0.3590                            1
0.3673                            1
0.3830                            1
0.3902                            2

In [30]:
df.columns

Index(['model_id', 'patient_id', 'patient_id.1', 'model_condition_id', 'id',
       'is_reference', 'd3s1358', 'th01', 'd21s11', 'd18s51', 'penta_e',
       'd5s818', 'd13s317', 'd7s820', 'd16s539', 'csf1po', 'penta_d', 'vwa',
       'd8s1179', 'tpox', 'fga', 'pellet_creation_date',
       'percentage_match_to_parental', 'lab_corp_spec_nbr',
       'lab_corp_case_nbr', 'comments', 'amelogenin', 'model_condition_id.1',
       'mouse', 'mycoplasma', 'patient_id.2', 'source', 'source_group',
       'pellet_submitted_date', 'sample_reference', 'created_at',
       'updated_at'],
      dtype='object')

In [31]:
#original df
df_percentage_match_to_parental = df[['model_id', 'patient_id', 'patient_id.1', 'model_condition_id', 'id',
       'is_reference','percentage_match_to_parental', 'patient_id.2', 'sample_reference']]
df_percentage_match_to_parental.sort_values(by='percentage_match_to_parental').head(35)

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,percentage_match_to_parental,patient_id.2,sample_reference
2596,ACH-002972,PT-dkXZB1,PT-dkXZB1,MC-002972-ufj0,STR-M9brIl,False,0.0513,PT-dkXZB1,NaN
956,ACH-000851,PT-klVvXs,PT-klVvXs,MC-000851-DKZr,STR-KQkaFR,False,0.0870,PT-klVvXs,NaN
397,ACH-000851,PT-klVvXs,PT-klVvXs,MC-000851-DKZr,STR-ewqd2d,False,0.0870,PT-klVvXs,NaN
3496,ACH-002972,PT-dkXZB1,PT-dkXZB1,MC-002972-J9L5,STR-4OcMg0,False,0.1364,PT-dkXZB1,NaN
615,ACH-002972,PT-dkXZB1,PT-dkXZB1,MC-002972-J9L5,STR-kljJ6z,False,0.1364,PT-dkXZB1,NaN
245,ACH-001428,PT-XQvpFQ,PT-KI2QoM,MC-001428-h8A5,STR-CjLjoz,False,0.1538,PT-KI2QoM,NaN
3300,ACH-002869,PT-sBk6t4,PT-sBk6t4,MC-002869-6t9f,STR-oyTlc9,False,0.1600,PT-sBk6t4,ACH-002869-PreO (p19)
730,ACH-003046,PT-TZOWm8,PT-TZOWm8,MC-003046-ean0,STR-0tABRc,False,0.1667,PT-TZOWm8,NaN
3242,ACH-002972,PT-dkXZB1,PT-dkXZB1,MC-002972-ufj0,STR-goPjQk,False,0.1778,PT-dkXZB1,972-PreO (p6)
66,ACH-000093,PT-X8PfQy,PT-X8PfQy,MC-000093-IB96,STR-Lw91ng,False,0.1778,PT-X8PfQy,NaN
436,ACH-001652,PT-IwYShD,PT-IwYShD,MC-001652-lAQg,STR-UUu375,False,0.1875,PT-IwYShD,NaN
2633,ACH-002416,PT-ItI5Wt,PT-ItI5Wt,MC-002416-8TT5,STR-FbDKAP,False,0.1951,PT-ItI5Wt,NaN
393,ACH-000093,PT-X8PfQy,PT-X8PfQy,MC-000093-IB96,STR-0z9fBq,False,0.2083,PT-X8PfQy,NaN
2302,ACH-003045,PT-TZOWm8,PT-TZOWm8,MC-003045-FTS6,STR-sq3GQG,False,0.2105,PT-TZOWm8,NaN
514,ACH-002734,PT-VvDCYY,PT-VvDCYY,MC-002734-kaoo,STR-gaT2ZL,False,0.2273,PT-VvDCYY,ACH-002734-PreS (p4)
1058,ACH-002734,PT-VvDCYY,PT-VvDCYY,MC-002734-kaoo,STR-2H7bIk,False,0.2273,PT-VvDCYY,734-PostS
3232,ACH-003045,PT-TZOWm8,PT-TZOWm8,MC-003045-FTS6,STR-liQl5q,False,0.2326,PT-TZOWm8,ACH-003045-Pre-H1 (p23)
2298,ACH-002949,PT-3w3Rm1,PT-3w3Rm1,MC-002949-YNXN,STR-OcPF3A,False,0.2326,PT-3w3Rm1,NaN
1768,ACH-003045,PT-TZOWm8,PT-TZOWm8,MC-003045-FTS6,STR-bhixRJ,False,0.2326,PT-TZOWm8,ACH-003045-Post-H1 (p26)
1770,ACH-003045,PT-TZOWm8,PT-TZOWm8,MC-003045-FTS6,STR-X47fhG,False,0.2326,PT-TZOWm8,ACH-003045-C12 C12 FP (p21)
1784,ACH-003045,PT-TZOWm8,PT-TZOWm8,MC-003045-FTS6,STR-EtAMVz,False,0.2326,PT-TZOWm8,ACH-003045-C12 (p32)
2679,ACH-003045,PT-TZOWm8,PT-TZOWm8,MC-003045-FTS6,STR-88EOSk,False,0.2326,PT-TZOWm8,ACH-003045-PreO (p12)
3453,ACH-003056,PT-l5NEzY,PT-l5NEzY,MC-003056-dMDj,STR-BpiKku,False,0.2326,PT-l5NEzY,ACH-003056-C12 (p35)
1737,ACH-003041,PT-81s9h1,PT-81s9h1,MC-003041-7ddT,STR-sQyYuq,False,0.2381,PT-81s9h1,ACH-003041-C12 (p21)
1771,ACH-003046,PT-TZOWm8,PT-TZOWm8,MC-003046-ean0,STR-Y9WDs2,False,0.2381,PT-TZOWm8,ACH-003046-Pre-O (p12)
1574,ACH-002949,PT-3w3Rm1,PT-3w3Rm1,MC-002949-YNXN,STR-NrwSe0,False,0.2553,PT-3w3Rm1,949-PreO (p9)
1973,ACH-003093,PT-mG2brs,PT-mG2brs,MC-003093-jlhL,STR-qI2eDX,False,0.2632,PT-mG2brs,ACH-003093 FP (pX+5)
1985,ACH-003093,PT-mG2brs,PT-mG2brs,MC-003093-jlhL,STR-yHWHCQ,False,0.2632,PT-mG2brs,ACH-003093-Pre-O (px+1)
642,ACH-001655,PT-yc0xLp,PT-yc0xLp,MC-001655-jaAf,STR-S99t8X,False,0.2667,PT-yc0xLp,NaN
1333,NaN,NaN,PT-BIG8te,NaN,STR-Ka0nUB,False,0.2857,PT-BIG8te,TC-71_LUA-3240
3972,ACH-000424,PT-BIG8te,PT-BIG8te,MC-000424-VRxU,STR-LxdwHI,False,0.2927,PT-BIG8te,NaN
2913,ACH-000424,PT-BIG8te,PT-BIG8te,MC-000424-VRxU,STR-APScZh,False,0.2927,PT-BIG8te,NaN
2441,ACH-002936,PT-v13Wpd,PT-v13Wpd,MC-002936-EOFj,STR-UoTict,False,0.2979,PT-v13Wpd,NaN
3806,ACH-002737,PT-FxhBrM,PT-FxhBrM,MC-002737-O4V6,STR-1rhSTh,False,0.3000,PT-FxhBrM,NaN
3791,ACH-002737,PT-FxhBrM,PT-FxhBrM,MC-002737-O4V6,STR-ab8aWU,False,0.3000,PT-FxhBrM,NaN

In [32]:
df

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-001345,PT-sGJOXH,PT-sGJOXH,MC-001345-KbHX,STR-fs0TWY,True,"16, 18","7, 9.3","29, 30","12, 13",...,MC-001345-KbHX,NaN,NaN,PT-sGJOXH,Internal,DMX,NaN,GP5 D,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,ACH-001293,PT-nHktCj,PT-nHktCj,MC-001293-ZkY1,STR-hQB6tQ,True,"14, 16",6,"29, 32.2","15, 17",...,MC-001293-ZkY1,NaN,NaN,PT-nHktCj,Internal,DMX,NaN,CHLA-200,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2,ACH-001111,PT-glFbpW,PT-glFbpW,MC-001111-jbYD,STR-Y48Vnl,False,"18, 17",9.3,NaN,16,...,MC-001111-jbYD,NaN,NaN,PT-glFbpW,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3,ACH-001338,PT-cvCz0R,PT-cvCz0R,MC-001338-wh8o,STR-nv1QA1,True,16,"9, 9.3","28, 29","15, 18",...,MC-001338-wh8o,NaN,NaN,PT-cvCz0R,Internal,DMX,NaN,CHP-134,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4,ACH-001353,PT-dEG8Km,PT-dEG8Km,MC-001353-5EnB,STR-p7M1AR,True,"17, 18","9, 9.3","30, 31",14,...,MC-001353-5EnB,NaN,NaN,PT-dEG8Km,Internal,DMX,NaN,JOPACA-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,15,"7, 9",NaN,"16, 17",...,MC-000167-lZrU,NaN,NaN,PT-ghtKEp,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:01:31.405005+00:00,2024-04-10 18:01:31.405005+00:00
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,15,6,29,13,...,MC-002964-0orR,Not Detected,NaN,PT-zfPfIU,Internal,Minerva,2022-06-16,ACH-002964-Post-H1 (p22),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4317,ACH-001794,PT-jDDO2a,PT-jDDO2a,MC-001794-IAqD,STR-ugSbzY,False,NaN,"8, 9",NaN,"12, 17",...,MC-001794-IAqD,NaN,NaN,PT-jDDO2a,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:40:45.030904+00:00,2024-06-13 16:40:45.030904+00:00
4318,ACH-002067,PT-EcVEYs,PT-EcVEYs,MC-002067-S9Nv,STR-UI09f9,False,15,6,31.3,14,...,MC-002067-S9Nv,NaN,NaN,PT-EcVEYs,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

# redo patient id search - not accounting for nan,                                ✓
# redo percentage matching use cutoff of .75                                      ✓
# Count of STRs with percentage_match_to_parental >=0.75 and <0.75    ✓         
# Check Patient IDs that do not match (from model condition and str)  ✓
# Count of reference STRs (reference_check)
# Count of total STRs uploaded 


### match sample id (new df- STR) to sample-sequence

# Count and list
# Count of total reference STRs
# Count of patients with reference STRs but no non-reference STRs to match
# Only reference, no non-reference
# Count and list of patients with non-reference STRs but no reference STR
# Only samples, no reference
# Split count between WGS Inferred and all other source groups
# Count of STRs of each source_group (WGS Inferred, Minerva, PRISM, etc)
# Count of source internal vs external STR            
# Count and list of profiles with no model condition IDs

In [34]:
# from above
df_patient_id_diff

[0       False
 1       False
 2       False
 3       False
 4       False
         ...
 4314    False
 4315    False
 4316     True
 4317    False
 4318    False
 Length: 4319, dtype: bool]

In [35]:
df_ignore_nan_all_patient_ids = df[(df['patient_id'].notna() & df['patient_id.1'].notna() & df['patient_id.2'].notna()) &
            ((df['patient_id'] != df['patient_id.1']) | (df['patient_id'] != df['patient_id.2']))]
df_ignore_nan_all_patient_ids

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
60,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-0baHbR,True,15,"7, 9.3",28,17,...,MC-002745-Nzrl,NaN,NaN,PT-SAJ1yK,Internal,Minerva,2021-03-19,ACH-002745-PreS (p5),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
187,ACH-001619,PT-xi87qq,PT-X8PfQy,MC-001619-IR6I,STR-GoBiim,True,15,"7, 9.3","28, 29","16, 19",...,MC-001619-IR6I,NaN,NaN,PT-X8PfQy,Internal,DMX,NaN,OCUG-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
245,ACH-001428,PT-XQvpFQ,PT-KI2QoM,MC-001428-h8A5,STR-CjLjoz,False,15,9,31.3,12,...,MC-001428-h8A5,NaN,NaN,PT-KI2QoM,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
659,ACH-002504,PT-RlnJiH,PT-K30rcU,MC-002504-DStn,STR-fIWITm,True,18,9.3,31,12,...,MC-002504-DStn,Not Detected,NaN,PT-K30rcU,Internal,DMX,NaN,U-CH17S (p5),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
664,ACH-001828,PT-mexpVs,PT-w2P6lJ,MC-001828-se6f,STR-JX028F,False,"15, 17","6, 9.3",31.3,"18, 16",...,MC-001828-se6f,NaN,NaN,PT-w2P6lJ,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
722,ACH-002464,PT-JWRsco,PT-ml8vcL,MC-002464-Ywbh,STR-P7Lv0T,False,"15, 16",9,"31, 32.2","14, 16",...,MC-002464-Ywbh,Not Detected,NaN,PT-ml8vcL,Internal,DMX,NaN,RPE1-ss6 (p6),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
734,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-lJI7zr,False,15,"7, 9.3",30.3,17,...,MC-002745-Nzrl,NaN,NaN,PT-SAJ1yK,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
743,ACH-002463,PT-JWRsco,PT-ml8vcL,MC-002463-lGXh,STR-GipHgv,False,"15, 16",9,"31, 32.2","14, 16",...,MC-002463-lGXh,Not Detected,NaN,PT-ml8vcL,Internal,DMX,NaN,RPE1-ss77,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
761,ACH-002467,PT-JWRsco,PT-ml8vcL,MC-002467-V3Px,STR-VBFdYX,False,"15, 16",9,"31, 32.2","14, 16",...,MC-002467-V3Px,Not Detected,NaN,PT-ml8vcL,Internal,DMX,NaN,RPE1-ss51,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
916,ACH-000602,PT-JpUzYa,PT-T0am5q,MC-000602-uVHZ,STR-432ym9,True,"16, 19","6, 8","30, 32.2","15, 20",...,MC-000602-uVHZ,NaN,NaN,PT-T0am5q,Internal,DMX,NaN,M-07e (p2),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1461,ACH-003017,PT-cqv92I,PT-BarPtO,MC-003017-iLhU,STR-Bv7v3q,True,"15, 16","6, 8, 9.3","28, 29, 32","13, 15, 17",...,MC-003017-iLhU,NaN,Not Detected,PT-BarPtO,Internal,Achilles,NaN,EAHY926,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1480,ACH-003201,PT-tY34fU,PT-fAGg4e,MC-003201-2p67,STR-nDNUWi,True,"15, 16",9,"29, 32.2, 33.2","10, 11",...,MC-003201-2p67,NaN,Not Detected,PT-fAGg4e,Internal,Achilles,NaN,C42,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1493,ACH-003077,PT-O15HlH,PT-QraDm6,MC-003077-naD1,STR-iq3kI6,False,"14, 15",9.3,31,13,...,MC-003077-naD1,NaN,Not Detected,PT-QraDm6,Internal,Achilles,NaN,VCaPEnzR,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1516,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-DSrIPu,False,15,"7, 9.3",28,17,...,MC-002745-Nzrl,Not Detected,NaN,PT-SAJ1yK,Internal,Minerva,2021-07-29,745-PreS-2 (p5),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1523,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-Xnhwrg,False,15,"7, 9.3",28,17,...,MC-002745-Nzrl,Not Detected,NaN,PT-SAJ1yK,Internal,Minerva,2023-04-20,ACH-002745-Post-C9 (2745 Dc9 fp) (p33),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1527,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-rBiekk,False,15,"7, 9.3",28,17,...,MC-002745-Nzrl,NaN,NaN,PT-SAJ1yK,Internal,Minerva,2021-05-11,745-PreO (p22),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1734,ACH-002463,PT-JWRsco,PT-ml8vcL,MC-002463-lGXh,STR-fNSY96,False,"15, 16",9,NaN,"16, 14",...,MC-002463-lGXh,NaN,NaN,PT-ml8vcL,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1812,ACH-003077,PT-O15HlH,PT-QraDm6,MC-003077-8tk9,STR-Fsr4da,True,"14, 15",9.3,31,13,...,MC-003077-8tk9,Not Detected,NaN,PT-QraDm6,Internal,Minerva,2023-02-22,VCAPEnzR FP/OM (pX+3),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1840,ACH-003330,PT-MXzfiQ,PT-N3H3AI,MC-003330-1sEE,STR-Ubh77O,False,"16, 17",9.3,31.2,21,...,MC-003330-1sEE,Positive,NaN,PT-N3H3AI,Internal,Minerva,2023-03-20,ACH-003330 Post-C12 (3330 C12 FP) (p12),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2075,ACH-002466,PT-JWRsco,PT-ml8vcL,MC-002466-lZtp,STR-90Gpc5,True,"15, 16",9,"31, 32.2","14, 16",...,MC-002466-lZtp,Not Detected,NaN,PT-ml8vcL,Internal,DMX,NaN,RPE1-ss111 (p6),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2155,ACH-003330,PT-MXzfiQ,PT-N3H3AI,MC-003330-1sEE,STR-3q1VyV,True,"16, 17",9.3,31.2,21,...,MC-003330-1sEE,Positive,NaN,PT-N3H3AI,Internal,Minerva,2023-02-22,PDM-246 Pre-O (PDM-246) (p10),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2217,ACH-002462,PT-JWRsco,PT-ml8vcL,MC-002462-9MWA,STR-gUr2pr,False,"15, 16",9,"31, 32.2","14, 16",...,MC-002462-9MWA,Not Detected,NaN,PT-ml8vcL,Internal,DMX,NaN,RPE1-ss48,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2373,ACH-002464,PT-JWRsco,PT-ml8vcL,MC-002464-Ywbh,STR-O7Zkdh,False,"15, 16",9,NaN,"16, 14",...,MC-002464-Ywbh,NaN,NaN,PT-ml8vcL,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2465,ACH-003017,PT-cqv92I,PT-BarPtO,MC-003017-iLhU,STR-t1YuSS,False,"15, 16","9.3, 8","31.3, 30.3","15, 17",...,MC-003017-iLhU,NaN,NaN,PT-BarPtO,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2556,ACH-001828,PT-mexpVs,PT-w2P6lJ,MC-001828-se6f,STR-LF3wi1,True,"15, 17","6, 9.3","30, 32","16, 18",...,MC-001828-se6f,NaN,NaN,PT-w2P6lJ,Internal,DMX,NaN,HCC1739 BL,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2573,ACH-001619,PT-xi87qq,PT-X8PfQy,MC-001619-IR6I,STR-KoNkaD,False,15,"7, 9.3",31.3,19,...,MC-001619-IR6I,NaN,NaN,PT-X8PfQy,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3019,ACH-003589,PT-iT1Q1S,PT-sgB9Cp,MC-003589-ujhg,STR-EoV8QU,False,15,"7, 9.3",NaN,"14, 17",...,MC-003589-ujhg,NaN,NaN,PT-sgB9Cp,Internal,WGS Inferred,NaN,NaN,2024-05-01 16:49:09.428324+00:00,2024-05-01 16:49:09.428324+00:00
3145,ACH-002462,PT-JWRsco,PT-ml8vcL,MC-002462-9MWA,STR-fdObP9,False,"15, 16",9,NaN,"14, 16",...,MC-002462-9MWA,NaN,NaN,PT-ml8vcL,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:04:02.811124+00:00,2024-04-10 18:04:02.811124+00:00
3167,ACH-002465,PT-JWRsco,PT-ml8vcL,MC-002465-1j4t,STR-kgdura,False,"15, 16",9,"31, 32.2","14, 16",...,MC-002465-1j4t,Not Detected,NaN,PT-ml8vcL,Internal,DMX,NaN,RPE1-ss119,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3190,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-mbv0SF,False,15,"7, 9.3",28,17,...,MC-002745-Nzrl,NaN,NaN,PT-SAJ1yK,Internal,Minerva,2021-05-11,745-PostS,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3259,ACH-000602,PT-JpUzYa,PT-T0am5q,MC-000602-uVHZ,STR-I3NX3v,False,"19, 16","6, 8",NaN,"15, 20",...,MC-000602-uVHZ,NaN,NaN,PT-T0am5q,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3279,ACH-002465,PT-JWRsco,PT-ml8vcL,MC-002465-1j4t,STR-LnGVbs,False,"15, 16",9,NaN,"16, 14",...,MC-002465-1j4t,NaN,NaN,PT-ml8vcL,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3680,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-zuKGSI,False,15,"7, 9.3",28,NaN,...,MC-002745-Nzrl,Not Detected,NaN,PT-SAJ1yK,Internal,Minerva,2022-06-16,ACH-002745-Pre-O-new (p31),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3938,ACH-002504,PT-RlnJiH,PT-K30rcU,MC-002504-DStn,STR-BFWKFc,False,18,9.3,32.3,12,...,MC-002504-DStn,NaN,NaN,PT-K30rcU,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4037,ACH-002462,PT-JWRsco,PT-ml8vcL,MC-002462-9MWA,STR-wywL8k,False,"15, 16",9,NaN,"16, 14",...,MC-002462-9MWA,NaN,NaN,PT-ml8vcL,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4183,ACH-002467,PT-JWRsco,PT-ml8vcL,MC-002467-V3Px,STR-R1WVcJ,False,"15, 16",9,NaN,"14, 16",...,MC-002467-V3Px,NaN,NaN,PT-ml8vcL,Internal,WGS Inferred,NaN,NaN,2024-05-24 16:49:01.499039+00:00,2024-05-24 16:49:01.499039+00:00

In [36]:
#save
df_ignore_nan_all_patient_ids.to_csv('patient_model_id_dsicrepancies.csv')

In [37]:
patient_id1_and_patient_id2 = df[df['patient_id.1'] != df['patient_id.2']]
patient_id1_and_patient_id2

Empty DataFrame
Columns: [model_id, patient_id, patient_id.1, model_condition_id, id, is_reference, d3s1358, th01, d21s11, d18s51, penta_e, d5s818, d13s317, d7s820, d16s539, csf1po, penta_d, vwa, d8s1179, tpox, fga, pellet_creation_date, percentage_match_to_parental, lab_corp_spec_nbr, lab_corp_case_nbr, comments, amelogenin, model_condition_id.1, mouse, mycoplasma, patient_id.2, source, source_group, pellet_submitted_date, sample_reference, created_at, updated_at]
Index: []

[0 rows x 37 columns]

In [38]:
patient_id_and_patient_id2 = df[df['patient_id'] != df['patient_id.2']]
patient_id_and_patient_id2

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
60,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-0baHbR,True,15,"7, 9.3",28,17,...,MC-002745-Nzrl,NaN,NaN,PT-SAJ1yK,Internal,Minerva,2021-03-19,ACH-002745-PreS (p5),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
147,NaN,NaN,PT-vEZ2Aw,NaN,STR-wfpoXW,False,"15, 16","6, 9.3","27, 30","14, 17",...,NaN,NaN,NaN,PT-vEZ2Aw,Internal,PRISM,NaN,C8166_LUA-4915,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
174,NaN,NaN,PT-xfVhgW,NaN,STR-0aaUxd,False,"14, 17","6, 9",30,"17, 19",...,NaN,Not Detected,NaN,PT-xfVhgW,Internal,PRISM,NaN,TE 617.T_LUA-4867,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
186,NaN,NaN,PT-pktZZ0,NaN,STR-0C5Man,True,18,9,31.2,14,...,NaN,Not Detected,NaN,PT-pktZZ0,Internal,Mnemosyne,2022-07-14,ACH-002815-Pre-O (p6),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
187,ACH-001619,PT-xi87qq,PT-X8PfQy,MC-001619-IR6I,STR-GoBiim,True,15,"7, 9.3","28, 29","16, 19",...,MC-001619-IR6I,NaN,NaN,PT-X8PfQy,Internal,DMX,NaN,OCUG-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4301,NaN,NaN,PT-ulmNPq,NaN,STR-zvYQrx,False,"16, 19, 20, 21","7, 8","28, 30, 31","12, 13, 15, 16",...,NaN,NaN,NaN,PT-ulmNPq,Internal,PRISM,NaN,SNU-C4_LUA-3577,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4303,NaN,NaN,PT-SQ6fkx,NaN,STR-shrrBt,False,17,"6, 9","29, 32.2","14, 21",...,NaN,NaN,NaN,PT-SQ6fkx,Internal,PRISM,NaN,BC-3C_LUA-3398,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4306,NaN,NaN,PT-wbA1oa,NaN,STR-yRIqBE,False,15,"7, 8","30, 32.1",12,...,NaN,NaN,NaN,PT-wbA1oa,Internal,PRISM,NaN,KMRC-1_LUA-3564,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4312,NaN,NaN,PT-Er9zxL,NaN,STR-DWrBck,True,"18, 19",7,"31, 33.2","13, 18",...,NaN,NaN,NaN,PT-Er9zxL,External,Cellosaurus,NaN,NaN,2024-06-14 21:06:05.759451+00:00,2024-06-14 21:06:05.759480+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [39]:
patient_id_and_patient_id1 = df[df['patient_id'] != df['patient_id.1']]
patient_id_and_patient_id1

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
60,ACH-002745,PT-urO852,PT-SAJ1yK,MC-002745-Nzrl,STR-0baHbR,True,15,"7, 9.3",28,17,...,MC-002745-Nzrl,NaN,NaN,PT-SAJ1yK,Internal,Minerva,2021-03-19,ACH-002745-PreS (p5),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
147,NaN,NaN,PT-vEZ2Aw,NaN,STR-wfpoXW,False,"15, 16","6, 9.3","27, 30","14, 17",...,NaN,NaN,NaN,PT-vEZ2Aw,Internal,PRISM,NaN,C8166_LUA-4915,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
174,NaN,NaN,PT-xfVhgW,NaN,STR-0aaUxd,False,"14, 17","6, 9",30,"17, 19",...,NaN,Not Detected,NaN,PT-xfVhgW,Internal,PRISM,NaN,TE 617.T_LUA-4867,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
186,NaN,NaN,PT-pktZZ0,NaN,STR-0C5Man,True,18,9,31.2,14,...,NaN,Not Detected,NaN,PT-pktZZ0,Internal,Mnemosyne,2022-07-14,ACH-002815-Pre-O (p6),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
187,ACH-001619,PT-xi87qq,PT-X8PfQy,MC-001619-IR6I,STR-GoBiim,True,15,"7, 9.3","28, 29","16, 19",...,MC-001619-IR6I,NaN,NaN,PT-X8PfQy,Internal,DMX,NaN,OCUG-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4301,NaN,NaN,PT-ulmNPq,NaN,STR-zvYQrx,False,"16, 19, 20, 21","7, 8","28, 30, 31","12, 13, 15, 16",...,NaN,NaN,NaN,PT-ulmNPq,Internal,PRISM,NaN,SNU-C4_LUA-3577,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4303,NaN,NaN,PT-SQ6fkx,NaN,STR-shrrBt,False,17,"6, 9","29, 32.2","14, 21",...,NaN,NaN,NaN,PT-SQ6fkx,Internal,PRISM,NaN,BC-3C_LUA-3398,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4306,NaN,NaN,PT-wbA1oa,NaN,STR-yRIqBE,False,15,"7, 8","30, 32.1",12,...,NaN,NaN,NaN,PT-wbA1oa,Internal,PRISM,NaN,KMRC-1_LUA-3564,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4312,NaN,NaN,PT-Er9zxL,NaN,STR-DWrBck,True,"18, 19",7,"31, 33.2","13, 18",...,NaN,NaN,NaN,PT-Er9zxL,External,Cellosaurus,NaN,NaN,2024-06-14 21:06:05.759451+00:00,2024-06-14 21:06:05.759480+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [40]:
df_under75 = df_percentage_match_to_parental[df_percentage_match_to_parental['percentage_match_to_parental'] < 0.75]
df_under75

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,percentage_match_to_parental,patient_id.2,sample_reference
25,ACH-002459,PT-czDcsE,PT-czDcsE,MC-002459-cRI0,STR-ywDfHZ,False,0.7442,PT-czDcsE,NaN
28,ACH-001401,PT-7a0mgm,PT-7a0mgm,MC-001401-l6Fd,STR-o1zkEG,False,0.7222,PT-7a0mgm,NaN
42,ACH-001973,PT-oJTeSY,PT-oJTeSY,MC-001973-ILv6,STR-FrA73B,False,0.7317,PT-oJTeSY,NaN
66,ACH-000093,PT-X8PfQy,PT-X8PfQy,MC-000093-IB96,STR-Lw91ng,False,0.1778,PT-X8PfQy,NaN
134,ACH-000201,PT-EY60tR,PT-EY60tR,MC-000201-rUIL,STR-0gVv3Y,False,0.3913,PT-EY60tR,NaN
...,...,...,...,...,...,...,...,...,...
4240,ACH-002835,PT-8JiqNz,PT-8JiqNz,MC-002835-H1W8,STR-bDo3Bw,False,0.4074,PT-8JiqNz,NaN
4247,ACH-001838,PT-cRrqep,PT-cRrqep,MC-001838-4mqk,STR-HDIDlk,False,0.7368,PT-cRrqep,NaN
4261,NaN,NaN,PT-EwSb3E,NaN,STR-iSabqL,False,0.3590,PT-EwSb3E,BT559
4270,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-S9K0,STR-u9FoCx,False,0.7368,PT-zfPfIU,NaN
4274,ACH-002506,PT-9iph8g,PT-9iph8g,MC-002506-aqq2,STR-kcM7Kb,False,0.6452,PT-9iph8g,ACH-002506 Post-C12 (2506 C12) (p25)

In [41]:
df_above75 = df_percentage_match_to_parental[df_percentage_match_to_parental['percentage_match_to_parental'] >= 0.75]
df_above75

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,percentage_match_to_parental,patient_id.2,sample_reference
11,ACH-002046,PT-SKC9qY,PT-SKC9qY,MC-002046-oaX8,STR-7FEfGM,False,0.8696,PT-SKC9qY,NaN
12,ACH-001465,PT-7eVJ3u,PT-7eVJ3u,MC-001465-V7hs,STR-BzNhKk,False,0.9362,PT-7eVJ3u,CHLA136--HumagneCD-RepA-P3(D21)
13,ACH-001465,PT-7eVJ3u,PT-7eVJ3u,MC-001465-V7hs,STR-cv3IyE,False,0.9362,PT-7eVJ3u,CHLA136-HumagneCD-RepB-P3(D21)
14,ACH-003183,PT-BqidXH,PT-BqidXH,MC-003183-dkwm,STR-gCZxPK,False,0.7568,PT-BqidXH,ACH-003183
24,ACH-002074,PT-kivgrW,PT-kivgrW,MC-002074-ehWg,STR-kVSoTN,False,0.7742,PT-kivgrW,NaN
...,...,...,...,...,...,...,...,...,...
4309,ACH-002954,PT-piVxVb,PT-piVxVb,MC-002954-yG88,STR-tmYIe3,False,1.0000,PT-piVxVb,ACH-002954-Post-C12 (p23)
4313,ACH-003047,PT-ts2yuC,PT-ts2yuC,MC-003047-mwE5,STR-TzxQjU,False,0.8000,PT-ts2yuC,ACH-003047 Pre Opt FP2 (p14)
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,0.9189,PT-zfPfIU,ACH-002964-Post-H1 (p22)
4317,ACH-001794,PT-jDDO2a,PT-jDDO2a,MC-001794-IAqD,STR-ugSbzY,False,0.7619,PT-jDDO2a,NaN
4318,ACH-002067,PT-EcVEYs,PT-EcVEYs,MC-002067-S9Nv,STR-UI09f9,False,0.8000,PT-EcVEYs,NaN

In [42]:
df['is_reference'].value_counts()

is_reference
False    3276
True     1043
Name: count, dtype: int64

In [43]:
df['id'].value_counts()

id
STR-fs0TWY    1
STR-o8eAeP    1
STR-fCV6A0    1
STR-HrgofM    1
STR-A1CqH3    1
             ..
STR-b4UUqL    1
STR-PZgR2a    1
STR-RmitIO    1
STR-fKBoYC    1
STR-UI09f9    1
Name: count, Length: 4319, dtype: int64

In [44]:
df

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-001345,PT-sGJOXH,PT-sGJOXH,MC-001345-KbHX,STR-fs0TWY,True,"16, 18","7, 9.3","29, 30","12, 13",...,MC-001345-KbHX,NaN,NaN,PT-sGJOXH,Internal,DMX,NaN,GP5 D,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,ACH-001293,PT-nHktCj,PT-nHktCj,MC-001293-ZkY1,STR-hQB6tQ,True,"14, 16",6,"29, 32.2","15, 17",...,MC-001293-ZkY1,NaN,NaN,PT-nHktCj,Internal,DMX,NaN,CHLA-200,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2,ACH-001111,PT-glFbpW,PT-glFbpW,MC-001111-jbYD,STR-Y48Vnl,False,"18, 17",9.3,NaN,16,...,MC-001111-jbYD,NaN,NaN,PT-glFbpW,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3,ACH-001338,PT-cvCz0R,PT-cvCz0R,MC-001338-wh8o,STR-nv1QA1,True,16,"9, 9.3","28, 29","15, 18",...,MC-001338-wh8o,NaN,NaN,PT-cvCz0R,Internal,DMX,NaN,CHP-134,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4,ACH-001353,PT-dEG8Km,PT-dEG8Km,MC-001353-5EnB,STR-p7M1AR,True,"17, 18","9, 9.3","30, 31",14,...,MC-001353-5EnB,NaN,NaN,PT-dEG8Km,Internal,DMX,NaN,JOPACA-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,15,"7, 9",NaN,"16, 17",...,MC-000167-lZrU,NaN,NaN,PT-ghtKEp,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:01:31.405005+00:00,2024-04-10 18:01:31.405005+00:00
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,15,6,29,13,...,MC-002964-0orR,Not Detected,NaN,PT-zfPfIU,Internal,Minerva,2022-06-16,ACH-002964-Post-H1 (p22),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4317,ACH-001794,PT-jDDO2a,PT-jDDO2a,MC-001794-IAqD,STR-ugSbzY,False,NaN,"8, 9",NaN,"12, 17",...,MC-001794-IAqD,NaN,NaN,PT-jDDO2a,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:40:45.030904+00:00,2024-06-13 16:40:45.030904+00:00
4318,ACH-002067,PT-EcVEYs,PT-EcVEYs,MC-002067-S9Nv,STR-UI09f9,False,15,6,31.3,14,...,MC-002067-S9Nv,NaN,NaN,PT-EcVEYs,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [45]:
df['source'].value_counts()

source
Internal    4247
External      72
Name: count, dtype: int64

In [46]:
df['source_group'].value_counts()

source_group
WGS Inferred                2125
DMX                          783
PRISM                        718
Minerva                      452
Mnemosyne                    135
GPP                           40
Achilles                      26
Oslo University Hospital      23
Cellosaurus                   13
CCLF                           1
Name: count, dtype: int64

In [47]:
counts = df.groupby('patient_id')['is_reference'].value_counts()
counts = counts.reset_index(name='count')
counts

     patient_id  is_reference  count
0     PT-00UDx5         False      3
1     PT-00UDx5          True      1
2     PT-01q6LP          True      1
3     PT-03AcoW         False      2
4     PT-03AcoW          True      1
...         ...           ...    ...
2637  PT-zwxgMM          True      1
2638  PT-zx0MVs          True      1
2639  PT-zy2Tek         False      1
2640  PT-zy2Tek          True      1
2641  PT-zzULgh          True      1

[2642 rows x 3 columns]

In [48]:
ref_counts = df.groupby(['patient_id', 'is_reference']).size().unstack(fill_value=0)
ref_counts.to_csv('ref_counts.csv')
ref_counts.head(50)

is_reference  False  True
patient_id
PT-00UDx5         3      1
PT-01q6LP         0      1
PT-03AcoW         2      1
PT-04HLfu         1      1
PT-0531Uw         1      1
PT-05dldv         1      0
PT-05hA76         1      1
PT-0Ds3by         1      0
PT-0E9rgp         2      0
PT-0F4qCF         2      0
PT-0Fp6tq         2      0
PT-0GisSs         0      1
PT-0GrZ0k         2      0
PT-0H6Zc0         1      0
PT-0MsFyj         1      1
PT-0RBdNq         2      0
PT-0UOmyW         1      0
PT-0VWXIm         1      0
PT-0ZDLSk         5      1
PT-0a2F5a         3      1
PT-0fXDWz         1      0
PT-0hCGTm         2      0
PT-0hMOxQ         1      0
PT-0lPf2W         1      1
PT-0lpZdv         1      1
PT-0mdkef         2      0
PT-0o7FOB         2      1
PT-0uFhp8         1      0
PT-0uXvN6         0      1
PT-0woxaX         1      0
PT-0yqjae         1      1
PT-0yrZJC         2      0
PT-0zEk9y         0      1
PT-1559gB         2      0
PT-1BkfPG         2      1
PT-1DyLm0         1      0
PT-1EAB3W         1      1
PT-1I8hCi         1      0
PT-1Ii4Q3         0      1
PT-1IphRN         1      1
PT-1JVU53         3      1
PT-1JhWBd         1      0
PT-1M8cz3         2      1
PT-1PHTgt         2      0
PT-1PVhNW         1      1
PT-1QXwef         1      0
PT-1Qm9m0         1      1
PT-1Sf7Sz         1      1
PT-1TshCj         1      0
PT-1UiNjR         1      1

In [49]:
type(ref_counts)

pandas.core.frame.DataFrame

In [50]:
ref_counts.columns

Index([False, True], dtype='bool', name='is_reference')

In [51]:
#pt with refs no sampple
ref_counts.columns = ref_counts.columns.astype(str)
ref_only = ref_counts[(ref_counts['False'] == 0) & (ref_counts['True'] == 1)]
ref_only.to_csv('pt_ref_only_no_sample.csv')
ref_only

is_reference  False  True
patient_id
PT-01q6LP         0     1
PT-0GisSs         0     1
PT-0uXvN6         0     1
PT-0zEk9y         0     1
PT-1Ii4Q3         0     1
...             ...   ...
PT-zAmHjA         0     1
PT-zQwaRW         0     1
PT-zXsYg6         0     1
PT-zx0MVs         0     1
PT-zzULgh         0     1

[264 rows x 2 columns]

In [83]:
#sample str no ref str
ref_counts.columns = ref_counts.columns.astype(str)
no_refs = ref_counts[(ref_counts['False'] >= 1) & (ref_counts['True'] == 0)]
no_refs.to_csv('str_with_no_refs.csv')
no_refs

is_reference  False  True
patient_id
PT-05dldv         1     0
PT-0Ds3by         1     0
PT-0E9rgp         2     0
PT-0F4qCF         2     0
PT-0Fp6tq         2     0
...             ...   ...
PT-zjdwU2         1     0
PT-zlBs5P         1     0
PT-zqsQMh         1     0
PT-zrYGap         1     0
PT-zshCzw         1     0

[886 rows x 2 columns]

In [53]:
df

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-001345,PT-sGJOXH,PT-sGJOXH,MC-001345-KbHX,STR-fs0TWY,True,"16, 18","7, 9.3","29, 30","12, 13",...,MC-001345-KbHX,NaN,NaN,PT-sGJOXH,Internal,DMX,NaN,GP5 D,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,ACH-001293,PT-nHktCj,PT-nHktCj,MC-001293-ZkY1,STR-hQB6tQ,True,"14, 16",6,"29, 32.2","15, 17",...,MC-001293-ZkY1,NaN,NaN,PT-nHktCj,Internal,DMX,NaN,CHLA-200,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2,ACH-001111,PT-glFbpW,PT-glFbpW,MC-001111-jbYD,STR-Y48Vnl,False,"18, 17",9.3,NaN,16,...,MC-001111-jbYD,NaN,NaN,PT-glFbpW,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3,ACH-001338,PT-cvCz0R,PT-cvCz0R,MC-001338-wh8o,STR-nv1QA1,True,16,"9, 9.3","28, 29","15, 18",...,MC-001338-wh8o,NaN,NaN,PT-cvCz0R,Internal,DMX,NaN,CHP-134,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4,ACH-001353,PT-dEG8Km,PT-dEG8Km,MC-001353-5EnB,STR-p7M1AR,True,"17, 18","9, 9.3","30, 31",14,...,MC-001353-5EnB,NaN,NaN,PT-dEG8Km,Internal,DMX,NaN,JOPACA-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,15,"7, 9",NaN,"16, 17",...,MC-000167-lZrU,NaN,NaN,PT-ghtKEp,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:01:31.405005+00:00,2024-04-10 18:01:31.405005+00:00
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,15,6,29,13,...,MC-002964-0orR,Not Detected,NaN,PT-zfPfIU,Internal,Minerva,2022-06-16,ACH-002964-Post-H1 (p22),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4317,ACH-001794,PT-jDDO2a,PT-jDDO2a,MC-001794-IAqD,STR-ugSbzY,False,NaN,"8, 9",NaN,"12, 17",...,MC-001794-IAqD,NaN,NaN,PT-jDDO2a,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:40:45.030904+00:00,2024-06-13 16:40:45.030904+00:00
4318,ACH-002067,PT-EcVEYs,PT-EcVEYs,MC-002067-S9Nv,STR-UI09f9,False,15,6,31.3,14,...,MC-002067-S9Nv,NaN,NaN,PT-EcVEYs,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [54]:
df

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-001345,PT-sGJOXH,PT-sGJOXH,MC-001345-KbHX,STR-fs0TWY,True,"16, 18","7, 9.3","29, 30","12, 13",...,MC-001345-KbHX,NaN,NaN,PT-sGJOXH,Internal,DMX,NaN,GP5 D,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,ACH-001293,PT-nHktCj,PT-nHktCj,MC-001293-ZkY1,STR-hQB6tQ,True,"14, 16",6,"29, 32.2","15, 17",...,MC-001293-ZkY1,NaN,NaN,PT-nHktCj,Internal,DMX,NaN,CHLA-200,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
2,ACH-001111,PT-glFbpW,PT-glFbpW,MC-001111-jbYD,STR-Y48Vnl,False,"18, 17",9.3,NaN,16,...,MC-001111-jbYD,NaN,NaN,PT-glFbpW,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3,ACH-001338,PT-cvCz0R,PT-cvCz0R,MC-001338-wh8o,STR-nv1QA1,True,16,"9, 9.3","28, 29","15, 18",...,MC-001338-wh8o,NaN,NaN,PT-cvCz0R,Internal,DMX,NaN,CHP-134,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4,ACH-001353,PT-dEG8Km,PT-dEG8Km,MC-001353-5EnB,STR-p7M1AR,True,"17, 18","9, 9.3","30, 31",14,...,MC-001353-5EnB,NaN,NaN,PT-dEG8Km,Internal,DMX,NaN,JOPACA-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,ACH-000167,PT-ghtKEp,PT-ghtKEp,MC-000167-lZrU,STR-vTNufH,False,15,"7, 9",NaN,"16, 17",...,MC-000167-lZrU,NaN,NaN,PT-ghtKEp,Internal,WGS Inferred,NaN,NaN,2024-04-10 18:01:31.405005+00:00,2024-04-10 18:01:31.405005+00:00
4315,ACH-002964,PT-zfPfIU,PT-zfPfIU,MC-002964-0orR,STR-UGcenx,False,15,6,29,13,...,MC-002964-0orR,Not Detected,NaN,PT-zfPfIU,Internal,Minerva,2022-06-16,ACH-002964-Post-H1 (p22),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4317,ACH-001794,PT-jDDO2a,PT-jDDO2a,MC-001794-IAqD,STR-ugSbzY,False,NaN,"8, 9",NaN,"12, 17",...,MC-001794-IAqD,NaN,NaN,PT-jDDO2a,Internal,WGS Inferred,NaN,NaN,2024-06-13 16:40:45.030904+00:00,2024-06-13 16:40:45.030904+00:00
4318,ACH-002067,PT-EcVEYs,PT-EcVEYs,MC-002067-S9Nv,STR-UI09f9,False,15,6,31.3,14,...,MC-002067-S9Nv,NaN,NaN,PT-EcVEYs,Internal,WGS Inferred,NaN,NaN,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [55]:
ref_only = ref_counts.loc[(ref_counts['True'] == 1) & (ref_counts['False'] == 0)]
ref_only

is_reference  False  True
patient_id
PT-01q6LP         0     1
PT-0GisSs         0     1
PT-0uXvN6         0     1
PT-0zEk9y         0     1
PT-1Ii4Q3         0     1
...             ...   ...
PT-zAmHjA         0     1
PT-zQwaRW         0     1
PT-zXsYg6         0     1
PT-zx0MVs         0     1
PT-zzULgh         0     1

[264 rows x 2 columns]

In [56]:
ref_only = ref_counts[(ref_counts['True'] == 1) & (ref_counts['False'] == 0)]
ref_only

is_reference  False  True
patient_id
PT-01q6LP         0     1
PT-0GisSs         0     1
PT-0uXvN6         0     1
PT-0zEk9y         0     1
PT-1Ii4Q3         0     1
...             ...   ...
PT-zAmHjA         0     1
PT-zQwaRW         0     1
PT-zXsYg6         0     1
PT-zx0MVs         0     1
PT-zzULgh         0     1

[264 rows x 2 columns]

In [57]:
#cant eliminate each
unique_patient_ids = counts['patient_id'].unique()
filtered_counts_ref = counts[(counts['patient_id'].isin(unique_patient_ids)) & (counts['is_reference'] == True)]
filtered_counts_ref

     patient_id  is_reference  count
1     PT-00UDx5          True      1
2     PT-01q6LP          True      1
4     PT-03AcoW          True      1
6     PT-04HLfu          True      1
7     PT-0531Uw          True      1
...         ...           ...    ...
2635  PT-zuTmVR          True      1
2637  PT-zwxgMM          True      1
2638  PT-zx0MVs          True      1
2640  PT-zy2Tek          True      1
2641  PT-zzULgh          True      1

[1010 rows x 3 columns]

In [58]:
##create list of pt_id, then filter using original df - then count orofile per patient

In [59]:
#no work
#unique_patient_ids = counts['patient_id'].unique()
filtered_counts = counts[(counts['patient_id'].isin(unique_patient_ids)) & (counts['is_reference'] == False)]
filtered_counts

     patient_id  is_reference  count
0     PT-00UDx5         False      3
3     PT-03AcoW         False      2
5     PT-04HLfu         False      1
8     PT-0531Uw         False      1
9     PT-05dldv         False      1
...         ...           ...    ...
2632  PT-zrYGap         False      1
2633  PT-zshCzw         False      1
2634  PT-zuTmVR         False      3
2636  PT-zwxgMM         False      3
2639  PT-zy2Tek         False      1

[1632 rows x 3 columns]

In [60]:
filtered_counts = counts[counts['is_reference'] == True]

# Extract unique patient_id that have 'True' as is_reference
patient_ids_with_true_reference = filtered_counts['patient_id'].unique()
df_filtered = pd.DataFrame(patient_ids_with_true_reference, columns=['patient_id'])
df_filtered

     patient_id
0     PT-00UDx5
1     PT-01q6LP
2     PT-03AcoW
3     PT-04HLfu
4     PT-0531Uw
...         ...
1005  PT-zuTmVR
1006  PT-zwxgMM
1007  PT-zx0MVs
1008  PT-zy2Tek
1009  PT-zzULgh

[1010 rows x 1 columns]

In [61]:
reference_only = df[df['is_reference']]
reference_only

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
0,ACH-001345,PT-sGJOXH,PT-sGJOXH,MC-001345-KbHX,STR-fs0TWY,True,"16, 18","7, 9.3","29, 30","12, 13",...,MC-001345-KbHX,NaN,NaN,PT-sGJOXH,Internal,DMX,NaN,GP5 D,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
1,ACH-001293,PT-nHktCj,PT-nHktCj,MC-001293-ZkY1,STR-hQB6tQ,True,"14, 16",6,"29, 32.2","15, 17",...,MC-001293-ZkY1,NaN,NaN,PT-nHktCj,Internal,DMX,NaN,CHLA-200,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
3,ACH-001338,PT-cvCz0R,PT-cvCz0R,MC-001338-wh8o,STR-nv1QA1,True,16,"9, 9.3","28, 29","15, 18",...,MC-001338-wh8o,NaN,NaN,PT-cvCz0R,Internal,DMX,NaN,CHP-134,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4,ACH-001353,PT-dEG8Km,PT-dEG8Km,MC-001353-5EnB,STR-p7M1AR,True,"17, 18","9, 9.3","30, 31",14,...,MC-001353-5EnB,NaN,NaN,PT-dEG8Km,Internal,DMX,NaN,JOPACA-1,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
5,ACH-001037,PT-XYdNvp,PT-XYdNvp,MC-001037-y3GW,STR-PLNOXp,True,"16, 18",7,"29, 30","13, 15",...,MC-001037-y3GW,NaN,NaN,PT-XYdNvp,Internal,DMX,NaN,CMK-86,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4302,ACH-002677,PT-6AFvnc,PT-6AFvnc,MC-002677-Kddq,STR-ZXxHdo,True,"15, 16","6, 9.3",30,"11, 17",...,MC-002677-Kddq,NaN,NaN,PT-6AFvnc,Internal,DMX,NaN,U-2946,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4305,ACH-002946,PT-HryOAg,PT-HryOAg,MC-002946-4pvi,STR-XTpKMS,True,"14, 15","9, 9.3","27, 32.2","16, 19",...,MC-002946-4pvi,NaN,Not Detected,PT-HryOAg,Internal,DMX,NaN,UKE-1 (p2),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4310,ACH-001949,PT-FxQs1g,PT-FxQs1g,MC-001949-eXWn,STR-VS3EPQ,True,15,7,"28, 32.2","16, 19",...,MC-001949-eXWn,Not Detected,NaN,PT-FxQs1g,Internal,DMX,NaN,MA-MEL-46,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4311,ACH-001828,PT-mexpVs,PT-mexpVs,MC-001828-se6f,STR-cvnKFq,True,"15, 17","6, 9.3","30, 32","16, 18",...,MC-001828-se6f,NaN,NaN,PT-mexpVs,External,Cellosaurus,NaN,NaN,2024-06-10 20:40:08.448261+00:00,2024-06-10 20:40:08.448280+00:00
4312,NaN,NaN,PT-Er9zxL,NaN,STR-DWrBck,True,"18, 19",7,"31, 33.2","13, 18",...,NaN,NaN,NaN,PT-Er9zxL,External,Cellosaurus,NaN,NaN,2024-06-14 21:06:05.759451+00:00,2024-06-14 21:06:05.759480+00:00

In [62]:
          
##### Count and list of profiles with no model condition IDs

In [63]:
ref_only = df[df['is_reference']]
non_ref = ref_only.groupby('patient_id')['is_reference'].count()
pt_with_ref = non_ref[non_ref == ref_only.groupby('patient_id').size()]

In [64]:
pt_with_ref

patient_id
PT-00UDx5    1
PT-01q6LP    1
PT-03AcoW    1
PT-04HLfu    1
PT-0531Uw    1
            ..
PT-zuTmVR    1
PT-zwxgMM    1
PT-zx0MVs    1
PT-zy2Tek    1
PT-zzULgh    1
Name: is_reference, Length: 1010, dtype: int64

In [65]:
non_ref2 = df[~df['is_reference']]
ref_ct = non_ref2 .groupby('patient_id')['is_reference'].count()
pt_without_ref = ref_ct[ref_ct == non_ref2 .groupby('patient_id').size()]
pt_without_ref

patient_id
PT-00UDx5    3
PT-03AcoW    2
PT-04HLfu    1
PT-0531Uw    1
PT-05dldv    1
            ..
PT-zrYGap    1
PT-zshCzw    1
PT-zuTmVR    3
PT-zwxgMM    3
PT-zy2Tek    1
Name: is_reference, Length: 1632, dtype: int64

In [66]:
#show source group
missing_model_cond_id = df[df['model_condition_id'].isna()]
missing_model_cond_id

,model_id,patient_id,patient_id.1,model_condition_id,id,is_reference,d3s1358,th01,d21s11,d18s51,...,model_condition_id.1,mouse,mycoplasma,patient_id.2,source,source_group,pellet_submitted_date,sample_reference,created_at,updated_at
147,NaN,NaN,PT-vEZ2Aw,NaN,STR-wfpoXW,False,"15, 16","6, 9.3","27, 30","14, 17",...,NaN,NaN,NaN,PT-vEZ2Aw,Internal,PRISM,NaN,C8166_LUA-4915,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
174,NaN,NaN,PT-xfVhgW,NaN,STR-0aaUxd,False,"14, 17","6, 9",30,"17, 19",...,NaN,Not Detected,NaN,PT-xfVhgW,Internal,PRISM,NaN,TE 617.T_LUA-4867,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
186,NaN,NaN,PT-pktZZ0,NaN,STR-0C5Man,True,18,9,31.2,14,...,NaN,Not Detected,NaN,PT-pktZZ0,Internal,Mnemosyne,2022-07-14,ACH-002815-Pre-O (p6),2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
198,NaN,NaN,PT-Mi0cKz,NaN,STR-0DiPWv,False,16,6,29,"16, 18",...,NaN,NaN,NaN,PT-Mi0cKz,Internal,PRISM,NaN,T24_LUA-3463,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
280,NaN,NaN,PT-j60QIc,NaN,STR-HoomuX,False,15,9.3,"28, 29, 30","15, 19",...,NaN,Not Detected,NaN,PT-j60QIc,Internal,PRISM,NaN,WM-88_LUA-3105,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4301,NaN,NaN,PT-ulmNPq,NaN,STR-zvYQrx,False,"16, 19, 20, 21","7, 8","28, 30, 31","12, 13, 15, 16",...,NaN,NaN,NaN,PT-ulmNPq,Internal,PRISM,NaN,SNU-C4_LUA-3577,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4303,NaN,NaN,PT-SQ6fkx,NaN,STR-shrrBt,False,17,"6, 9","29, 32.2","14, 21",...,NaN,NaN,NaN,PT-SQ6fkx,Internal,PRISM,NaN,BC-3C_LUA-3398,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4306,NaN,NaN,PT-wbA1oa,NaN,STR-yRIqBE,False,15,"7, 8","30, 32.1",12,...,NaN,NaN,NaN,PT-wbA1oa,Internal,PRISM,NaN,KMRC-1_LUA-3564,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00
4312,NaN,NaN,PT-Er9zxL,NaN,STR-DWrBck,True,"18, 19",7,"31, 33.2","13, 18",...,NaN,NaN,NaN,PT-Er9zxL,External,Cellosaurus,NaN,NaN,2024-06-14 21:06:05.759451+00:00,2024-06-14 21:06:05.759480+00:00
4316,NaN,NaN,PT-gEiUjw,NaN,STR-vWVw0d,False,18,6,"30, 32.2","11, 15",...,NaN,NaN,NaN,PT-gEiUjw,Internal,PRISM,NaN,CAL-78_LUA-3002,2024-04-09 16:00:46.487764+00:00,2024-04-09 16:00:46.668811+00:00

In [67]:
missing_model_cond_id.to_csv('missing_model_cond_id.csv')

In [68]:
sample_str = pd.read_excel('str_batch.xlsx')
sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
3,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

SELECT
p.patient_id "patient_id_patient",
str.id "str_id",
str.patient_id "patient_id_str",
str.model_condition_id "model_condition_id_str",
str.*,
sc.screen_id,
sc.model_condition_id "model_condition_id_screen",
sc.model_condition.model_id "model_condition.model_id_screen",
seq.sequence_id,
seq.screen_id "screen_id_screen_sequence",
FROM str_profile str
FULL OUTER JOIN patient p ON p.patient_id = str.patient_id
FULL OUTER JOIN screen sc ON sc.
FULL OUTER JOIN screen_sequence seq ON seq.

LEFT JOIN model_condition mc ON str.model_condition_id=mc.model_condition_id
LEFT JOIN model m ON m.model_id=mc.model_id

In [69]:
scr = pd.read_csv('screen.csv')
scr.columns
#screen_sq_index cant be pulled from gumbo for verification
#has a sample_id column already

Index(['screen_id', 'previous_screening_id', 'cas_activity',
       'screen_doubling_time', 'screen_start', 'date_completed', 'cdsqc',
       'proposed_internal_release', 'public_release_date',
       'consortium_release_date', 'internal_release_date', 'ibm_release_date',
       'crispr_screen_funding_source', 'deliverables',
       'crispr_screen_deliverables', 'destination_datasets', 'blacklist',
       'blacklist_reason', 'blacklist_expiration_date',
       'puromycin_selection_ug_ml', 'observed_infection_rate',
       'vol_pooled_virus_for_each_well', 'blasticidin_selection_ug_ml',
       'transfected', 'consortium_release_annot', 'ibm_release_annot',
       'internal_release_annot', 'library', 'model_condition_id',
       'public_release_annot', 'sample_id', 'screen_type', 'screener',
       'screener_qc_pass', 'gpp_received_date', 'screen_fail_reason',
       'screen_order_date', 'status_description', 'to_gpp_date', 'status',
       'substatus', 'depmap_priority', 'infection_rate',
       'screen_population_doublings', 'exclude_from_crispr_combined',
       'opt_stage_sent_to_broad', 'comments', 'days_pretreatment',
       'optimization', 'optimization_team', 'optimization_type',
       'pretreatment', 'benchling_id'],
      dtype='object')

In [70]:
seq = pd.read_csv('seq.csv')
seq.columns

Index(['sequence_entry', 'sequence_id', 'previous_arxspan_id', 'screen_id',
       'replicate', 'p_dna_sequence', 'p_dna_batch', 'days', 'files',
       'directory', 'str_result_file', 'str_query_name', 'cds_exclude',
       'cds_seq_qc', 'exclusion_notes', 'screener_exclude', 'snp_fingerprint',
       'str_fingerprint', 'library_subset', 'plate_id', 'str_profile',
       'sequencing_technology', 'comments'],
      dtype='object')

In [71]:
mc = pd.read_csv('model_cond.csv')
mc.columns

Index(['model_condition_id', 'condition_only', 'comments', 'supplements',
       'drug', 'to_gpp', 'freezerpro_uid', 'thaw_date', 'initials_status_pic',
       'source_growth_pattern', 'split_recommendation', 'expansion_issues',
       'expansion_completed_date', 'cell_characteristics', 'cell_format',
       'cell_grouping', 'cell_has_debris', 'cell_shape', 'cell_size',
       'dmx_priority', 'freeze_media', 'model_id', 'parent_model_condition_id',
       'source', 'batch_doubling_time', 'expansion_completed',
       'line_received_for_expansion', 'onboarding_myco_order',
       'onboarding_str_order', 'prism_notes', 'source_doubling_time',
       'expansion_team', 'onboarding_str', 'contaminated',
       'contamination_details', 'passage_number', 'number_vials_available',
       'growth_media', 'plate_coating', 'drug_concentration',
       'measured_survival', 'resistance_mechanism', 'days_with_drug',
       'cell_morphology', 'project'],
      dtype='object')

In [72]:
model = pd.read_csv('model.csv')
model.columns

Index(['model_id', 'patient_id', 'cell_line_name', 'stripped_cell_line_name',
       'date_cell_line_received', 'age', 'converge_id', 'orspid',
       'onboarded_doubling_time', 'source_type', 'sanger_model_id', 'comments',
       'cell_line_ordered_date', 'proposed_deliverable',
       'proposed_release_date', 'registration_complete', 'rrid',
       'depmap_model_type', 'ncit_code', 'ncit_subtype',
       'new_molecular_subtype', 'new_histological_subtype', 'age_category',
       'cell_line_received', 'growth_pattern', 'lineage', 'molecular_subtype',
       'primary_disease', 'primary_or_metastasis', 'sample_collection_site',
       'sex', 'source_detail', 'sub_subtype', 'subtype', 'ancestry',
       'catalog_number', 'ccle_line', 'ccle_name', 'cell_line_aliases',
       'cosmic_id', 'public_comments', 'vendor_link', 'wtsi_master_cell_id',
       'consent_2015', 'geo_loc', 'inferred_ethnicity', 'part_of_prism',
       'stated_race', 'cell_line_in_stock', 'peddep_line', 'peddep_subgroup',
       'derived_outside_us', 'permission_to_release', 'treatment_status',
       'tissue_origin', 'onboarded_media', 'plate_coating',
       'date_first_publication', 'date_model_derived', 'date_shared_in_dbgap',
       'first_publication_link', 'model_data_sharing_comments',
       'model_transfer_comments', 'dbgap', 'model_data_sharing',
       'model_transfer', 'sj_compbio_id', 'model_subtype_features',
       'patient_subtype_features', 'model_derivation_material',
       'treatment_details', 'engineered_model', 'stage',
       'tumor_regression_score', 'hcmi_id', 'patient_resistance',
       'patient_response_score', 'patient_response_score_system',
       'patient_treatment_type', 'patient_tumor_grade', 'primary_diagnosis',
       'staging_system', 'recurrent', 'model_transferred_to_stjude'],
      dtype='object')

In [73]:
Select
seq.sequence_entry "seq_screen_entry", 
seq.cds_seq_qc "seq_cds_seq_qc",
seq.sequence_id "seq_sequence_id",
seq.screen_id "seq_screen_id",
seq.snp_fingerprint "seq.snp_fingerprint",
seq.str_result_file "seq_str_result_file",
seq.str_query_name "seq_str_query_name",
seq.str_profile "seq_str_profile",

scr.screen_id "scr_screen_id", 
scr.previous_screening_id "scr_previous_screening_id",
scr.model_condition_id "scr_model_condition_id",
scr.screener "scr_screener",
scr.library "scr_library",
scr.screen_type "scr_screen_type",
scr.cdsqc "scr_cdsqc",
scr.screener_qc_pass "scr_screener_qc_pass",

mc.model_condition_id "mc_model_condition_id",
mc.model_id "mc_model_id",
mc.parent_model_condition_id "mc_parent_model_condition_id",
mc.source "mc_source",

m.model_id "m_model_id",
m.patient_id "m_patient_id",
m.age "m_age",
m.age_category "m_age_category",
m.sex "m_sex",
m.source_type "m_source",

FROM screen_sequence seq

LEFT JOIN screen scr ON seq.screen_id = scr.screen_id
LEFT JOIN model_condition mc ON scr.model_condition_id = mc.model_condition_id
LEFT JOIN model m ON mc.model_id = m.model_id

SyntaxError: invalid syntax (1738985100.py, line 2)

In [ ]:
#ignore
Select
seq.sequence_entry "seq_screen_entry", 
seq.cds_seq_qc "seq_cds_seq_qc",
seq.sequence_id "seq_sequence_id",
seq.screen_id "seq_screen_id",
seq.snp_fingerprint "seq.snp_fingerprint",
seq.str_result_file "seq_str_result_file",
seq.str_query_name "seq_str_query_name",
seq.str_profile "seq_str_profile",

scr.screen_id "scr_screen_id", 
scr.previous_screening_id "scr_previous_screening_id",
scr.model_condition_id "scr_model_condition_id",
scr.screener "scr_screener",
scr.library "scr_library",
scr.screen_type "scr_screen_type",
scr.cdsqc "scr_cdsqc",
scr.screener_qc_pass "scr_screener_qc_pass",

mc.model_condition_id "mc_model_condition_id",
mc.model_id "mc_model_id",
mc.parent_model_condition_id "mc_parent_model_condition_id",
mc.source "mc_source",

m.model_id "m_model_id",
m.patient_id "m_patient_id",
m.age "m_age",
m.age_category "m_age_category",
m.sex "m_sex",
m.source_type "m_source",
str*

FROM screen_sequence seq

LEFT JOIN screen scr ON seq.screen_id = scr.screen_id
LEFT JOIN model_condition mc ON scr.model_condition_id = mc.model_condition_id
LEFT JOIN model m ON mc.model_id = m.model_id
FULL OUTER JOIN str_profile str ON mc.model_condition_id = str.model_condition_id;

In [2]:
str = pd.read_csv('str2.csv')
str.info()

NameError: name 'pd' is not defined

In [ ]:
pd.set_option('display.max_rows', 25)
str

In [75]:
screens = pd.read_csv('screens.csv')
screens

                          seq_sequence_id   seq_screen_id   scr_screen_id
0     A375-311Cas9-ParalogV2-RepB-P6(D22)  SC-000219.PL01  SC-000219.PL01
1     TE11-311Cas9-ParalogV2-RepB-P6(D21)  SC-000488.PL01  SC-000488.PL01
2      JAR-311Cas9-ParalogV2-RepA-P5(D18)  SC-001529.PL01  SC-001529.PL01
3      JAR-311Cas9-ParalogV2-RepB-P5(D18)  SC-001529.PL01  SC-001529.PL01
4              ACH-003260_CD02_d24_RepA_1  SC-003260.CD02  SC-003260.CD02
...                                   ...             ...             ...
5835                                  NaN             NaN  SC-002643.CD01
5836                                  NaN             NaN  SC-001672.AV01
5837                                  NaN             NaN  SC-002795.CD01
5838                                  NaN             NaN  SC-003061.CD01
5839                                  NaN             NaN  SC-001565.AV01

[5840 rows x 3 columns]

In [77]:
#unique in scr_screen_id
unique_screens = screens['scr_screen_id'].nunique()
unique_screens

2884

In [79]:
#dup list
screen_dup = screens['scr_screen_id'].value_counts()
screen_dup

scr_screen_id
SC-000226.AV01    24
SC-000552.AV01    16
SC-002662.CD01    14
SC-001975.CD01    14
SC-002879.CD01    13
                  ..
SC-000087.GK01     1
SC-001625.AV01     1
SC-002056.CD01     1
SC-001373.AV02     1
SC-001565.AV01     1
Name: count, Length: 2884, dtype: int64

In [6]:
sample_str = pd.read_excel('str_batch.xlsx')
sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
3,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [8]:
screens

NameError: name 'screens' is not defined

In [10]:
seq = pd.read_csv('sequences.csv')
seq

,seq_screen_entry,seq_cds_seq_qc,seq_sequence_id,seq_screen_id,seq.snp_fingerprint,seq_str_result_file,seq_str_query_name,seq_str_profile,scr_screen_id,scr_previous_screening_id,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,4270,NaN,A375-311Cas9-ParalogV2-RepB-P6(D22),SC-000219.PL01,NaN,NaN,NaN,NaN,SC-000219.PL01,ACH-000219/paralog,...,MC-000219-yd7j,ACH-000219,NaN,BROAD,ACH-000219,PT-3FxmoJ,54.0,Adult,Female,ATCC
1,4271,NaN,TE11-311Cas9-ParalogV2-RepB-P6(D21),SC-000488.PL01,NaN,NaN,NaN,NaN,SC-000488.PL01,ACH-000488/paralog,...,MC-000488-sREU,ACH-000488,NaN,BROAD,ACH-000488,PT-wdkGZi,58.0,Adult,Male,RIKEN
2,4272,NaN,JAR-311Cas9-ParalogV2-RepA-P5(D18),SC-001529.PL01,NaN,NaN,NaN,NaN,SC-001529.PL01,ACH-001529/paralog,...,MC-001529-g0Ic,ACH-001529,NaN,BROAD,ACH-001529,PT-RI1Xeu,NaN,Fetus,Male,ATCC
3,4273,NaN,JAR-311Cas9-ParalogV2-RepB-P5(D18),SC-001529.PL01,NaN,NaN,NaN,NaN,SC-001529.PL01,ACH-001529/paralog,...,MC-001529-g0Ic,ACH-001529,NaN,BROAD,ACH-001529,PT-RI1Xeu,NaN,Fetus,Male,ATCC
4,4997,NaN,ACH-003260_CD02_d24_RepA_1,SC-003260.CD02,NaN,NaN,NaN,NaN,SC-003260.CD02,NaN,...,MC-003260-201p,ACH-003260,NaN,BROAD,ACH-003260,PT-aNhCiT,NaN,Adult,NaN,Academic lab
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4775,3400,PASS,HT29_c904R1,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4776,3402,PASS,HT29_c904R3,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4777,3403,PASS,HT29_c905R1,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4778,3427,PASS,IM9_c907R2,SC-002247.KY01,PASS,NaN,NaN,NaN,SC-002247.KY01,NaN,...,MC-002247-hsx5,ACH-002247,NaN,SANGER,ACH-002247,PT-7Xxqhs,NaN,Unknown,Female,Academic lab
4779,3428,PASS,IM9_c907R3,SC-002247.KY01,PASS,NaN,NaN,NaN,SC-002247.KY01,NaN,...,MC-002247-hsx5,ACH-002247,NaN,SANGER,ACH-002247,PT-7Xxqhs,NaN,Unknown,Female,Academic lab

In [12]:
sample_str = pd.read_excel('str_batch.xlsx')
sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
3,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [14]:
#count of sample str to input into db
merged = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
#merged.to_csv('sample_str_draft.csv')
merged

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepA-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepB-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NaN,CX4019414,"15, 18",8,...,MC-003189-aahm,ACH-003189,NaN,BROAD,ACH-003189,PT-eY3uqu,56.0,Adult,Female,Academic lab
524,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
525,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
526,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC
527,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC

In [358]:
#cleaning () and whitespace
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.replace(r'\(.*?\)', '', regex=True)
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.strip()

In [360]:
#rerunning merge
merged = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
#merged.to_csv('sample_str_draft.csv')
merged

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Copy_Sample_ID,Sample_ID,DepMap ID,Case number,D3S1358,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepA-p6,LO68-311cas9-RepA-p6,NaN,CX4009888,"16, 18",...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepB-p6,LO68-311cas9-RepB-p6,NaN,CX4009888,"16, 18",...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,58c,CH157MN,2023-11-01 00:00:00,AL,NaN,CH157MN-Parental-HumagneCD-RepB-P2,CH157MN-Parental-HumagneCD-RepB-P2,NaN,CX4017929,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,58c,CH157MN,2023-11-01 00:00:00,AL,NaN,CH157MN-Parental-HumagneCD-RepB-P4,CH157MN-Parental-HumagneCD-RepB-P4,NaN,CX4017929,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327,58c,NOMO1,2023-11-01 00:00:00,AL,NaN,NOMO1-Parental-HumangeCD-RepA-p2,NOMO1-Parental-HumangeCD-RepA-p2,NaN,CX4017929,"15, 17",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,58c,NOMO1,2023-11-01 00:00:00,AL,NaN,NOMO1-Parental-HumangeCD-RepB-p2,NOMO1-Parental-HumangeCD-RepB-p2,NaN,CX4017929,"15, 17",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,61c,NOMO1,2023-12-13 00:00:00,AL,NaN,NOMO1-Parental-HumangeCD-RepB-p2,NOMO1-Parental-HumangeCD-RepB-p2,NaN,CX4018284,"15, 17",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [362]:
#lowercase and special characters for sampleId
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.replace(r'[^a-zA-Z0-9]', '', regex=True)
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.lower()
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.strip()

In [364]:
#clean seq_sequence_id
seq['seq_sequence_id'] = seq['seq_sequence_id'].str.replace(r'[^a-zA-Z0-9]', '', regex=True)
seq['seq_sequence_id'] = seq['seq_sequence_id'].str.lower()
seq['seq_sequence_id'] = seq['seq_sequence_id'].str.strip()

In [447]:
merged1 = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
#merged.to_csv('sample_str_draft.csv')
merged1

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Copy_Sample_ID,Sample_ID,DepMap ID,Case number,D3S1358,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepA-p6,LO68-311cas9-RepA-p6,NaN,CX4009888,"16, 18",...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepB-p6,LO68-311cas9-RepB-p6,NaN,CX4009888,"16, 18",...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NaN,CX4019414,"15, 18",...,MC-003189-aahm,ACH-003189,NaN,BROAD,ACH-003189,PT-eY3uqu,56.0,Adult,Female,Academic lab
524,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NaN,CX4019414,18,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
525,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NaN,CX4019414,18,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
526,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),NaN,CX4019414,15,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC
527,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),NaN,CX4019414,15,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC

In [368]:
sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Copy_Sample_ID,Sample_ID,DepMap ID,Case number,D3S1358,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,bt12311cas9,NaN,CX4009888,"15, 16",...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,chla06311cas9,NaN,CX4009888,"15, 16",...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,hsq89311cas9repap6,NaN,CX4009888,15,...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
3,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,hsq89311cas9repbp6,NaN,CX4009888,15,...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,kcimoh1311cas9repbp6,NaN,CX4009888,"15, 17",...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),ncih1568311cas9paralogv2repap6,NaN,CX4019483,17,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),ncih1568311cas9paralogv2repbp6,NaN,CX4019483,17,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),panc0203cas9vyparalogv2repap6,NaN,CX4019483,14,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),panc0203cas9vyparalogv2repbp6,NaN,CX4019483,14,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),snuc2acas9vyparalogv2repap4,NaN,CX4019483,13,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [370]:
seq

,seq_screen_entry,seq_cds_seq_qc,seq_sequence_id,seq_screen_id,seq.snp_fingerprint,seq_str_result_file,seq_str_query_name,seq_str_profile,scr_screen_id,scr_previous_screening_id,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,4270,NaN,a375311cas9paralogv2repbp6d22,SC-000219.PL01,NaN,NaN,NaN,NaN,SC-000219.PL01,ACH-000219/paralog,...,MC-000219-yd7j,ACH-000219,NaN,BROAD,ACH-000219,PT-3FxmoJ,54.0,Adult,Female,ATCC
1,4271,NaN,te11311cas9paralogv2repbp6d21,SC-000488.PL01,NaN,NaN,NaN,NaN,SC-000488.PL01,ACH-000488/paralog,...,MC-000488-sREU,ACH-000488,NaN,BROAD,ACH-000488,PT-wdkGZi,58.0,Adult,Male,RIKEN
2,4272,NaN,jar311cas9paralogv2repap5d18,SC-001529.PL01,NaN,NaN,NaN,NaN,SC-001529.PL01,ACH-001529/paralog,...,MC-001529-g0Ic,ACH-001529,NaN,BROAD,ACH-001529,PT-RI1Xeu,NaN,Fetus,Male,ATCC
3,4273,NaN,jar311cas9paralogv2repbp5d18,SC-001529.PL01,NaN,NaN,NaN,NaN,SC-001529.PL01,ACH-001529/paralog,...,MC-001529-g0Ic,ACH-001529,NaN,BROAD,ACH-001529,PT-RI1Xeu,NaN,Fetus,Male,ATCC
4,4997,NaN,ach003260cd02d24repa1,SC-003260.CD02,NaN,NaN,NaN,NaN,SC-003260.CD02,NaN,...,MC-003260-201p,ACH-003260,NaN,BROAD,ACH-003260,PT-aNhCiT,NaN,Adult,NaN,Academic lab
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4775,3400,PASS,ht29c904r1,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4776,3402,PASS,ht29c904r3,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4777,3403,PASS,ht29c905r1,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4778,3427,PASS,im9c907r2,SC-002247.KY01,PASS,NaN,NaN,NaN,SC-002247.KY01,NaN,...,MC-002247-hsx5,ACH-002247,NaN,SANGER,ACH-002247,PT-7Xxqhs,NaN,Unknown,Female,Academic lab
4779,3428,PASS,im9c907r3,SC-002247.KY01,PASS,NaN,NaN,NaN,SC-002247.KY01,NaN,...,MC-002247-hsx5,ACH-002247,NaN,SANGER,ACH-002247,PT-7Xxqhs,NaN,Unknown,Female,Academic lab

In [16]:
#reset vars
seq = pd.read_csv('sequences.csv')
sample_str = pd.read_excel('str_batch.xlsx')

In [18]:
#rerun initial merge
merged1 = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
#merged.to_csv('sample_str_draft.csv')
merged1

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepA-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepB-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NaN,CX4019414,"15, 18",8,...,MC-003189-aahm,ACH-003189,NaN,BROAD,ACH-003189,PT-eY3uqu,56.0,Adult,Female,Academic lab
524,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
525,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
526,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC
527,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC

In [20]:
#extract list of matching Sample_IDs
first_match_sample_ids = pd.DataFrame(merged1['Sample_ID'].unique(), columns=['Sample_ID'])
first_match_sample_ids

                                    Sample_ID
0                       HSQ89-311cas9-RepA-p6
1                       HSQ89-311cas9-RepB-p6
2                        LO68-311cas9-RepA-p6
3                        LO68-311cas9-RepB-p6
4                   RPE1SS119-311Cas9-RepA-p6
..                                        ...
496    NRHLS3-enCas12a-HumagneCD-RepB-P5(D22)
497    NRHOS4-enCas12a-HumagneCD-RepA-P6(D21)
498    NRHOS4-enCas12a-HumagneCD-RepB-P6(D21)
499  UCHCF365-enCas12a-HumagneCD-RepA-P6(D22)
500  UCHCF365-enCas12a-HumagneCD-RepB-P6(D22)

[501 rows x 1 columns]

In [22]:
first_match_sample_ids_all = pd.DataFrame(merged1['Sample_ID'], columns=['Sample_ID'])
first_match_sample_ids_all

                                    Sample_ID
0                       HSQ89-311cas9-RepA-p6
1                       HSQ89-311cas9-RepA-p6
2                       HSQ89-311cas9-RepB-p6
3                        LO68-311cas9-RepA-p6
4                        LO68-311cas9-RepB-p6
..                                        ...
523    NRHLS3-enCas12a-HumagneCD-RepB-P5(D22)
524    NRHOS4-enCas12a-HumagneCD-RepA-P6(D21)
525    NRHOS4-enCas12a-HumagneCD-RepB-P6(D21)
526  UCHCF365-enCas12a-HumagneCD-RepA-P6(D22)
527  UCHCF365-enCas12a-HumagneCD-RepB-P6(D22)

[528 rows x 1 columns]

In [24]:
#shows dupes
first_match_sample_ids_all= first_match_sample_ids_all['Sample_ID'].value_counts(ascending=False)
first_match_sample_ids_all.head(35)

Sample_ID
CCLFNEURO0007T-enCas12a-HumagneC-P3(D21)      4
HSQ89-311cas9-RepA-p6                         2
JHH5-311Cas9-ParalogV2-RepB-P6(D21)           2
SNU1330-311cas9-RepB-p6                       2
SNU1330-311cas9-RepA-p6                       2
SKLMS1-311cas9-RepA-p6                        2
YD15-311Cas9-RepA-P6                          2
M140325-311cas9-RepA-p6                       2
PLCPRF5-311Cas9-ParalogV2-RepB-P6(D22)        2
PLCPRF5-311Cas9-ParalogV2-RepA-P6(D22)        2
SKGT4-311Cas9-ParalogV2-RepB-P6(D22)          2
SKGT4-311Cas9-ParalogV2-RepA-P6(D22)          2
NOMO1-Parental-HumangeCD-RepB-p2              2
RS411-enCas12a-HumagneCD-RepB-P5(D21)         2
CH157MN-Parental-HumagneCD-RepA-P2            2
KE39-311Cas9-ParalogV2-RepA-P4(D21)           2
KE39-311Cas9-ParalogV2-RepB-P4(D21)           2
RH4-311Cas9-ParalogV2-RepB-P6(D21)            2
RL952-311Cas9-ParalogV2-RepA-p6               2
176592-311cas9-RepB-p6                        2
RL952-311Cas9-ParalogV2-RepB-p6               2
SUM190PT-311cas9-RepA-p6                      2
JHH5-311Cas9-ParalogV2-RepA-P6(D21)           2
JVE528-311cas9-RepB-p6                        2
CCLFNEURO0017T-enCas12a-HumagneC-P4(D18)      2
CCLFNEURO0013T-enCas12a-HumagneC-P5(D21)      1
CHLA02ATRT-enCas12a-HumagneCD-RepA-P5(D18)    1
SKM1-enCas12a-HumagneC-P6(D21)                1
SKM1-enCas12a-HumagneD-P6(D21)                1
CCLFNEURO0007T-enCas12a-HumagneC-P2(D15)      1
SNU685-311Cas9-ParalogV2-RepB-P6(D21)         1
SNU685-311Cas9-ParalogV2-RepA-P6(D21)         1
RH4-311Cas9-ParalogV2-RepA-P6(D21)            1
RD-311Cas9-ParalogV2-RepB-P6(D21)             1
RD-311Cas9-ParalogV2-RepA-P6(D21)             1
Name: count, dtype: int64

In [26]:
first_match_sample_ids_allb = pd.DataFrame(merged1['Sample_ID'], columns=['Sample_ID'])
first_match_sample_ids_allb

                                    Sample_ID
0                       HSQ89-311cas9-RepA-p6
1                       HSQ89-311cas9-RepA-p6
2                       HSQ89-311cas9-RepB-p6
3                        LO68-311cas9-RepA-p6
4                        LO68-311cas9-RepB-p6
..                                        ...
523    NRHLS3-enCas12a-HumagneCD-RepB-P5(D22)
524    NRHOS4-enCas12a-HumagneCD-RepA-P6(D21)
525    NRHOS4-enCas12a-HumagneCD-RepB-P6(D21)
526  UCHCF365-enCas12a-HumagneCD-RepA-P6(D22)
527  UCHCF365-enCas12a-HumagneCD-RepB-P6(D22)

[528 rows x 1 columns]

In [31]:
#removing matching sample_id from sample_str
first_filter_sample_str = sample_str[~sample_str['Sample_ID'].isin(first_match_sample_ids_allb)]
first_filter_sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
3,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [33]:
match1 = merged1['Sample_ID']
match1

0                         HSQ89-311cas9-RepA-p6
1                         HSQ89-311cas9-RepA-p6
2                         HSQ89-311cas9-RepB-p6
3                          LO68-311cas9-RepA-p6
4                          LO68-311cas9-RepB-p6
                         ...
523      NRHLS3-enCas12a-HumagneCD-RepB-P5(D22)
524      NRHOS4-enCas12a-HumagneCD-RepA-P6(D21)
525      NRHOS4-enCas12a-HumagneCD-RepB-P6(D21)
526    UCHCF365-enCas12a-HumagneCD-RepA-P6(D22)
527    UCHCF365-enCas12a-HumagneCD-RepB-P6(D22)
Name: Sample_ID, Length: 528, dtype: object

In [35]:
first_match_sample_ids_all.info()

<class 'pandas.core.series.Series'>
Index: 501 entries, CCLFNEURO0007T-enCas12a-HumagneC-P3(D21) to UCHCF365-enCas12a-HumagneCD-RepB-P6(D22)
Series name: count
Non-Null Count  Dtype
--------------  -----
501 non-null    int64
dtypes: int64(1)
memory usage: 7.8+ KB

In [37]:
match1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 528 entries, 0 to 527
Series name: Sample_ID
Non-Null Count  Dtype
--------------  -----
528 non-null    object
dtypes: object(1)
memory usage: 4.3+ KB

In [39]:
#removing matching sample_id from sample_str
#use to combine in the end has the originial column
first_filter_sample_str1 = pd.merge(sample_str, seq[['seq_sequence_id']], left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
first_filter_sample_str1

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse,seq_sequence_id
0,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN,HSQ89-311cas9-RepA-p6
1,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN,HSQ89-311cas9-RepA-p6
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN,HSQ89-311cas9-RepB-p6
3,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepA-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,2024-10-12 00:00:00,2024-10-11 00:00:00,2024-12-14 00:00:00,"17, 18",14,2024-08-11 00:00:00,"20, 22",X,NaN,LO68-311cas9-RepA-p6
4,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepB-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,2024-10-12 00:00:00,2024-10-11 00:00:00,2024-12-14 00:00:00,"17, 18",14,2024-08-11 00:00:00,"20, 22",X,NaN,LO68-311cas9-RepB-p6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NaN,CX4019414,"15, 18",8,...,11,2024-11-12 00:00:00,2024-09-11 00:00:00,17,13,9,"22, 23",X,NaN,NRHLS3-enCas12a-HumagneCD-RepB-P5(D22)
524,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NaN,CX4019414,18,9.3,...,2024-11-13 00:00:00,2024-09-11 00:00:00,2024-12-14 00:00:00,"17, 18","14, 15",8,"22, 23","X, Y",NaN,NRHOS4-enCas12a-HumagneCD-RepA-P6(D21)
525,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NaN,CX4019414,18,9.3,...,2024-11-13 00:00:00,2024-09-11 00:00:00,2024-12-14 00:00:00,"17, 18","14, 15",8,"22, 23","X, Y",NaN,NRHOS4-enCas12a-HumagneCD-RepB-P6(D21)
526,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,2024-12-14 00:00:00,12,12,18,13,2024-08-11 00:00:00,"20, 22","X, Y",NaN,UCHCF365-enCas12a-HumagneCD-RepA-P6(D22)
527,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,2024-12-14 00:00:00,12,12,18,13,2024-08-11 00:00:00,"20, 22","X, Y",NaN,UCHCF365-enCas12a-HumagneCD-RepB-P6(D22)

In [41]:
first_filter_sample_str = sample_str[~sample_str['Sample_ID'].isin(match1)]
first_filter_sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
7,1a,P3HR1,NaN,NaN,NaN,P3HR1-311cas9,NaN,CX4009888,"16, 17",2024-07-09 00:00:00,...,2024-08-10 00:00:00,2024-10-11 00:00:00,2024-10-11 00:00:00,"2.2, 12","15, 19","14, 15",2024-06-08 00:00:00,"23, 24","X, Y",NaN
8,1a,PSS008,NaN,NaN,NaN,PSS008-311cas9,NaN,CX4009888,16,2024-07-09 00:00:00,...,10,2024-09-12 00:00:00,2024-10-12 00:00:00,2024-10-12 00:00:00,"14, 18",2024-10-15 00:00:00,8,"22, 26",X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [43]:
#cleaning up ()
first_filter_sample_str['Sample_ID'] = first_filter_sample_str['Sample_ID'].str.replace(r'\(.*?\)', '', regex=True)
first_filter_sample_str

/var/folders/dw/gtrsn4tx0696w7m9ppcbnysr0000gp/T/ipykernel_63644/4191333392.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_filter_sample_str['Sample_ID'] = first_filter_sample_str['Sample_ID'].str.replace(r'\(.*?\)', '', regex=True)

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
7,1a,P3HR1,NaN,NaN,NaN,P3HR1-311cas9,NaN,CX4009888,"16, 17",2024-07-09 00:00:00,...,2024-08-10 00:00:00,2024-10-11 00:00:00,2024-10-11 00:00:00,"2.2, 12","15, 19","14, 15",2024-06-08 00:00:00,"23, 24","X, Y",NaN
8,1a,PSS008,NaN,NaN,NaN,PSS008-311cas9,NaN,CX4009888,16,2024-07-09 00:00:00,...,10,2024-09-12 00:00:00,2024-10-12 00:00:00,2024-10-12 00:00:00,"14, 18",2024-10-15 00:00:00,8,"22, 26",X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4,NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [45]:
first_filter_sample_str.loc[:, 'Sample_ID'] = first_filter_sample_str['Sample_ID'].str.replace(r'\(.*?\)', '', regex=True)
first_filter_sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
7,1a,P3HR1,NaN,NaN,NaN,P3HR1-311cas9,NaN,CX4009888,"16, 17",2024-07-09 00:00:00,...,2024-08-10 00:00:00,2024-10-11 00:00:00,2024-10-11 00:00:00,"2.2, 12","15, 19","14, 15",2024-06-08 00:00:00,"23, 24","X, Y",NaN
8,1a,PSS008,NaN,NaN,NaN,PSS008-311cas9,NaN,CX4009888,16,2024-07-09 00:00:00,...,10,2024-09-12 00:00:00,2024-10-12 00:00:00,2024-10-12 00:00:00,"14, 18",2024-10-15 00:00:00,8,"22, 26",X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4,NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [47]:
#rerun merge
merged2 = pd.merge(first_filter_sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
merged2

Empty DataFrame
Columns: [Batch Number, Cell Line Name, Date on vial, Tech, Find_Sample_id, Sample_ID, DepMap ID, Case number, D3S1358, TH01, D21S11, D18S51, Penta E, D5S818, D13S317, D7S820, D16S539, CSF1PO, Penta D, vWA, D8S1179, TPOX, FGA, AMEL, Mouse, seq_screen_entry, seq_cds_seq_qc, seq_sequence_id, seq_screen_id, seq.snp_fingerprint, seq_str_result_file, seq_str_query_name, seq_str_profile, scr_screen_id, scr_previous_screening_id, scr_model_condition_id, scr_screener, scr_library, scr_screen_type, scr_cdsqc, scr_screener_qc_pass, mc_model_condition_id, mc_model_id, mc_parent_model_condition_id, mc_source, m_model_id, m_patient_id, m_age, m_age_category, m_sex, m_source]
Index: []

[0 rows x 51 columns]

In [519]:
#rerun merge
merged2 = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
merged2

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepA-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepB-p6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NaN,CX4019414,"15, 18",8,...,MC-003189-aahm,ACH-003189,NaN,BROAD,ACH-003189,PT-eY3uqu,56.0,Adult,Female,Academic lab
524,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
525,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
526,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC
527,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC

In [480]:

merged2 = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
merged2

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Copy_Sample_ID,Sample_ID,DepMap ID,Case number,D3S1358,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepA-p6,LO68-311cas9-RepA-p6,NaN,CX4009888,"16, 18",...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,LO68-311cas9-RepB-p6,LO68-311cas9-RepB-p6,NaN,CX4009888,"16, 18",...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NRHLS3-enCas12a-HumagneCD-RepB-P5(D22),NaN,CX4019414,"15, 18",...,MC-003189-aahm,ACH-003189,NaN,BROAD,ACH-003189,PT-eY3uqu,56.0,Adult,Female,Academic lab
524,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NRHOS4-enCas12a-HumagneCD-RepA-P6(D21),NaN,CX4019414,18,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
525,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NRHOS4-enCas12a-HumagneCD-RepB-P6(D21),NaN,CX4019414,18,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
526,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),UCHCF365-enCas12a-HumagneCD-RepA-P6(D22),NaN,CX4019414,15,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC
527,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),UCHCF365-enCas12a-HumagneCD-RepB-P6(D22),NaN,CX4019414,15,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC

In [436]:
#getting list of matching ids
second_match_sample_ids_all = pd.DataFrame(merged2['Sample_ID'], columns=['Sample_ID'])
second_match_sample_ids_all

                              Sample_ID
0                 HSQ89-311cas9-RepA-p6
1                 HSQ89-311cas9-RepA-p6
2                 HSQ89-311cas9-RepA-p6
3                 HSQ89-311cas9-RepA-p6
4                 HSQ89-311cas9-RepB-p6
..                                  ...
329  CH157MN-Parental-HumagneCD-RepB-P2
330  CH157MN-Parental-HumagneCD-RepB-P4
331    NOMO1-Parental-HumangeCD-RepA-p2
332    NOMO1-Parental-HumangeCD-RepB-p2
333    NOMO1-Parental-HumangeCD-RepB-p2

[334 rows x 1 columns]

In [438]:
#shows dupes
second_match_sample_ids_all= second_match_sample_ids_all['Sample_ID'].value_counts(ascending=False)
second_match_sample_ids_all.head(25)

Sample_ID
HSQ89-311cas9-RepA-p6                 4
M140325-311cas9-RepA-p6               4
CH157MN-Parental-HumagneCD-RepA-P2    2
RL952-311Cas9-ParalogV2-RepB-p6       2
RL952-311Cas9-ParalogV2-RepA-p6       2
JVE528-311cas9-RepB-p6                2
SNU1330-311cas9-RepB-p6               2
SNU1330-311cas9-RepA-p6               2
YD15-311Cas9-RepA-P6                  2
176592-311cas9-RepB-p6                2
SUM190PT-311cas9-RepA-p6              2
SKLMS1-311cas9-RepA-p6                2
NOMO1-Parental-HumangeCD-RepB-p2      2
PSS131R-311cas9-RepA-p6               1
ETCC016-311cas9-RepB-p5               1
ETCC016-311cas9-RepA-p5               1
UPMD1-311cas9-RepB-p6                 1
UPMD1-311cas9-RepA-p6                 1
SKGIIIa-311cas9-RepB-p6               1
SKGIIIa-311cas9-RepA-p6               1
PSS131R-311cas9-RepB-p6               1
NZM42-311cas9-RepB-p6                 1
HMY1-311Cas9-RepB-P6                  1
NZM42-311cas9-RepA-p6                 1
HMVII-311cas9-RepB-p6                 1
Name: count, dtype: int64

In [240]:
#extracting matching id
match2 = merged2['Sample_ID']
match2

0                   HSQ89-311cas9-RepA-p6
1                   HSQ89-311cas9-RepA-p6
2                   HSQ89-311cas9-RepB-p6
3                    LO68-311cas9-RepA-p6
4                    LO68-311cas9-RepB-p6
                      ...
325    CH157MN-Parental-HumagneCD-RepB-P2
326    CH157MN-Parental-HumagneCD-RepB-P4
327      NOMO1-Parental-HumangeCD-RepA-p2
328      NOMO1-Parental-HumangeCD-RepB-p2
329      NOMO1-Parental-HumangeCD-RepB-p2
Name: Sample_ID, Length: 330, dtype: object

In [242]:
second_filter_sample_str = sample_str[~sample_str['Sample_ID'].isin(match2)]
second_filter_sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
7,1a,P3HR1,NaN,NaN,NaN,P3HR1-311cas9,NaN,CX4009888,"16, 17",2024-07-09 00:00:00,...,2024-08-10 00:00:00,2024-10-11 00:00:00,2024-10-11 00:00:00,"2.2, 12","15, 19","14, 15",2024-06-08 00:00:00,"23, 24","X, Y",NaN
8,1a,PSS008,NaN,NaN,NaN,PSS008-311cas9,NaN,CX4009888,16,2024-07-09 00:00:00,...,10,2024-09-12 00:00:00,2024-10-12 00:00:00,2024-10-12 00:00:00,"14, 18",2024-10-15 00:00:00,8,"22, 26",X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4,NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [314]:
#third strip special characters and change caps for sample_str
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.replace(r'[^a-zA-Z0-9]', '', regex=True)
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.lower()
sample_str['Sample_ID'] = sample_str['Sample_ID'].str.strip()

In [316]:
#clean seq_sequence_id
seq['seq_sequence_id'] = seq['seq_sequence_id'].str.replace(r'[^a-zA-Z0-9]', '', regex=True)
seq['seq_sequence_id'] = seq['seq_sequence_id'].str.lower()
seq['seq_sequence_id'] = seq['seq_sequence_id'].str.strip()

In [318]:
#merge
merged3 = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
merged3

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repap6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repap6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repbp6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,lo68311cas9repap6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,lo68311cas9repbp6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,nrhls3encas12ahumagnecdrepbp5d22,NaN,CX4019414,"15, 18",8,...,MC-003189-aahm,ACH-003189,NaN,BROAD,ACH-003189,PT-eY3uqu,56.0,Adult,Female,Academic lab
669,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,nrhos4encas12ahumagnecdrepap6d21,NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
670,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,nrhos4encas12ahumagnecdrepbp6d21,NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
671,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,uchcf365encas12ahumagnecdrepap6d22,NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC
672,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,uchcf365encas12ahumagnecdrepbp6d22,NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC

In [290]:
sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,bt12311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,chla06311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
2,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repap6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
3,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repbp6,NaN,CX4009888,15,"7, 9.3",...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,kcimoh1311cas9repbp6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,ncih1568311cas9paralogv2repap6d22,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,ncih1568311cas9paralogv2repbp6d22,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,panc0203cas9vyparalogv2repap6d26,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,panc0203cas9vyparalogv2repbp6d26,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,snuc2acas9vyparalogv2repap4d22,NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [292]:
seq

,seq_screen_entry,seq_cds_seq_qc,seq_sequence_id,seq_screen_id,seq.snp_fingerprint,seq_str_result_file,seq_str_query_name,seq_str_profile,scr_screen_id,scr_previous_screening_id,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,4270,NaN,a375311cas9paralogv2repbp6d22,SC-000219.PL01,NaN,NaN,NaN,NaN,SC-000219.PL01,ACH-000219/paralog,...,MC-000219-yd7j,ACH-000219,NaN,BROAD,ACH-000219,PT-3FxmoJ,54.0,Adult,Female,ATCC
1,4271,NaN,te11311cas9paralogv2repbp6d21,SC-000488.PL01,NaN,NaN,NaN,NaN,SC-000488.PL01,ACH-000488/paralog,...,MC-000488-sREU,ACH-000488,NaN,BROAD,ACH-000488,PT-wdkGZi,58.0,Adult,Male,RIKEN
2,4272,NaN,jar311cas9paralogv2repap5d18,SC-001529.PL01,NaN,NaN,NaN,NaN,SC-001529.PL01,ACH-001529/paralog,...,MC-001529-g0Ic,ACH-001529,NaN,BROAD,ACH-001529,PT-RI1Xeu,NaN,Fetus,Male,ATCC
3,4273,NaN,jar311cas9paralogv2repbp5d18,SC-001529.PL01,NaN,NaN,NaN,NaN,SC-001529.PL01,ACH-001529/paralog,...,MC-001529-g0Ic,ACH-001529,NaN,BROAD,ACH-001529,PT-RI1Xeu,NaN,Fetus,Male,ATCC
4,4997,NaN,ach003260cd02d24repa1,SC-003260.CD02,NaN,NaN,NaN,NaN,SC-003260.CD02,NaN,...,MC-003260-201p,ACH-003260,NaN,BROAD,ACH-003260,PT-aNhCiT,NaN,Adult,NaN,Academic lab
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4775,3400,PASS,ht29c904r1,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4776,3402,PASS,ht29c904r3,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4777,3403,PASS,ht29c905r1,SC-000552.KY01,PASS,NaN,NaN,NaN,SC-000552.KY01,NaN,...,MC-000552-7gEK,ACH-000552,NaN,SANGER,ACH-000552,PT-sF39aT,44.0,Adult,Female,ATCC
4778,3427,PASS,im9c907r2,SC-002247.KY01,PASS,NaN,NaN,NaN,SC-002247.KY01,NaN,...,MC-002247-hsx5,ACH-002247,NaN,SANGER,ACH-002247,PT-7Xxqhs,NaN,Unknown,Female,Academic lab
4779,3428,PASS,im9c907r3,SC-002247.KY01,PASS,NaN,NaN,NaN,SC-002247.KY01,NaN,...,MC-002247-hsx5,ACH-002247,NaN,SANGER,ACH-002247,PT-7Xxqhs,NaN,Unknown,Female,Academic lab

In [326]:
third_match_sample_ids_all = pd.DataFrame(merged3['Sample_ID'], columns=['Sample_ID'])
third_match_sample_ids_all

                              Sample_ID
0                    hsq89311cas9repap6
1                    hsq89311cas9repap6
2                    hsq89311cas9repbp6
3                     lo68311cas9repap6
4                     lo68311cas9repbp6
..                                  ...
668    nrhls3encas12ahumagnecdrepbp5d22
669    nrhos4encas12ahumagnecdrepap6d21
670    nrhos4encas12ahumagnecdrepbp6d21
671  uchcf365encas12ahumagnecdrepap6d22
672  uchcf365encas12ahumagnecdrepbp6d22

[673 rows x 1 columns]

In [328]:
third_match_sample_ids_all= third_match_sample_ids_all['Sample_ID'].value_counts(ascending=False)
third_match_sample_ids_all.head(60)

Sample_ID
a549h3311cas9avanap6repbdox            4
a549h3311cas9avanap6repadox            4
cclfneuro0007tencas12ahumagnecp3d21    4
yd15311cas9repap6                      4
chla32311cas9repap6                    3
bt12311cas9repbp6                      2
rl952311cas9paralogv2repap6            2
rh4311cas9paralogv2repbp6d21           2
ke39311cas9paralogv2repbp4d21          2
ke39311cas9paralogv2repap4d21          2
jhh5311cas9paralogv2repap6d21          2
jhh5311cas9paralogv2repbp6d21          2
bt12311cas9repap6                      2
bt16311cas9repbp6                      2
skut1311cas9repbp6                     2
pss131r311cas9repbp6                   2
ch157mnparentalhumagnecdrepap2         2
nomo1parentalhumangecdrepbp2           2
m140325311cas9repap6                   2
skgt4311cas9paralogv2repap6d22         2
skgt4311cas9paralogv2repbp6d22         2
plcprf5311cas9paralogv2repap6d22       2
plcprf5311cas9paralogv2repbp6d22       2
rl952311cas9paralogv2repbp6            2
hsq89311cas9repap6                     2
skut1311cas9repap6                     2
mcc13311cas9repap6                     2
176592311cas9repbp6                    2
flo1311cas9repap6                      2
ttc549311cas9repbp6                    2
ttc549311cas9repap6                    2
sudhl10311cas9repap6                   2
flo1311cas9repbp6                      2
sklms1311cas9repap6                    2
sudhl10311cas9repbp6                   2
cclfneuro0017tencas12ahumagnecp4d18    2
hmy1311cas9repap6                      2
hmy1311cas9repbp6                      2
tccpan2encas12asetdp4                  2
sum190pt311cas9repap6                  2
nccmpnst1c1311cas9repbp6               2
st8814311cas9repbp6                    2
rs411encas12ahumagnecdrepbp5d21        2
sudhl1311cas9repap6                    2
mcc13311cas9repbp6                     2
bt16311cas9repap6                      2
jve528311cas9repbp6                    2
lu165311cas9repap6                     2
chla32311cas9repbp6                    2
snu1330311cas9repbp6                   2
snu1330311cas9repap6                   2
skgii311cas9paralogv2repap6d21         1
li7311cas9paralogv2repbp6d22           1
rh4311cas9paralogv2repap6d21           1
h314311cas9repap6                      1
h314311cas9repbp6                      1
jve207encas12asetcrepap6               1
rd311cas9paralogv2repbp6d21            1
rd311cas9paralogv2repap6d21            1
kyse450311cas9paralogv2repbp6d21       1
Name: count, dtype: int64

In [334]:
match3 = merged3['Sample_ID']
match3

0                      hsq89311cas9repap6
1                      hsq89311cas9repap6
2                      hsq89311cas9repbp6
3                       lo68311cas9repap6
4                       lo68311cas9repbp6
                      ...
668      nrhls3encas12ahumagnecdrepbp5d22
669      nrhos4encas12ahumagnecdrepap6d21
670      nrhos4encas12ahumagnecdrepbp6d21
671    uchcf365encas12ahumagnecdrepap6d22
672    uchcf365encas12ahumagnecdrepbp6d22
Name: Sample_ID, Length: 673, dtype: object

In [336]:
#removing matching sample_id from sample_str
third_filter_sample_str = sample_str[~sample_str['Sample_ID'].isin(match3)]
third_filter_sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,bt12311cas9,NaN,CX4009888,"15, 16",2024-07-09 00:00:00,...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,chla06311cas9,NaN,CX4009888,"15, 16",7,...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,kcimoh1311cas9repbp6,NaN,CX4009888,"15, 17",9.3,...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
7,1a,P3HR1,NaN,NaN,NaN,p3hr1311cas9,NaN,CX4009888,"16, 17",2024-07-09 00:00:00,...,2024-08-10 00:00:00,2024-10-11 00:00:00,2024-10-11 00:00:00,"2.2, 12","15, 19","14, 15",2024-06-08 00:00:00,"23, 24","X, Y",NaN
8,1a,PSS008,NaN,NaN,NaN,pss008311cas9,NaN,CX4009888,16,2024-07-09 00:00:00,...,10,2024-09-12 00:00:00,2024-10-12 00:00:00,2024-10-12 00:00:00,"14, 18",2024-10-15 00:00:00,8,"22, 26",X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,ncih1568311cas9paralogv2repap6d22,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,ncih1568311cas9paralogv2repbp6d22,NaN,CX4019483,17,9,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,panc0203cas9vyparalogv2repap6d26,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,panc0203cas9vyparalogv2repbp6d26,NaN,CX4019483,14,6,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,snuc2acas9vyparalogv2repap4d22,NaN,CX4019483,13,9,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [344]:
combined = pd.concat([merged, merged2, merged3], ignore_index=True)
combined

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Sample_ID,DepMap ID,Case number,D3S1358,TH01,...,mc_model_condition_id,mc_model_id,mc_parent_model_condition_id,mc_source,m_model_id,m_patient_id,m_age,m_age_category,m_sex,m_source
0,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repap6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
1,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repap6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
2,1a,HSQ89,NaN,NaN,NaN,hsq89311cas9repbp6,NaN,CX4009888,15,"7, 9.3",...,MC-002044-OqIP,ACH-002044,NaN,BROAD,ACH-002044,PT-v9ccBc,74.0,Adult,Male,RIKEN
3,1a,LO68,NaN,NaN,NaN,lo68311cas9repap6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
4,1a,LO68,NaN,NaN,NaN,lo68311cas9repbp6,NaN,CX4009888,"16, 18",2024-08-09 00:00:00,...,MC-001547-7JIQ,ACH-001547,NaN,BROAD,ACH-001547,PT-xjKkQm,57.0,Adult,Male,Sigma-Aldrich
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1104,72b,NRHLS3,2024-05-16 00:00:00,JK,NaN,nrhls3encas12ahumagnecdrepbp5d22,NaN,CX4019414,"15, 18",8,...,MC-003189-aahm,ACH-003189,NaN,BROAD,ACH-003189,PT-eY3uqu,56.0,Adult,Female,Academic lab
1105,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,nrhos4encas12ahumagnecdrepap6d21,NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
1106,72b,NRHOS4,2024-05-16 00:00:00,JK,NaN,nrhos4encas12ahumagnecdrepbp6d21,NaN,CX4019414,18,9.3,...,MC-003185-gh7b,ACH-003185,NaN,BROAD,ACH-003185,PT-McNlZE,38.0,Adult,Male,Academic lab
1107,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,uchcf365encas12ahumagnecdrepap6d22,NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC
1108,72b,UCHCF365,2024-05-16 00:00:00,JK,NaN,uchcf365encas12ahumagnecdrepbp6d22,NaN,CX4019414,15,2024-06-07 00:00:00,...,MC-003410-erdf,ACH-003410,NaN,BROAD,ACH-003410,PT-Dz7ENW,11.0,Pediatric,Male,ATCC

In [523]:
##reset variables 
seq = pd.read_csv('sequences.csv')
sample_str = pd.read_excel('str_batch.xlsx')

In [526]:
#duplicating column
sample_str['Copy_Sample_ID'] = sample_str['Sample_ID']

In [528]:
sample_str = pd.concat([sample_str.iloc[:, :-1], sample_str.iloc[:, -1:]], axis=1)
sample_str = pd.concat([sample_str.iloc[:, :5], sample_str.iloc[:, -1:], sample_str.iloc[:, 5:-1]], axis=1)
sample_str

,Batch Number,Cell Line Name,Date on vial,Tech,Find_Sample_id,Copy_Sample_ID,Sample_ID,DepMap ID,Case number,D3S1358,...,D7S820,D16S539,CSF1PO,Penta D,vWA,D8S1179,TPOX,FGA,AMEL,Mouse
0,1a,BT12,NaN,NaN,NaN,BT12-311cas9,BT12-311cas9,NaN,CX4009888,"15, 16",...,2024-09-12 00:00:00,2024-11-12 00:00:00,2024-10-12 00:00:00,2024-09-11 00:00:00,"16, 18","13, 15",2024-08-11 00:00:00,22,X,NA*
1,1a,CHLA06,NaN,NaN,NaN,CHLA06-311cas9,CHLA06-311cas9,NaN,CX4009888,"15, 16",...,2024-11-13 00:00:00,2024-11-12 00:00:00,11,2024-10-11 00:00:00,16,"13, 14",12,"24, 25",X,NaN
2,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepA-p6,HSQ89-311cas9-RepA-p6,NaN,CX4009888,15,...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
3,1a,HSQ89,NaN,NaN,NaN,HSQ89-311cas9-RepB-p6,HSQ89-311cas9-RepB-p6,NaN,CX4009888,15,...,2024-12-13 00:00:00,2024-11-12 00:00:00,12,11,"14, 20",2024-12-14 00:00:00,2024-11-12 00:00:00,23,X,NaN
4,1a,KCIMOH1,NaN,NaN,NaN,KCIMOH1-311cas9-RepB-p6,KCIMOH1-311cas9-RepB-p6,NaN,CX4009888,"15, 17",...,2024-10-12 00:00:00,2024-09-10 00:00:00,13,13,"15, 17",2024-12-14 00:00:00,2024-10-11 00:00:00,24,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),NCIH1568-311Cas9-ParalogV2-RepA-P6(D22),NaN,CX4019483,17,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2200,73b,NCIH1568,2024-05-31 00:00:00,JK,NaN,NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),NCIH1568-311Cas9-ParalogV2-RepB-P6(D22),NaN,CX4019483,17,...,2024-08-09 00:00:00,2024-10-12 00:00:00,11,11,"16, 17","13, 14",2024-08-11 00:00:00,23,X,NaN
2201,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),PANC0203-Cas9VY-ParalogV2-RepA-P6(D26),NaN,CX4019483,14,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2202,73b,PANC0203,2024-05-31 00:00:00,JK,NaN,PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),PANC0203-Cas9VY-ParalogV2-RepB-P6(D26),NaN,CX4019483,14,...,2024-09-10 00:00:00,11,2024-11-12 00:00:00,9,17,2024-11-12 00:00:00,2024-09-12 00:00:00,"20, 21",X,NaN
2203,73b,SNUC2A,2024-05-31 00:00:00,JK,NaN,SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),SNUC2A-Cas9VY-ParalogV2-RepA-P4(D22),NaN,CX4019483,13,...,"13, 16",2024-08-09 00:00:00,2014-11-13 00:00:00,10,"15, 19",2024-11-13 00:00:00,8,"20, 22, 23",X,NaN

In [ ]:
merged = pd.merge(sample_str, seq, left_on='Sample_ID', right_on='seq_sequence_id', how='inner')
#merged.to_csv('sample_str_draft.csv')
merged

In [ ]:
sample_str.info()

In [ ]:
merged_df = seq.merge(sample_str[['Sample_ID', 'Find_Sample_id']], left_on='seq_sequence_id', right_on='Sample_ID', how='left')
merged_df

In [ ]:
pd.set_option('display.max_rows', None)
counts7 = merged_df['Find_Sample_id'].values
counts7

In [ ]:
counts8 = merged_df['Find_Sample_id'].tolist()
counts8

In [ ]:
seq

In [ ]:
#numbers off
relevant_columns = seq.columns.tolist()  
merged_relevant = merged_df[relevant_columns]
seq_reset = seq.reset_index(drop=True)
merged_relevant_reset = merged_relevant.reset_index(drop=True)

In [ ]:
differences = merged_relevant_reset.compare(seq_reset, keep_shape=True)
differences

In [ ]:
if 'seq_screen_entry' not in seq.columns or 'seq_screen_entry' not in merged_df.columns:
    raise ValueError("The column 'seq_screen_entry' must exist in both DataFrames.")

merged_comparison = seq.merge(merged_df, on='seq_screen_entry', how='left', suffixes=('_seq', '_merged'))
columns_to_compare = [col for col in merged_df.columns if col != 'seq_screen_entry']

In [ ]:

for col in columns_to_compare:
    if col in seq.columns:  # Ensure the column exists in both DataFrames
        merged_comparison[f'diff_{col}'] = merged_comparison[f'{col}_seq'] != merged_comparison[f'{col}_merged']


differing_rows = merged_comparison[merged_comparison.filter(like='diff_').any(axis=1)]

In [ ]:
differing_rows

In [ ]:
value_counts = merged_df['seq_screen_entry'].value_counts()
value_counts

In [ ]:
value_counts_df = value_counts.reset_index()
value_counts_df.columns = ['seq_screen_entry', 'count']
sorted_value_counts_df = value_counts_df.sort_values(by='seq_screen_entry')
sorted_value_counts_df

In [ ]:
value_counts1 = seq['seq_screen_entry'].value_counts()
value_counts1

In [ ]:
value_counts1 = seq['seq_screen_entry'].value_counts()
value_counts_df1 = value_counts1.reset_index()
value_counts_df1.columns = ['seq_screen_entry', 'count']
sorted_value_counts_df1 = value_counts_df1.sort_values(by='seq_screen_entry')
sorted_value_counts_df1

In [ ]:
#index view - 4804#
merged_df.index

In [ ]:
#find different rows based on col for seq and merged_df

#modify 
def compare_dataframes_on_column(seq, merged_df, seq_screen_entry):
    merged_comparison = seq[[seq_screen_entry]].merge(
        merged_df[[seq_screen_entry]],
        on=seq_screen_entry,
        how='outer'
    )
    merged_comparison['identical'] = merged_comparison[seq_screen_entry].notna() & merged_comparison[seq_screen_entry].notna()
    result_df = merged_comparison[[seq_screen_entry, 'identical']]
    
    return result_df
result = compare_dataframes_on_column(seq, merged_df, 'seq_screen_entry')

result

In [ ]:
def compare_dataframes_on_column(seq, merged_df, seq_screen_entry):
    seq_set = set(seq[seq_screen_entry])
    merged_set = set(merged_df[seq_screen_entry])
    comparison_result = {
        'seq_screen_entry': [],
        'identical': []
    }
    all_entries = seq_set.union(merged_set)
    for entry in all_entries:
        comparison_result['seq_screen_entry'].append(entry)
        comparison_result['identical'].append(entry in seq_set and entry in merged_set)

    result_df = pd.DataFrame(comparison_result)
    return result_df
result1 = compare_dataframes_on_column(seq, merged_df, 'seq_screen_entry')
result1

In [ ]:
false_values = result[result['identical'] == False]
false_values

In [ ]:
false_values1 = result1[result1['identical'] == False]
false_values1

In [ ]:
def compare_dataframes_on_index(seq, merged_df):
    combined_indices = set(seq.index).union(set(merged_df.index))
    comparison_results = {
        'index': [],
        'identical': []
    }
    for idx in combined_indices:
        comparison_results['index'].append(idx)
        comparison_results['identical'].append(idx in seq.index and idx in merged_df.index)
    result_df = pd.DataFrame(comparison_results)  
    return result_df
result3 = compare_dataframes_on_index(seq, merged_df)
result3

In [ ]:
seq.tail(50)

In [ ]:
result3.tail(50)

In [ ]:
false_values2 = result3[result3['identical'] == False]
false_values2

In [ ]:
#match on both index and col???
#use min lenth
def compare_dataframes_on_index_and_column(seq, merged_df, seq_screen_entry):
    min_length = min(len(seq), len(merged_df))
    comparison_result = {
        'index': [],
        'seq_screen_entry': [],
        'identical': []
    }
    for idx in range(min_length):
        index_value = seq.index[idx]
        if index_value in merged_df.index:
            seq_value = seq.loc[index_value, seq_screen_entry]
            merged_value = merged_df.loc[index_value, seq_screen_entry]
            comparison_result['index'].append(index_value)
            comparison_result['seq_screen_entry'].append(seq_value)
            comparison_result['identical'].append(seq_value == merged_value)
    result_df = pd.DataFrame(comparison_result)
    return result_df

result4 = compare_dataframes_on_index_and_column(seq, merged_df, 'seq_screen_entry')
result4

In [ ]:
#checking both 
def compare_dataframes_on_index_and_column(seq, merged_df, seq_screen_entry):
    comparison_result = {
        'index': [],
        'seq_screen_entry': [],
        'identical': []
    }
    for index_value in seq.index:
        if index_value in merged_df.index:
            seq_value = seq.loc[index_value, seq_screen_entry]
            merged_value = merged_df.loc[index_value, seq_screen_entry]
            comparison_result['index'].append(index_value)
            comparison_result['seq_screen_entry'].append(seq_value)
            comparison_result['identical'].append(seq_value == merged_value)
    result_df = pd.DataFrame(comparison_result)
    return result_df
result5 = compare_dataframes_on_index_and_column(seq, merged_df, 'seq_screen_entry')
result5

In [ ]:
#try again
def compare_dataframes_on_index_and_column(seq, merged_df, seq_screen_entry):
    comparison_result = {
        'index': [],
        'seq_screen_entry': [],
        'identical': []
    }
    for index_value in merged_df.index:
        if index_value in seq.index:
            seq_value = seq.loc[index_value, seq_screen_entry]
            merged_value = merged_df.loc[index_value, seq_screen_entry]
            comparison_result['index'].append(index_value)
            comparison_result['seq_screen_entry'].append(seq_value)
            comparison_result['identical'].append(seq_value == merged_value)
        else:
            comparison_result['index'].append(index_value)
            comparison_result['seq_screen_entry'].append(None)  
            comparison_result['identical'].append(False)
    result_df = pd.DataFrame(comparison_result)
    return result_df

result6 = compare_dataframes_on_index_and_column(seq, merged_df, 'seq_screen_entry')
result6

In [ ]:
false_values3 = result6[result6['identical'] == False]
false_values3

In [ ]:
nan_count = merged_df.isnull().sum()
nan_count